### ISSUE TITLE
isAuthenticated and user are false after successful login

### ISSUE THREAD

**Issue by dennisMeeQ** [auth0/auth0-react#100]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I have setup a the Auth0 React SDK and I am running into similar issues like #82 and #93 .

After a successful login (User enters username/password, auth code flow with PKCE is successful) on the client I have the following behaviour:
* ``getAccessTokenSilently`` returns a valid token ✅ 
* both ``user`` and ``isAuthenticated`` return false 🙅 

Interestingly, this is the behaviour for Chrome and FF, in Safari the login fails completely.

After reading the other issues mentioned above I have tried the following things to resolve this:
* Check the application's 'Application type' to be 'Single Page Application' and the 'Token Endpoint Authentication Method' to be 'None'
* Cycle both of these values to a different one and then back to the original ones.
* Set up the ``Auth0Provider`` with or without ``onRedirectCallback``.

None of these seem to make a difference.

### What was the expected behavior?

If ``getAccessTokenSilently`` returns a valid token, I would expect that ``user`` and ``isAuthenticated`` are set correctly.

### Reproduction

My setup looks like this:

```
// index.js
import React from 'react';
import ReactDOM from 'react-dom';
import { Auth0Provider } from '@auth0/auth0-react';

// const onRedirectCallback = (appState) => {
//   let returnPath;
//   if (appState) {
//     returnPath = appState.returnTo;
//   }
//   history.replace(returnPath || window.location.pathname);
// };

ReactDOM.render(
  <Auth0Provider
    domain={auth0Config.domain}
    clientId={auth0Config.clientId}
    redirectUri={window.location.origin}
    // onRedirectCallback={onRedirectCallback}
  >
    <App />
  </Auth0Provider>,
  document.getElementById('root')
);
```

```
// loginPage.js

import React, { useEffect } from 'react';
import { useAuth0 } from '@auth0/auth0-react';
import CircularProgress from '@material-ui/core/CircularProgress';

// [...]

export const LoginPage = () => {
  const { isLoading, loginWithRedirect } = useAuth0();

  useEffect(() => {
    loginWithRedirect({ audience });
  }, []);

  return <div>{isLoading && <CircularProgress />}</div>;
};
```

```
// someOtherComponent.js

import React, { useEffect, useState } from 'react';
import { useAuth0 } from '@auth0/auth0-react';

// [...]

export const someComponent = (props) => {
  const [token, setToken] = useState();
  const { isAuthenticated, user, getAccessTokenSilently } = useAuth0();

  useEffect(() => {
    const fn = async () => {
      setToken(await getAccessTokenSilently({ audience }));
    };
    fn();
  }, []);

  return (
    <>
      User: {JSON.stringify(user)}
      {isAuthenticated ? <div>logged in</div> : <div>logged out</div>}
      token: {JSON.stringify(token)}
    </>
  );
};
```

### Environment

- **Version of `auth0-react` used:** 1.0.0
- **Which browsers have you tested in?**: Chrome, FF, Safari
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** react-admin

**Comment by dennisMeeQ** [comment]
After reading #85, this might also have to do with sameSite cookies. I am currently getting the following warning:

``
A cookie associated with a cross-site resource at http://auth0.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`.
``

Please note: ** It has been blocked**

**Comment by adamjmcgrath** [comment]
Hi @dennisMeeQ - thanks for raising this

> getAccessTokenSilently returns a valid token ✅
> both user and isAuthenticated return false 🙅

I can't see anything in your code that would cause this, my only note would be that in `someComponent.js`, your `useEffect` will only run once, and if this happens when the SDK is loading (`isLoading`) and `isAuthenticated: false`, you might not get a token:, this would be better:

```js
useEffect(() => {
  if (!isAuthenticated) return;
  const fn = async () => {
    setToken(await getAccessTokenSilently({ audience }));
  };
  fn();
}, [isAuthenticated]);
```

Could you check the Network tab and console in chrome and see if you have any errors?
Also could you check that your `clientId` and `domain` work in the auth0-react playground app https://github.com/auth0/auth0-react/blob/master/static/index.html#L85-L86 or share your `clientId` and `domain` on this thread and I'll check

> After reading #85, this might also have to do with sameSite cookies. I am currently getting the following warning:

This should not affect your login, have a look at my comment in https://github.com/auth0/auth0-react/issues/85#issuecomment-673934742

**Comment by dennisMeeQ** [comment]
Hey @adamjmcgrath,

thanks for looking into this!

> I can't see anything in your code that would cause this, my only note would be that in someComponent.js, your useEffect will only run once, and if this happens when the SDK is loading (isLoading) and isAuthenticated: false, you might not get a token:, this would be better:

You are right, that would be better. Unfortunately, at the moment, your code does not work for me because ``isAuthenticated`` never becomes ``true`` (that is the original problem I reported).

> Could you check the Network tab and console in chrome and see if you have any errors?

No errors, both calls to Auth0 (to ``/authorize`` and to ``/oauth/token``) work as expected.

> share your clientId and domain on this thread and I'll check
```

> Also could you check that your clientId and domain work in the auth0-react playground app

Will do that in the meantime.

Thanks a lot!
Dennis
{
  "domain": "zamdo.eu.auth0.com",
  "clientId": "PF46H6TiE2yb5RYFfTORbZttL0W6uDfD",
}
```

**Comment by kennyworkman** [comment]
@dennisMeeQ I was running into this exact same issue. All requests responding normally and `isAuthenticated` taking on `false` rather than `undefined` after everything pointed to a successful login (console showed it as such). 

I forgot to specify CORS origin in my app's console. Maybe try that?

**Comment by dennisMeeQ** [comment]
Hey @kennyworkman, thanks for the tip! Unfortunately, setting the CORS origin did not change anything. 

Did you run into this issue on localhost or in a deployed scenario?

**Comment by dennisMeeQ** [comment]
@adamjmcgrath: I did some more investigation. I built a minimal version of my app and committed it to:
https://github.com/dennisMeeQ/auth0-tester

It shows exactly the same effects as described before: login succeeds, the token can be accessed but ``isAuthenticaed`` and ``user`` both stay ``false``.

I also added a second version of the code that uses the old package ``@auth0/auth0-spa-js'`` with a custom Auth0Context (mostly copy&pasted from one of the Auth0 tutorials) and the same code works perfectly. I committed it in a PR to my test repo to check:
https://github.com/dennisMeeQ/auth0-tester/pull/1/files

I think I will switch to this method in my app to save time. It would still be interesting though, what is going wrong in the original version.

**Comment by adamjmcgrath** [comment]
Hi @dennisMeeQ 

Thanks for sharing the whole app, I see the issue now.

By not specifying an `audience` in the Provider, you've told the library to base it's `isAuthenticated` state on the existence of an access token for the default audience (which we call `default`).

You've then logged in to your tenant specifying "https://api.zamdo.io" as your audience, so you will have an access token for that audience, but not the default audience.

In short, you should specify "https://api.zamdo.io" as the `audience` in your Provider options: https://github.com/dennisMeeQ/auth0-tester/blob/master/src/index.js#L21-L26

Your other branch works because you are correctly specifying the default audience https://github.com/dennisMeeQ/auth0-tester/blob/use-auth0-spa-js/src/index.js#L15

**Comment by dennisMeeQ** [comment]
Hey @adamjmcgrath,

ah, great! I get it now, too.

It makes sense now with your explanation, but I have to say the concepts seems counterintuitive without the explanation. I was migrating from the ``@auth0/auth0-spa-js`` library, read the README of ``@auth0/auth0-react`` and in the first example, the provider is defined without an audience. So I thought "hmm, they must have changed the  API". Then in a few examples further down in the README ``getTokenSilently`` is called with an audience, so I thought "hmm, this is where the audience is passed to the API now".

Maybe it makes sense to put an explanation somewhere in the docs on how this works.

Thanks a lot for the support! You guys rock! 🤘 
Dennis

**Comment by adamjmcgrath** [comment]
Thanks @dennisMeeQ - glad you got it working, happy to help!

**Comment by madmaxlax** [comment]
> Hi @dennisMeeQ
> 
> Thanks for sharing the whole app, I see the issue now.
> 
> By not specifying an `audience` in the Provider, you've told the library to base it's `isAuthenticated` state on the existence of an access token for the default audience (which we call `default`).
> 
> You've then logged in to your tenant specifying "https://api.zamdo.io" as your audience, so you will have an access token for that audience, but not the default audience.
> 
> In short, you should specify "https://api.zamdo.io" as the `audience` in your Provider options: [dennisMeeQ/auth0-tester@master...adamjmcgrath:patch-1](https://github.com/dennisMeeQ/auth0-tester/compare/master...adamjmcgrath:patch-1)
> 
> Your other branch works because you are correctly specifying the default audience https://github.com/dennisMeeQ/auth0-tester/blob/use-auth0-spa-js/src/index.js#L15

if i could add a suggestion: 
since it seems any difference in scope or audience from your <Auth0provider /> setup, and the getAccessTokenSilently({}) options or loginWithRedirect({}) options can cause this isAuthenticated invalidation
it would be best to recommend setting up the audience ONLY at the Auth0Provider level,  and recommend not adding any options to the other function calls. or point out that those HAVE to match or else you will end up with an invalidated auth situation like we're seeing

**Comment by Sergioamjr** [comment]
Just for the record I was facing a similar problem on Safari and Chrome Incognito mode but I have set the audience ID and followed the instructions of the documentation.

What solved the issue for me was adding the property `cacheLocation="localstorage"` on my `Auth0Provider`, thankfully to [this comment](https://github.com/auth0/auth0-react/issues/359#issuecomment-1129914157).

```js
    <Auth0Provider
      cacheLocation="localstorage"
      domain={AUTH0_DOMAIN}
      clientId={AUTH0_CLIENT_ID}
      redirectUri={AUTH0_CALLBACK_URI || window.location.origin}
      audience={AUTH0_API_AUDIENCE}
      scope="openid profile email"
      onRedirectCallback={onRedirectCallback}
    >
      {children}
    </Auth0Provider>
```
