### ISSUE TITLE
Passwordless - Magic link from email

### ISSUE THREAD

**Issue by felixnoriel** [auth0/auth0-react#102]
### Describe the problem

We've enabled the passwordless (Email) in our auth0 and trying to implement it using this SDK. 

We receive the generated magic link from auth0 via email and the magic link goes like ourdomain.com/passwordless/verify_direct?scope=openid&response_type=token&redirect_uri=ourdomain.com/callback&verification_code=350357&connection=email&client_id=OUR_CLIENT_ID&email=MY_EMAIL. 

Now when we click on it our app is stuck on the callback url with these params ourdomain.com/callback#access_token=REDACTED&scope=openid&expires_in=7200&token_type=Bearer

Question is if the SDK supports this feature? or is part of the roadmap?

We're aware that the SDK is using auth0-spa-js and it supports passwordless. But the current sdk doesnt expose the Auth0Client. Do you have any suggestions?

Thank you very much

### What was the expected behavior?

 Successfully login using the magic link

### Reproduction

- Enable passwordless in auth0 dashboard and use email as the option
- Trigger a magic link to be sent to your email
-  Click on the link 

### Environment

- **Version of `auth0-react` used: latest
- **Which browsers have you tested in?**: chrome and safari
- **Which framework are you using, if applicable (Angular, React, etc):** React

**Comment by adamjmcgrath** [comment]
Hi @felixnoriel 

We don't support embedded passwordless, but we do support Passwordless through the Universal Login Page (which is the preferred way to do Passwordless). More info here https://github.com/auth0/auth0-react/issues/79#issuecomment-668587745

**Comment by felixnoriel** [comment]
thanks for the reply @adamjmcgrath 
That might not be what we want for our use case as we try to get rid of those extra steps for our users with single click (magic link)

If we authenticate the user using auth0-js and get the desired tokens, is there a way to set these tokens manually in auth0-react? so we can still use this sdk at the end.

**Comment by adamjmcgrath** [comment]
Hi @felixnoriel - there is no public API that would enable this and we have nothing planned I'm afraid. Currently this SDK is purely for use with the Universal Login Page.

**Comment by theIYD** [comment]
Is there a way of using this SDK for Passwordless with Magic link with Universal login enabled? 

Desired outcome: 
1. Auth0 sends the magic link on the email
2. Click on the link
3. Lands on the application logged in
