### ISSUE TITLE
Possible api call duplication in Auth0Provider

### ISSUE THREAD

**Issue by MaxBrokhman** [auth0/auth0-react#103]
### Description

I was looking a the code of both auth0-react and auth0-spa-js libraries and i noticed that in auth0-spa-sj in isAuthenticated method of Auth0Client getUser method is used:
<pre>
  <code>
      public async isAuthenticated() {
        const user = await this.getUser();
        return !!user;
    }
  </code>
</pre>
And in auth0-react  Auth0Provider both methods are used like this:
<pre>
  <code>
      const isAuthenticated = await client.isAuthenticated();
      const user = isAuthenticated && (await client.getUser());
      dispatch({ type: 'INITIALISED', isAuthenticated, user });
  </code>
</pre>

### Possible solution

It is possible to remove duplicated getUser invokation:
<pre>
  <code>
      const user = await client.getUser();
      dispatch({ type: 'INITIALISED', isAuthenticated: !!user, user });
  </code>
</pre>
Is that right or am I missing something?

### Additional context

Sorry about my english.

**Comment by adamjmcgrath** [comment]
Thanks @MaxBrokhman 

> Is that right or am I missing something?
You are correct sir

Happy to accept a PR if you'd like to change it

**Comment by MaxBrokhman** [comment]
> Thanks @MaxBrokhman 
> 
> > Is that right or am I missing something?
> 
> You are correct sir
> 
> Happy to accept a PR if you'd like to change it
> 
> 

Will do, thank you
