### ISSUE TITLE
Support Auth0Provider's clientId change

### ISSUE THREAD

**Issue by lazybean** [auth0/auth0-react#106]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

We are using different clientId in our app for different environments (maybe we shouldn't, but we are stuck with that for a while). 
Currently Auth0Provider creates the Auth0 client once with the first initial props. (https://github.com/auth0/auth0-react/blob/master/src/auth0-provider.tsx#L189-L191)
If we change later the clientId, the client wont be changed.

Auth0Provider should properly update/recreate the auth0 CLient when the clientId or (other clientOpts) change. Perhaps with a useEffect.

## Alternatives and current work-arounds

Our current workaround is to pass a `key` prop with the clientId as key. This will cause the Auth0Provider and the auth0 client to be recreated. But the big drawback is that it unmounts all the child tree.

**Comment by adamjmcgrath** [comment]
Hi @lazybean  - thanks for raising this

Unfortunately, creating and recreating the client based on some props would introduce an unnecessary amount of complexity to the SDK for what is a fairly non standard use case.

I can only suggest you use your current workaround - thanks!

**Comment by mathpangSangJoon** [comment]
Just leaving a comment here to show that there is some demand to this feature.

Also, thanks @lazybean 
Your workaround works in situations where more than two tenants are used in one website.
