### ISSUE TITLE
Enable loginWithPopup to optionally accept an existing popup window

### ISSUE THREAD

**Issue by lukexor** [auth0/auth0-react#108]
This [change](https://github.com/auth0/auth0-spa-js/pull/368) was recently added to allow passing in an existing popup window to loginWithPopup allowing customization of additional windowFeatures in the window.open specification.

However, Auth0Provider appears to not have been updated and does not allow passing in this new configuration.

It'd be great to get this interface updated so we can use this new feature in auth0-spa-js!

**Comment by lukexor** [comment]
My mistake - it is updated but not in the release I was using!

**Comment by adamjmcgrath** [comment]
Hey @lukexor - going to do a release in about a week, which will have this in it
