### ISSUE TITLE
Redirecting new users to /signup instead of /login

### ISSUE THREAD

**Issue by maxpaj** [auth0/auth0-react#114]
# Describe the problem you'd like to have solved

Users are redirected to login page in Universal Login regardless of being a new user or existing. [This solution](https://community.auth0.com/t/how-do-i-link-users-directly-to-the-hosted-signup-page/42520) does not apply to this library.

I think I'm missing out on new signups because new users can't find the "Not a user? Sign up" text at the very bottom. This is indeed quite confusing.

### Describe the ideal solution

Using something like this:

```
signupWithRedirect({
   ...
})

signupWithPopup({
   ...
})
```

or 

```
loginWithRedirect({
   fragment: "screen_hint=signup"
   ...
})
```

Which then takes the user into the signup flow immediately.

**Comment by maxpaj** [comment]
Very much related https://github.com/auth0/auth0-spa-js/issues/397

**Comment by maxpaj** [comment]
I was able to achieve it using the following, however that still doesn't allow me to control it depending on what button the user clicks (signup / login):



```
<Auth0Provider
    screen_hint="signup"
    audience={config.AUTH0_AUDIENCE || ""}
    domain={config.AUTH0_DOMAIN || ""}
    clientId={config.AUTH0_CLIENT_ID || ""}
    redirectUri={config.APP_URL + "/profile"}
>
    <BrowserRouter>
        <ScrollToTop />
        <App></App>
    </BrowserRouter>
</Auth0Provider>
```

**Comment by maxpaj** [comment]
I'm stupid. I could just do it 
```
loginWithRedirect({
    screen_hint: "signup",
})
```

**Comment by stevehobbsdev** [comment]
Not stupid at all :) glad you found a solution!
