### ISSUE TITLE
IE11 Errors and infinite fetch loop whenever importing components from React UI library

### ISSUE THREAD

**Issue by vitalizatroutine** [auth0/auth0-react#116]
### Describe the problem

I have an app that uses Auth0's passwordless authentication via email link. I've been running into issues in IE11 using auth0-react, and have been spending some time trying to narrow down / debug the issue. I am seeing some really weird behaviour in IE11, where common conditions such as running a locally imported function will cause IE11 to infinitely-refetch credentials (generating new ?code=&state= query params each time).

For simplicity, I am now working with the sample application (quickstart), and have noticed that the application breaks whenever I attempt to import one of my UI library components. Simply having the import statement in the code will cause Auth0 to experience some sort of error when fetching credentials. Rendering the component is not a requirement to get the error "Oops... ID token is required but missing". Removing the import statement and forcing a log-out will return expected behaviour.

On my own app, which is a typescript version of the sample app, I experience even weirder behaviour, where importing a function from a parent's sister directory (`../utils/browser.utils.ts`) and running it will cause the app to infinitely loop for credentials. Same goes for importing and rendering a component from the UI library.

All other browsers are not affected. Does anyone have any ideas around why this is happening with IE11?

### What was the expected behavior?

Auth0 fetches the credentials and renders the app with no issues regardless of UI / functional imports from local or outside sources, such as a UI library.

### Reproduction

Step 1: install the quick-start application (https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01)
Step 2: `import` a component in `src/views/ExternalApi.js`. I'm using a private npm package lib, but have also ran `npm install` using a locally packed version to see if the private part of the package was causing the issue.
Step 3: simply load the app via `npm start` and login. After returning back to the app, Auth0 should return an error.
> import { Spinner, SpinnerTheme} from "@q4/nimbus-ui";

I can probably provide a `.tz` file for better reproduction. Let me know if this is necessary.

### Environment

- Using IE11
- Using `auth0-react` 1.1.0
- Using ReactJS Quickstart App (https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01)

**Comment by adamjmcgrath** [comment]
Hi @vitalizatroutine - thanks for raising this

> Step 1: install the quick-start application (https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01)

The sample app doesn't support IE11, I get a `'Symbol' is undefined` when I try and run it in prod mode (we [don't support it at all in dev mode](https://github.com/auth0-samples/auth0-react-samples/blob/master/Sample-01/package.json#L54-L56)). Because we use [higlight.js v10](https://github.com/highlightjs/highlight.js/blob/master/VERSION_10_BREAKING_CHANGES.md) which breaks the sample app in IE11

**Comment by adamjmcgrath** [comment]
Going to close this - feel free to reopen i you have any more questions about this
