### ISSUE TITLE
User roles rule error

### ISSUE THREAD

**Issue by Jacobjeevan** [auth0/auth0-react#117]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I am trying to use the rule (Add user roles from a SQL Server database) to access user role and render elements based on user's role. However, I am getting the following error whenever I enable the rule:

> http://localhost:3000/?error=access_denied&error_description=The "config.server" property is required and must be of type string.&state

I didn't edit the rule (and it does have the server property). My assumption is that the rule accesses 'Username-Password-Authentication' database created by default.

I am getting the same error when using the try connection under Connections > Database.

### What was the expected behavior?

- Authentication database would include role information (and updated whenever a user's role is updated in the Auth0 dashboard).
- Rule would add role as an attribute, which can then be read as part of metadata on the front end

Am I supposed to store roles information in another database? If so, how would I go about ensuring that a corresponding entry is created in the database when I assign user roles in Auth management dashboard?

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducible steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1. Enable 'Add user roles from a SQL Server database' rule on Auth0 dashboard
- Step 2. Try to login on React front end.
- Step 3. Login fails due to the error.

If I were to disable the rule, login works.

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-react` used: 1.0.0
- **Which browsers have you tested in? Firefox
- **Which framework are you using, if applicable (Angular, React, etc): React frontend, Node.js backend.
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hey @Jacobjeevan - thanks for raising this

Your question is not related to the react sdk, you'd be better of posing it on https://community.auth0.com/

> My assumption is that the rule accesses 'Username-Password-Authentication' database created by default.

I don't think this assumption is correct. That rule is for accessing custom SQL DB connections. If you want to access the default user store you should use the management api.

Closing for now, feel free to reopen if you have any other questions
