### ISSUE TITLE
Make AppState type more accessible

### ISSUE THREAD

**Issue by palfrey** [auth0/auth0-react#119]
## Describe the problem you'd like to have solved

The `onRedirectCallback` of Auth0Provider takes a function that has an argument of `AppState`. However, the type of AppState isn't easily available outside the library, which makes TypeScript work without using `any` harder.

### Describe the ideal solution

`import { AppState } from '@auth0/auth0-react'` should just work, via exporting AppState.

## Alternatives and current workarounds

`import { AppState } from '@auth0/auth0-react/dist/auth0-provider'` works, but is annoying.

**Comment by adamjmcgrath** [comment]
Good point... thanks @palfrey
