### ISSUE TITLE
Custom Claims added in Auth0 rules not coming in getIdTokenClaims

### ISSUE THREAD

**Issue by raghavendracs** [auth0/auth0-react#121]
Hi, 

I have configured my Auth0Provider as follows,

```
<Auth0Provider
   domain={`${auth0Domain}`}
   clientId={`${auth0ClientId}`}
   redirectUri={`${process.env.BASE_APIPATH}/auth0_callback`}
   onRedirectCallback={() => {
     router.push('/dashboard');
   }}
>
```

I have added a rule in my Auth0 to see if the user is logging in for the first time.

```
function (user, context, callback) {
  const namespace = 'https://xxxxx.eu.auth0.com/';
  context.idToken[namespace + 'isNewUser'] = (context.stats.loginsCount === 1);
  return callback(null, user, context);
}
```

When I test the rule on Auth0, it all works fine and an idToken is added under my namespace.

I am using google-auth for logging in my front end. Post successful login, in my AuthCallback on the Front End am trying to get the idTokenClaims as follows,

```
getIdTokenClaims().then(claims => console.log("Claims : ", claims)
```

While the standard, profile, email details are there under claims, the custom claim I added is not visible.

Not sure if I am doing anything wrong or is there a problem?

**Comment by adamjmcgrath** [comment]
Hi @raghavendracs - thanks for raising this

Your namespace cannot be `*.auth0.com` - more info here https://auth0.com/docs/tokens/create-namespaced-custom-claims

Can you change it to something valid (eg `http://www.myexample.com/`) and let me know if that works for you.

**Comment by raghavendracs** [comment]
Thanks a lot, Adam. My bad, I missed reading that Auth0 domains cant be used for custom namespaced claims. Works fine now.
