### ISSUE TITLE
Auth0Provider sends an authorize call on mount

### ISSUE THREAD

**Issue by ellioseven** [auth0/auth0-react#124]
### Describe the problem

> Provide a clear and concise description of the issue

When the Auth0Provider (with refresh tokens and localstorage cache) mounts, it makes an authorize call to Auth0, even if a user hasn't initialised a session. This creates a "login required" error in the Auth0 logs, which will potentially flood them.

### What was the expected behavior?

> Tell us about the behavior you expected to see

Auth0Provider shouldn't automatically make an authorize query on mount, or at least this should be "opt-in".

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

I used the nextjs example in the example folder and configured the provider like so:

```
<Auth0Provider
  cacheLocation="localstorage"
  useRefreshTokens={ true }
  domain={process.env.NEXT_PUBLIC_DOMAIN}
  clientId={process.env.NEXT_PUBLIC_CLIENT_ID}
  audience={process.env.NEXT_PUBLIC_AUDIENCE}
  scope="read:users"
  redirectUri={typeof window !== 'undefined' && window.location.origin}
  onRedirectCallback={onRedirectCallback}
>
```

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.1.0
- **Which browsers have you tested in?** Chrome Version 85.0.4183.102 (Official Build) (64-bit)
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** Auth0 SPA SDK 1.12.1

**Comment by adamjmcgrath** [comment]
Hi @ellioseven - thanks for raising this.

This is a known issue in `auth0-spa-js` that stems from our decision to fallback to silent iframe auth when no refresh token is present (to prevent user's being logged out when clients switched to rotating refresh tokens).

We are currently planning some work to resolve this in `auth0-spa-js`, and I'll update this bug when that work has started (which may not be for a few weeks)
