### ISSUE TITLE
Allow in-app redirects in the logout returnTo, in the same way logging in redirects

### ISSUE THREAD

**Issue by hanvyj** [auth0/auth0-react#127]
### Describe the problem you'd like to have solved

The `returnTo` parameter when logging out should be passed to the `onRedirectCallback` callback.

When I'm logging out and want to redirect, the `returnTo` has to be explicitly listed in the allowed callback URLs. This is not possible for every endpoint in the application.

For example, I'm logging out when the tokens have timed out, redirecting the user to the "Your authentication session has expired, please [login again]". I then want to call:

```
    logout({
        returnTo: thePreviousURL,
    });
```
So they return to their previous place in the app. However, this could be "/users/1234112", which of course wouldn't be in the allowed callback URLs and you get the error: 

> The "returnTo" querystring parameter "http://mysite.com/users/1234112" is not defined as a valid URL in "Allowed Logout URLs".

The library does deal with this on login using the `returnTo` property in the callback though. I have logic for dealing with that redirect when the `onRedirectCallback` is fired, and it gives me the subpath to be routed to. This occurs when the user is already logged out and navigates to a link, e.g. "/users/1234112".

```
<Auth0Provider
      ...
      redirectUri="http://mysite.com/login-redirect"
      onRedirectCallback={({ returnTo }) => {
        if (returnTo) {
          // here we can deal with returnTo that are not in the allowed URL list
          history.replace(returnTo);
        }
      }}
```

### Describe the ideal solution

I propose that you can specify a logoutUri, which must match our allowed logout URI list, but a local `returnTo`:

```
    logout({
        logoutUri="http://mysite.com"
        returnTo: "/users/1234112",
    });
```
It will log out using the logoutUri, "http://mysite.com", but pass the `returnTo` specified in the logout ("/users/1234112") to the `onRedirectCallback` `returnTo`, just like when logging in.

## Alternatives and current work-arounds

I'm currently putting my logout's  `returnTo` in localstorage, and in the redirect:

```
      onRedirectCallback={({ returnTo }) => {
        const logoutReturnTo = localStorage.getItem("logout-redirect");
        history.replace(logoutReturnTo || returnTo || "/");
        localStorage.removeItem("logout-redirect");
      }}
```

```
      localStorage.setItem("logout-redirect", logoutRedirect)
      logout({
        returnTo: config.redirectUri,
      });
```

**Comment by adamjmcgrath** [comment]
Hi @hanvyj - thanks for your suggestion

We don't have a callback handler for logout and we can't verify a logout redirect is from the authorization server (there's no code to exchange) - so performing any actions after logout would be out of scope for the SDK.

Your suggestion looks fine, since logout url's ignore the query param and hash fragment, you could also use that (`logout({ returnTo: 'https:example.com?logoutReturnTo=/users/1234112' })`) just make sure you check that `logoutReturnTo` is a relative url so you don't have an open redirect.
