### ISSUE TITLE
Consider memoizing Auth0context functions

### ISSUE THREAD

**Issue by zdila** [auth0/auth0-react#131]
Currently [functions references of `Auth0Context.Provider`](https://github.com/auth0/auth0-react/blob/504a6eab2fbef3ae90d7a9ac8dd8c26837ba4613/src/auth0-provider.tsx#L235) are changed everytime when `<Auth0Provider>` renders. In that case it makes `useAuth0()` to return different function references and then, if they are later used in dependency arrays for other hooks (eg. `useEffect`), they cause them to reevaluate.

From what I see it should be safe to exclude those functions from dependencies of other hooks, but react-hooks eslint rules will still complain.

Introducing `useCallback` for all functions of the context value in `auth0-provider.tsx` should fix this.

**Comment by adamjmcgrath** [comment]
Het @zdila - thanks for your suggestion

I'll add something to our backlog to investigate this
