### ISSUE TITLE
isLoading & isAuthenticated are false & user is undefined after login

### ISSUE THREAD

**Issue by Rocinante89** [auth0/auth0-react#132]
## Describe the problem

When a user logs in via a protected route, there is a period where isLoading and isAuthenticated is false, and user is still undefined, then isAuthenticated updates to true and the user is available. This is occurring intermittently on browsers on PC and android, but is repeatable on iPhone thus causing users to experience a momentarily flash of the unauthorized state 

Console:
![image](https://user-images.githubusercontent.com/8224386/96148272-039d7700-0f00-11eb-8232-0197ad63e142.png)

Application Settings:
![image](https://user-images.githubusercontent.com/8224386/96141393-e0bb9480-0ef8-11eb-8548-da2200209361.png)

Using non rotating tokens:
![image](https://user-images.githubusercontent.com/8224386/96141719-33954c00-0ef9-11eb-8d86-fd7ad1aa8147.png)

ClientId: 63H4MRCI7mw1jnDlQKHHmh0GW5Jao4g7
Domain: technifit.eu.auth0.com (but have a custom domain configured pointing to auth.technifit.com)

here's the protectedRoute:

```
const AppRoute = ({ component, ...rest }: any) => {
    const { isLoading, user, isAuthenticated, loginWithRedirect } = useAuth0();

    console.table([
        ['isLoading', isLoading],
        ['isAuthenticated', isAuthenticated],
        ['user', user],
    ]);

    useEffect(() => {
        if (user) checkForShadowAccount();
    }, [user, isAuthenticated]);

    const checkForShadowAccount = async () => {
        const techniFitUser = AccountUtils.getTechniFitUser(user);

        if (!techniFitUser.user_metadata?.isSignupCompleted) {
            const accountsAPI = new AccountsDAO();
            await accountsAPI.convertShadowAccount(techniFitUser);
        }
    };

    return isLoading ? (
        <Loading />
    ) : isAuthenticated && user ? (
        AccountUtils.getTechniFitUser(user).user_metadata?.isSignupCompleted ? (
            <AppLayout>
                <Route
                    component={withAuthenticationRequired(component, {
                        onRedirecting: () => <Loading />,
                    })}
                    {...rest}
                    render={(props) => <Component {...props} />}
                />
            </AppLayout>
        ) : (
            <Redirect to={'/signup'} />
        )
    ) : (
        <Result
            status={'error'}
            title={'There was an issue logging you in'}
            subTitle={
                <Button type={'primary'} onClick={() => loginWithRedirect()}>
                    Retry
                </Button>
            }
        />
    );

export default AppRoute;
```

### What was the expected behavior?

Users should not get stuck in a login loop

**Comment by adamjmcgrath** [comment]
Hi @Rocinante89 - thanks for raising this

I'm not able to reproduce on an iPhone simulator using the playground and adding:

```js
console.table([
     ['isLoading', isLoading],
     ['isAuthenticated', isAuthenticated],
     ['user', user],
]);
```

![image](https://user-images.githubusercontent.com/1299658/96161659-75c98800-0f0f-11eb-9350-92616a78e08b.png)

If I had to guess, it looks like there might be a couple of versions of the Context running in parallel? Can you link to your whole app? Or can you create a minimal reproduction using the playground app that I could test this on?

**Comment by Rocinante89** [comment]
I actually had a go at making it reproducible on chrome. It only seems to happen on slow internet/3g speeds. I can repro it on a PC with chrome if I throttle the speed to slow 3g in the network tab. 

Here's what's happening on our staging site with slow 3g enabled. That error component is only rendered when isLoading & isAuthenticated are false.
![error](https://user-images.githubusercontent.com/8224386/96167082-c7294580-0f16-11eb-962d-9e638f57fe4b.gif)

I'll try and reproduce it on the playground app.

**Comment by Rocinante89** [comment]
It looks like nesting the Auth0Provider inside the react router Router was causing my issue. Once I swapped their placement everything works as expected. If I nest them using the Auth0ProviderWithHistory method described in https://auth0.com/blog/complete-guide-to-react-user-authentication/ the issue persists

**Comment by silencej** [comment]
My Auth0Provider is already the outmost, but I still have this problem.

The response to the following request is always 302, @adamjmcgrath do you know why?

```
https://dev-6lxe0uxd.us.auth0.com/authorize?client_id=airzp1gz654zGCu90ZLNwPJVmfgfFxVm&redirect_uri=http%3A%2F%2Flocalhost%3A65002&dispatchConfig=%5Bobject%20Object%5D&_targetInst=%5Bobject%20Object%5D&_dispatchListeners=function%20loginWithRedirect(opts)%20%7B%0A%20%20%20%20%20%20%20%20return%20client.loginWithRedirect(toAuth0LoginRedirectOptions(opts))%3B%0A%20%20%20%20%20%20%7D&_dispatchInstances=%5Bobject%20Object%5D&nativeEvent=%5Bobject%20MouseEvent%5D&type=click&target=%5Bobject%20HTMLSpanElement%5D&currentTarget=%5Bobject%20HTMLButtonElement%5D&eventPhase=3&bubbles=true&cancelable=true&timeStamp=12607.399999978952&defaultPrevented=false&isTrusted=true&view=%5Bobject%20Window%5D&detail=1&screenX=549&screenY=161&clientX=543&clientY=26&pageX=543&pageY=26&ctrlKey=false&shiftKey=false&altKey=false&metaKey=false&getModifierState=function%20modifierStateGetter(keyArg)%20%7B%0A%20%20%20%20%20%20var%20syntheticEvent%20%3D%20this%3B%0A%20%20%20%20%20%20var%20nativeEvent%20%3D%20syntheticEvent.nativeEvent%3B%0A%0A%20%20%20%20%20%20if%20(nativeEvent.getModifierState)%20%7B%0A%20%20%20%20%20%20%20%20return%20nativeEvent.getModifierState(keyArg)%3B%0A%20%20%20%20%20%20%7D%0A%0A%20%20%20%20%20%20var%20keyProp%20%3D%20modifierKeyToProp%5BkeyArg%5D%3B%0A%20%20%20%20%20%20return%20keyProp%20%3F%20!!nativeEvent%5BkeyProp%5D%20%3A%20false%3B%0A%20%20%20%20%7D&button=0&buttons=0&relatedTarget=null&movementX=0&movementY=0&isDefaultPrevented=function%20functionThatReturnsFalse()%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D&isPropagationStopped=function%20functionThatReturnsFalse()%20%7B%0A%20%20%20%20%20%20return%20false%3B%0A%20%20%20%20%7D&scope=openid%20profile%20email&response_type=code&response_mode=query&state=SjZYV1ZnSUp%2BYTdwZ1lZZU5LcEw4Z2RwNTRqWlNJcEc2WDhBRWVUZWdpVg%3D%3D&nonce=bDBBNGZvTERKOWgwMlZZSkp1R3hlQURQME16WmxXV3NKfk4wMm9pWDVFTw%3D%3D&code_challenge=Et8h4yNiCzGrdTJLmE_I0z0gyRNeqOxbC6nNTvW6V24&code_challenge_method=S256&auth0Client=eyJuYW1lIjoiYXV0aDAtcmVhY3QiLCJ2ZXJzaW9uIjoiMS4xLjAifQ%3D%3D
```
