### ISSUE TITLE
Updating User Profile

### ISSUE THREAD

**Issue by VED-StuartMorris** [auth0/auth0-react#135]
Hello,

We are using the latest version of auth0-react and have an issue/question around updating a user profile.

We store a user's phone number within Auth0 and have a profile screen in our React application allowing the user to update this information. 
We use a rule to add the metadata to the id Token claims and get the information when displaying the form.

```
defaultValue={
              user['INTERNALURL/phone_number'] || ''
            }
```

This all works fine apart from the update path. We call an API which in turn calls the management API. 
```
 await auth0.updateUser({ id: userId }, userPatchObj).catch((err) => {
```

The update itself works as expected and the user is updated, however the cached user in the React app is never updated until the user re-authenticates.

Presumably, this is due to the cached user profile? (https://auth0.com/docs/users/update-user-profiles-using-your-database#user-profile-cache)

What would be the correct way to handle this? Here are some options that come to mind...
- We could store the updated value in our state management, React/Redux potentially and if there is a value there we would use that as the default.
- Force re-authentication
- Is there a way to force getting the latest information for the user?

I have tried to add a useEffect and check the values:
```
useEffect(() => {
    (async () => {
      const idTokenClaims = await getIdTokenClaims();
      console.log('idTokenClaims');
      console.log(idTokenClaims);
    })();
  }, [getIdTokenClaims]);
```
However, this just logs out the previous values and not the updated id token claims.

Thanks

**Comment by adamjmcgrath** [comment]
Hi @VED-StuartMorris - thanks for raising this issue

> Is there a way to force getting the latest information for the user?

If you do `getAccessTokenSilently({ ignoreCache: true })`, this will update the claims from `getIdTokenClaims()`

It should also update the `user`, but there's a known issue with that #109 which we're looking to address soon

Am going to close this in favour of #109, but feel free to reopen if you have any other questions

**Comment by rohitp934** [comment]
Hi @adamjmcgrath , I have tried all the solutions you have provided, and no matter what I do the `user` object isn't getting updated, and even if I use `getAccessTokenSilently({ ignoreCache: true })` the claims are not being updated in `getIdTokenClaims()`.

When testing out the rule on auth0 dashboard, i am able to see this.
![image](https://user-images.githubusercontent.com/54208873/125183507-9cb1b200-e234-11eb-8ac0-3f9c01a1355d.png)


Idk how to proceed further, any help would be appreciated
