### ISSUE TITLE
1.1.0 bundle size exploded

### ISSUE THREAD

**Issue by adenta** [auth0/auth0-react#137]
### Describe the problem

https://bundlephobia.com/result?p=@auth0/auth0-react@1.1.0

### What was the expected behavior?

smaller bundle 

### Reproduction

https://bundlephobia.com/result?p=@auth0/auth0-react@1.1.0

**Comment by adenta** [comment]
Is there a reason _why_ is repo got almost 2x as big in 1.1?

**Comment by frederikprijck** [comment]
Hi @adenta ,

Looks like this increase in size is mostly due to the increase in size of our `@auth0/auth0-spa-js` library. We will do some more research internally about why this has increased and get back to you.

Thanks.

**Comment by frederikprijck** [comment]
As mentioned, this is related to the SPA JS SDK and the fact that that library increased in size.
We have a ticket on our internal backlog to try and reduce its size, which should possitively impact the React SDK.

From the React SDK, the bundle increase is unfortunate but expected, however we hope for this to be as temporary as possible.

Thanks for reporting this, closing this for now as we are tracking it from the appropriate SDK's backlog.

**Comment by davidgilbertson** [comment]
Yeah ~130 KB is crazy. We're trying very hard to keep our app slim and this blows us waaaaay past where we want to be. But we want to use Auth0.

Can you offer some guidance for the performance-conscious developer? Is this going to be fixed, or is 130 KB just the cost of using Auth0? Is it feasible to replicate the core functionality of this library? I'm using `useAuth0` (`isAuthenticated`, `isLoading`, `loginWithRedirect`, `logout`, `getAccessTokenSilently`) and `Auth0Provider`. Can I just hit the right endpoints and implement this myself, or is there a lot of smarts going on behind the scenes?

**Comment by frederikprijck** [comment]
> Can I just hit the right endpoints and implement this myself, or is there a lot of smarts going on behind the scenes?

There is definitely a lot going on behind the scenes. If you are interested, we use https://github.com/auth0/auth0-spa-js under the hood, which is where the magic happens for the most part.

The main reason for the bundle size is that our SDK ships with quite some polyfills built-in, as auth0-spa-js supports IE11 and other less modern browsers, requiring the need for said polyfills.

> Is this going to be fixed, or is 130 KB just the cost of using Auth0?

From that point of view, the bundle size is expected. However, we do think this is a problem and have this on our backlog to get this resolved.

**Comment by adenta** [comment]
What if you released a bundle for products that don't support IE?
