### ISSUE TITLE
Oops... Invalid authorization code being returned on first login. Refreshing after that works fine

### ISSUE THREAD

**Issue by augustosamame** [auth0/auth0-react#138]
### Describe the problem

Logging in for the first time or refreshing a logged in page after a long time will take an abnormally long time (about 10 seconds) and then show "Oops... Invalid authorization code" error.

Checking console indicates:

POST https://starsona.us.auth0.com/oauth/token returns 403: {"error":"invalid_grant","error_description":"Invalid authorization code"}

However, just refreshing after seeing this error, logs the user in normally. It only fails the first time, or after refreshing after several minutes. Subsequent refreshes work fine.

### What was the expected behavior?

Refreshing a page with a logged in user should work normally without errors.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

We cloned the auth0-react project and have not modified it at all, except for adding the appropriate settings in auth_config.json

{
  "domain": "starsona.us.auth0.com",
  "clientId": "C7KpWJOGVf5E3UPrUc9LRNmJsaDjgRfw",
  "audience": "https://starsona.us.auth0.com/api/v2/"
}

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

it's an unmodified copy of the repo.
we have deployed this project to https://starsonafans.net/
where the issue can be replicated with ease.

### Environment

- **Version of `auth0-react` used:**

master branch as of today

- **Which browsers have you tested in?**

Chrome 86

- **Which framework are you using, if applicable (Angular, React, etc):**

React

- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Hi @augustosamame ,

I tried your application an `Logging in for the first time` works fine for me.
![image](https://user-images.githubusercontent.com/2146903/96837526-e2c8aa80-1446-11eb-891e-3d3bb90ce87f.png)

It also doesn't take 10 seconds for me:
![image](https://user-images.githubusercontent.com/2146903/96837636-0986e100-1447-11eb-8e97-ecf60c50331c.png)


I tried several times in a new browser (incognito) and I haven't been able to reproduce the behavior you mention in terms of logging in for the first time.

I will try waiting `refreshing a logged in page after a long time` in a while and see how that behaves. 

Could you perhaps give some more context on how to easily replicate it ?

**Comment by augustosamame** [comment]
Thanks for the quick reply. I just tried again, and got the error once more:

![image](https://user-images.githubusercontent.com/16038063/96838072-fb1bd380-140c-11eb-9621-846d79ffac7a.png)

I am keeping both starsonafans.net and sso1.starsona.com open with the same active session in each. They are the same codebase, just in different domains, as this is the scenario we're testing, cross-domain sessions.

After 15 minutes of both being open, I always get that error. It's been 100% reproducible under this scenario for me.
If you're unable to reproduce, I can switch browsers / computers to rule out a device-specific issue.

**Comment by frederikprijck** [comment]
SSO is working fine for me, both on initial login on both domains as well as after a refresh after +15 mins. 
It works as expected both in Incognito and outside Incognito. 

Even though I can not reproduce the issue, it sounds more like something unrelated to our React SDK. 
These kind of questions might be better of by asking on https://community.auth0.com/.

Closing this for now, but if you feel like this is related to our React SDK and can provide valid reproduction steps, please do not hesitate from continuing the conversation.
