### ISSUE TITLE
expose a signupWithRedirect function

### ISSUE THREAD

**Issue by cpenarrieta** [auth0/auth0-react#142]
### Describe the problem you'd like to have solved
there is no a similar functionality for `loginWithRedirect` that takes you to the Sign Up page instead. I want to have on my website 2 buttons. Sign in and Sign Up.

### Describe the ideal solution
Expose a function called `signupWithRedirect` that takes you to the sign up page and redirects you after the user is created.
![image](https://user-images.githubusercontent.com/1692542/97277070-42330b80-17f5-11eb-8f93-0eaa73714c99.png)

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

**Comment by frederikprijck** [comment]
Hi @cpenarrieta ,

You can direct a user to the signUp page by passing a custom argument to the loginWithRedirect function. You can read this here: https://github.com/auth0/auth0-react/issues/59#issuecomment-654333541.

**Comment by cpenarrieta** [comment]
@frederikprijck perfect, thanks for the help 👍
