### ISSUE TITLE
isLoading & isAuthenticated are false & user is undefined after login

### ISSUE THREAD

**Issue by wab** [auth0/auth0-react#145]
### Describe the problem

> Provide a clear and concise description of the issue

isLoading & isAuthenticated are false & user is undefined after login in `useAut0` hook, so loginWithRedirect enter. in a loop with this kind of effect on. routing

```
const { isAuthenticated, loginWithRedirect, isLoading } = useAuth();

  useEffect(() => {
    if (isAuthenticated || isLoading) return;

    loginWithRedirect({
      appState: { targetUrl: url },
    });
  }, [isAuthenticated, loginWithRedirect, url, isLoading]);
```

### What was the expected behavior?

expect that isAuthenticated return true (user setted) synchronous after loading state in order to avoid this tricky state.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

using this implementation https://auth0.com/blog/complete-guide-to-react-user-authentication/ with custom private route that check authenticated state before redirect

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

If so, provide steps:

App is wrapped with 

```
const Auth0ProviderWithHistory = ({ children }) => {
  const history = useHistory();

  const onRedirectCallback = (appState) => {
    history.push(appState?.returnTo || window.location.pathname);
  };

  return (
    <Auth0Provider
      domain={AUTH0_DOMAIN}
      clientId={AUTH0_CLIENT_ID}
      audience={AUTH0_AUDIENCE}
      login_hint={AUTH0_DB_CONNECTION}
      redirectUri={window.location.origin}
      onRedirectCallback={onRedirectCallback}
    >
      {children}
    </Auth0Provider>
  );
};

```

AuthRoute is like

```
const AuthRoute = (props) => {
  const { url } = useRouteMatch();
  const { isAuthenticated, loginWithRedirect, isLoading } = useAuth();

  useEffect(() => {
    if (isAuthenticated || isLoading) return;

    loginWithRedirect({
      appState: { targetUrl: url },
    });
  }, [isAuthenticated, loginWithRedirect, url, isLoading]);

  switch (true) {
    case isLoading:
      return <Loader isCover />;
    case isAuthenticated:
      return <Route {...props} />;
    default:
      console.info('You need to log in to access this part');
      // TODO: return specific page ?
      return <div>Redirecting you to the login...</div>;
  }
};

```

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** "@auth0/auth0-react": "^1.1.0",
- **Which browsers have you tested in?** all
- **Which framework are you using, if applicable (Angular, React, etc):** react
- **Other modules/plugins/libraries that might be involved:** none

**Comment by wab** [comment]
btw. i've already checked similars closed issues like :

- https://github.com/auth0/auth0-react/issues/93
- https://github.com/auth0/auth0-react/issues/133
- https://github.com/auth0/auth0-react/issues/132

but none are relevant.

**Comment by frederikprijck** [comment]
Hey @wab,

It is expected to redirect back to an unprotected route so the Auth0 SDK can process the state and code arguments.
Redirecting back to a protected router does result in an infinite loop as you have noticed.

In general, using something like this should work:

```
<Auth0Provider
  domain="..."
  clientId="..."
  redirectUri={`${window.location.origin}/callback`}
  audience="..."
>
    <BrowserRouter>
        <Route path="/" component={withAuthenticationRequired(HomePage, {
              onRedirecting: () => <Loading />,
              })}
         />
        <Route path="/test" component={withAuthenticationRequired(TestPage, {
              onRedirecting: () => <Loading />,
              })}
         />
        <Route path="/callback" exact>
          <Loading />
        </Route>
  </BrowserRouter>
</Auth0Provider>
```

In this case,
- If a user comes directly to `/`, they will be redirected to Auth0, redirected back to `/callback` and redirected back after succesful login to `/`
- If a user comes directly to `/test`, they will be redirected to Auth0, redirected back to `/callback` and redirected back after succesful login to `/test`

Note that the AuthRoute you are using could also make use of `withAuthenticationRequired` so you could use something like this:
```
const AuthRoute = ({ component, ...args }) => (
  <Route
    component={withAuthenticationRequired(component, {
      onRedirecting: () => <Loading />,
    })}
    {...args}
  />
);
```

```
<Auth0Provider
  domain="..."
  clientId="..."
  redirectUri={`${window.location.origin}/callback`}
  audience="..."
>
    <BrowserRouter>
        <AuthRoute path="/" component={HomePage} />
        <AuthRoute path="/test" component={TestPage} />
        <Route path="/callback" exact>
          <Loading />
        </Route>
  </BrowserRouter>
</Auth0Provider>
```

By using `withAuthenticationRequired`, the SDK takes care of the redirect for you. However, this is not a requirement to make it work, you can take care of the redirecting yourself as long as you ensure you navigate back to an unprotected route such as /callback mentioned above, for which you do not redirect back to Auth0 incase the user is not authenticated.

**Comment by wab** [comment]
Hi. @frederikprijck 
Many thanx for your detailed answer, understood your point on the `redirectUri` it seems prevent redirection from looping. However i certainly miss a point because as the second redirection appears after /callback, but App render stay on that screen without refreshing, router has no effect on url replacement `/callback?code&state` to `/initialroute`

**Comment by wab** [comment]
Seems come from switch implementation of routing.
Thx again, we can close this issue

**Comment by wab** [comment]
note that it stays on callback url when i add this callback on `AuthProvider`
`const onRedirectCallback = (appState) => {
    history.push(appState?.returnTo || window.location.pathname);
  };`

![image](https://user-images.githubusercontent.com/341980/97419669-9da2ed80-190a-11eb-8c89-43ea47cc342e.png)

**Comment by adamjmcgrath** [comment]
Hi @wab - what version of `react-router` are you using? They've changed the api a few times recently, for v6 I believe you should now use `navigate` https://github.com/ReactTraining/react-router/blob/dev/docs/advanced-guides/migrating-5-to-6.md#use-navigate-instead-of-history

**Comment by wab** [comment]
Hi, still on v5.

**Comment by adamjmcgrath** [comment]
ok thanks @wab - I think we'd need to see the source code for your app or (better) a minimal reproduction of the issue in order to help you debug

**Comment by frederikprijck** [comment]
I am also on react-router 6 for an app I maintain that uses Auth0 and I do not provide any `onRedirectCallback `. Does it work without specifiying that?

**Comment by wab** [comment]
it seems to log the correct path : `/auth`

**Comment by EddieGr** [comment]
Just to add on this issue. I realised that there is an error when I try to log in. I thought it might be the cause of the isAuthenticated flag being false all the time for me. Inspecting the oauth/token response I don't see an id_token inside of the response. If you use `const { error, isAuthenticated } = useAuth();` you'll see `error.message` says that id token is required but it's missing. Even though the logs on the Auth0 site shows that it was a successful login, the frontend seems to rely on the id_token.

Consequently when I use my Gmail to log in, it works (because there's an id_token inside of the oauth/token payload). But unfortunately it doesn't work with a test email I created inside of the Auth0 console.

**Comment by frederikprijck** [comment]
@EddieGr Doesnt sound related to this issue. But please make sure that `openid` is sent as scope to the /authorize endpoint.

**Comment by frederikprijck** [comment]
@wab 
What do you mean with

>  url is correctly replaced but render is not refreshed.

Anyway, as @adamjmcgrath mentioned, can you please produce a minimal reproduction so we can help you look into the cause?

**Comment by wab** [comment]
Gotit, BrowserRouter was under AuthProvider so  `history.push` wasn't defined and it redirection not fired

**Comment by adamjmcgrath** [comment]
Cool, glad you got it working @wab - and thanks for the assist @frederikprijck!

**Comment by wab** [comment]
thanks

**Comment by EddieGr** [comment]
> @EddieGr Doesnt sound related to this issue. But please make sure that `openid` is sent as scope to the /authorize endpoint.

Actually, my issue is now solved, you are right. What happened was that we had a rule set on the Auth0 that changed our scopes to a custom scope. And when that happened it ignored the openid. Thanks for the help

**Comment by adamjmcgrath** [comment]
> we had a rule set on the Auth0 console that changed our scopes to a custom scope

Great, glad you got it working @EddieGr - good catch @frederikprijck!

**Comment by mattc-eostar** [comment]
Thank you for opening this issue. Setting up an open `/callback` route fixed one of the issues I was having but only when logging in directly to the web app.

I need this same behavior with SAML SSO. So the redirect URI is *.auth0.com/samlp/..... with a RelayState parameter that points to ```encodeURIComponent(`${window.location.origin}/callback`)```

The authentication of the third-party app is successful and it properly redirects back into my app to the callback route, but no `code` or `state` parameters come with it and it just stays on `/callback`

I am using `onRedirectCallback()` defined as:
```
  const onRedirectCallback = (appState) => {
    props.history.push(appState?.returnTo || window.location.pathname);
  };
```

Again, this all works properly when the redirect URI is ``` `${window.location.origin}/callback` ```, but then no third-party authentication takes place.

Is this a different issue? If so, I can open a new issue.

**Comment by jrobber** [comment]
For anyone else coming here, to fix these issues in my react & react-router-dom app I had to:

add this to `<Auth0Provider:
```
useRefreshToken={true}
cacheLocation={'localstorage'}
```

Use this as my onRedirectCallback:

```
onRedirectCallback={appState => {        
      history.replace(appState?.returnTo || window.location.pathname);
      history.go(0);
}}
```

Manually set the returnTo on login:
```
 loginWithRedirect({
      appState: {
        returnTo: window.location.pathname,
      },
    });
```

In the Auth0 dashboard the callbackUrl and allowedWebOrigins had to match the root of my react app.
