### ISSUE TITLE
Custom Auth URL-Endpoint

### ISSUE THREAD

**Issue by danielsogl** [auth0/auth0-react#149]
My application uses two different auth endpoints. For development, I use an Auth0 tenant and for production our custom OpenID Connect backend. The problem is that I'm unable to overwrite the '/authorize' route from the domain I pass to the Authprovider.

It should be possible to change also the Auth-URL and not only the domain

**Comment by frederikprijck** [comment]
The Authorize URL is created as part of our SPA JS SDK, which this React SDK wraps. Both SDKs are specific for Auth0 and not intended as a generic OpenID compliant SPA SDK.

So there is no way for you to change the URLs if you can not use the Auth0 URLs.

On top of that, our internals make other assumptions besides the URLs about using Auth0.
