### ISSUE TITLE
Support running Auth0 callback on callback route only

### ISSUE THREAD

**Issue by aaronadamsCA** [auth0/auth0-react#152]
In short, I don't want `Auth0Provider` to run its callback on every page; I want to call the callback explicitly from the callback route only.

Similar to #75, we have non-Auth0 OAuth use cases in our app (registered users authorizing us to access their Shopify/Instagram accounts). `Auth0Provider` is interfering with these flows; as soon as `state` appears in the query parameters, this triggers the Auth0 callback, causing an authentication error.

I don't think Auth0 should look at those query parameters anywhere other than on its defined callback route, and I'd like to restrict the callback to run only on the correct callback route.

**Comment by aaronadamsCA** [comment]
I just saw #126 and it does look like that could solve my problem; it does seem very backwards to run the callback everywhere and then abort it everywhere except the callback route - I'd have preferred to actually implement a callback route - but if it works I'll take it.

Hopefully this change can be released soon.

**Comment by adamjmcgrath** [comment]
Hi @aaronadamsCA - thanks for raising this

>  it does seem very backwards to run the callback everywhere and then abort it everywhere except the callback route - I'd have preferred to actually implement a callback route

This SDK doesn't provide a router or assume that you have a router, so providing a callback route would not be possible.

We'll be releasing #148 next week, closing for now - feel free to reopen if it doesn't work out for you.

**Comment by aaronadamsCA** [comment]
@adamjmcgrath Friendly off-topic heads-up, I built my own package from `master` (`@shopnishe/auth0-react@1.1.1`) and it's broken; `useAuth0` is kicking my Gatsby app into an infinite loop.

I tried again by rebasing from `v1.1.0` and picking only #148, and your change is working great for me now, thank you (`@shopnishe/auth0-react@1.1.0-patch`).

So it seems one of your other commits since v1.1.0 breaks auth in (at least) Gatsby.

**Comment by adamjmcgrath** [comment]
Thanks for the heads up @aaronadamsCA! Our create react app and Gatsby tests are [failing](https://app.circleci.com/pipelines/github/auth0/auth0-react/295/workflows/d474e81c-18e7-40b8-acdc-d29522069ea3/jobs/307/tests) but the CI wasn't picking it up.

It's an issue with https://github.com/auth0/auth0-react/pull/146 and (to a lesser extent) our use of `ProtectedRoute` in [the Gatsby example](https://github.com/auth0/auth0-react/blob/master/examples/gatsby-app/src/components/ProtectedRoute.js) and [Create React App example](https://github.com/auth0/auth0-react/blob/master/examples/cra-react-router/src/ProtectedRoute.tsx)

**Comment by adamjmcgrath** [comment]
Raised #155 - which I'll fix before releasing
