### ISSUE TITLE
When signing up users, we can only redirect them to the Auth0 login form

### ISSUE THREAD

**Issue by jgresham** [auth0/auth0-react#153]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> When signing up users, we can only redirect them to the Auth0 login form
### Describe the ideal solution

> Redirect users directly to Auth0 Sign up form
## Alternatives and current work-arounds

> Users signing up have to navigate to the login form, scroll down and click the Sign up button. This is not ideal as we would like to have a sign up and log in button on our website. I checked the https://auth0.github.io/auth0-react/interfaces/redirectloginoptions.html to see if there was an option for 'sign up', but there is not. Please add this or a new method called auth0.signupWithRedirect()

**Comment by stevehobbsdev** [comment]
Hey @jgresham, I appreciate that this isn't obvious but you're able to achieve this by setting `screen_hint` to `signup`, and your users should see the "sign up" page first.

**Note:** this assumes that you have configured your Universal Login page to the "New" experience.

```jsx
ReactDOM.render(
  <Auth0Provider
    domain="YOUR_AUTH0_DOMAIN"
    clientId="YOUR_AUTH0_CLIENT_ID"
    redirectUri={window.location.origin}
    screen_hint="signup"
  >
    <App />
  </Auth0Provider>,
  document.getElementById('app')
);
```

See [the docs](https://auth0.com/docs/universal-login/new-experience#signup) for more info. This param doesn't currently appear in the options for our SDKs, but it is an option accepted by the login endpoint and our SDKs generally allow you to send arbitrary parameters through, in addition to the ones we mention in the SDK docs, like `domain` and `clientId`.

Does this help?

**Comment by jgresham** [comment]
Thanks for the response @stevehobbsdev! I would still like to use the SDK to either take the user directly to the sign up form or directly to the login form based on which button they click.

It appears that this works! 
`auth0.loginWithRedirect({ screen_hint: "signup" })`
and `auth0.loginWithRedirect({ screen_hint: "login" })`

**Comment by stevehobbsdev** [comment]
Perfect! Glad you got it working :)

**Comment by jgresham** [comment]
@stevehobbsdev it would be great to put screen_hint in the docs for https://auth0.github.io/auth0-react/interfaces/redirectloginoptions.html . If you point me to a guide to generate docs, I can submit a PR for this.

**Comment by stevehobbsdev** [comment]
@jgresham Thanks. This is already something we're discussing internally as part of a bigger thing across a few of our SDKs.
