### ISSUE TITLE
Support for React 17

### ISSUE THREAD

**Issue by cgault** [auth0/auth0-react#159]
i see that master has peer dependency of "16... || 17" but the latest tagged version does not - and that the latest npm does not - i am trying to start a project with react17 using my auth0 account, but npm will not resolve the dependencies as it is today - i am using a freshly created react app using create-react-app

> npm install @auth0/auth0-react
npm ERR! code ERESOLVE
npm ERR! ERESOLVE unable to resolve dependency tree
npm ERR! 
npm ERR! While resolving: fplink@0.1.0
npm ERR! Found: react@17.0.1
npm ERR! node_modules/react
npm ERR!   react@"^17.0.1" from the root project
npm ERR! 
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.11.0" from @auth0/auth0-react@1.1.0
npm ERR! node_modules/@auth0/auth0-react
npm ERR!   @auth0/auth0-react@"*" from the root project
npm ERR! 
npm ERR! Fix the upstream dependency conflict, or retry
npm ERR! this command with --force, or --legacy-peer-deps
npm ERR! to accept an incorrect (and potentially broken) dependency resolution.

**Comment by frederikprijck** [comment]
> i see that master has peer dependency of "16... || 17" but the latest tagged version does not

This should be solved once https://github.com/auth0/auth0-react/pull/158 is merged and a release is cut.

**Comment by adamjmcgrath** [comment]
Hi @cgault - this has been released in 1.2.0
