### ISSUE TITLE
Example using custom login UI

### ISSUE THREAD

**Issue by charklewis** [auth0/auth0-react#161]
### Describe the problem you'd like to have solved

I am not able to find any examples of how to use the `auth0-react` SDK with a custom login. 

### Describe the ideal solution

An example of how to integrate this SDK with a custom login. The docs are great for getting started but don't give much support in wanting to go further.
## Alternatives and current work-arounds

I am currently exploring this with the web SDK. This means I am loading two sdks in my project.

**Comment by adamjmcgrath** [comment]
Hey @charklewis - `auth0-react` uses the [Universal Login](https://auth0.com/docs/universal-login), it's not possible to use it with a custom login.

We recommend you use the Universal Login page for SPAs, but if you still want create a custom login yourself - you can checkout https://github.com/auth0/auth0.js

**Comment by charklewis** [comment]
Thanks @adamjmcgrath. Does it mentioned this anywhere in the docs, and how to migrate to using `auth0.js` once you have outgrown `auth0-react`? Do you know if there is any plans on having `auth0-react` support custom login?

**Comment by adamjmcgrath** [comment]
Hi @charklewis 

> Does it mentioned this anywhere in the docs

It's on our docs site https://auth0.com/docs/libraries/auth0-react, but I'll have a think about where I can add it on the readme

> how to migrate to using auth0.js once you have outgrown auth0-react?
> Do you know if there is any plans on having auth0-react support custom login?

Logging in via the Universal Login Page is our recommended way of logging in via a SPA (more info: https://auth0.com/docs/universal-login/universal-vs-embedded-login#universal-login-with-auth0). So no plans to support custom login on auth0-react and no migration guides for auth0-react to auth0.js

We actually have the reverse https://auth0.com/docs/libraries/auth0-single-page-app-sdk/migrate-from-auth0-js-to-the-auth0-single-page-app-sdk (auth0-spa-js is the library that auth0-react is based on)
