### ISSUE TITLE
Question around handling different application sessions

### ISSUE THREAD

**Issue by VED-StuartMorris** [auth0/auth0-react#162]
Posting this question here, but can also be seen in support. 
https://support.auth0.com/tickets/00472410

Posting here to see if there is any React specific context that could help get around this issue.

**Context**:
We have two applications, one is a React SPA and the other is a .NET Application. Both have the same surroundings, so you wouldn't know as a user which application you are accessing.
The React SPA only has protected routes, when you access the application, you are sent to the auth server, once auth'd you have an application session (specific for the React app).
If you then navigate to the .net application, you are not logged in. If you click on the Login button/link you would be challenged for auth, hit the auth server and returned with an application session.

**Expectation**:
We are trying to avoid the user having to click login on the .net application. As the applications look the same, the user should only login once and be shown the relevant information in both applications that they are logged in. 

**Attempts**
When talking to our consultant, we thought we could have a login-post endpoint on the .Net application. When the React application loads (after auth) we call a useEffect to post to that endpoint.
```
  useEffect(() => {
    async function postVEDLogin() {
      postLogin();
    }

    if (isAuthenticated) {
      postVEDLogin();
    }
  }, [user, isAuthenticated]);
```
This just does a POST to the endpoint. 

The issue we have at the moment relates to CORS:
Access to fetch at 'https://CUSTOM_DOMAIN/authorize?....' (redirected from 'https://OUR_DOMAIN_NETAPP/login-post') from origin 'https://OUR_DOMAIN_REACT_APP' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

**Question**
Is this possible in any other way? Can anyone provide any information on how we could get this working from the React side? 

We do not need to worry about the .NET application session first, because when accessing the React app all routes are protected and so auth is handled on access. It's just when you login via the React app first, we need to create an application session on the other application (.net).

**Comment by adamjmcgrath** [comment]
Hi @VED-StuartMorris - I would suggest you do the following:

- enable seamless sso on your tenant https://auth0.com/docs/get-started/dashboard/enable-sso-for-legacy-tenants
- user logs in to your react app, creates session in your tenant `CUSTOM_DOMAIN`
- user visits your .NET app
- your .NET app detects no local session so redirects the user to `CUSTOM_DOMAIN/authorize` with "prompt=none"
- user redirects back to your .NET app and is logged in

Because the user is not prompted for a login the experience of going from the react app to the .net app should be seamless

```
REACT_APP -- visit --> NET_APP -- login redirect --> TENANT -- active session/redirect --> .NET_APP
```

**Comment by frederikprijck** [comment]
Closing this at it looks like it was answered. If not, please continue the conversation and we can re-open if needed.
