### ISSUE TITLE
Support refresh token rotation

### ISSUE THREAD

**Issue by oneillsp96** [auth0/auth0-react#164]
The auth0 docs recommend refresh token rotation, but currently it is only available for the SPA sdk

[https://auth0.com/docs/flows/authorization-code-flow-with-proof-key-for-code-exchange-pkce](url)

**Comment by frederikprijck** [comment]
`Auth0-React` uses `SPA SDK`, it mainly provides React entry points and wrappers to make using SPA SDK in React easier, so Refresh Token Rotation is supported. If you would enable Refresh Token Rotation in your Auth0 Application dashboard, and configure the Auth0 Provider in React with `useRefreshTokens={true}` (https://github.com/auth0/auth0-react/blob/master/src/auth0-provider.tsx#L95), your application should be using Rotating Refresh Tokens.

Closing this, but if you are facing problems with getting Refresh Token Rotation to work, please provide more information and we can reopen.
