### ISSUE TITLE
Allow popup logins in withAuthenticationRequired

### ISSUE THREAD

**Issue by Vivalldi** [auth0/auth0-react#166]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved
My react app can be loaded in an iframe (and in a normal window at times). In order to perform auth, it's best to use the `loginWithPopup`. This however isn't possible with the `withAuthenticationRequired` HOC 

### Describe the ideal solution
`withAuthenticationRequired` options accepts field that can be toggled to enable/disable popup login. By default this can default to using redirect login. 

```jsx

export default withAuthenticationRequired(component, { popup: true })
```

## Alternatives and current work-arounds
The only workaround is to ensure that a login occurs by using an onclick event for the navigation links. Doesn't work if the iframe loads at the route with a `withAuthenticationRequire` component.

**Comment by adamjmcgrath** [comment]
Hey @Vivalldi - thanks for raising this

This looks like a valid use case, we will add something to our backlog - in the meantime, you could create your own `withAuthenticationRequired` using https://github.com/auth0/auth0-react/blob/master/src/with-authentication-required.tsx as an example - it uses only public APIs so you should be good to duplicate it. We're also happy to accept PRs if you'd like to have a go at it.

**Comment by adamjmcgrath** [comment]
Leaving a simple example of how you might do this here.

```js
const withAuthenticationRequired = (Component, options) => {
  function WithAuthenticationRequired(props) {
    const { isAuthenticated, isLoading, loginWithPopup } = useAuth0();

    useEffect(() => {
      if (isLoading || isAuthenticated) {
        return;
      }
      (async () => {
        await loginWithPopup(opts);
      })();
    }, [ isLoading, isAuthenticated, loginWithpopup, options ]);

    return routeIsAuthenticated ? <Component {...props} /> : null;
  };
};
```

Am reluctant to add this, as the popup will most likely be blocked by the user agent (when loading the route doesn't come from a user interaction)

Will review this decision if I get anymore info about this.
