### ISSUE TITLE
Handle the user closing the window

### ISSUE THREAD

**Issue by aaronadamsCA** [auth0/auth0-react#168]
Right now if I call `loginWithPopup()` and the user closes the pop-up window without logging in, they need to wait for the full duration of the timeout before an error is thrown. Then I need to handle this timeout error differently from other errors.

It would be preferable if the library could clear the login timer and set `isLoading = false`, to return the window to its state prior to the user clicking the login button.

**Comment by frederikprijck** [comment]
Thanks for reporting this.
This is a known issue in the `auth0-spa-js` SDK, which the `auth0-react` SDK is using, see https://github.com/auth0/auth0-spa-js/issues/599.

I am keeping this open to track the fact this is not supported in our React SDK. But most of the work will need to happen in  `auth0-spa-js`.

**Comment by aaronadamsCA** [comment]
Thanks @frederikprijck, I'll be following that issue!

**Comment by aaronadamsCA** [comment]
@frederikprijck It looks like the work has been competed in the upstream library:

https://github.com/auth0/auth0-spa-js/pull/724

I tried writing a PR but quickly found I have no idea how to write tests. 🙂

Hopefully you can add this support soon, as it's quite nice to close the window and have the application immediately return to a usable state. Thanks!

**Comment by adamjmcgrath** [comment]
Released in [1.5.0](https://github.com/auth0/auth0-react/releases/tag/v1.5.0) 🎉

**Comment by esperancaJS** [comment]
This is back to not working :s

**Comment by saadman13** [comment]
@adamjmcgrath @frederikprijck - It seems to be not working as @esperancaJS mentioned. 

This is what I am trying to do, but no error is being thrown when the user closes the popup without completing the steps.

```
import { useAuth0 } from '@auth0/auth0-react';
 const { loginWithPopup } = useAuth0();
 try {
   await loginWithPopup({
     audience: `https://${getWebsocketBaseUrl()}/api`,
     enroll_mfa: true,
    });
 } catch (e) {
      console.debug('Popup was closed before login completed');
 }
```

The version of auth0-react we are using is` "@auth0/auth0-react": "1.12.1"`

Appreciate the help!
