### ISSUE TITLE
`getIdTokenClaims` fails silently when passing `audience` parameter

### ISSUE THREAD

**Issue by cihati** [auth0/auth0-react#169]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

`getIdTokenClaims` works when it's not passed an `options` argument, or if it's passed `{audience: "default"}` or `{audience: <WHATEVER_IS_IN_audience_PARAMETER_OF_Auth0Provider>}`. However, if I pass some other value, it becomes `undefined`.

### What was the expected behavior?

Throw an exception in case of failure? To be perfectly honest, my expectation is that if I pass `audience` and then get the token using `__raw`, the token I get has the `audience` I pass. My understanding might be incorrect, in which case, I think the documentation must be enriched.

### Reproduction

```
    const claims = await getIdTokenClaims({
      audience: Config.auth.audience,
    });
    return claims.__raw;
```
=> `Cannot read property '__raw' of undefined`

```
    const claims = await getIdTokenClaims();
    return claims.__raw;
```
=> works fine

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.2.0
- **Which browsers have you tested in?** Chrome 86.0.4240.198
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
We will need more information to be able to understand your problem better.

A little background on how `getIdTokenClaims` works:

- When you get a token using `getAccessTokenSilently`, you can pass an (optional) audience. Let's say we pass `AudienceA` here. 
- When the token is retrieved, it will be stored in the SDK's cache internally. Our SDK now is aware of a token that matches `AudienceA`.
- Wen you call `getIdTokenClaims` it will:
  - Try retrieving the token from the cache using the specified 
  - If a token was found: Parse it and return the claims
  - If no token was found: return undefined.

As you can see, if you pass anything other then `AudienceA` as the audience when calling `getIdTokenClaims`, it will return undefined.

I can not determine based on the information provided, but it looks like you are passing an audience for which no token has been retrieved. In that case, returning undefined is expected.

**Comment by cihati** [comment]
Thanks for providing more information @frederikprijck. A few things:

* In you first bullet point, you mention `getAccessTokenSilently` -- is it correct if I'm trying to get an *id* token as well?
* I think my situation is exactly as you described, so it's working as intended. However, it'd be super useful if this information is put into the documentation directly. Most of these nuances are not documented anywhere.

Thanks!

**Comment by frederikprijck** [comment]
Calling `getAccessTokenSilently` will also retrieve an idToken and store it internally in the SDKs cache. However, `getAccessTokenSilently` will only return the Access Token as a string, that is why it is named `getAccessTokenSilently`.

**Comment by cihati** [comment]
@frederikprijck awesome -- these answer all my questions. I'd highly suggest encapsulating these extra bits of information within the docs (happy to be put in as a PR reviewer too). Many thanks!

**Comment by frederikprijck** [comment]
I will keep this issue open to see how we can improve here.

**Comment by adamjmcgrath** [comment]
I'm going to close this issue off as it's been inactive for a little while - happy to accept a PR if anyone has suggestions for how we can improve the docs

**Comment by cihati** [comment]
@adamjmcgrath I think it's obvious that there are gaps in the documentation -- if all the information was in the docs I wouldn't bother @frederikprijck and wouldn't be slowed down myself.

As a paying customer of Auth0, I'd expect the team to handle the documentation update (rather than expecting the paying customers to do it for you)

**Comment by adamjmcgrath** [comment]
Hey @cihati - apologies, let me reopen this for you. I'll catch up with @frederikprijck this week to see what we can do.

**Comment by islami00** [comment]
Hello, 
I came across this same issue while using this package,
I was relying on the typescript types and inline documentation from the underlying auth0-spa-js package and they both show that `getIdTokenClaims` returns a  `Promise<IdToken>`

* From `Auth0ContextInterface` definition in `auth0-context.ts` :   
```ts
getIdTokenClaims: (options?: GetIdTokenClaimsOptions) => Promise<IdToken>;
```
* From the `Auth0Client` definition in `Auth0Client.d.ts`:     
```ts
getIdTokenClaims(options?: GetIdTokenClaimsOptions): Promise<IdToken>;
```

My package version is: `"@auth0/auth0-react": "^1.5.0",`
