### ISSUE TITLE
unable to set `useCookiesForTransactions`

### ISSUE THREAD

**Issue by weyert** [auth0/auth0-react#170]
### Describe the problem

I am trying to set the `useCookiesForTransactions`-option that comes with `@auth0/spa-js` but it's not possible to use it through `auth0-react`. Instead of passing it as Auth0 client option its instead included in the authorise url.

### What was the expected behavior?
I would expect that the `useCookiesForTransactions`-option is passed to the `Auth0Client`-class instead of being passed to the authorise url

### Reproduction

- Step 1: Open `static/index.html` in your favourite editor
- Step 2: Go to line 87 which should be `redirectUri={window.location.origin}` 
- Step 3: Add a new line below this with the following `useCookiesForTransactions={true}`
- Step 4: Run `npm run start` from the command-line

Now when you try to login by pressing `login with redirect` and you analyse the network requests you will notice that the parameter `&useCookiesForTransactions=true` is included in the authorise url below:

```
https://brucke.auth0.com/login?state=g6Fo2SBZbXhwanVvY1BVSms0VGVCdU5IYVROYkMwZ1p0VlVHNaN0aWTZIGJlTm9odG9qRTRIQWU1M0pNWmVremNLMklwQnVqb1dno2NpZNkgd0xTSVA0N3dNMzl3S2REbU9qNlpiNWVTRXczSlZoVnA&client=wLSIP47wM39wKdDmOj6Zb5eSEw3JVhVp&protocol=oauth2&useCookiesForTransactions=true&redirect_uri=http%3A%2F%2Flocalhost%3A3000&scope=openid%20profile%20email&response_type=code&response_mode=web_message&nonce=cWFwY3E2ZFYzTlBnY2hweUJvZ1BwRWJoSmZaMFNNUjl0Z2cuYS4tbjhnNg%3D%3D&code_challenge=YrB6_784L3DfCRO0cvlFAAq65SDdUcImGboVleCxIDM&code_challenge_method=S256&auth0Client=eyJuYW1lIjoiYXV0aDAtcmVhY3QiLCJ2ZXJzaW9uIjoiMS4yLjAifQ%3D%3D
```

### Environment
master branch

- **Version of `auth0-react` used: *master*
- **Which browsers have you tested in? *Firefox*
- **Which framework are you using, if applicable (Angular, React, etc): *React*
- **Other modules/plugins/libraries that might be involved: *None*

**Comment by frederikprijck** [comment]
Thanks for raising this @weyert.
The fact that it is sent as part of the URL to `/authorize` is caused by `@auth0/auth0-spa-js`, so that is nothing `auth0-react` can resolve.

However, `useCookiesForTransactions` has been available as of `@auth0/auth0-spa-js` 1.13.0. The playground we have available uses `1.7`, so if u change that to use `https://cdn.auth0.com/js/auth0-spa-js/1.13.5/auth0-spa-js.production.js`, `useCookiesForTransactions` should work as expected.

**Comment by weyert** [comment]
Thank you :)
Yeah, seems to work, I do think that the use of local storage is confusing in general. If you enable `cacheLocation` = `memory` it's still  using local storage in other areas (e.g. browser-tab-lock). As my experience is that when third party cookies are disabled you neither can access local storage.

**Comment by frederikprijck** [comment]
Browser tab lock is solving a locking issue in the browser, which can not rely on memory as that is not shared across tabs to handle the locking.

The library is relying on local-storage to set a lock on a specific request to ensure other tabs do not execute the same request, which is needed when using Refresh Token Rotation.

**Comment by weyert** [comment]
Thank your for your response. You are suggesting that third party cookies are required to allow this or spa library to work. I will raise a ticket with the `spa`-library and see what they say.
