### ISSUE TITLE
AbortController is not defined

### ISSUE THREAD

**Issue by alexislucas-toast** [auth0/auth0-react#173]
### Describe the problem

Hi! On Firefox 52 (and probably other browsers versions that doesn't support AbortController API), the `getAccessTokenSilently` method will throw this error. It seems like this API is used in `@auth0/auth0-spa-js`, and there is a Polyfill for this API, but it isn't working. And it's probably the case for any browser version that doesn't support natively this API (https://developer.mozilla.org/en-US/docs/Web/API/AbortController).

Here is the stack trace I have when catching errors from the `getAccessTokenSilently`:

```
10:34:13.434 Error: AbortController is not defined
Stack trace:
OAuthError@http://localhost:3000/static/js/0.chunk.js:3816:17
["../../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js"]/</normalizeErrorFn/<@http://localhost:3000/static/js/0.chunk.js:3841:14
["../../node_modules/@auth0/auth0-react/dist/auth0-react.esm.js"]/</Auth0Provider/getAccessTokenSilently</</<@http://localhost:3000/static/js/0.chunk.js:4127:19
step@http://localhost:3000/static/js/0.chunk.js:210:12
verb/<@http://localhost:3000/static/js/0.chunk.js:141:14
rejected@http://localhost:3000/static/js/0.chunk.js:103:14
 1 0.chunk.js:83125:18
	["../../node_modules/react-error-overlay/lib/index.js"]/</</</g/console[e] http://localhost:3000/static/js/0.chunk.js:83125:18
	ExportAuth/</< http://localhost:3000/static/js/main.chunk.js:3009:7
```

### What was the expected behavior?

The `getAccessTokenSilently` should not fail because of AbortController API being undefined on browsers versions that don't support this API natively.

### Reproduction

I'm working on a Private instance in Auth0, so I can't share client id, etc. And it seems that I can't make the examples working locally, but the private repository I'm working on is very simple, so I think you should be able to reproduce it by setting up the example and running it on Firefox 52.

### Environment

- **Version of `auth0-react` used:** 1.2.0
- **Which browsers have you tested in?** Firefox 52, Chromium 65
- **Which framework are you using, if applicable (Angular, React, etc):** React 16.13.1
- **Other modules/plugins/libraries that might be involved:** indirect dependency with auth0-spa-js: 1.13.5

**Comment by frederikprijck** [comment]
Thanks for raising.
As you mentioned, this issue originated in our `@auth0/auth0-spa-js` package so there is nothing the React SDK can do to resolve this.

Just to be sure, can you confirm that you are using Refresh Tokens and that the issue goes away when you are not using Refresh Tokens @alexislucas-toast ?

**Comment by alexislucas-toast** [comment]
Thank you for your answer!

I understand, I was hesitant to create an issue in `@auth0/auth0-spa-js` as there was already a closed issue about AbortController, so I thought I would give it a try here. I think I'll move it there.

Yes, it seems to work fine when not using refresh tokens. And we are trying to move forward the adoption of recent browsers, but it's not always possible. Anyway, that's a different discussion that we have internally. The thing is that the library is using a polyfill internally, which should fix the issue for older browsers, but it is not. That's what I wanted to raise here.

**Comment by dev-usa** [comment]
Trying to use this in a node module and receiving the `AbortController is not defined` error. Please see below. Tried using [this polyfill](https://github.com/mo/abortcontroller-polyfill) but could not get it to work. Any suggestions?

```shell
2022-01-05T19:28:56.943Z        undefined       ERROR   Uncaught Exception      {"errorType":"ReferenceError","errorMessage":"AbortController is not defined","stack":["ReferenceError: AbortController is not defined","    at Object.<anonymous> (/var/task/node_modules/cockatiel/dist/common/abort.js:7:34)","    at Module._compile (internal/modules/cjs/loader.js:1085:14)","    at Object..js (internal/modules/cjs/loader.js:1114:10)","    at Module.load (internal/modules/cjs/loader.js:950:32)","    at Function._load (internal/modules/cjs/loader.js:790:14)","    at Module.require (internal/modules/cjs/loader.js:974:19)","    at require (internal/modules/cjs/helpers.js:92:18)","    at Object.<anonymous> (/var/task/node_modules/cockatiel/dist/CircuitBreakerPolicy.js:4:17)","    at Module._compile (internal/modules/cjs/loader.js:1085:14)","    at Object..js (internal/modules/cjs/loader.js:1114:10)"]}
time="2022-01-05T19:28:56.95" level=panic msg="ReplyStream not available"
```
