### ISSUE TITLE
Gatsby Example Does Not Work on Firefox

### ISSUE THREAD

**Issue by osseonews** [auth0/auth0-react#174]
### Describe the problem

We followed the instructions to install this on Gatsby. We are using the code below for the "login"
`<a href="/" onClick={() => loginWithRedirect()}>`

On Chrome, and Safari, this works and the user is sent to Auth0 form to login (i.e. https://OURWEBSITE.auth0.com/login. On Firefox, however, when the user clicks on the Login Link, the page simply reloads the user is not sent to the log in URL: https://OURWEBSITE.auth0.com/login

The error that is shown in firefox is: NS_BINDING_ABORTED on the GET method to the Auth0 login URL.

### What was the expected behavior?

The Loginwithredirect should work on all browsers.

### Reproduction

Follow steps to install auth0-react on Gatsby. Try to log in with Firefox.

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** ^1.2.0
- **Which browsers have you tested in?** All. Doesn't work Firefox.
- **Which framework are you using, if applicable (Angular, React, etc):** React and Gatsby

**Comment by frederikprijck** [comment]
@osseonews 

Could you see if the issue persists if you use a button instead of a link?
In general it is confusing to use an `a` element that both has an `href` attribute set as well as an `onClick`.

**Comment by osseonews** [comment]
Thanks. Changing to a button fixed the issue.

**Comment by lamellama** [comment]
Had a similar issue with https://github.com/gatsbyjs/gatsby-starter-shopify which uses ChakraUI, the <Button> component requires
`type={"button"}`
to avoid crashing firefox
