### ISSUE TITLE
Invalid state error when opening many tabs at the same time

### ISSUE THREAD

**Issue by deita0x** [auth0/auth0-react#175]
Hello

I have a SPA application and I have implemented the authentication as detailed here https://auth0.com/docs/quickstart/spa/react/01-login however on some occasions when many browser tabs are opened at the same time, auth throws this error:
`Error: Invalid state` even though `isAuthenticated` is `true` and `user` contains the user's data

Steps to Reproduce:

- Log in
- Open many tabs at once

My code:
```
const { isAuthenticated, error, isLoading, user } = useAuth0();

  useEffect(() => {
    if (error) {
      // Sometimes this error is Error: invalid state
    }

    if (!isLoading && !error && !isAuthenticated) {
      loginWithRedirect();
    }

    // ...
  }, [isLoading, isAuthenticated, error]);
```

**Comment by frederikprijck** [comment]
Thanks for raising this.

Could you please provide a reproduction sample so we can investigate what is going wrong?

Are you logging in before opening a new tab ? 
What is the URL you are using in all the different tabs, does it include code and state in the URL?

**Comment by adamjmcgrath** [comment]
Hi @deita0x - we haven't heard from you in a while, so I'm going to close this issue. Feel free to reopen it if you want any more help
