### ISSUE TITLE
User can login without RBAC permissions

### ISSUE THREAD

**Issue by Legion2** [auth0/auth0-react#179]
### Describe the problem you'd like to have solved
I use Auth0 and RBAC for an API. Only users with the required permissions are allows to access the API. This works on the server side by validating the scopes of the access token. But in react users without the required permissions still successfully login and get an access token. The token does not contain the required claims (scopes) which are requested in the `Auth0Provider`. Also when using `getAccessTokenSilently` and specify a specific scope and the user does not have permissions of that scope, an access token is return without the required scope, which is useless to make a request to the API.

When the user logs in there is no hint or notice that he/she has not the required permission, which were requested by the application. 

### Describe the ideal solution
`getAccessTokenSilently` should throw an exception instead of returning an access token which does not have the requested scope.
## Alternatives and current work-arounds

One must manually check if the requested scope is contained in the IdToken claims using the `getIdTokenClaims` function.

**Comment by adamjmcgrath** [comment]
Hi @Legion2 - thanks for raising this

> One must manually check if the requested scope is contained in the IdToken claims using the getIdTokenClaims function.

Yep, this is our current best practice for implementing RBAC in a SPA

Closing this for now, feel free to reopen if you have any other questions

**Comment by Legion2** [comment]
for reference https://community.auth0.com/t/checking-user-scopes-in-react-spa/41410
