### ISSUE TITLE
Legacy context API has been detected within a strict-mode tree.

### ISSUE THREAD

**Issue by Jay-study-nildana** [auth0/auth0-react#180]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I am starting with a fresh copy of react js app with typescript. It has not other components. I wanted to add Auth0 first. I ran into this warning in the console. 

I am new to React JS programming, yes (but not new to programming itself. .NET API developer for 8 years). However, this warning appeared immediately after adding Auth0 components to my landing page. any code I have written is borrowed from the latest version of the Auth0 React Sample. So, I am inclined to believe it might be a issue with Auth0-React.

```
Warning: Legacy context API has been detected within a strict-mode tree.

The old API will be supported in all 16.x releases, but applications using it should migrate to the new version.

Please update the following components: Transition

Learn more about this warning here: https://reactjs.org/link/legacy-context
Transition@http://localhost:3000/static/js/0.chunk.js:49356:30
Fade@http://localhost:3000/static/js/0.chunk.js:57480:13
Alert@http://localhost:3000/static/js/0.chunk.js:53941:19
div
Hero
Home
Route@http://localhost:3000/static/js/0.chunk.js:47766:29
Switch@http://localhost:3000/static/js/0.chunk.js:47968:29
Router@http://localhost:3000/static/js/0.chunk.js:47401:30
App
Auth0Provider@http://localhost:3000/static/js/0.chunk.js:3956:18
```

Also, this one. 
```

Warning: findDOMNode is deprecated in StrictMode. findDOMNode was passed an instance of Transition which is inside StrictMode. Instead, add a ref directly to the element you want to reference. Learn more about using refs safely here: https://reactjs.org/link/strict-mode-find-node
div
Transition@http://localhost:3000/static/js/0.chunk.js:49356:30
Fade@http://localhost:3000/static/js/0.chunk.js:57480:13
Alert@http://localhost:3000/static/js/0.chunk.js:53941:19
div
Hero
Home
Route@http://localhost:3000/static/js/0.chunk.js:47766:29
Switch@http://localhost:3000/static/js/0.chunk.js:47968:29
Router@http://localhost:3000/static/js/0.chunk.js:47401:30
App
Auth0Provider@http://localhost:3000/static/js/0.chunk.js:3956:18
```

### What was the expected behavior?

I am planning to use Strict Mode and React 17 in my new project. So, I was hoping not to have this big large warning in my project. 

Please note, I already have another react app (using one of your existing samples) working just fine. However, the react sdk sample has so many old libraries, it is no longer feasible to use that. In fact, i have already raised a issue on that here. 

https://github.com/auth0-samples/auth0-react-samples/issues/212

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

It's fairly easy to reproduce the issue. 

- Create a brand new react app with. For example, npx create-react-app quote3point0 -–template typescript

- Try and include Auth0Provider, run the app, check the console. (Please note : the app runs just fine)

```
ReactDOM.render(
  <Auth0Provider
  domain={config.domain}
  clientId={config.clientId}
  audience={config.audience}
  redirectUri={window.location.origin}
  scope = {config.scope}
>
  <React.StrictMode>
    <App />
  </React.StrictMode>,
  </Auth0Provider>,  
  document.getElementById('root')
);
```

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

I would like to but I am using React 17.X. I think playground is using an older version. 

I am sort of new to react development, so, I am not even sure if this is an issue. But, I am posting it here so someone can point me in the right direction. I am already using Auth0 on my API server, so, I really need to get this react demo working for a client of mine, and I cannot have this big red warning on day one. 

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-react` used:**

```
{
  "name": "quote3point0",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@auth0/auth0-react": "^1.2.0",
    "@testing-library/jest-dom": "^5.11.4",
    "@testing-library/react": "^11.1.0",
    "@testing-library/user-event": "^12.1.10",
    "react": "^17.0.1",
    "react-dom": "^17.0.1",
    "react-scripts": "4.0.1",
    "reactstrap": "^8.8.1",
    "web-vitals": "^0.2.4"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },
  "eslintConfig": {
    "extends": [
      "react-app",
      "react-app/jest"
    ]
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-router-dom": "^5.1.7",
    "react-router-dom": "^5.2.0",
    "typescript": "^4.1.3"
  }
}
```

- **Which browsers have you tested in?**

Currently using Firefox but the issue comes up on any browser.

- **Which framework are you using, if applicable (Angular, React, etc):**
included package.json above.
- **Other modules/plugins/libraries that might be involved:**
included package.json above

Please let me know if there is any more information I can help you with. Thank you.

**Comment by Jay-study-nildana** [comment]
Folks,

It seems obvious but, the sample does not use <React.StrictMode>. 

So, is that the solution? the SDK is not supposed to work with <React.StrictMode>? If so, it's alright, you can close this as resolved. As I mentioned I am still new so I dont know how important or non important strict mode is for React. 

But, if it is supposed to work, do let me know, how to solve it.

**Comment by adamjmcgrath** [comment]
> Warning: Legacy context API has been detected within a strict-mode tree.
> Please update the following components: Transition

Hi @Jay-study-nildana 

This warning is coming from the `Transition` component. It looks like it comes from `react-transition-group` which is being brought in by your dependency on `reactstrap`

**Comment by Jay-study-nildana** [comment]
@adamjmcgrath 

ah! thank you so much for pointing that out. I am closing this issue and raise this with the folks at reactstrap.
