### ISSUE TITLE
`getAccessTokenSilently` doesn't seem to respect `scope` option

### ISSUE THREAD

**Issue by sw-yx** [auth0/auth0-react#183]
### What was the expected behavior?

when i specify the `scope` option of `getAccessTokenSilently` it should generate a JWT with the different scope

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

1. clone https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01
2. modify the `getAccessTokenSilently` to get a different scope, e.g.
    ```js
          const token = await getAccessTokenSilently({
            audience: 'https://orgs-beta-temporal.us.auth0.com/api/v2/',
            scope: 'default:admin',
          });
    ```
3. observe that the returned JWT sees NO change in scope. it is still the default `"openid profile email"` 

## 2.5 minute Video recording of bug

https://www.loom.com/share/2a56bb28f8524984825a08a7eaeb237c

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.1.0
- **Which browsers have you tested in?** chrome
- **Which framework are you using, if applicable (Angular, React, etc):** react
- **Other modules/plugins/libraries that might be involved:** no

**Comment by frederikprijck** [comment]
Hi @sw-yx ,

Thanks for the video, it helps understanding your situation.

It looks like you are using a scope that does not exist on the API, could that be the case?
When you request `ScopeX` for `AudienceY`, if that audience doesnt have that scope, Auth0 will ignore that. 

So the first thing I would check is verify that your API has the scope registered at the API settings in Auth0:

![image](https://user-images.githubusercontent.com/2146903/103989939-bc3a2600-5190-11eb-8d8c-161839dd7dcd.png)

Once you have that, it should still not work but this tine you should see the following popup in your application after clicking `Ping API`:

![image](https://user-images.githubusercontent.com/2146903/103990036-e0960280-5190-11eb-8266-f27fbedde63c.png)

As mentioned in https://auth0.com/docs/quickstart/spa/react/02-calling-an-api, you also need to provide the scope to the Auth0Provider:

```
<Auth0Provider
    ...
    scope="default:admin"
  >
    <App />
  </Auth0Provider>
```

Now you should be asked for consent first, meaning the user has to tell Auth0 that the application is allowed to use that scope on behalve of the authenticated user:

![image](https://user-images.githubusercontent.com/2146903/103990240-2e126f80-5191-11eb-90bf-2a6d44fc452a.png)

Once you accept, and click Call API, this is what your JWT should look like:
![image](https://user-images.githubusercontent.com/2146903/103990335-51d5b580-5191-11eb-8110-7ec30b89e2bf.png)

Let me know is this doesn't work for you.

**Comment by sw-yx** [comment]
thanks so much for your prompt responses Frederik! trying now, will update soon.

for what its worth this is how i found my way here:

- i searched "scopes" in the docs https://auth0.com/docs/search?q=scope&page=1
- found https://auth0.com/docs/scopes and didnt find anything i could use
- looked up the `@auth0/auth0-react` docs where the only mention of scope was in https://auth0.github.io/auth0-react/globals.html#call-an-api

just offering feedback on the info architecture/search experience

**Comment by sw-yx** [comment]
i am still getting insufficient scope errors even after adding the permission thing you pointed out. :( never even got to the point where i can grant consent.

i will sleep on this and retry on monday. thank you for your detailed responses so far, very helpful.

**Comment by frederikprijck** [comment]
@sw-yx Did you also include the scope as part of the Auth0Provider? The idea is that you need to go trough a redirect flow to Auth0 first, give consent for the scope and then ask for a token for that scope.

Without giving consent, Auth0 will not issue a token using that scope. So I would focus on fixing the consent part, and not so much on trying to get access to an API that requires that scope.

Would you have a sample application to share?

**Comment by sw-yx** [comment]
yes i did all that :(


after making a new app, i am currently getting a new error: https://community.auth0.com/t/unauthorizederror-jwt-malformed-in-express-js/7352/9

this is just a hot mess; i'm going to just delete everything and start over. hanging in there!

**Comment by sw-yx** [comment]
i am getting some help from Kiessak; turns out the JWT malformed error was because i had commented out the `audience` field in `Auth0Provider` (because i was trying to follow the tutorial)

**Comment by frederikprijck** [comment]
Closing as we have been able to resolve it offline. It was an issue with RBAC and missing permissions on the user.

**Comment by sw-yx** [comment]
yes, in particular i didn't understand that `getAccessTokenSilently`'s `scope` arg is for scope narrowing, and we need to declare all scopes the app needs at the `Auth0Provider` level first.

**Comment by frederikprijck** [comment]
> we need to declare all scopes the app needs at the Auth0Provider level first.

Just to add a little nuance for this, this is for ensuring the user has given consent. When you are skipping consent for first party applications, this is not realy required, but yet I think it is a good practise to do so.

> - In Auth0's admin panel, make sure the USER has the right permission set, ONLY IF the API has RBAC enabled.
> - In Auth0's admin panel, make sure the API has the right permission set.

Just to avoid confusion, it should be the other way around. You can not set the USER's permissions if you haven't set the API's permissions. So start with the API, then the USER.

**Comment by wayne-o** [comment]
Can someone please explain this part? 

`In Auth0's admin panel, make sure the USER has the right permission set, ONLY IF the API has RBAC enabled.`

Is there a way to set the permission on the user without needing to do it through the admin panel? I'd have thought that adding the audience and scopes to the `Auth0Provider` it would be granting that - surely it can't be a case of manually adding these to each user before they can be issued in tokens?
