### ISSUE TITLE
Get token twice

### ISSUE THREAD

**Issue by bernardomichel** [auth0/auth0-react#185]
### Describe the problem

> I use getTokenSiltently to save access_token in my cookies in order to use it with my API server. I see the networks that the function loginWithRedirect() eventually make a `GET` to `<tenant>/oauth/token`. So, I asked for a token twice, when login and when geTokenSilently().

### What was the expected behavior?

> I need to get the token after loginWithRedirect() finished. Something like:
`loginWithRedirect().then(token => cookies.set('access_token', token))`

### Environment

> Please provide the following:

- auth0-react version: 1.2.0
- Testing in google chrome
- React 
- react-cookies to save cookies.

**Comment by stevehobbsdev** [comment]
@bernardomichel Can you tell us more about your use case? The SDK already stores these tokens for you so that (by default) when you call `getTokenSilently`, you'll either get an access token from our internal cache or it will automatically be renewed for you using the `/oauth/token` endpoint (if your browser does not block third-party cookies).

> I need to get the token after loginWithRedirect() finished

That's not possible to do unfortunately, as `loginWithRedirect()` is a full browser redirect, so there's nothing to wait on.

**Comment by bernardomichel** [comment]
I think that the `getTokenSilently()` always asked for a new token using the `/oauth/token` endpoint.

```
useEffect( () => {
		if(isAuthenticated) {
			// I have token saved in cookies?
			if(cookies.get('access_token')) {
				API.get(...)
			} else {
				// Asked for a Token
				getAccessTokenSilently().then(result => {
					cookies.set('access_token', result, {secure: process.env.NODE_ENV !== 'development', path: '/'});
					API.get(...)
				})
			}
		} else if(!isLoading) {
			// Not logged, loginWithRedirect
			loginWithRedirect()
		}
	}, [isLoading, isAuthenticated])
```

**Comment by bernardomichel** [comment]
Do I need to force `ignoreCache?: boolean` to false?

**Comment by stevehobbsdev** [comment]
> I think that the getTokenSilently() always asked for a new token using the /oauth/token endpoint.

Not always, no. I will use the `expires_in` time from the token call to cache the access token and will use it (by default) until it expires. `ignoreCache` is `false` by default, too.

If you're seeing a call to the token endpoint every time you call it, are you using a particularly short expiry time on your access tokens? (less than 60 seconds, for example).

**Comment by bernardomichel** [comment]
To test it, i set the access_token lifetime to 30seconds. I'll change it to 1hr and try it again

**Comment by stevehobbsdev** [comment]
Anything greater than 60 seconds should work. We have a built-in 60 second leeway where the token will be re-requested before it expires.

**Comment by ptcoregon** [comment]
The 60-second leeway is what was messing me up during testing.
