### ISSUE TITLE
Add an option to `loginWithRedirect` that redirect to the signup page instead of login page.

### ISSUE THREAD

**Issue by totobest** [auth0/auth0-react#189]
### Describe the problem you'd like to have solved
In my app, I know that some users would like to sign up, so I would like the ability to show the `https://<domain>.auth0.com/u/signup` page instead of `https://<domain>.auth0.com/u/login`.

### Describe the ideal solution
Maybe something like :
`loginWithRedirect({signup: true})`

## Alternatives and current work-arounds
I haven't found one yet.

**Comment by frederikprijck** [comment]
Hey @totobest ,

This is already possible, see https://github.com/auth0/auth0-react/issues/59#issuecomment-654333541.
