### ISSUE TITLE
Auth0-react bundled with old version of @auth0/spa-js

### ISSUE THREAD

**Issue by weyert** [auth0/auth0-react#198]
### Describe the problem
Appear that @auth0/spa-js gets bundled with 1.13.1 instead of 1.13.6

I would suggest to release a new version with the more recent version of @auth0/spa-js so we can benefit from the improvements.

**Comment by adamjmcgrath** [comment]
Hi @weyert - if you install the latest version of auth0-react `@auth0/auth0-react@1.2.0` you'll get the latest `@auth0/auth0-spa-js` release that satisifies the semver `^1.13.1` (as specified in the [package.json](https://github.com/auth0/auth0-react/blob/v1.2.0/package.json#L102)), which is currently `1.13.6`

```
⚡ mkdir my-app
⚡ cd my-app
⚡ npm init -f
⚡ npm install @auth0/auth0-react
⚡ npm list @auth0/auth0-spa-js
my-app@0.1.0
└─┬ @auth0/auth0-react@1.2.0
  └── @auth0/auth0-spa-js@1.13.6
```

**Comment by weyert** [comment]
Yeah, but if you then do `cat node_modules/@auth0/auth0-react/dist/auth0-react.cjs.js | grep 1.13.1` in that same directory its referring to 1.13.1 like:

```
return e.prototype._url=function(e){var t=encodeURIComponent(btoa(JSON.stringify(this.options.auth0Client||{name:"auth0-spa-js",version:"1.13.1"})));re
```

Did I misunderstand the code block?
```

**Comment by adamjmcgrath** [comment]
D'oh - you're right @weyert, I forgot we did that - I'm doing a release shortly for #190 so I'll make sure I update the embedded version of SPA js

**Comment by weyert** [comment]
Thank you :)

**Comment by adamjmcgrath** [comment]
no problem! released in https://github.com/auth0/auth0-react/releases/tag/v1.3.0
