### ISSUE TITLE
Better integration with e2e tests (ex. Cypress) using Password Grant flow

### ISSUE THREAD

**Issue by dallonf** [auth0/auth0-react#199]
### Describe the problem you'd like to have solved
Our Cypress test suite, which currently follows the actual Auth0 login flow, is becoming flaky and unreliable. 

I came across this official article, which suggests getting a token directly from the Auth0 API instead of automating the login flow: https://auth0.com/blog/end-to-end-testing-with-cypress-and-auth0/

However, the article assumes a traditional web app architecture, not a Single Page App, and there's no clear way to pass an auth token to the Auth0 React SDK.

## Alternatives and current work-arounds

Still working on finding a reliable workaround. I can mock the requests auth0-react makes to the Auth0 API, and intercept my own responses, but this requires knowledge of this library's implementation details. I could also try to insert the token into localStorage using the `cacheLocation="localStorage"` prop on `Auth0Provider`, but again, that requires knowledge of implementation details. 

Finally, I could try to abstract uses of the Auth0 React SDK (particularly `isAuthenticated`, `getTokenSilently`, and `withAuthenticationRequired`) so that they aren't ever called while using Cypress, but this would require a lot of refactoring, and nullify a lot of the convenience of this library.

**Comment by adamjmcgrath** [comment]
Hi @dallonf - I've put an example of testing SPA JS with the Password Grant flow here https://github.com/adamjmcgrath/cypress-spa-example

The process would be the same for auth0-react as this SDK uses SPA JS under the hood

Let me know if you have any questions about it

**Comment by adamjmcgrath** [comment]
Hi @dallonf - closing due to innactivity. Feel free to ping me to reopen if you have any other questions

**Comment by makinhs** [comment]
Hi @adamjmcgrath, I am facing a similar issue with my react app.
I was able to test your example but it seems I need to have access to checkSession in order to create the login after having the access token from Cypress. 

I am using "@auth0/auth0-react": "^1.2.0"

At Cypress I am using the same configuration from your example, but having my auth0 credentials.

I am wondering if there is any code sample as you provide but using @auth0/auth0-react instead of auth0-spa-js

Thanks in advance!

**Comment by adamjmcgrath** [comment]
Hey @makinhs - I don't have a code sample using auth0-react, but I'd be happy to debug an example app if you had one that demonstrates the problem you're having

**Comment by divinentd** [comment]
Here's an additional solution for anyone who finds this: create a separate user for each test. As Cypress tests they should not be as granular as a unit test, so if you're following that best practice this will not be as much work as it seems.

I also had the requirement that the tests be able to run in parallel, so the solution to login in `before` and then run the tests in sequence would not work.
