### ISSUE TITLE
Improve accuracy of AuthState type definitions

### ISSUE THREAD

**Issue by supermacro** [auth0/auth0-react#201]
#### Main Problem: Usage of `any` on `User` type and hard-to-find information on what `User` really represents

I personally learn more about a library and the set of its possible behaviours by reading the types. Unfortunately, when I stumble upon an `any`, not only do I not gain insight into the meaning of a type, I also now have to deal with extreme ambiguity in my own code.

Specifically, I am referring to the [`AuthState` interface](https://github.com/auth0/auth0-react/blob/2ca701ed78f68d60c5a6b9e36127ba53249bb873/src/auth-state.tsx#L6) which defines a field of `user` of type `any`.

Neither the code itself, nor the [React SDK docs](https://auth0.com/docs/libraries/auth0-react#user) actually tell me what `user` really represents.

I am inclined to believe that it actually represents an [ID token](https://auth0.com/docs/tokens#id-tokens) given that when I `console.log` `user` I get an object with a `sub` field. 

#### Secondary Problem: Potentially Non-Sensical Types

As it stands, the `AuthState` definition implies that you can have a state that is:

```typescript
  {
    isAuthenticated: true,
    isLoading: true,
  }
```

What does `isLoading === true && isAuthenticated === true` mean? Is this a valid state? My intuition tells me it isn't, but maybe i'm wrong! 

I don't really want to cover this problem here, but I just wanted to bring this to light. A better solution is to define `AuthState` as an algebraic data type. Example:

```typescript
type AuthState
  = { state: 'loading' }
  | { state: 'authenticated', user: User }
  | { state: 'failed', error: Error } 
```

### Describe the ideal solution

Replace `export type User = any;` defined in https://github.com/auth0/auth0-react/blob/2ca701ed78f68d60c5a6b9e36127ba53249bb873/src/auth-state.tsx#L1 with a more accurate type definition. Or, at the very least, use `unknown` as at least this is typesafe. 

## Alternatives and current work-arounds

One solution is to override / supersede the type definition of `User` in my own code.

```typescript
declare module '@auth0/auth0-react' {
  // currently I think `User` is a IdToken but I need confirmation
  export type User = IdToken
}
```

### Additional context

None, other than I really like it when libraries use `unknown` instead of `any`. But regardless, thank you for your awesome open source library! 🙂

**Comment by adamjmcgrath** [comment]
Thanks for raising this @supermacro 

We can't change `user` to `unknown` as this would be a breaking change. But we can probably make an improvement on `any`. We'll take a look at this the next time we're making updates to this SDK.
