### ISSUE TITLE
withAuthenticationRequired prevents hot reload for development

### ISSUE THREAD

**Issue by harounansari-cj** [auth0/auth0-react#203]
### Describe the problem

> Provide a clear and concise description of the issue

When using `withAuthenticationRequired` the app does not hot reload when changes are made. When I remove the `withAuthenticationRequired` code it hot reloads as normal.

### What was the expected behavior?

> Tell us about the behavior you expected to see

If I change any files the app should hot reload and present the changes I made.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.

```js
import './App.css';
import { 
  withAuthenticationRequired 
} from "@auth0/auth0-react";

import Profile from './Components/Profile';
import LogoutButton from './Components/LogoutButton';

import React, { Component } from 'react';

class App extends Component {
  render() {
    return (
      <div className="App">
        <LogoutButton />
        <Profile /> 
      </div>
    )
  }
}

export default withAuthenticationRequired(App, {
  onRedirecting: () => <div>Loading...</div>,
});`
```

when you make a small change to this code, it doesn't hot reload.

### Environment

> Please provide the following:

- **Version of `auth0-react` used:*1.1.0*
- **Which browsers have you tested in?*Chrome*
- **Which framework are you using, if applicable (Angular, React, etc):*React*
- **Other modules/plugins/libraries that might be involved:*N/A*

**Comment by harounansari-cj** [comment]
looks like the code paste isnt working, I added it to this paste bin here:
https://pastebin.com/b5eP18yQ

**Comment by adamjmcgrath** [comment]
Hi @harounansari-cj - thanks for raising this.

I can't reproduce your issue in our example app or the playground app.

Have tried wrapping the whole app in `withAuthenticationRequired(App, { onRedirecting: () => <div>Loading...</div> });` and hot reload continues to work as expected.

Can you share the code for your app or a minimal reproducable example app?

**Comment by harounansari-cj** [comment]
I'm confused. I think I did what you are asking for. And when I do that the hot reload doesnt work

**Comment by adamjmcgrath** [comment]
Hey @harounansari-cj - I can't reproduce your issue with the code snippet you've given me, so now I need to figure out if it's something else, perhaps I'm using the wrong version of react/webpack/hot reload, perhaps it's some other part of the application.

The only way I can debug the issue is if I can run an application that can reproduce it, and since the 2 application's I've run don't reproduce the issue with the code snipprt you've given me, I'm asking if you could share an application that does (rather than just a snippet of code)

**Comment by harounansari-cj** [comment]
I just tried again and it worked, you can close. I am not sure where the issue came from, but I believe it may stem from having multiple projects running
