### ISSUE TITLE
Provide guidance on loginWithPopup

### ISSUE THREAD

**Issue by mattyweb** [auth0/auth0-react#205]
There isn't any documentation that I can find on using the loginWithPopup approach with the Auth0 React toolkit.

I'm surprised that the loginWithRedirect is documented. Is that the recommended choice? Does the popup not work?

I'd assume that all React SPA developers would prefer not to redirect. My apps tend to load a bunch of data up front and don't want to have to reinitialize after a redirect. There's also no 'cancel' button on the redirect page which forces users to hit the 'back' button if they decide they don't want to register. Not super user friendly.

When prototyping I just changed the loginWithRedirect call to loginWithPopup but that still triggers a redirect with a "Oops!, something went wrong" message.

The tech looks promising. Hoping this can get sorted!

**Comment by adamjmcgrath** [comment]
Hi @mattyweb - thanks for raising this

`loginWithPopup` is documented here https://auth0.github.io/auth0-react/interfaces/auth0_context.auth0contextinterface.html#loginwithpopup

We don't tend to use it in our examples because we prefer `loginWithRedirect` (mostly due to issues with popup blockers)

> When prototyping I just changed the loginWithRedirect call to loginWithPopup but that still triggers a redirect with a "Oops!, something went wrong" message.

Getting this message on the `/authorize` page is usually a sign that you have a configuration issue. There's usually more information on that page (in the section under the "Oops" message). Or failing that you can view the log events in the dashboard https://auth0.com/docs/logs/view-log-events-in-the-dashboard

**Comment by mattyweb** [comment]
Thanks for the quick response! I was missing a web origin and fixing that got the error sorted out. The pop-up is working now.

So...the part I wasn't grasping was that it is a **real popup window**. I assumed it was a modal of some kind.

I like the popup behavior for 2 reasons:

1. I can log the user in without requiring my SPA to be reloaded (triggering bunch of initialization logic)
2. The user can simply close the window and keep using the app if they change their mind about logging in

However, the pop-up behavior isn't great on a desktop. The little popup windows can get blocked or lost behind the bigger window.

My new question is whether there is a pattern for replicating the popup window behavior in a modal popup. That would be an ideal solution for my current project!

**Comment by adamjmcgrath** [comment]
Hey @mattyweb 

> My new question is whether there is a pattern for replicating the popup window behavior in a modal popup. That would be an ideal solution for my current project!

This SDK uses the Universal Login Page, so your user has to visit the login page on auth0.com. If you don't want to reidrect the user to that page, or open a popup to that page, all you're left with is opening that page in an iframe. This would be possible, but [we don't recommend it](https://auth0.com/docs/product-lifecycle/deprecations-and-migrations/clickjacking-protection-for-universal-login) and therefore the SDK doesn't support it - so you'd be on your own there I'm afraid.

**Comment by adamjmcgrath** [comment]
@mattyweb - closing this, feel free to ping me if you have another question

**Comment by captDaylight** [comment]
The link https://auth0.github.io/auth0-react/interfaces/auth0_context.auth0contextinterface.html#loginwithpopup above is 404

**Comment by frederikprijck** [comment]
Thanks, that would be https://auth0.github.io/auth0-react/interfaces/Auth0ContextInterface.html#loginWithPopup with an updated version of the docs tool we use.
