### ISSUE TITLE
Ability to check user session

### ISSUE THREAD

**Issue by audifaxdev** [auth0/auth0-react#209]
Could we expose checkSession from auth0's JS SDK?

We would like to be able to revoke a current/valid access token when the user session has expired.

**Comment by adamjmcgrath** [comment]
Hey @audifaxdev - thanks for raising this.

We don't use `auth0.js` in this SDK, it wraps `auth0-spa-js` - which is a [bit different](https://auth0.com/docs/libraries/auth0-single-page-app-sdk/migrate-from-auth0-js-to-the-auth0-single-page-app-sdk).

We expose the method [getAccessTokenSilently](https://auth0.github.io/auth0-react/interfaces/auth0_context.auth0contextinterface.html#getaccesstokensilently) - which is effectively the same as `checkSession` - does that work for you?
