### ISSUE TITLE
A change to the user's data redeclares the getAccessToken method, cascading unnecessary renders

### ISSUE THREAD

**Issue by xepps** [auth0/auth0-react#210]
### Describe the problem

This is a tricky one to explain, please bear with me.

In version 1.2.0 of the library, there was a change (specifically in [this commit](https://github.com/auth0/auth0-react/pull/156/commits/9cf4245be68cf1fa76a373b89fee5dcd2b56d8ff)) which introduced a feature to trigger an update to anything using the `useAuth0` hook when the `user` was updated. This change had a side effect that the `getAccessTokenSilently` and `getAccessTokenWithPopup` callbacks now get recreated at the same time as the update. 

This causes every request in a hook with `getAccessToken*` as a dependancy to re-render whenever the user is updated too. We think that this is unnecessary as those functions to update the token do not use the user information whatsoever (as they get it from the underlying auth0 client).

In any arbitrarily large application there will be situations where there are nested components making different requests. If a child component makes a request that updates the token (for example, either manually with `ignoreCache` after the token has been updated, or token expiry) then every component in the tree that makes a request will re-render / re-fetch their data. We don't think this is a valid case for a re-render as these hooks wouldn't/aren't using the user's information, just the token. 

One more concrete example could be in a user's 'update profile' page, where updating the user's information and then fetching a new token would effectively cause the entire application to restart due to cascading re-renders.

I hope this explanation makes sense. Please feel free to follow me up with any questions for more information/examples.

### What was the expected behavior?

We would expect that when the `user` is updated for components using `useAuth0` hook that the `getAccessTokenSilently` and `getAccessTokenWithPopup` callbacks are not re-created. 

We are happy to raise a PR which would potentially resolve this issue.

### Reproduction

This is difficult for us to reproduce in the sdk playground as it requires us to update the token which we could not do in that instance. However, we can reliably reproduce in our application when we update a user's information (which is stored in auth0), and then make another request using the `ignoreCache` flag to fetch the updated token.

[Here's our best attempt in the sdk playground](https://gist.github.com/helloitsdan/c51025b435fb9fa888b503c269316ac8). Please be aware that it only illustrates the problem as line 90 is unable to actually update the user's token in the playground.

### Environment

- **Version of `auth0-react` used:** 1.2.0
- **Which browsers have you tested in?** All
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** N/A

**Comment by adamjmcgrath** [comment]
Hey @xepps - thanks for raising this

`getAccessTokenSilently` and `getAccessTokenWithPopup` update the user if the user has been updated on the authorization server. So they [depend on](https://github.com/auth0/auth0-react/blob/master/src/auth0-provider.tsx#L293) the user's updated at property. I don't see how we would keep that behaviour without that dependency.

**Comment by xepps** [comment]
Hi @adamjmcgrath 

We were wondering if the logic to determine whether or not to update the user in the store could be pushed into the reducer. In this way the component doesn't need to access the `userUpdatedAt` variable and potentially recreate those `getAccessToken*` hooks.

Eg. 

```tsx
// auth0-provider.tsx
const getAccessTokenSilently = useCallback(
    async (opts?: GetTokenSilentlyOptions): Promise<string> => {
      let token;
      try {
        token = await client.getTokenSilently(opts);
      } catch (error) {
        throw tokenError(error);
      }
      const user = await client.getUser();
      dispatch({ type: 'UPDATE_USER_IF_NEW', user });
      }
      return token;
    },
    [client]
  );
  
  ...
  
  // reducer.tsx
  export const reducer = (state: AuthState, action: Action): AuthState => {
  switch (action.type) {
    case 'UPDATE_USER_IF_NEW':
      if (state.user.updated_at === action.user.updated_at) {
        return state;
      }
      
      return {
        ...state,
        isAuthenticated: !!action.user,
        user: action.user,
      };
  }
};

**Comment by adamjmcgrath** [comment]
Hmm.. that sounds like a good idea @xepps 

I will try this out next week and get back to you - thanks!

**Comment by xepps** [comment]
Thank you @adamjmcgrath. 🤞  it works out for you. It'll help us out a lot.
