### ISSUE TITLE
login_required error does not reset isAuthenticated to false

### ISSUE THREAD

**Issue by audifaxdev** [auth0/auth0-react#218]
I believe isAuthenticated should be reset to false once we get an error in https://github.com/auth0/auth0-react/blob/a49de64d7ebc68b45f40b9c55003429ff83eac26/src/reducer.tsx#L43

### Describe the problem

Our app calls getAccessTokenSilently periodically to check if the user token / session has become / is still valid 

When this throws a login_required error, we show a popup of the type  "Login required with 2 actions Sign-in / Cancel".
If the user decides not to sign-in again, he can cancel, and continue using the app unauthenticated.

The problem : isAuthenticated from useAuth0 is still set to true, even after receiving a login required error and not signing-in.

### What was the expected behavior?
I would expect isAuthenticated to be set to false once the user login is required

### Reproduction

Any react component within a provider using the browser local Storage to share the access token across tabs. Have a routine like so, and a login/logout button.

```
  const {isAuthenticated, getAccessTokenSilently, user, logout, loginWithRedirect } = useAuth0();
  
  console.log({isAuthenticated})

  //setup auth0 session check
  React.useEffect(() => {
    if (routineAuth0Check) {
      clearInterval(routineAuth0Check);
    }
    //getAccessTokenSilently AKA token check is rate limited : 10 req / user / mn
    routineAuth0Check = setInterval(() => {
      console.log('AUTH0 SESSION ROUTINE CHECK');
      getAccessTokenSilently(auth0TokenOptions).then((newAuth0Token) => {
        console.log('AUTH0 SESSION ROUTINE TOKEN OK');
        dispatch(setAuth0TokenActionCreator(newAuth0Token));
      }).catch((err) => {
        //Only show an error if we are currently authenticated
        if (isAuthenticated) {
          const error = get(err, 'error', null);
          if (error === 'login_required') {
            clearUserSession();
          }
        }
      });
    },  10000);
  }, [clearUserSession, getAccessTokenSilently, isAuthenticated]);
```
    
- Open the apps in 2 tabs
- Login in one tab
- Wait for other tab to pick-up on the authenticated state. 
- Now in one tab, logout, and observe the other tab. 
- It will throw a login_required error, but isAuthenticated will still be set to true

**Comment by adamjmcgrath** [comment]
You raise a good point - thanks @audifaxdev 

I'll take a look at fixing this shortly
