### ISSUE TITLE
Ability to invoke handleRedirectCallback() from the useAuth0 hook

### ISSUE THREAD

**Issue by ben-hunter-andrew-robertson** [auth0/auth0-react#222]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> I am currently building a Capacitor App that generates a link using `buildAuthoriseUrl`, navigates to that link using a popover Capacitor Browser window and then allows the user to sign in. An authorisation code is generated, however I need to manually invoke `handleRedirectCallback` to authenticate the user. 

> It would be great if the `handleRedirectCallback` method could be accessed anywhere using the `useAuth0` hook. 

Thanks!

### Describe the ideal solution

> Allow the `handleRedirectCallback` method to be accessed through the `useAuth0` hook (similar to how `buildAuthoriseUrl` can). 

## Alternatives and current work-arounds

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

### None at this stage. 

> Add any other context or screenshots about the feature request here.

**Comment by benandrew** [comment]
I have forked the repo to achieve the functionality I want (available [here](https://github.com/benhunterandrewrobertson/auth0-react)). 

Would you be interested in merging this feature?

**Comment by adamjmcgrath** [comment]
Hey @benandrew - `loginWithPopup` accepts a custom [config.popup](https://auth0.github.io/auth0-react/interfaces/index.popupconfigoptions.html#popup) option, which looks compatible with the [Capacitor Browser API](https://capacitorjs.com/docs/apis/browser) - would this work for you?

**Comment by benandrew** [comment]
> Hey @benandrew - `loginWithPopup` accepts a custom [config.popup](https://auth0.github.io/auth0-react/interfaces/index.popupconfigoptions.html#popup) option, which looks compatible with the [Capacitor Browser API](https://capacitorjs.com/docs/apis/browser) - would this work for you?

Hey @adamjmcgrath, cheers for the response. Unfortunately, `loginWithPopup` doesn't appear to give the functionality I need. I currently have a listener setup that checks whether the Capacitor Browser navigates to the `./?code=XXX&state=XXX` address (after successful authentication), and upon receiving that call, fires the `handleRedirectCallback()` to finalise the authentication process.

I tried implementing it using `loginWithPopup` but unfortunately it seemed to stop after generating the `./?code=XXX&state=XXX` address.

Appreciate the help!

**Comment by adamjmcgrath** [comment]
Hey @benandrew - I was planning on having a go at using `loginWithPopup` with Capacitor myself, but I haven't gotten round to it yet. I should have some time next week

**Comment by adamjmcgrath** [comment]
Hey @ben-hunter-andrew-robertson - we're going to do some work to expose the `handleRedirectCallback` for this use case. I'll update this thread when we have a PR ready

**Comment by benhunterandrewrobertson** [comment]
Fantastic, thank you very much @adamjmcgrath!
