### ISSUE TITLE
withAuthenticationRequired HOC corrupts react-router Prompt component behavior

### ISSUE THREAD

**Issue by EeeasyBreezy** [auth0/auth0-react#226]
### Describe the problem

> Provide a clear and concise description of the issue

Assume you have a form, which is available via `<ProtectedRoute />` which is taken from here: https://auth0.com/blog/complete-guide-to-react-user-authentication/#Protecting-Routes

On a form you have a `<Prompt />` component. This React Router component is used to prevent navigation on some condition: https://reactrouter.com/core/api/Prompt.

I use `<Prompt />` for preventing user navigation in case when user changed form, but didn't submit it, so he would not be able to loose changes immediately. The problem is with the browser back navigation button.
Consider the user flow below:

- Open a form available via protected route
- Input some changes to the form
- Click back browser button
- Prompt appears. Message: "If you leave the changes gonna be lost. Would you like to leave?" with OK/Cancel options
- User clicks Cancel
 
After user clicks Cancel I want to display a form for user with the most recent changes he/she made to the data.
However, forms behavior under protected routes are different: despite you click cancel the page re-renders and the form returns to its initial state it had before the most recent changes were made by the user.
Forms which are available under default React router `<Route />` component are able to save the most recent user input after cancel was clicked.

> Tell us about the behavior you expected to see

In this case the behavior of  `<ProtectedRoute />` should be the same as default React router  `<Route />` component: after clicking Cancel user must stay on the same page and see his/her most recent changes

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.

Demo project imitating the bug
https://github.com/EeeasyBreezy/Auth0PromptBug

Requires an Auth0 tenant and login/password credentials to authorize. 

### Environment

> Please provide the following:

- auth0-react: 1.4.0
- react-router: 5.2.0
- react: 17.0.1
- Tested in Chrome 89.0.4389.90 x64, Windows 10

**Comment by adamjmcgrath** [comment]
Thanks for providing a repro project @EeeasyBreezy, will take a look and get back to you

**Comment by adamjmcgrath** [comment]
Hi @EeeasyBreezy - I've had a look at your repro project and the problem looks to be with your implementation of the `ProtectedRoute` component, here https://github.com/EeeasyBreezy/Auth0PromptBug/blob/master/src/Routing/ProtectedRoute.tsx#L36

You are passing an inline function ot the `component` prop, and according to the `react-router` docs:

> When you use component (instead of render or children, below) the router uses React.createElement to create a new React element from the given component. That means if you provide an inline function to the component prop, you would create a new component every render. This results in the existing component unmounting and the new component mounting instead of just updating the existing component. When using an inline function for inline rendering, use the render or the children prop (below).

Source: https://reactrouter.com/web/api/Route/component

Better to use the `render` prop - see the `ProtectedRoute` implementation in the react router example app here https://github.com/auth0/auth0-react/blob/master/examples/cra-react-router/src/ProtectedRoute.tsx#L10

I updated your `ProtectedRoute` as follows and noticed that the user input was restored on cancellation of the prompt.

```jsx
const ProtectedRoute: FC<Props> = ({ allowedRoles, component, ...args }: Props) => {
    let componentToUse = component;
    const onRedirect = (): JSX.Element => {
        return <LoadingOverlay />
    }
    return <Route {...args} render={(props) => {
      const WrappedComponent = withAuthenticationRequired(componentToUse as ComponentType<any>,  { onRedirecting: onRedirect });
      return <WrappedComponent {...props} />
    }} />;
};
```

**Comment by adamjmcgrath** [comment]
@EeeasyBreezy - I think https://github.com/auth0/auth0-react/issues/226#issuecomment-822400532 will have resolved your issue, closing this - feel free to ping me to reopen

**Comment by richardscarrott** [comment]
Hi @adamjmcgrath - surely calling a HoC anywhere within a component's render fn isn't a good idea?...React will see it as a new component on each render causing it to unmount the entire subtree?

**Comment by prufrock123** [comment]
Agree with @richardscarrott -

This is still a big problem @adamjmcgrath. Wanting to bump this to see if anyone has uncovered a solution?

**Comment by adamjmcgrath** [comment]
Hi @prufrock123 - if you want me to take a look at this. Please raise an issue with a sample project that reproduces the issue.

**Comment by CTLaChance** [comment]
In case anyone comes along with a similar issue, I 'solved' this problem by implementing the barebones functionality of the `withAuthenticationRequired` HOC as a straight up component. The problem here, as described above, is that the `component` prop of the `Route` component from React-Router triggers mounts and dismounts instead of updating the component.

I decided to solve this as simply as possible using `{children}` which matches how one would typically work with a react-router `Route` component.

```
import { useAuth0 } from '@auth0/auth0-react'
import React, { ReactElement, ReactNode, useEffect } from 'react'
import { Route, RouteProps } from 'react-router-dom'

interface ProtectedRouteV2Props extends RouteProps {
  children: ReactNode
  path: string
}

// This component is designed to not trigger duplicate renders when child components change.
// For more information please refer to this documentation:
// https://v5.reactrouter.com/web/api/Route/component
// https://github.com/auth0/auth0-react/issues/226
export const ProtectedRouteV2 = ({ children, ...args }: ProtectedRouteV2Props): ReactElement => {
  const { user, isAuthenticated, isLoading, loginWithRedirect } = useAuth0()

  useEffect(() => {
    if (isLoading || isAuthenticated) {
      return
    }

    (async (): Promise<void> => {
      await loginWithRedirect({
        appState: {
          returnTo: `${window.location.pathname}${window.location.search}`,
        },
      })
    })()
  }, [isLoading, isAuthenticated, loginWithRedirect])

  return (
    // eslint-disable-next-line react/jsx-props-no-spreading
    isAuthenticated ? <Route {...args}>{children}</Route> : <h1>Redirecting. . .</h1>
  )
}
```
