### ISSUE TITLE
Allow generic typing on useAuth0 hook to extend User

### ISSUE THREAD

**Issue by Jameskmonger** [auth0/auth0-react#228]
### Describe the problem you'd like to have solved

I have added namespaced claims to my users and would like to apply type safety for these claims when using the `user` property from the `useAuth0` hook

### Describe the ideal solution

```ts
const { user } = useAuth0<{
    'example.com/bar': string,
    'example.com/foo': { someValue: number }
}>();

const bar = user['example.com/bar']; // has type `string`
const { someValue } = user['example.com/foo'];
```

## Alternatives and current work-arounds

`user` is currently of type `any` so the workaround for this is just to manually apply a type.

**Comment by Jameskmonger** [comment]
@adamjmcgrath would you accept a PR for this?

**Comment by adamjmcgrath** [comment]
Hi @Jameskmonger - sure, providing it's done in a non breaking way

**Comment by Jameskmonger** [comment]
@adamjmcgrath please see #230
