### ISSUE TITLE
Passwordless with email results in `invalid state` intermittently

### ISSUE THREAD

**Issue by qbunt** [auth0/auth0-react#229]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

> When using a passwordless login, with link as the passwordless option, the quickstart configured with our tenant always results in an `Invalid State` error. This error could be originating from auth0-spa, but presents reliably in the basic quickstart for login located [here](https://auth0.com/docs/quickstart/spa/react/01-login). In some cases, this login does work correctly, but there seems to be some character in the URL that throws an error on the client side, however, the tenant reports it as a successful login.

### What was the expected behavior?

> A successful login with no `Invalid State` error with passwordless login

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> download and configure https://auth0.com/docs/quickstart/spa/react/01-login with a new tenant and `email` passwordless connection
- Fire a `loginWithRedirect` using the `useAuth0` hook
- Fill in your email
- Click the link in your email and see the redirect back to your application
- Witness the `Oops... Invalid state` in the bare sample

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

> I did not try this, the sample and our main application seemed like enough

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- `auth0-react` 1.1.0 & 1.4.0
- Chrome, Firefox
- React
- auth0-spa-js

**Comment by adamjmcgrath** [comment]
Hi @qbunt - by default we store the login transaction state in `sessionStorage`, but this doesn't work for passwordless, since you don't complete the OAuth flow on the same tab you started it.

For Passwordless, you should use cookies to store the transaction state, you can enable this with the [useCookiesForTransactions](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#usecookiesfortransactions) option. eg

```jsx
<Auth0Provider useCookiesForTransactions={true} ... >
```

The auth0-react docs havn't caught up with the spa-js docs, will make sure they do on the next release.

**Comment by qbunt** [comment]
@adamjmcgrath Appears to solve our use case, there's no way I would have found that in the docs, maybe a special callout for passwordless would be good, we were super stumped. Thanks for getting back to me

**Comment by adamjmcgrath** [comment]
No problem, thanks @qbunt - I'll make sure this gets addressed in the docs

**Comment by qbunt** [comment]
@adamjmcgrath any chance this could get an update? We're having additional issues with this library, and curious if there's new docs hidden somewhere else that haven't been published yet.

**Comment by adamjmcgrath** [comment]
Hi @qbunt 

> @adamjmcgrath any chance this could get an update? 

We have a backlog item to make sure the auth0-react docs stay up to date with the spa-js docs (so that new options like [useCookiesForTransactions](https://auth0.github.io/auth0-spa-js/interfaces/auth0clientoptions.html#usecookiesfortransactions)). But that's not been started yet.

> We're having additional issues with this library

If you'd like help with these, feel free to raise an issue

**Comment by qbunt** [comment]
@adamjmcgrath thanks, still trying to figure out if it's on our side or yours, but will do, thanks so much

**Comment by dgbau** [comment]
+1 on revising the docs about passwordless! I was stumped for quite a while on this. incidentally, the docs also do not specify how to enable links instead of codes, even in the link-specific example. I had to dig that one up as well!
