### ISSUE TITLE
React/Apollo useAuth0 context is undefined when navigating to a page manually

### ISSUE THREAD

**Issue by RoniFinTech** [auth0/auth0-react#232]
### Describe the problem

I utuilize useAuth0 to access the context and parameters such as isAuthenticated and user.
When I navigate through my App’s Header bar, everything works fine after I log in (e.g. isAuthenticated has the value true).
However, if I go to my browser's url bar and type a specific route (e.g. http://localhost:3000/profile), the userAuth0() context gets erased and isAuthenticated returns false.

But, if I go to the Profile route through my Header bar, isAuthenticated returns true.

### What was the expected behavior?

The expected behavior is for isAuthenticated to return `true` in both situations.

### Environment
`@auth0/auth0-react`: 1.4.0
`react`: 17.0.2

### Reproduction

My Auth0Provider code:
```
const Auth0ProviderWithHistory = ({children}: PropsWithChildren<{}>) => {

    const onRedirectCallback = (appState: any) => {
        window.history.replaceState(
            {},
            document.title,
            appState && appState.targetUrl
                ? appState.returnTo
                : window.location.pathname
        );
    }
    
    return (
        <Auth0Provider
            domain={config.domain}
            clientId={config.clientId}
            audience={config.audience}
            // redirectUri={config.redirect_uri}
            redirectUri={window.location.origin}
            onRedirectCallback={onRedirectCallback}
            useRefreshTokens={true}
            cacheLocation="localstorage"
        >
            {children}
        </Auth0Provider>
    );
```

**Comment by adamjmcgrath** [comment]
Hi @RoniFinTech - I can't see anything wrong with the code you've shared

And you're using Refresh Tokens and localStorage, so you wont be affected by [IDP or Social connection Developer keys](https://github.com/auth0/auth0-react/blob/master/FAQ.md#1-user-is-not-logged-in-after-page-refresh)

Could you try and debug the issue by looking in the network tab and console when you update the url in the console and your authentication state is not persisted?

Failing that, can you create a minimal reproduction that demonstrates the issue, and I would be happy to debug it for you.

You could also try sharing your `clientId` and I can see if it is misconfigured somehow

**Comment by RoniFinTech** [comment]
@adamjmcgrath sorry for the delay... thought I had responded.

The only strange thing that I see when I load the route manually is that it returns the status code of 304 (Not Modified). 
My clientId is `Zqe5LmASXGj08IJQarOJmm0nsqPaDOJn`

**Comment by adamjmcgrath** [comment]
Hi @RoniFinTech - I can't see any issue with how your client is configured and your page being cached shouldn't make a difference.

I think I'd need to debug it to figure out what's going on, if you'd like me to do that - please provide a minimal reproduction that demonstrates the issue

**Comment by RoniFinTech** [comment]
@adamjmcgrath what do you mean by " please provide a minimal reproduction that demonstrates the issue"?
Do you want me to provide you with my code?

**Comment by RoniFinTech** [comment]
@adamjmcgrath if to give more color,
`/profile` is a protected route for me and this is the routing I'm doing for protected routes:

`export const ProtectedRoute = ({component: Component, ...rest}) => {
    const {isAuthenticated} = useAuth0();
    return (
        <Route {...rest}
               render={(props) => {
                   if (isAuthenticated) {
                       return <Component {...props} />;
                   } else {
                       return (
                           <Redirect
                               to={{
                                   pathname: "/",
                                   state: {from: props.location}
                               }}
                           />
                       );
                   }
               }}
        />
    );
};`

**Comment by RoniFinTech** [comment]
Ahh found the issue...
I need to wait for useAuth0() to finish loading with `isLoading`

```
export const ProtectedRoute = ({component: Component, ...rest}) => {
    const {isAuthenticated, isLoading} = useAuth0();
    if (isLoading)
        return <div>Loading...</div>

    return (
        <Route {...rest}
               render={(props) => {
                   if (isAuthenticated) {
                       return <Component {...props} />;
                   } else {
                       return (
                           <Redirect
                               to={{
                                   pathname: "/",
                                   state: {from: props.location}
                               }}
                           />
                       );
                   }
               }}
        />
    );
};
```
