### ISSUE TITLE
Err404 & Can not override scope option in auth0-react

### ISSUE THREAD

**Issue by SeyyedKhandon** [auth0/auth0-react#242]
### Describe the problem

I'm using the `"@auth0/auth0-react": "^1.5.0"` package for `pkce` authentication. 
I tried to set the `scope`, but it seems it didn't work:
```javascript
// method1 which I've tried
   <Auth0Provider
      domain={urls().oauth}
      clientId={apiConstants.clientId}
      redirectUri={urls().redirect}
      scope="read"
    >
          <AppRouter />
    </Auth0Provider>

```

```javascript
// method2 in the loginWithRedirect
import { useAuth0 } from '@auth0/auth0-react';

function Auth0LoginButton() {
  const { isAuthenticated, loginWithRedirect } = useAuth0();

  return isAuthenticated ? null : (
    <button onClick={() => loginWithRedirect({ scope: "read" })}>
      Log in via Auth0 PKCE
    </button>
  );
}

export default Auth0LoginButton;

```

Also tried both method together, but no progress. The output will be always `scope=openid profile email read`.
How can I fix this?

### What was the expected behavior?

`scope=read`

### Environment

> Please provide the following:

- **Version of `auth0-react` used:**     `"@auth0/auth0-react": "^1.5.0"`
- **Which browsers have you tested in?** `Chrome`
- **Which framework are you using, if applicable (Angular, React, etc):** `React`

### 404 Error for Doc

These two pages also is not available(`404 page not found`):

https://auth0.github.io/auth0-react/TROUBLESHOOTING.md
https://auth0.github.io/auth0-react/FAQ.md

**Comment by frederikprijck** [comment]
Closing this as it looks like the docs issue (404 URLs) is fixed, see https://github.com/auth0/auth0-react/pull/243, as well as the question been answered.

Thanks again for reporting the broken links!
