### ISSUE TITLE
Cannot pass isAuthenticated through Context API

### ISSUE THREAD

**Issue by bitshiftnetau** [auth0/auth0-react#253]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

When passing isAuthenticated through a Provider and importing via ContextAPI, I receive a `TypeError: Object(...)(...) is undefined` error

### What was the expected behavior?

I should be able to pass isAuthenticated and other objects through the ContextAPI [untested for other objects returned from useAuth0()]

### Reproduction

App.js:

```
    const { isAuthenticated } = useAuth0();
    ....
    const providing = {
        isAuthenticated
    }
    ....
    return (
            ....
            <Provider value={providing}>
                    <Navbar />
            </Provider>
    ....
```

 Context.js:
```
import React from 'react'

const Context = React.createContext()

export const Provider = Context.Provider
export const Consumer = Context.Consumer

export default Context
```

nav-bar.js

....
import { useAuth0 } from "@auth0/auth0-react";
....
import Context from '../Context';

const NavBar = () => {
  const { isAuthenticated } = useContext(Context);
  ....
....
....
  
};

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?** Possibly though I'm not sure how. Happy to share my project code with you if necessary. 

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.5.0
- **Which browsers have you tested in?** firefox and chromium
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** react-bootstrap navbar

**Comment by adamjmcgrath** [comment]
HI @bitshiftnetau,

> I should be able to pass isAuthenticated and other objects through the ContextAPI 

`isAuthenticated` is a boolean, so if you can pass `var foo = true;` through the Context API you can pass `isAuthenticated`

Also, you don't need to create your own Provider to pass `isAuthenticated` through the Context API. Use `Auth0Provider` and `useAuth0` will provide `isAuthenticated` to your components through the Context API. See the basic example https://github.com/auth0/auth0-react#getting-started for how this should work

**Comment by bitshiftnetau** [comment]
Ah I see! Yes that makes sense. I'm already using Auth0Provider but didn't
make the connection there.

Also I had made an error with my code anyway so this can be closed.

Thank you!
