### ISSUE TITLE
isLoading always true and no user Info is fetched?

### ISSUE THREAD

**Issue by Ditizen** [auth0/auth0-react#257]
Hello, all of a sudden Auth0 information just stopped coming back from service. isLoading is always true and the user never gets updated with new data.

this is my protectedRoute component

        import { useAuth0 } from '@auth0/auth0-react';
        import React from 'react';
        import { Redirect, Route } from 'react-router-dom';
        
        function ProtectedRoute({ component: Component, render, ...rest }) {
	        const { isAuthenticated, user } = useAuth0();
        
                return (
		        <Route
			        {...rest}
			        render={props => {
				        if (isAuthenticated) {
					        return Component ? <Component {...props} /> : render(props);
				        }
				        return (
					        <Redirect
						        to={{
							        pathname: '/login',
							        state: { from: props.location },
						        }}
					        />
				        );
			        }}
		        ></Route>
	        );
        }
        
        export default ProtectedRoute;

and these are my deps:

        "dependencies": {
		        "@auth0/auth0-react": "^1.5.0",
		        "@material-ui/core": "^4.11.2",
		        "@material-ui/data-grid": "^4.0.0-alpha.32",
		        "@material-ui/icons": "^4.11.2",
		        "@material-ui/lab": "^4.0.0-alpha.57",
		        "@material-ui/pickers": "^3.3.10",
		        "@reduxjs/toolkit": "^1.5.0",
		        "@testing-library/jest-dom": "^5.11.8",
		        "@testing-library/react": "^11.2.2",
		        "@testing-library/user-event": "^12.6.0",
		        "axios": "^0.21.1",
		        "clsx": "^1.1.1",
		        "lodash": "^4.17.21",
		        "material-ui-dropzone": "^3.5.0",
		        "moment": "^2.29.1",
		        "react": "^17.0.1",
		        "react-dom": "^17.0.1",
		        "react-moment": "^1.1.1",
		        "react-number-format": "^4.5.0",
		        "react-redux": "^7.2.2",
		        "react-router-dom": "^5.2.0",
		        "react-scripts": "^4.0.1",
		        "recharts": "^2.0.3",
		        "soap": "^0.36.0",
		        "socket.io-client": "^4.1.0",
		        "web-vitals": "^0.2.4"
	        },

**Comment by Ditizen** [comment]
UPDATE... after something between three to five minutes with the app open, it did get the user information back... But when refreshed, not response received once again

**Comment by Ditizen** [comment]
It was a problem with my redirect setting on the protected route... so i'm closing the issue

**Comment by Ditizen** [comment]
I read on another thread that I need to use isLoading, before reading the isAuthenticated value... I'm not really sure why is that but it worked.... so i'm closing the issue

**Comment by frederikprijck** [comment]
> I'm not really sure why is that but it worked.

This is because, when using an SPA, there are situations where the SPA application has no knowledge of it self on whether or not a user is authenticated.

In order to know that, the application will need to ask Auth0 (or any other Identity Provider) about the authentication state of the current user.

In those cases, isLoading will be true for the time for which our SDK is waiting on a response from Auth0.

On the other hand, there are also situations where our SDK is able to know about the user, e.g. when you have a valid set of tokens stored in local storage.

That said, happy you have been able to resolve it!

**Comment by Ditizen** [comment]
@frederikprijck thank you... I know now cause I need to, and actually, our real problem was that we were using the locaLStorage to make some decisions. Now we left all auth decisions to Auth0 and oh wow! is better haha (sarcasm)

Thanks
