### ISSUE TITLE
expose id_token 

### ISSUE THREAD

**Issue by tgerk** [auth0/auth0-react#262]
I want access to the raw id_token (from the /oauth/token response).  My "serverless" single-page app integrates with a third-party app that needs an oidc token, access tokens are not appropriate.  I found that id_token is digested into the User object (accessible from ```useAuth0```) but then that token is cached & inaccessible.  The auth0-spa-js and auth0-react SDKs (nevermind the Auth0 dashboard & docs) don't address this problem.

Blog articles [why-should-use-accesstokens-to-secure-an-api](https://auth0.com/blog/why-should-use-accesstokens-to-secure-an-api/) come somewhat close, but again do not recognize that the 3rd-party Service will have the same relationship to Auth0 as Auth0 has to (e.g.) Google OAUTH.  Based on an id_token, Service will establish a user and issue its own access/refresh tokens.

### Describe the ideal solution
```useAuth0()``` should provide a method to get the authenticated user's id_token, or maybe the id_token should be a static member of the ```user``` object.  (The latter might be easier and require modification in auth0-spa-js only, but I see reasons to not make that object a Christmas tree.)

### Alternatives and current work-arounds
There is more than one strategy to intercept fetch/request/xhr responses, but these are not accessible to a moderately skilled frontend dev.  SAML et al are not available or preferable for my intended 3rd-party Service (MongoDB Realm, btw).  

### Additional context
I look forward to discussion here, I'll likely submit a PR here and/or on auth0-spa-js sometime.

**Comment by tgerk** [comment]
Dig deeply enough into the source, and you'll find that type IdToken has a member __raw.  Not sure if this is a documented feature _anywhere_, but it'll serve the need.

**Comment by khitrenovich** [comment]
We had similar need, and ended up using `__raw` property too.
If that's the supported way, having it officially documented would be nice. If not, then we do need something supported.

**Comment by frederikprijck** [comment]
@tgerk ,

Thanks for opening this, before we look into whether or not exposing the ID Token would be something we want to be doing, could you elaborate on why you need the ID Token to access MongoDB Realm? When I read https://docs.mongodb.com/realm/authentication/custom-jwt/, it talks about JWT format and which fields it expects but doesn't realy mention the fact that it should be an ID Token.

Thanks.

**Comment by khitrenovich** [comment]
@frederikprijck The backend service I'm using requires ID token. Unfortunately, that's outside of my control to change that.

**Comment by tgerk** [comment]
The Realm login flow is to issue its own access token for some provided user credential (email + password) or a third-party credential.  It makes more sense to me to provide an id_token in exchange for an access_token.  This flow is neither a subset or superset of OIDC or necessarily OAUTH.

Auth0-provided id_token and access_token provide different basic claims.  There is information in the id_token (e.g. data from the original social provider) which is useful to pass along.

I admit your point that setting up an audience for my Realm app, defining permissions and roles for that audience makes good sense.  Both paths will make sense, though:  an access_token can be passed as a second authorization with each Realm request to control function capabilities.  I believe I still need the id_token to establish user identity and the tenant they belong to.

**Comment by stevehobbsdev** [comment]
> If that's the supported way

This is the supported way and you should continue to use `__raw` if you _really_ need the raw ID token. We would not remove it without considering it a breaking change. We will also take on board the feedback to improve our docs in this area, but we're not sure yet what form that will take.

**Comment by tgerk** [comment]
Appreciation and thanks for <3 for the __raw property.

My previous comment in other words:  It is interesting to think of Auth0 as just another social provider.  And also, the assumption that the OAuth "Resource Provider" is on a managed server is unwarranted; counter-example being a serverless app, native app, or PWA.

Auth0 is miles ahead of Onelogin in this regard, though.  So thanks!
