### ISSUE TITLE
Can't resolve @auth0/auth0-react 

### ISSUE THREAD

**Issue by Jassi10000** [auth0/auth0-react#264]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

> Provide a clear and concise description of the issue

I am creating a react web app with Auth0 authentication, using Create React App, and am using the latest auth0 version. I have installed the npm package " @auth0/auth0-react " . However, I get this error "./src/index.js
Module not found: Can't resolve '@auth0/auth0-react' in 'C:\Users\dell\Desktop\auth\src'"
when importing "import { Auth0Provider } from "@auth0/auth0-react";" . Even I rechecked if the package is installed correctly

I have well researched on Google about this , but not able to find anything regarding this 

### What was the expected behavior?

> Tell us about the behavior you expected to see

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1..
- Step 2..
- ...

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-react` used:**
- **Which browsers have you tested in?**
- **Which framework are you using, if applicable (Angular, React, etc):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
Thanks for the report. I followed the steps in the issue and am unable to reproduce what you're seeing - do you have a repo that we can clone to see the issue in action?

Thanks.

**Comment by Jassi10000** [comment]
Ya sure 

https://github.com/Jassi10000/User-Login-Authentication

Its a react app , so you need to install node modules first and then just run <code> npm start </code>  to see the error .

**Comment by frederikprijck** [comment]
I can see that in LoginButton it is using `import { useAuth0 } from '@auth/auth0-react'`, which is incorrect.

Once I change that to `import { useAuth0 } from '@auth0/auth0-react'`, everything seems to work as expected and I am not seeing any error.

Closing this as it seems like everything works fine in the reproduction sample.
