### ISSUE TITLE
Provide access to the underlying `auth0-spa-js` methods

### ISSUE THREAD

**Issue by qbunt** [auth0/auth0-react#266]
### Describe the problem you'd like to have solved

When working with this library, one occasionally needs access to methods like `getAccessTokenSilently` outside of a react component. For instance, inside a set of Apollo links (for refreshing the token when expired).

### Describe the ideal solution

Ideally, this would include a way to get access to `auth0-spa-js` outside of a hook, either by direct method access, or something like a ref pointing to the underlying library. This library abstracts a lot of the complexity, but having some kind of escape hatch would be great.

## Alternatives and current work-arounds

Currently we handle this by passing the hook-provided `getAcccessTokenSilently` method to a setter in our Apollo client setup file. If there's a more elegant way to handle this, I'd be interested	to hear alternatives, it feels a little kludgey. I think part of the issue is that there's no great mechanism to update an existing Apollo link with a promise-resolved token. Thanks!

**Comment by marcoacierno** [comment]
I think even just exposing the client might be enough.

My use case is that I want to automatically call getAccessToken in a urql exchange, examples here: https://formidable.com/open-source/urql/docs/advanced/authentication/

> Currently we handle this by passing the hook-provided getAcccessTokenSilently method to a setter in our Apollo client setup file. If there's a more elegant way to handle this, I'd be interested to hear alternatives, it feels a little kludgey. I think part of the issue is that there's no great mechanism to update an existing Apollo link with a promise-resolved token. Thanks!

Do you have examples of this approach?

For now I am considering creating a custom graphql-codegen plugin that inside the hook calls `useAuth0()` and passes the token somehow to the request

**Comment by qbunt** [comment]
@marcoacierno agreed. We're using this to auth against Hasura, but I would imagine it'd effect anything with graphql passing an auth header. I don't get why you can't pass this to Apollo post-creation.

**Comment by frederikprijck** [comment]
Hi @qbunt,

For using this with Apollo, I would say it is recommended to use an approach comparable to this:

``` 
export const AuthorizedApolloProvider = ({ children }) => {
  const { getAccessTokenSilently } = useAuth0();

  const httpLink = createHttpLink({
    // eslint-disable-next-line @typescript-eslint/no-explicit-any
    // uri: (window as any).hasuraUrl || 'https://kitzen-api.herokuapp.com/v1/graphql' || 'http://localhost:8080/v1/graphql',
    uri: (window as any).hasuraUrl || 'http://localhost:8080/v1/graphql',
  });

  const authLink = setContext(async () => {
    const token = await getAccessTokenSilently();
    return {
      headers: {
        Authorization: `Bearer ${token}`,
      },
    };
  });

  const apolloClient = new ApolloClient({
    link: authLink.concat(httpLink),
    cache: new InMemoryCache(),
  });

  return <ApolloProvider client={apolloClient}>{children}</ApolloProvider>;
};
```
and then use
```
<AuthorizedApolloProvider>...</AuthorizedApolloProvider>
```
instead of `ApolloProvider`.

That way you can use Apollo to ensure it always adds a token to every request as well as refresh the token when expired.

**Comment by fxlemire** [comment]
Hi all, I have the same need, but for RTK-Query instead of Apollo. See the custom [graphqlBaseQuery](https://redux-toolkit.js.org/rtk-query/usage/customizing-queries#graphql-basequery) base query function from their documentation: I would ideally call `getAccessTokenSilently` before the request, but I can't wrap my head around a smart way to use hooks with a custom RTK-Query Base Query function.

Unless suggested otherwise, I'm about to create my own custom `Auth0Client` to do so, but being able to import the client or the `getAccessTokenSilently` function on its own would be marvelous.

**Comment by adamjmcgrath** [comment]
Hi @qbunt and all, I've created a guide as to why we don't offer the option to pass your own SPA JS client into the Provider and what solutions we suggest to takle these sorts of problems here https://gist.github.com/adamjmcgrath/0ed6a04047aad16506ca24d85f1b2a5c

**Comment by adamjmcgrath** [comment]
Closing as I think https://gist.github.com/adamjmcgrath/0ed6a04047aad16506ca24d85f1b2a5c answers the question
