### ISSUE TITLE
Application Sessions for Multiple organizations on client

### ISSUE THREAD

**Issue by PuravManojShah** [auth0/auth0-react#267]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

> Provide a clear and concise description of the issue

Hi,
Here is the situation I am dealing with--

Lets suppose that we have two organizations org1 and org2. Both these orgs have a common connection of logging in via google besides other connections as well. Let's also assume that user1 is already a part of both these orgs.
Now when the user logs into org1 Auth0 takes the user successfully through the entire log in flow and everything works smoothly. Once the user has successfully logged into org1 Auth0 saves a cookie called auth0.is.authenticated on the browser. Now whenever I visit any route Auth0 at the background calls the /authorize endpoint with prompt=None.

**When the user now tries to log into org2 the user is not taken through the log in flow and is directly logged into the organization and I also receive a token.**

My question is why is this behavior happening? How do I override this behavior? I would like the user to sign in every time they visit an organization for the first time(even if two orgs share a common connection and the user is already a member of both orgs).How do I maintain an application session for every organization the user is a part of on the client side?

Is it possible to dynamically change the organization parameter being passed into the Auth0Provider for different organizations?

I am new to using Auth0 and have tried a lot from my end but can't seem to get the desired behavior I am expecting of having the user log into an org if they do not have a valid session.

I would highly appreciate some guidance on the above scenario. I have also tried to go through the library source code but cannot figure out why this is happening.
Thanks!

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.6.0
- **Which browsers have you tested in?** Google Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** auth0-spa-js(used internally by auth0-react)

**Comment by adamjmcgrath** [comment]
> When the user now tries to log into org2 the user is not taken through the log in flow and is directly logged into the organization and I also receive a token.
> My question is why is this behavior happening?

This is happening because you already have a session on auth0.com so the authorization server doesn't have to prompt you again to login. You can force the login prompt by passing `prompt: 'login'` on your login request (see https://auth0.github.io/auth0-react/interfaces/auth0_context.redirectloginoptions.html#prompt and https://auth0.com/docs/brand-and-customize/text-customization-new-universal-login/prompt-login)

> Is it possible to dynamically change the organization parameter being passed into the Auth0Provider for different organizations?

You can't dynamically change this field on the fly, but you can dynamically initialise the `Auth0Provider` with an org id on page load - which should be ok for logging into different orgs with `loginWithRedirect`
