### ISSUE TITLE
Original error code is not available on OAuthError object

### ISSUE THREAD

**Issue by khitrenovich** [auth0/auth0-react#269]
### Describe the problem you'd like to have solved

I've tried to use machine-readable error code (for example, `access_denied`) that comes from Auth0 server in the URL. Unfortunately, only the error description is available as error message. I see that the error code is ignored when description is available - https://github.com/auth0/auth0-react/blob/master/src/errors.tsx#L9

### Describe the ideal solution

It would be nice to have `error.code` with the actual error code (for example, `access_denied`) available.

### Alternatives and current work-arounds

Currently we have to parse URL for query string parameters, which is not ideal.

**Comment by adamjmcgrath** [comment]
Hi @khitrenovich - yeah, good point.

Will add this to our backlog and happy to accept a PR to add this if you'd like it done sooner

**Comment by khitrenovich** [comment]
Thank you for the quick response!

After digging deeper into the code I realized the error code is actually available on the error object as `error` property along with `error_description` property - they are just not immediately visible for TS users since `useAuth0` exposes error object as generic `Error` and not as `OAuthError`. 

There are probably ways to improve the typings, but I think we can close the ticket.
