### ISSUE TITLE
Forgot password auth0

### ISSUE THREAD

**Issue by ovidiumihaibelciug** [auth0/auth0-react#273]
Hello, first of all thank you for creating this awesome library.

I have a website where I implemented a loginWithRedirect using a custom login form. I want to add a forgot password page (where the users puts the email and he gets an email with a link after that). I'm not sure how to do that using this library, from my understanding I need to use a "changePassword" method, but it doesn't seem to be available. 

Do I need to use auth-0.js for this? It's a bit confusing.

**Comment by danactive** [comment]
@ovidiumihaibelciug How did you solve this?

**Comment by ovidiumihaibelciug** [comment]
Hey @danactive,

I called the api endpoint directly

This is the endpoint: 
**POST** `https://${YOUR_AUTH0_DOMAIN}/dbconnections/change_password` 

and on that endpoint you have to send this data

`{ 
      client_id: YOUR_AUTH0_CLIENTID,
      email: "the email from the input",
      connection: "Username-Password-Authentication",
      }`
      
     And then the user should receive an email with a link to a page where he can reset the password.
