### ISSUE TITLE
Incorrect Auth Token URL for GitLab

### ISSUE THREAD

**Issue by codewithbugs01** [auth0/auth0-react#275]
GitLab documentation: https://docs.gitlab.com/ee/api/oauth2.html

If the domain is:
```
<Auth0Provider
  domain = https://gitlab.example.com/oauth
  ...
>
```

The redirect URL gets created correctly:

- https://gitlab.example.com/oauth/authorize?client_id=APP_ID....

The token URL is incorrect. It contains an extra "/oauth"

- https://gitlab.example.com/oauth/oauth/token

**Comment by adamjmcgrath** [comment]
Hi @codewithbugs01 - thanks for raising this

`auth0-react` only supports using auth0 as your identity provider I'm afraid - you'd run into other propblems trying to use GitLab, like incompatibility with Auth0's proprietary logout.

**Comment by adamjmcgrath** [comment]
Closing as https://github.com/auth0/auth0-react/issues/275#issuecomment-915245708 answers this question
