### ISSUE TITLE
Component definition is missing display name when using withAuthenticationRequired & Eslint

### ISSUE THREAD

**Issue by drydenwilliams** [auth0/auth0-react#282]
### Describe the problem

> Provide a clear and concise description of the issue

When using `withAuthenticationRequired` with `onRedirecting` options it produces an error in Eslint: `Component definition is missing display name` 
```
import React from "react";
import {withAuthenticationRequired} from "@auth0/auth0-react";

function MyComponent () {
    return (<div>Hello</div>);
}

export default withAuthenticationRequired(MyComponent, {
    // Show a message while the user waits to be redirected to the login page.
    onRedirecting: () => <div>Redirecting you to the login page...</div>,
});
```

### What was the expected behavior?
I should not error when wrapping in a HOC

### Reproduction
1. Add `@auth0/auth0-react` to a basic Gatsby website with Eslint
2. Wrap a component in `withAuthenticationRequired` 

---

**Note: ** duplicate of this: https://stackoverflow.com/questions/68156751/component-definition-is-missing-display-name-when-using-withauthenticationrequir/69346913#69346913

**Comment by adamjmcgrath** [comment]
Hi @drydenwilliams - thanks for raising this

If your eslint settings require you to define your components with a display name, then you should define the `onRedirecting` component with a display name, eg

```js
export default withAuthenticationRequired(MyComponent, {
    onRedirecting: function OnRedirectingComponent() {
      return <div>Redirecting you to the login page...</div>
    },
});
```

**Comment by drydenwilliams** [comment]
Thanks @adamjmcgrath that worked like a charm!
