### ISSUE TITLE
Router vs BrowserRouter with the auth0-react

### ISSUE THREAD

**Issue by prakash2091** [auth0/auth0-react#289]
i see the example use **Router** from react-router-dom. 

what if i use **BrowserRouter**? it was the mistake i had in my previous code.

When I use "createbrowserhistory from react router"  , i was able to login with other browser like safari.

but if i use BrowserRouter, i see the login breaks.

**Comment by adamjmcgrath** [comment]
Hi @prakash2091

> what if i use BrowserRouter? it was the mistake i had in my previous code.

`BrowserRouter` doesn't work with `createBrowserHistory`. 

see https://github.com/remix-run/react-router/issues/4059#issuecomment-254437084
