### ISSUE TITLE
User object not updating with latest org_id after getAccessTokenSilently

### ISSUE THREAD

**Issue by juandiegocastrillon** [auth0/auth0-react#292]
### Describe the problem

When calling getAccessTokenSilently with an `organization`, the `user` object is not updating. We built a flow where a user is able to switch Auth0 Organizations from within the web application after logging in. The new id_token includes the new `org_id` claim, but the `updated_at` claim still shows the old claim. It seems this library only checks the `updated_at` claim to [update the user](https://github.com/auth0/auth0-react/blob/master/src/reducer.tsx#L38).

This can lead to some issues where the previous org_id is used when the user is now logged into the new org_id.

Is this a bug with this library, or with Auth0 itself not updating the `updated_at` claim?

### What was the expected behavior?

The `user` object has the most recent `org_id` claim.

### Reproduction

Unit test to reproduce error
```
  it('should update the user with new claim after getAccessTokenSilently', async () => {
    clientMock.getTokenSilently.mockReturnThis();
    clientMock.getUser.mockResolvedValue({ name: 'foo', updated_at: '1',  organization: 'org_2'  });
    const wrapper = createWrapper();
    const { waitForNextUpdate, result } = renderHook(
      () => useContext(Auth0Context),
      { wrapper }
    );
    await waitForNextUpdate();

    clientMock.getUser.mockResolvedValue({ name: 'foo', updated_at: '1', organization: 'org_1' });
    await act(async () => {
      await result.current.getAccessTokenSilently();
    });
    expect(result.current.user?.organization).toBe('org_1');
  })
```

### Environment

> Please provide the following:

- **Version of `auth0-react` used: v1.8.0
- **Which browsers have you tested in? chrome
- **Which framework are you using, if applicable (Angular, React, etc): react
- **Other modules/plugins/libraries that might be involved: None

**Comment by adamjmcgrath** [comment]
Hi @juandiegocastrillon - thanks for raising this

You can only change the organization by logging the user in interactively (you can't change it using `getAccessTokenSilently`). So I wouldn't expect your test to pass

Can you share a minimal app that reproduces your issue?

**Comment by juandiegocastrillon** [comment]
Hi @adamjmcgrath -- Thanks for the help. Switching to `loginWithRedirect` worked well since it forced a full auth flow.

For others, to interactively switch organizations within the application, post-login, I switched the call from 
```
await getAccessTokenSilently({
  organization: organizationId,
  ignoreCache: true,
}
```
to 
```
await loginWithRedirect({
  organization: firstOrganizationId,
})
```
