### ISSUE TITLE
Token and User data disappear after MFA Login

### ISSUE THREAD

**Issue by Denchooo** [auth0/auth0-react#301]
### Reproduction

Hi guys, I’m using Auth0react and my issue is that when I click loginWithPopUp and I put my credentials (MFA Is disabled) I can login successfully and to retrieve user data. But if I enable the MFA Auth (SMS with Twilio) I write down my credentials after that I’ve receive a SMS code and my login is successful, but after 2-3 my users object becomes empty.
![InkedScreenshot_32_LI](https://user-images.githubusercontent.com/92311461/140956050-04c12ff8-7361-433a-91c1-50557bac7a9e.jpg)

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**
If so, provide steps:

just download the sample
login there via MFA (SMS)
refresh the page
and you will see that there is no user data

### Environment

> Please provide the following:

auth0-react: 1.8.0
Chrome
ReactJS

**Comment by stevehobbsdev** [comment]
@adamjmcgrath Could be related to https://github.com/auth0/auth0-spa-js/issues/828, I'm investigating today.

**Comment by adamjmcgrath** [comment]
Thanks @stevehobbsdev!

**Comment by stevehobbsdev** [comment]
@Denchooo this is actually related to the underlying SDK that is used by Auth0 React; I've [left a comment]https://github.com/auth0/auth0-spa-js/issues/828#issuecomment-966224022) over there that may help.
