### ISSUE TITLE
Expose underlying client

### ISSUE THREAD

**Issue by harrycollin** [auth0/auth0-react#303]
I've been looking at ways to get the access token outside of the React component tree. There seems to be some talk on this subject in the Auth0 forums, but the solutions aren't perfect. A simple option here would be to expose the Auth0 client in the state. This would allow us to set it as a global variable in our apps and access it anywhere after initialization. The primary use case for this is to gain access to the access token. Not all of the API requests are made inside components! I think this is an easy feature to implement. 

What do you think?

**Comment by adamjmcgrath** [comment]
Hi @harrycollin - this has been answered a few times

See https://gist.github.com/adamjmcgrath/0ed6a04047aad16506ca24d85f1b2a5c for more details and workarounds to your problem
