### ISSUE TITLE
Login required error

### ISSUE THREAD

**Issue by drydenwilliams** [auth0/auth0-react#305]
### Describe the problem

I keep seeing a `Login required` error. It's super linked to [this issue](https://community.auth0.com/t/failed-silent-auth-login-required/33165) but only seems to happen on an incognito session (when I don't already have a token or cookie), because of this I'm worried this happens for all new users. 

I can't figure out how to comment on the auth0 community (as it's pants) so hope it's ok here.

When this error shows it seems the cookie has been added ok (screenshot attached). I've realized too sometimes when I see this error, navigate to the homepage, and then to the dashboard, I am actually logged in. 

### What was the expected behavior?

It should log me in. Or it should actually be an error and not set the token.

### Reproduction

1. When you log in to [EcoPing](https://ecoping.earth/) in incognito 
2. Hit confirm and see the Login Required Error.
3. `getAccessTokenSilently` seems to fail immediately 

<img width="1135" alt="Screenshot 2021-12-02 at 17 39 21" src="https://user-images.githubusercontent.com/4403089/144474660-b4721475-a0cd-460f-812b-b21c6715d6b0.png">

<img width="653" alt="Screenshot 2021-12-02 at 16 36 42" src="https://user-images.githubusercontent.com/4403089/144474089-d4bfa12d-e8f9-4e35-b17c-e5d5ea683f83.png">

**NOTE**: Once I redirect to the homepage I seem to have another cookie that is set which makes me logged in, which is super strange. 

<img width="409" alt="Screenshot 2021-12-02 at 17 44 23" src="https://user-images.githubusercontent.com/4403089/144476547-1164a43b-6a79-4f06-9ab4-1b6a9d7a5e92.png">
### Environment

> Please provide the following:

- **Version of `auth0-react` used:** "^1.8.0"
- **Which browsers have you tested in?** Chrome - Version 96.0.4664.55 
- **Which framework are you using, if applicable (Angular, React, etc):** React

**Comment by adamjmcgrath** [comment]
Hi @drydenwilliams - thanks for raising this

> I keep seeing a Login required error. It's super linked to this issue but only seems to happen on an incognito session (when I don't already have a token or cookie), because of this I'm worried this happens for all new users.

This is because you're in incognito mode, it won't happen for new users. I've just signed up and successfully logged in but I can reproduce the issue you described when I use incognito mode.

3rd party cookies (like cookies for sites in iframes) are blocked in Chrome incognito. As you can see in the screenshot below, silent auth works in the left hand pane because it has access to the `auth0` cookie on auth0.com in the iframe. Silent auth fails in the incognito window on the right because there are no cookies available to the auth0.com request.

![image](https://user-images.githubusercontent.com/1299658/144629606-5103b651-57f8-4a6e-9815-397a44de97be.png)

If you click the eye icon in the address bar it will tell you that cookies have been blocked and that the site might not be working correctly

![image](https://user-images.githubusercontent.com/1299658/144630330-e4c68811-9e72-486e-88c2-801c1e9c60e7.png)

**Comment by adamjmcgrath** [comment]
If you want your site to work when 3rd party cookies are blocked, take a look at Custom Domains or Refresh Tokens and LocalStorage - see https://auth0.com/docs/troubleshoot/troubleshoot-authentication/renew-tokens-when-using-safari#workarounds for more info

**Comment by drydenwilliams** [comment]
Hi Adam, thanks for the details search, would you mind trying with a username and password? Most of the error logs show it's through this not via social login.

**Comment by stevehobbsdev** [comment]
Worth noting here that Brave [blocks third-party cookies by default](https://support.brave.com/hc/en-us/articles/360050634931-How-Do-I-Manage-Cookies-In-Brave-#2) (through it's "Shield" feature) whether you're in incognito mode or not, so I believe @adamjmcgrath's recommendation here is still relevant.

**Comment by adamjmcgrath** [comment]
Also @drydenwilliams 

You're not waiting for the library to initialise on the `/auth-callback` page before trying to get a token
![image](https://user-images.githubusercontent.com/1299658/145027889-13b07764-d161-403b-a121-60f9ede025dc.png)

So you're essentially doing silent-auth on the callback page when you should be doing the code exchange.

If you wait for the code exchange to complete, then you wont need to do silent auth and your login wont rely on 3rd party cookies

eg

```js
const { getAccessTokenSilently, isLoading } = useAuth0();

useEffect(() => {
    if (!isLoading) {
      // The code exchange is complete, so you now have a valid Access Token
      // in the cache and `getAccessTokenSilently` wont have to do silent auth
      fetchUserInformation();
   }
}, [isLoading]);

const fetchUserInformation = async () => { ... getAccessTokenSilently ... };
```

You'll still rely on 3rd party cookies to persist the tokens when the user refreshes the page - but you can mitigate this using https://github.com/auth0/auth0-react/issues/305#issuecomment-985626129

**Comment by drydenwilliams** [comment]
Thanks @adamjmcgrath that's super interesting! Will have a look ASAP
