### ISSUE TITLE
loginWithPopup has no "onClose" event

### ISSUE THREAD

**Issue by esperancaJS** [auth0/auth0-react#306]
The previously mentioned method (in these issues, not in any docs) for detecting a user closing the pop up window seem to not be working.

**Comment by esperancaJS** [comment]
```
const { isLoading } = useAuth0();
```

This boolean goes to **true** when the pop up opens, and **false** once it's closed. That helped achieve the intended behaviour.

**Comment by frederikprijck** [comment]
It's not clear whether or not you are still experiencing issues. If you do, please open a new issue with a bit more information, keep in mind it is hard for anyone to action an issue that lacks any kind of information.
