### ISSUE TITLE
Add 'user_metadata' field to user object

### ISSUE THREAD

**Issue by VovaMorozov3228** [auth0/auth0-react#307]
Hello, Auth0 Community! Pls, help me with one thing, which I want to implement inside our project. We use this React package on the client-side, so I need to get the ‘user_metadata’ field in the user object somehow on my client-side. How can I achieve that?

**Comment by adamjmcgrath** [comment]
Hi @VovaMorozov3228 - thanks for raising this

Have a look at https://github.com/auth0/auth0-react/issues/110#issuecomment-689228046 which explains how to use a rule to add this as a custom claim to your ID Token
