### ISSUE TITLE
Suspense support for `useAuth0`

### ISSUE THREAD

**Issue by peterhirn** [auth0/auth0-react#312]
### Describe the problem you'd like to have solved
I'm currently building an app which heavily relies on `React.lazy` and Suspense. The top-level Suspense is rendering a splash screen with a spinner. When the app hits `useAuth0.isLoading` the spinner flickers/resets multiple times, as this hook 'breaks' the suspense chain.

Sample load
1) App starts and loads directly imported (non-lazy) components
2) App hits first lazy component, renders Suspense splash screen
3) App hits `useAuth0`, `isLoading` is true, returns splash screen, React replaces top-level splash screen (flicker)
4) `isLoading` changes to false, App continues rendering (removes intermediary splash screen)
5) App hits next (nested) lazy component, re-renders the top-level Suspense splash screen (flicker)
6) Nested lazy components finish to load, React replaces splash screen with app

### Describe the ideal solution
Optional suspense support like `useSWR`, suspend rendering until `isLoading == false`

```
const { isAuthenticated } = useAuth0({ suspense: true })
```

**Comment by adamjmcgrath** [comment]
Hi @peterhirn - thanks for the suggestion

We'll definitely look into support for this React feature when it's no longer experimental - but not for the time being

**Comment by peterhirn** [comment]
Suspense is not experimental, it was added to React v16.6 back in 2018 https://reactjs.org/blog/2018/10/23/react-v-16-6.html

**Comment by adamjmcgrath** [comment]
I thought that was just for code-splitting

> Now you can use the Suspense component to do code-splitting by wrapping a dynamic import in a call to React.lazy().
> The Suspense component will also allow library authors to start building data fetching with Suspense support in the future.
https://reactjs.org/blog/2018/10/23/react-v-16-6.html#reactlazy-code-splitting-with-suspense

I assume you're talking about Suspense for data fetching which is still experimental AFAIK

**Comment by peterhirn** [comment]
Yes, code-splitting in combination with useAuth0 is exactly what I'd like to have fixed.

**Comment by adamjmcgrath** [comment]
Ah, ok my bad, your `useSWR` example threw me off. Would you mind sharing some code that demonstrates the issue and I'd be happy to investigate

**Comment by peterhirn** [comment]
Much appreciated.

index.tsx
```tsx
import { StrictMode, Suspense, lazy } from "react"
import { createRoot } from "react-dom"

import { Auth0Provider } from "@auth0/auth0-react"

const App = lazy(() => import("./App"))

const root = document.getElementById("root") as HTMLElement

createRoot(root).render(
  <StrictMode>
    <Auth0Provider
      domain={AUTH0_DOMAIN}
      audience={AUTH0_AUDIENCE}
      clientId={AUTH0_CLIENT_ID}
      useRefreshTokens={true}
      redirectUri={window.location.origin}
    >
      <Suspense fallback={<p>SPLASH SCREEN</p>}>
        <App />
      </Suspense>
    </Auth0Provider>
  </StrictMode>
)
```

App.tsx
```tsx
import { lazy } from "react"
import { useAuth0 } from "@auth0/auth0-react"

const Nested = lazy(() => import("./Nested"))

const App = () => {
  const { isLoading } = useAuth0()

  if (isLoading) return <p>AUTH0 IS LOADING</p>

  return <Nested />
}

export default App
```

Current UX:
1) SPLASH SCREEN
2) AUTH0 IS LOADING
3) SPLASH SCREEN
4) App with nested component

If the splash screen contains a spinner it will be reset on every load.

Desired UX:
1) SPLASH SCREEN
2) App with nested component

**Comment by adamjmcgrath** [comment]
Hi @peterhirn - I can't reproduce the issue you're describing (flickering between splash screen -> auth0 loading -> splash screen) using the following codepen https://codepen.io/adamjmcgrath/pen/dyVjbQx

Do you know what I have to do to that code to reproduce your issue?

**Comment by peterhirn** [comment]
Hi Adam, thanks for trying to reproduce.

The nested component (LOADING) needs to be lazy as well.

Suspense -> lazy -> useAuth0 -> lazy

When react hits the nested lazy component it will fallback to the top-level suspense and produce:

splash -> auth0 loading -> splash -> finish

**Comment by adamjmcgrath** [comment]
Ah, ok - have changed to codepen to add a nested lazy component and I see the behaviour you're describing https://codepen.io/adamjmcgrath/pen/dyVjbQx

However, I've also created a pen replacing auth0 with a simple 'loading' provider and get the same result https://codepen.io/adamjmcgrath/pen/yLzqpOm

Do you know how you would change `MyProvider` to get the behaviour you're after?

```js
const MyProvider = ({ children }) => {
  const [loading, setLoading] = useState(true);
  useEffect(() => {
    const timer = setTimeout(() => setLoading(false), 1000);
    return () => clearTimeout(timer);
  }, []);
  return <MyContext.Provider value={loading}>{ children }</MyContext.Provider>
}
```

**Comment by peterhirn** [comment]
Unfortunately I don't understand how to interact with Suspense on that level yet. I just found this very interesting example in the book [React Hooks in Action](https://www.manning.com/books/react-hooks-in-action).

https://codesandbox.io/s/suspensefordata2-xue0l

**Comment by adamjmcgrath** [comment]
I don't think the problem is with the SDK, you just need an extra suspense boundary for the nested lazy component (the components will be loaded sequentially, not in parallel)

```js
const App = () => {
  const { isLoading } = useAuth0()

  if (isLoading) return <p>AUTH0 IS LOADING</p>

  return (
    <Suspense fallback={<p>NESTED SPLASH SCREEN</p>}>
      <Nested />
    </Suspense>
  )
}
```

Have updated the codepen to illustrate this working https://codepen.io/adamjmcgrath/pen/dyVjbQx

**Comment by peterhirn** [comment]
The nested splash screen is what I'm trying to avoid, since I don't have anything meaningful to display until I know if the user is authenticated or not.

I think this Promise https://github.com/auth0/auth0-react/blob/master/src/auth0-provider.tsx#L241 has to be wrapped and thrown somehow to get a continuous suspense. I don't know if this is straightforward or entails a lot of restructuring.

Thank you very much for your efforts, I'm ok if you close this as won't-fix.

**Comment by adamjmcgrath** [comment]
You can't avoid 2 loading screens if you're loading 2 components sequentially - I don't think there's anything for the SDK to do here, but happy to reopen if you want to continue to discuss

**Comment by peterhirn** [comment]
I've been thinking about this a bit more and at some point was convinced that I'm wrong, and getting a continuous splash screen with lazy loading and additional suspended hooks is not possible.

Turns out that's not the case and everything works as I originally expected. Check out this sample app using `useSWR`.

*(omitted some code/imports for brevity)*

**index.tsx**
```tsx
const App = lazy(() => import("./App"))

let rendered = 0

const Splash = () => {
  rendered = rendered + 1
  console.debug("[Splash]", rendered)
  return <p>SPLASH</p>
}

const root = document.getElementById("root") as HTMLElement

createRoot(root).render(
  <StrictMode>
    <Suspense fallback={<Splash />}>
      <App />
    </Suspense>
  </StrictMode>
)
```

**App.tsx**
```tsx
const Nested = lazy(() => import("./Nested"))

const App = () => {
  const { data } = useSWR<Todo>("https://jsonplaceholder.typicode.com/todos/1", fetcher, {
    suspense: true
  })

  console.debug("[App]", data?.title)
  return (
    <>
      <p>App: {data?.title}</p>
      <Nested />
    </>
  )
}
```

**Nested.tsx**
```tsx
const Nested = () => {
  const { data } = useSWR<Todo>("https://jsonplaceholder.typicode.com/todos/2", fetcher, {
    suspense: true
  })

  console.debug("[Nested]", data?.title)
  return <p>Nested: {data?.title}</p>
}
```

Console log for production build
```
Navigated to http://localhost:3000/
index.tsx:10 [Splash] 1
App.tsx:13 [App] delectus aut autem
App.tsx:13 [App] delectus aut autem
App.tsx:13 [App] delectus aut autem
Nested.tsx:9 [Nested] quis ut nam facilis et officia qui
```

Even though there are multiple suspended hooks interleaved with lazy loaded components the splash screen is rendered exactly once and only replaced after the full app is loaded.

Now I also agree that this involves experimental APIs as you suggested in your first comment. It would be great if `useAuth0` could support `Suspense` at some point. In the meantime I'll probably just write a minimal custom AuthProvider using PKCE.

**Comment by adamjmcgrath** [comment]
Hi @peterhirn - thanks for sharing the `useSWR` example.

Yes, I'm sure there is something we can do in a similar vein when those APIs are promoted from experimental.

> In the meantime I'll probably just write a minimal custom AuthProvider using PKCE.

Couple of suggestions if you're planning to do this:

- You could try forking this repo and adding Suspense support yourself, there's always the possibility that we might want to integrate it further down the line.
- If you do want to create a new `AuthProvider`, note that this SDK is a (very thin) wrapper around `auth0-spa-js` - which can do all the PKCE heavy lifting for you.

**Comment by tplorts** [comment]
@peterhirn I think I'm trying to achieve exactly the same thing as you and this may help.

> If the splash screen contains a spinner it will be reset on every load.

^ that's why I've been trying to find a way to do this!

```ts
import { useAuth0 } from '@auth0/auth0-react';
import { FC, Fragment } from 'react';

export const Auth0LoadingBarrier: FC = ({ children }) => {
  const { isLoading } = useAuth0();

  if (isLoading) {
    throw new Promise(() => undefined);
  }

  return <Fragment>{children}</Fragment>;
};
```

and then my app structure at the root looks like:
```tsx
<Auth0Provider>
  <Suspense fallback={<Loader />}>
    <Auth0LoadingBarrier>
      <App />
    </Auth0LoadingBarrier>
  </Suspense>
</Auth0Provider>;
```

Now I'm no suspense expert so maybe what I'm doing here is breaking something and I have yet to discover the problem, but I'm getting the visual effect I was hoping for - my app has an animated loader, and throughout the entire initial app loading process which includes auth0 and then some data fetching, the animation is smooth and uninterrupted.

I found it a little suspicious that such a simple piece of code did what I wanted since I was reading various things and kept on finding stuff that was more complicated than what I needed (e.g. https://blog.logrocket.com/react-suspense-data-fetching/) but I hope this helps!

**Comment by latviancoder** [comment]
How exactly does that work for you @tplorts? Are you using React 18?

I tried your example and it just endlessly suspends on `isLoading=true`. For that example to work instead of returning `undefined` the Promise needs to be resolved when `isLoading` changes back to `false`, but it doesn't happen because it comes from a hook which is suspended too.

**Comment by abouroubi** [comment]
Looks like suspense is not experimental now, and a lot of frameworks are implementing it. 
are you planning on having a suspense version of Auth0-react ?

**Comment by frederikprijck** [comment]
Hey @abouroubi , can you clarify that?

On the [react docs regarding Suspense](https://react.dev/reference/react/Suspense), I found:

> Suspense-enabled data fetching without the use of an opinionated framework is not yet supported. The requirements for implementing a Suspense-enabled data source are unstable and undocumented. An official API for integrating data sources with Suspense will be released in a future version of React.

That doesn't look stable and recommended for us, as we do not use either Relay nor Nextjs.

**Comment by abouroubi** [comment]
Well auth0-react is a data fetching library that should implement the suspense api, IMHO.
Most of the react packages used in the community have implemented or are implementing it, for example:
react-router, relay, @apollo/client, react-query, ....

The part that talks about data fetching without a framework is not yet supported, as I understand it, is for implementing suspense in user facing app. But implementing suspense in a library/framework is supported, and has been implemented in many of them.

I have projects for many clients that uses react-router, react-query, apollo and auth0, and the only one not supporting suspense, and blocking us from updating is auth0.
