### ISSUE TITLE
Support for react-router-dom v6

### ISSUE THREAD

**Issue by euan-cowie** [auth0/auth0-react#315]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

The package in its current state only supports react-router-dom v5 as far as I'm aware. The existing `withAuthenticationRequired` does not work with the new <Route> components. The new <Route> components now have an `element` prop rather than `render` or `component`. The new format for protecting Routes, according to the docs, is something like so:

`
<Route path="/" element={
                    <RequireAuth>
                        <Something/>
                    </RequireAuth>
                }/>
`

A wrapper like the following will not work as it gives a `Functions are not valid as a React child` error.

```
function RequireAuth({ children }) {

        return withAuthenticationRequired(children);
    }
```

The following code from the [Complete Guide to React User Authentication](https://auth0.com/blog/complete-guide-to-react-user-authentication/#Protecting-Routes) guide also gives an error - `[ProtectedRoute] is not a <Route> component.`:

```
const ProtectedRoute = ({ element, ...args }) => (
  <Route
    element={withAuthenticationRequired(element, {
      onRedirecting: () => <div>Loading...<div/>,
    })}
    {...args}
  />
);
```

### Describe the ideal solution

A way of writing declarative routing for react-router-dom v6 using auth0-react. I might be missing an obvious workaround.

## Alternatives and current work-arounds

The only existing way I can get it working is by wrapping the export of my components but this prevents declarative routing, masking which Components are protected.

### Additional context

nil

**Comment by jeremy-marcus** [comment]
FYI, `react-router-dom` has an example of how to do auth with v6 here: https://stackblitz.com/github/remix-run/react-router/tree/main/examples/auth

**Comment by euan-cowie** [comment]
@jeremy-marcus Thanks for the response Jeremy! I was looking at that earlier today, yes. I suppose it might suffice for me to check also in a similar fashion whether the user exists using the auth0 hook, or `isAuthenticated`...

I suppose I was just unsure whether `withAuthenticationRequired` did anything special I might miss with my own checks, and subsequently if it might make sense to use it somehow with react-router-dom v6.

**Comment by jeremy-marcus** [comment]
You should be able to copy most of the code verbatim from `withAuthenticationRequired`.
https://github.com/auth0/auth0-react/blob/1f460701ab9cef676a4748ca3cd2f9f38411f2d1/src/with-authentication-required.tsx#L82-L119

**Comment by euan-cowie** [comment]
@jeremy-marcus Thanks! I've done that now. I have the following:

```
function RequireAuth({ children }) {
        const { isAuthenticated, isLoading, loginWithRedirect } = useAuth0();
        const location = useLocation();
        const navigate = useNavigate();

        const routeIsAuthenticated = isAuthenticated;

        useEffect(() => {
            if (isLoading || routeIsAuthenticated) {
                return;
            }
            // return setRedirect(true);
            return navigate("/login", { state: { from: location } });
        }, [isLoading, routeIsAuthenticated, loginWithRedirect, location, navigate]);

        return children;
    }
```

I opted for the useNavigate() hook but could have used useState and <Navigate> also I believe. There is an issue though. For some reason when I try to go to a protected page when I'm not logged in I always get 

```
react_devtools_backend.js:4045 Error: Login required
    at new OAuthError (errors.tsx:8)
   ...
```

So it's still rendering one time before navigating (due to `isLoading` I believe) and you can see a bit of a screen flash as this happens. This seems to happen with `loginWithRedirect` too but is muted when the Universal Login appears or something. It's not a major issue but a bit annoying.

**Comment by jeremy-marcus** [comment]
That might be because you don't have the `onRedirecting()` when `isAuthenticating` is false. That can display some other content like `<div>Redirecting to login</div>`.
```
return routeIsAuthenticated ? children : onRedirecting();
```

**Comment by euan-cowie** [comment]
Ah yes! Spot on. My bad for that. Thanks tremendously for your help @jeremy-marcus. I'm not sure if I should leave this open or not? [The Complete Guide to React User Authentication](https://auth0.com/blog/complete-guide-to-react-user-authentication/#Protecting-Routes) is outdated due to it...

**Comment by jeremy-marcus** [comment]
I'd leave it open for Auth0 to see and maybe integrate into their examples and docs.

**Comment by adamjmcgrath** [comment]
Hi @euan-cowie - thanks for raising this

I've upgraded the react router example app in the repo to v6 and it seems to work correctly, you can try it out here https://github.com/auth0/auth0-react/compare/react-router-v6 

Once react-router [releases a stable version](https://github.com/remix-run/react-router/releases/tag/v6.1.1) of `HistoryRouter` I'll update the example to v6 in the main branch

**Comment by Carlchk** [comment]
> Hi @euan-cowie - thanks for raising this
> 
> I've upgraded the react router example app in the repo to v6 and it seems to work correctly, you can try it out here https://github.com/auth0/auth0-react/compare/react-router-v6
> 
> Once react-router [releases a stable version](https://github.com/remix-run/react-router/releases/tag/v6.1.1) of `HistoryRouter` I'll update the example to v6 in the main branch

Hi @adamjmcgrath , seems that `<Switch>` has been removed from v6, so your method won't work. I am currently using 6.2.1 [react-router-v6](https://github.com/auth0/auth0-react/compare/react-router-v6)
