### ISSUE TITLE
Bundle size of auth0-react is large

### ISSUE THREAD

**Issue by LucasLemanowicz** [auth0/auth0-react#316]
### Describe the problem

The auth0-react bundle size is quite big at 100kb (31kb gzip compressed). This is by far the largest package in my front end JS bundle.

<img width="554" alt="Screen Shot 2022-01-09 at 5 03 45 PM" src="https://user-images.githubusercontent.com/361348/148708641-a50f05f3-6496-41c4-b5b5-53d8dc516509.png">

### What was the expected behavior?

It would be nice to make it smaller. Looks like there's been a couple of tickets on this already:
* https://github.com/auth0/auth0-react/issues/176
* https://github.com/auth0/auth0-react/issues/137

### Reproduction

1. Import the auth0-react library into your project
2. Run a bundle analyzer

### Environment

- **Version of `auth0-react` used:** "@auth0/auth0-react": "^1.8.0",
- **Which browsers have you tested in?** browser agnostic
- **Which framework are you using, if applicable (Angular, React, etc):** NextJS 12, React 17, Typescript 4.3
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @LucasLemanowicz - thanks for raising this

~80% of this SDK is https://github.com/auth0/auth0-spa-js and a significant proportion of that is polyfills to make the SDK operate with IE 11.

We have plans to reduce the size of auth0-spa-js by offering the option to load your required polyfills yourself, which will significantly reduce the bundle size. But for now the bundle size is expected and there's nothing to do for this SDK so closing.
