### ISSUE TITLE
withAuthenticationRequired's claimsCheck causing infinite loop in Next.js SPA

### ISSUE THREAD

**Issue by LucasLemanowicz** [auth0/auth0-react#320]
### Describe the problem
Hi, I think I'm misunderstanding how the authorization paradigm in `auth0-react` works. I have two pages on my Next.js site, both of which use `withAuthenticationRequired`:

Homepage (accessible with `/`):
```typescript
// ...
export default withAuthenticationRequired(Index);
```

ExtraSecurePage (accessible with `/ExtraSecurePage`):
```typescript
// ...
export default withAuthenticationRequired(ExtraSecurePage, {
    claimCheck: myClaimCheckFunction,
});
```

My `_app.tsx` is wrapped with the `<Auth0Provider />`:
```typescript
// https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#3-protecting-a-route-in-a-nextjs-app-in-spa-mode
const onRedirectCallback = (appState: AppState) => {
    // Use Next.js's Router.replace method to replace the url
    Router.replace(appState?.returnTo || "/");
};

// ...

return (
    <Auth0Provider {...AUTH0_CONFIG} onRedirectCallback={onRedirectCallback}>
        {/* ... */}
    <Auth0Provider>
);
```

If I have all the right claims on my account, both pages load fine.

If I don't have all the right claims, the home page works fine but `ExtraSecurePage` gets stuck in an infinite redirect loop of failing the claims check -> redirecting to `/` -> redirecting to `/ExtraSecurePage` -> failing the claims check -> ... (presumably because of the `onRedirectCallback` handler).

If I add the `returnTo: '/'` option to `withAuthenticationRequired`, that fixes the infinite redirect, but it now _always_ redirects to `/` when you directly visit that page (not via a link) - even when your account has all the correct claims to pass the claim check.

Can you help me understand what I'm doing wrong?

### What was the expected behavior?

* I expect someone with an account which passes the claims check to be able to type in the URL of the ExtraSecurePage to be able to load the page (and not be redirected home).
* I expect someone with an account that does not pass the claims check to not be able to view the page, be redirected elsewhere, and/or be shown an error
* I expect to be able to specify where to redirect the user if the claims check fails, but not have that affect the returnTo for someone who is simply not yet logged in.

### Reproduction

See above.

### Environment

- **Version of `auth0-react` used:** 1.8.0
- **Which browsers have you tested in?** Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** Next.js 12, React 17
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @LucasLemanowicz - thanks for raising this.

You can achieve this by nesting `withAuthenticationRequired`, so that you can make sure only authenticated visitors are hitting your `claimCheck` routes, for example:

```jsx
<Router>
  <AnonymousPage/>
  <SecureSection>
    <SecurePage/>
    <ExtraSecurePage/>
  </SecureSection>
</Router>

const SecureSection = withAuthenticationRequired(Component);
const ExtraSecurePage = withAuthenticationRequired(Component, { claimCheck: myClaimCheckFunction });

// Or if you have a flat route structure

const ExtraSecurePage = withAuthenticationRequired(
  withAuthenticationRequired(Component, { claimCheck: myClaimCheckFunction, returnTo: '/somewhere-else' })
);
```

I'm wondering if there's a way to do this without redirecting to login again, I guess we could pass user to the `returnTo` option when it's supplied as a function, so you could make better decisions about `returnTo` based on the user:

```js
const returnTo = (user) => {
  if (user) {
    // logged in, so you've failed a claim check
    return '/'
  }
  return window.location.pathname;
}
```

Let me know if that would be better and I'll look into adding it.

**Comment by LucasLemanowicz** [comment]
Thanks, that seems to fix the core issue. Having the `returnTo` be a function would be very helpful IMO.

One additional small nit with `withAuthenticationRequired`: if a user fails the claims check it triggers a hard redirect / re-login instead of just a clean route-based redirect to "/":

https://user-images.githubusercontent.com/361348/149399946-fc0ce488-2b18-4046-a8b5-5663ea9591ac.mov

I presume this is because `auth0-react`'s `returnTo` uses `auth0-spa-js`'s `loginWithRedirect` method, which uses [window.location](https://github.com/auth0/auth0-spa-js/blob/9c834f11093487828251fe61e0f5e4173b1662af/src/Auth0Client.ts#L623), which is incompatible with Next.js's (or other JS) Route libraries.

Do you have any suggestions for how to fix that? Ideally I'd be able to control how the redirect happens on the claim check fail, ex: `returnToFn: (_user: User | undefined) => () => Router.push("/"),` but maybe this is already a solved problem with a cleaner solution.

**Comment by adamjmcgrath** [comment]
> One additional small nit with withAuthenticationRequired: if a user fails the claims check it triggers a hard redirect / re-login instead of just a clean route-based redirect to "/":

Yeah, I can see how this is undesired in your case. `claimCheck` should probably be it's own method, rather than including it in `withAuthenticationRequired` - since this is designed to log you in if any of the checks fail, and you just want a route guard for already logged in users.

> Do you have any suggestions for how to fix that? 

I would personally just create another HOC that did the claim check for you and nest it in `withAuthenticationRequired`, eg (untested)

```js
const withClaimCheck = (Component, myClaimCheckFunction, returnTo) => {
  const { user } =  useAuth0();
  if (myClaimCheckFunction(user)) {
    return <Component />
  }
  Router.push(returnTo);
}

// Usage
const ExtraSecurePage = withAuthenticationRequired(
  withClaimCheck(Component, myClaimCheckFunction, '/somewhere-else' )
);
```

**Comment by adamjmcgrath** [comment]
Closing - feel free to ping me if you want to discuss further
