### ISSUE TITLE
Doesn't work with react-router 6

### ISSUE THREAD

**Issue by orinoco** [auth0/auth0-react#332]
### Describe the problem

React router 6 has been out for a while now. Protecting a route as described by auth0 simply errors.

https://reactrouter.com/

Error: [ProtectedRoute] is not a <Route> component. All component children of <Routes> must be a <Route> or <React.Fragment>

### What was the expected behavior?

The page should show and be protected.

### Reproduction

- Step 1. Follow the example provided by auth0: https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#1-protecting-a-route-in-a-react-router-dom-app
- Step 2. Use react-router 6 in package.json
- Step 3. Try to run the app

### Environment

> Please provide the following:

- @auth0/auth0-react: 1.9.0

**Comment by speediac** [comment]
i'm not a contributor here but have updated my app to react-router v6 already. Here's an updated example for you to get it working:

```
import React from 'react';
import { BrowserRouter, Route, Routes } from 'react-router-dom';
import { Auth0Provider, withAuthenticationRequired } from '@auth0/auth0-react';
import Profile from './Profile';

const ProtectedProfile = withAuthenticationRequired(Profile);

export default function App() {
  return (
    <Auth0Provider
      domain="YOUR_AUTH0_DOMAIN"
      clientId="YOUR_AUTH0_CLIENT_ID"
      redirectUri={window.location.origin}
    >
      <BrowserRouter>
        <Routes>
          <Route path="/" />
          <Route path="/profile" element={ProtectedProfile} />
        </Routes>
      </BrowserRouter>
    </Auth0Provider>
  );
}
```
There are a couple other options for you too @orinoco. he's the docs for upgrading from v5 to v6. They changed a lot about how the Route component works

**Comment by orinoco** [comment]
Yes that works quite nicely as a workaround. I just abstracted the HOC a bit.

`const ProtectedRoute = ({ component, ...props }) => {
  const WrappedComponent = withAuthenticationRequired(component);
  return <WrappedComponent {...props} />;
};
...
<Route path="/profile" element={<ProtectedRoute component={Profile} />} />
`

**Comment by Gil3co** [comment]
> withAuthenticationRequired

This worked like a charm!
