### ISSUE TITLE
Safari MacOS, getAccessTokenSilently({ ignoreCache: true }) issues 

### ISSUE THREAD

**Issue by speediac** [auth0/auth0-react#333]
### Describe the problem

> Provide a clear and concise description of the issue

MacOS Safari Only (MacOS 12.2.1)

1. On returning to the login callback url after "successful" login, `getAccessTokenSilently({ ignoreCache: true })` will fail with "Login Required" error even though the useAuth0().isAuthenticated value is true before calling.
2. Accounting for the first issue by not ignoring the cache on the return from login. When later calling `getAccessTokenSilently({ ignoreCache: true })`, the browser redirects to auth0's authorise url and then back to the app thus full page reload rather than silently fetching a new token like in previous versions.

> Tell us about the behavior you expected to see
1. if the useAuth0 hook is returning isAuthorised set to true, then calling for a new accessToken shouldn't return a "Login Required" error.
2. when requesting a new accessToken, the browser url should not change and the SPA should not be reloaded.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- See description

### Environment

> Please provide the following:

- **Version of `auth0-react` used: 1.9.0
- **Which browsers have you tested in? Issue is only with Safari MacOS. Chrome & Firefox are fine
- **Which framework are you using, if applicable (Angular, React, etc): React 17.0.2
- **Other modules/plugins/libraries that might be involved: N/A

**Comment by frederikprijck** [comment]
As mentioned in the FAQ: https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md, Silent Authentication does not work with Safari. You need to work around this by either using custom domains or use refresh tokens.

That said, you typically do not need to ignore the cache, any reason you need that here?

Calling `getAccessTokenSilently` isn't supposed to redirect. Could you provide more information about that? Could there be any code that calls loginWithRedirect?

**Comment by speediac** [comment]
Hi @frederikprijck, thanks for responding so quickly. Yes, you are correct, i had `loginWithRedirect` in the catch of `getAccessTokenSilently` so it is just failing always. sorry.

Thanks the FAQs. the odd thing is that it was working before upgrading to the latest version. I don't "need" it on the login callback but i have instances where we're changing attributes on the token or user profile e.g. changing permissions of the user so was relying on our own logic to decide when to fetch a new token.

Thanks 👍
