### ISSUE TITLE
Auth0 React SDK - make presence of sign-up link configurable

### ISSUE THREAD

**Issue by lcbuchanan** [auth0/auth0-react#337]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

> We've just started using the Auth0 SDK for React apps and would like to hide the "sign up" link/button from the login page. We have a few extra steps to our sign-up process and don't want to confuse users.

### Describe the ideal solution

> Ideally, we'd love to be able to hide this button by passing in specific props to the Auth0 login page component.

## Alternatives and current work-arounds

> We've found a way to achieve this outcome by disconnecting our instance of the Auth0 SDK from our database, but this feels a heavy-handed solution.
### Additional context

> I've been poking around the internet and have not yet found an easy way to do this. If one exists, please let me know!

**Comment by frederikprijck** [comment]
I don't believe the Auth0 API provided a way for any SDK to configure whether or not the signup should be available.

If you are using a Database Connection, u can however disable Signup from your Auth0 dashboard. To do so, go to `Authentication` > `Database`, then all the way at the bottom u can toggle `Disable Sign Ups`:

![image](https://user-images.githubusercontent.com/2146903/157197126-a39c1d77-11f8-459d-95c0-3676e487ce9e.png)

Would that help?

**Comment by lcbuchanan** [comment]
oh thanks! I'll investigate!

**Comment by lcbuchanan** [comment]
aha! that did it. thank you @frederikprijck!
