### ISSUE TITLE
Auth0 library not found react [Duplicate Issue]

### ISSUE THREAD

**Issue by Hamza-101** [auth0/auth0-react#338]
Hi, using the latest version of Create React App and VSCode in Windows 11, "@auth0/auth0-react": "^1.9.0", I know it's installed because I can check my version in package.json, However, I get this error "./src/index.js
```
Compiled with problems:

ERROR in ./src/index.js 8:0-46

Module not found: Error: Can't resolve '@auth/auth0-react' in 'C:\Users\Cr7th\login\src'
```
when importing "import { Auth0Provider } from "@auth0/auth0-react";".

Thanks!

**Comment by evansims** [comment]
Hi @Hamza-101 👋 The error message you shared states `@auth/auth0-react` instead of `@auth0/auth0-react`. Could be a typo in your import?

**Comment by Hamza-101** [comment]
So it was  a typo, @auth0/auth0-react works. but the error persists 
![image](https://user-images.githubusercontent.com/45544623/157383197-e7d05746-d88b-472e-9530-e2a71fee1c05.png)
