### ISSUE TITLE
Accessing `getAccessTokenSilently` outside react component (function/class components)

### ISSUE THREAD

**Issue by aibrahim3546** [auth0/auth0-react#339]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved
My project is using React class components. I have setup a function for my api request. Currently I am facing an issue, where I need to pass around the `accessToken` every time I make api request. How can I access the accessToken directly inside my **api request** function?

> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
### Describe the ideal solution
the solution will be to access the `getAccessTokenSilently` method outside the react component.

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.
### Additional context
I don't have any workaround in place at the moment.

**Comment by adamjmcgrath** [comment]
Hi @aibrahim3546 - this has been answered a few times

See https://gist.github.com/adamjmcgrath/0ed6a04047aad16506ca24d85f1b2a5c for more details and workarounds to your problem
