### ISSUE TITLE
Typing for `onRedirectCallback` in `Auth0Provider` component is incorrect

### ISSUE THREAD

**Issue by jbean96** [auth0/auth0-react#340]
### Describe the problem

> I believe that the type for `onRedirectCallback` prop for the `Auth0Provider` component is incorrect. It is currently typed as `(appState: AppState) => void`.

### What was the expected behavior?

> The type should be `(appState?: AppState) => void` as the parameter may be `undefined` if it is not supplied to the call of login. This is both based on practical testing of the functionality as well as the default definition in the `Auth0Provider` which is defined as 
```
const defaultOnRedirectCallback = (appState?: AppState): void => {
  window.history.replaceState(
    {},
    document.title,
    appState?.returnTo || window.location.pathname
  );
};
```

### Reproduction

Invoke `loginWithRedirect` without supplying an `appState` property in an Auth0 application. Provide an `onRedirectedCallback = (appState?: AppState) => { ... }` function to the `Auth0Provider`. Set a breakpoint and observe that `appState` is undefined.

**Comment by adamjmcgrath** [comment]
Good point @jbean96 - raised #341 to fix
