### ISSUE TITLE
How to add token as a query parameter to the redirectUrl?

### ISSUE THREAD

**Issue by alexmyshchyshyn** [auth0/auth0-react#342]
Hello guys.

I have 2 applications - mobile ( React Native ) and web ( React ). For auth, I am using deep linking. The redirect URL in my case is `smartcrowdapp://auth`. 

Currently, if I will enter `http://localhost:3000/?redirectUrl=smartcrowdapp://auth` then after login user will be asked to open the mobile application and I expect that he will be logged in. But I want to add a token to this redirect URL for storing it at the mobile application to make API Calls.

I can not get token at `redirectCallBack` and i tried auth0 actions, but it says 
`Invalid redirect URL smartcrowdapp://auth?session_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE2NDgwNjM0NjksImlzcyI6InNjLXN0YWdpbmcuZXUuYXV0aDAuY29tIiwic3ViIjoiYXV0aDB8NjIwZDJkNTU1YWNmNzEwMDZmN2FiMjBiIiwiZXhwIjoxNjQ4MDY0MzY5LCJpcCI6Ijk0LjIzMS43Ni4xMjMiLCJlbWFpbCI6ImFsZXh0ZXN0QHlvcG1haWwuY29tIn0.NHq2qBWzDLfUPVXqZY0Olg4rbTdADrpDg92Shr2iEBw`

Auth0 Action:
```
exports.onExecutePostLogin = async (event, api) => {
  const query = event.request.query.redirectUrl;

      // Craft a signed session token
  const token = api.redirect.encodeToken({
    secret: MY_SECRET,
    payload: {
      email: event.user.email,
    },
  });

  
  api.redirect.sendUserTo("smartcrowdapp://auth", {
    query: { session_token: token }
  });
};
```

React Auth0 Provider
```
const redirectUrl = parsedLocationSearch?.redirectUrl || `${window.location.origin}/property-browse`;

const redirectCallBack = (appState) => {
    const { code, state, ...params } = parse(window.location.search);
    const stringifiedSearch = stringify(params);
    myHistory.push(
         appState && appState.returnTo ? appState.returnTo : 
                             `${window.location.pathname}${stringifiedSearch}`,
    );
};



 <Auth0Provider
    domain={process.env.REACT_APP_AUTH_DOMAIN}
    clientId={process.env.REACT_APP_AUTH_CLIENT_ID}
    redirectUri={redirectUrl}
    audience={audience}
    scope={requestedScopes.join(' ')}
    useRefreshTokens
    cacheLocation="localstorage"
    onRedirectCallback={redirectCallBack}
>
    {children}
</Auth0Provider>
```

P.S I tried react-native-auth0 library, but it can not handle my case.

**Comment by adamjmcgrath** [comment]
Closing - feel free to ping me if you want to continue the conversation
