### ISSUE TITLE
React: Login @auth0/auth0-react using loginWithRedirect not working while loginWithPopup works well 

### ISSUE THREAD

**Issue by tiwarivijay123** [auth0/auth0-react#344]
### Problem

> When trying to use `loginWithRedirect` using https://auth0.com/docs/quickstart/spa/react/01-login first time it successfully logging me in and takes to onboard page means `window.location.origin` after login when I'm trying to login next time it just reloads the page and taking me back again and again while loginWithPopup works well.

### What was the expected behavior?

> Expected behaviour is after login it should take me to dashboard with token & user details.

### Reproduction
- `npm install @auth0/auth0-react`
-  follow the steps as suggested here  https://auth0.com/docs/quickstart/spa/react/01-login

### Environment
<img width="268" alt="Screenshot 2022-03-25 at 11 11 27 PM" src="https://user-images.githubusercontent.com/59466967/160173610-9297deba-6c9d-4086-89f0-4a9369cbaa30.png">

- **Version  "@auth0/auth0-react": "^1.9.0", used.**
- **Browsers Chrome & safari.**
- **Framework `next js` ( used this SDK also https://auth0.com/docs/quickstart/webapp/nextjs/01-login ) same behaviour for redirect login now using  https://auth0.com/docs/quickstart/spa/react/01-login.**

**Comment by adamjmcgrath** [comment]
Hi @tiwarivijay123 - thanks for raising this

Looks like you've [raised the same issue with the underlying library](https://github.com/auth0/auth0-spa-js/issues/889), so let's keep the conversation there
