### ISSUE TITLE
Version 1.9.0 can't be installed with React 18

### ISSUE THREAD

**Issue by asafyish** [auth0/auth0-react#349]
When trying to install @auth0/auth0-react@1.9.0 in a React 18 project, npm fails with:
```shell
npm ERR! Could not resolve dependency:
npm ERR! peer react@"^16.11.0 || ^17" from @auth0/auth0-react@1.9.0
npm ERR! node_modules/@auth0/auth0-react
```

**Comment by adamjmcgrath** [comment]
Hi @asafyish - thanks for raising this.

I can't give you a timeline, but we'll be updating the peer dependencies at some point. For the time being you should be able to install the SDK with the `--legacy-peer-deps` npm flag

**Comment by cyyprezz** [comment]
Is there any workaround for working with this sdk & React18? Becouse 1.9 seems to be incompatible. And is there a timeline?

**Comment by frederikprijck** [comment]
@cyyprezz , wouldn't what is mentioned here https://github.com/auth0/auth0-react/issues/349#issuecomment-1087371438 work for now?

**Comment by onionhammer** [comment]
IMO just because there's a workaround doesn't mean this is fixed...

**Comment by frederikprijck** [comment]
Sorry, this got closed because the PR got merged, will cut a new release early next week.

**Comment by frederikprijck** [comment]
We cut a new release, you should be able to use React 18 with version 1.10.0.
