### ISSUE TITLE
Facebook permission error

### ISSUE THREAD

**Issue by nuoanunu** [auth0/auth0-react#360]
Hi guys 1 of the scope in auth0 is out dated and need to be fixed asap
I wonder how come nobody in the team keep track of all of this
![image](https://user-images.githubusercontent.com/11647245/167060750-b2a30197-55e0-429e-94ad-2de9179dd33d.png)
![image](https://user-images.githubusercontent.com/11647245/167060760-e15ea420-7cab-40e3-832e-f1fc79861bc2.png)

**Comment by stevehobbsdev** [comment]
Hi @nuoanunu, could you please leave this feedback on our [product feedback page](https://auth0.com/feedback)?

I have also notified the correct team internally of your feedback.

Thanks
