### ISSUE TITLE
Authentication not persisting on safari

### ISSUE THREAD

**Issue by nthh** [auth0/auth0-react#362]
### Describe the problem
Using Safari Version 14.1.2, using the method loginWithRedirect works and authenticates correctly. 

After refresh, no calls are made to the auth0 domain. On Firefox, the auth0 domain is called and authentication is successful. 

### What was the expected behavior?
Authentication to persist across refreshing on Safari. 

### Environment
nextjs app, safari

**Comment by frederikprijck** [comment]
Thanks for reporting, this is a known limitation when using browsers that block 3rd party cookies, such as Safari. [See our FAQ](https://github.com/auth0/auth0-react/blob/master/FAQ.md#1-user-is-not-logged-in-after-page-refresh).

This can be solved by using custom domains or refresh tokens.
