### ISSUE TITLE
Pass a client to Auth0Provider

### ISSUE THREAD

**Issue by reify-thomas-smith** [auth0/auth0-react#364]
### Describe the problem you'd like to have solved

I'd like to use `<Auth0Provider>`/`useAuth0()` in my React app, but for complicated reasons I have an existing Auth0Client object I need to use, whereas `<Auth0Provider>` expects to build its own client from props.

### Describe the ideal solution

```jsx
<Auth0Provider client={myClient}>…</Auth0Provider>
```

## Alternatives and current work-arounds

- A new provider component to use instead of `<Auth0Provider>`.
- Don't use `<Auth0Provider>`/`useAuth0()`.
- Copy/paste the `<Auth0Provider>` implementation and modify it.

**Comment by adamjmcgrath** [comment]
HI @reify-thomas-smith - thanks for raising this

We've covered this a few times before, see https://github.com/auth0/auth0-react/pull/348 for more information
