### ISSUE TITLE
authorize using username and password by loginWithRedirect?

### ISSUE THREAD

**Issue by rhoiyds** [auth0/auth0-react#372]
When creating a custom built login page on my site, it is possible to login with social connections such as Twitter and Google by specifying the `connection` option on the `RedirectLoginOptions` passed to the `loginWithRedirect` function, however in the same manner, I was expecting the ability to specify the connection to be the Auth0 connection on my tenant used for storing username and password logins, as well as adding the user filled-in properties `username` and `password` onto the `RedirectLoginOptions`.
I'm however always taken to my tenants `/login` universal login page for my tenant, which I don't want to use - as I'm building a custom styled login/sign up page.
Is this intentional - or is there something I am missing?

**Comment by adamjmcgrath** [comment]
Hi @rhoiyds - thanks for raising this

This is intentional, this SDK works by redirecting you to the Universal Login page to login. You cannot use embedded authentication with this SDK, see https://auth0.com/docs/authenticate/login/universal-vs-embedded-login for more info
