### ISSUE TITLE
Access token not reloaded despite `ignoreCache` flag

### ISSUE THREAD

**Issue by Ruyven** [auth0/auth0-react#375]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

When calling `getAccessTokenSilently({ ignoreCache: true });` right after updating the user's name or email address, no network call to `/auth0/token` is being made and the name is not updated.

Only when using `setTimeout` (with or without delay) can I observe the network call in the dev tools and the request comes back with the new name.

### What was the expected behavior?

Specifying `ignoreCache: true` should always cause the user to be refreshed from the auth0 API.

### Reproduction

- Update user details, e.g. name or email via a call to the management API. Wait for the result, e.g. with async / await.
- Call `getAccessTokenSilently({ ignoreCache: true });`
- No network request, method immediately returns with the outdated data.
- Call `setTimeout(() => { getAccessTokenSilently({ ignoreCache: true }); });`
- The network request to the token endpoint is made and returns the correct data.

### Environment

- **Version of `auth0-react` used:** 1.10.1
- **Which browsers have you tested in?** Chrome 103.0.5060.53
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @Ruyven - thanks for raising this

> Update user details, e.g. name or email via a call to the management API. Wait for the result, e.g. with async / await.

You shouldn't be able to update the user's name or email from a public client like a SPA. only the user's metadata - using `update:current_user_metadata`, see https://auth0.com/docs/secure/tokens/access-tokens/get-management-api-tokens-for-single-page-applications#available-scopes-and-endpoints

I'm not able to reproduce the issue you describe, using the steps you provided and updating the users metadata.

When I update the user then immediately call `getAccessTokenSilently({ ignoreCache: true })` I see the new requests (have tested both for the web_message response_mode and refresh grant) and the new access token is different to the original one.

eg

```jsx
<Auth0Provider
    audience={`https://${domain}/api/v2/`}
    scope={'update:current_user_metadata'}>
   // other props
```

```js
const at = await getAccessTokenSilently();
const resp = await fetch(
  `https://${domain}/api/v2/users/${user.sub}`,
  {
    method: 'PATCH',
    headers: {
      authorization: `Bearer ${at}`,
      'content-type': 'application/json',
    },
    body: JSON.stringify({
      user_metadata: { foo: `foo-${Date.now()}` },
    }),
  }
);
console.log(await resp.json()); // logs updatated user metadata
const at2 = await getAccessTokenSilently({ ignoreCache: true });
console.log(at === at2); // Logs `false` because a new token has been fetched
```

**Comment by adamjmcgrath** [comment]
Closing due to innactivity
