### ISSUE TITLE
Call to getAccessTokenSilently cause a re render

### ISSUE THREAD

**Issue by guillame33** [auth0/auth0-react#376]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

We want to have the equivalent of the `getSSOData` method that was available in the `auth0-js` SDK. 

This method was used by us to know if a user has logged out of an application, in order to automatically log him out in other applications.
 
To have the same functionality we wanted to call the getAccessTokenSilently method regularly.
The problem is that regular calls to getAccessTokenSilently cause the whole application to be rendered 

### What was the expected behavior?

A call to getAccessTokenSilently should not case re-rendering.
Or
Provide a way to have the equivalent of the `getSSOData` method i.e. a way to know when a SSO session has ended.

### Reproduction

With a simple application I can reproduce the behavior.

In the `index.js` file :
```js
<React.StrictMode>
    <Auth0Provider
      domain="<myAuth0Domain>"
      clientId="<myClientID>"
      redirectUri={window.origin}
    >
      <App />
    </Auth0Provider>
  </React.StrictMode>
```

in the `App.js` file :
```js
mport React from "react";
import { useAuth0 } from "@auth0/auth0-react";

import "./App.css";

function App() {
  const {
    getAccessTokenSilently,
    logout,
    error,
    isAuthenticated,
    isLoading,
    user,
    loginWithRedirect,
  } = useAuth0();

  // This effect causes re rendering of the entire application
  React.useEffect(() => {
    const ssoInterval = setInterval(async () => {
      try {
        const sso = await getAccessTokenSilently({
          ignoreCache: true,
        });
        if (!sso) {
          logout();
        }
      } catch (error) {
        // We are probably offline... Do nothing...
      }
    }, 10000);
    return () => clearInterval(ssoInterval);
  }, []);

  // no re rendering with a very simple interval
  React.useEffect(() => {
    const otherInterval = setInterval(async () => {
      console.log("Just writing to the console, no rerender...");
    }, 9500);
    return () => clearInterval(otherInterval);
  }, []);

  if (isLoading) {
    return <div>Loading ...</div>;
  }

  if (error) {
    return <div>Oups Something went wrong : {error.message}</div>;
  }

  return isAuthenticated ? (
    <div className="App">
      <header className="App-header">
        <DisplayInfos label="Email" value={user.email} />
        <DisplayInfos label="Family Name" value={user.family_name} />
        <DisplayInfos label="Name" value={user.given_name} />
        <button onClick={() => logout({ returnTo: window.origin })}>
          Logout
        </button>
      </header>
    </div>
  ) : (
    <button onClick={() => loginWithRedirect()}>Clic to login</button>
  );
}

const DisplayInfos = ({ label, value }) => {
  console.log(`Render for ${label}`);
  return (
    <p>
      {label} : {value}
    </p>
  );
};

export default App;
```

### Environment

- **Version of `auth0-react` used:** 1.10.2
- **Which browsers have you tested in?** : Chrome latest
- **Which framework are you using, if applicable (Angular, React, etc):** : React 18

**Comment by adamjmcgrath** [comment]
Hi @guillame33  - thanks for raising this

> A call to getAccessTokenSilently should not case re-rendering.

Calling `getAccessTokenSilently({ ignoreCache: true })` when you're not using Refresh Tokens, is effectively telling the SDK to login the user in again silently. Logging the user in again means you'll get a new user (with a new `updated_at` prop and possibly others, since this [gets updated when the user logs in](https://auth0.com/docs/manage-users/user-accounts/user-profiles/user-profile-structure#:~:text=Timestamp%20indicating%20when%20the%20user%27s%20profile%20was%20last%20updated/modified.%20Changes%20to%20last_login%20are%20considered%20updates%2C%20so%20most%20of%20the%20time%2C%20updated_at%20will%20match%20last_login.)), so it's expected that any component that relies on the user will get rendered again.

If you don't want this behaviour, you could create a proxy user that only gets updated when you want it to, and have your components rely on that. Something like (untested):

```js
const { user } = useAuth0();
const [ proxyUser, setProxyUser ] = useState(user);

useEffect(() => {
  setProxyUser(user);
}, [user?.name]) // Only updated proxy user when user.name changes (ignore user.updated_at)

return <DisplayInfos label="Name" value={proxyUser.name} />;
```

**Comment by guillame33** [comment]
Hi @adamjmcgrath. Thank you for your quick response.

I did some tests using your solution.

Unfortunately it won't work for me because I think your example requires memoizing the child components.

However my case is more complex than the example I have provided here.

We want to produce a library and so I don't have the control of what will be the children of my provider.

Are there no other solutions?

Maybe we can give access to the `Auth0Client` provided by the `@auth0/auth0-spa-js` library to be able to use directly `getTokenSilently` without any effect being triggered?

Any other ideas?

**Comment by guillame33** [comment]
Hello.
Finally, for those who are interested, I made the following code to check the connection status regularly using directly the `@auth0/auth0-spa-js` library : 

```js
const { logout } = useAuth0()
const auth0Client = new Auth0Client({
        domain,
        client_id: clientId,
        redirect_uri: redirectUri,
})

React.useEffect(() => {
        if (ssoHeartBeat) {
            const ssoInterval = setInterval(async () => {
                try {
                    const sso = await auth0Client.getTokenSilently({ ignoreCache: true })
                    if (!sso) {
                        logout()
                    }
                } catch (error) {
                    const { error: auth0Error } = error
                    if (auth0Error === "login_required") {
                        logout()
                    }
                    // otherwise do nothing we are probably offline...
                }
            }, interval)
            return () => clearInterval(ssoInterval)
        }
        // eslint-disable-next-line react-hooks/exhaustive-deps
 }, [ssoHeartBeat])
```
