### ISSUE TITLE
getAccessTokenSilently({ignoreCache: true}) errors with "Login required" on Safari

### ISSUE THREAD

**Issue by NeilJ247** [auth0/auth0-react#377]
### Describe the problem

When calling `getAccessTokenSilently({ignoreCache: true})` I get "Unhandled Promise Rejection: Error: Login required" error in the console.  This only appears to happen on Safari for some reason.

### What was the expected behavior?

I should be able to get a new token without error.

### Reproduction

I have attached an example project to help replicate the problem.  Replace domain and client id.

Two buttons: one for logging in and the other for logging token to the console.

[auth0-token-example.zip](https://github.com/auth0/auth0-react/files/9028149/auth0-token-example.zip)

### Environment

Auth0: "@auth0/auth0-react": "^1.10.2"
Browsers (macOS: 
- Chrome Version 103.0.5060.53 - works fine
- Safari Version 15.5 (17613.2.7.1.8) - broken
- Samsung Internet v17.0.6.9 - broken

Framework: "react": "^18.2.0"

**Comment by NeilJ247** [comment]
Updated browsers list.  Same issue with Samsung Internet.

**Comment by NeilJ247** [comment]
@stevehobbsdev I am still seeing "Login required" error with `useRefreshTokens` enabled and `cacheLocation` set to `localstorage` as per the link you provided.  Any ideas?

**Comment by GMaiolo** [comment]
@NeilJ247 did you ever find a reason?

**Comment by grantbrooksdev** [comment]
@stevehobbsdev Do you have a recommendation for @NeilJ247 ’s situation? Thanks!

**Comment by stevehobbsdev** [comment]
It's difficult to say without seeing a repro. That configuration should work fine. However, you would see this error if the user has not logged in through the front channel at some point before calling `getRefreshTokenSilently`.

If you can proved a small repro that shows the issue (you can base it on the [quickstart sample](https://github.com/auth0-samples/auth0-react-samples) if you like), we can take a look.

**Comment by NeilJ247** [comment]
Hi, 

Apologies for the late reply. 

In the end we ended up configuring the custom domain in Auth0.  It should still be reproduceable by taking my attached code in the description and setting useRefreshTokens and cacheLocation as per previous instructions.

**Comment by grantbrooksdev** [comment]
Thanks for your replies @NeilJ247 and @stevehobbsdev 

I ended up fixing the issue in my project and without a custom domain by wrapping components in the withAuthenticationRequired HOC. I ensured specifically that my login/signup redirect callback was wrapped like this.

`export default withAuthenticationRequired(SomeComponent, { onRedirecting: () => <>Loading…</>}); `
