### ISSUE TITLE
Missing SameSite attributes on some Auth0 cookies

### ISSUE THREAD

**Issue by caribou-code** [auth0/auth0-react#389]
### Describe the problem

On initial load of `Auth0Provider` I see issues flagged in the console about missing SameSite attributes on some of the Auth0 cookies:

```
Indicate whether a cookie is intended to be set in a cross-site context by specifying its SameSite attribute.

Resolve this issue by updating the attributes of the cookie:
  - Specify SameSite=None and Secure if the cookie is intended to be set in cross-site contexts. Note that only cookies sent over HTTPS may use the Secure attribute.
  - Specify SameSite=Strict or SameSite=Lax if the cookie should not be set by cross-site requests.

Affected resources:

2 cookies
  - did_compat
  - auth0_compat
```

The cookies above are being set on a custom domain I have configured for Auth0. I am developing on localhost which is of course a different domain. Aside from the 2 cookies above, I can also see that the legacy cookie doesn't have the SameSite attribute set, but maybe that's intended?

### What was the expected behavior?

Not to see a bunch of issues being flagged about missing attributes on the Auth0 cookies.

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.10.1
- **Which browsers have you tested in?** Chrome & Firefox latest
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by stevehobbsdev** [comment]
👋🏻  This is intended. We don't set the SameSite attribute on those cookies specifically for browsers that don't support this attribute. Unfortunately, it does mean some warnings for these cookies in browsers that _do_ support them but shouldn't cause any adverse effects.

For more detailed information, please read: https://auth0.com/docs/manage-users/cookies/samesite-cookie-attribute-changes
