### ISSUE TITLE
Remove react-dom as peer-dependency

### ISSUE THREAD

**Issue by sirvess** [auth0/auth0-react#394]
### Describe the problem you'd like to have solved

I would like `react-dom` to be removed from the `peerDependencies` list. For a project using `auth0-react` but not using `react-dom`, this causes warnings/errors when trying to install the project with `npm`, and requires the use of `npm i --legacy-peer-deps`.

### Describe the ideal solution

`react-dom` does not seem to be used for anything else than some examples. Can we just remove it?

## Alternatives and current work-arounds

`npm i` with `--legacy-peer-deps` flag (when not using react-dom)

### Additional context

> Add any other context or screenshots about the feature request here.

**Comment by adamjmcgrath** [comment]
Hi @sirvess - thanks for raising this

Can you tell me a bit more about how you are using this SDK, how are you able to do it without the DOM?

**Comment by sirvess** [comment]
We are in the end using it with `react-dom`, but have an intermediary sdk which uses type-definitions from auth0 (but no runtime dependencies). Still, this causes the intermediary sdk to require the react-dom, which we don't want.

**Comment by adamjmcgrath** [comment]
Hi @sirvess - since this SDK doesn't work without react-dom, then I don't see a good reason to remove it from the peer deps. It sends the wrong message about this SDK (like that it could be used with react-native for example, when it can't)
