### ISSUE TITLE
Email verification doesn't refresh without a logout and login

### ISSUE THREAD

**Issue by GMaiolo** [auth0/auth0-react#396]
### Describe the problem

When the user verifies their account, the session doesn't refresh until they logout and login again.
If we execute `getAccessTokenSilently` with `ignoreCache: true`, then the user gets automatically logged out with the `"login required"` error.

### What was the expected behavior?

Refresh the user session without logging them out to provide a good user experience.

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.4.0
- **Which browsers have you tested in?** Chrome / Firefox / Safari
- **Which framework are you using, if applicable (Angular, React, etc):** React/Next
- **Other modules/plugins/libraries that might be involved:** -

**Comment by adamjmcgrath** [comment]
Hi @GMaiolo

> If we execute getAccessTokenSilently with ignoreCache: true, then the user gets automatically logged out with the "login required" error.

This sounds like silent auth is failing (probably due to third party cookies are being blocked) - have a look at this FAQ https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-is-the-user-logged-out-when-they-refresh-the-page-in-their-spa

**Comment by adamjmcgrath** [comment]
Closing as I think https://github.com/auth0/auth0-react/issues/396#issuecomment-1234308491 answers your question, feel free to ping me if you want to reopen

**Comment by GMaiolo** [comment]
Thanks @adamjmcgrath 
I'll investigate, but it seems that the reason the silent auth was failing was because of using Auth0's developer keys!

Your link helped a lot, thanks again.
