### ISSUE TITLE
Log Out

### ISSUE THREAD

**Issue by patzj** [auth0/auth0-react#397]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

> We host two apps. One is the main app built in React and is using this library. The other is a supporting app built in Next.js and is using [auth0/nextjs-auth0](https://github.com/auth0/nextjs-auth0). Both supports a logout feature. The **logout** functionality have from `auth0/nextjs-auth0` logs out both our main app and supporting app. The **logout** from `auth0/auth0-react` only logs out the main app. We've tried the `federated` option but it doesn't seem the one we need for the use case.

### What was the expected behavior?

> The `logout` API should be able to logout both the main and supporting app. Please let me know if this is expected behavior and should be posted to feature request instead. Thank you.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

> Our main app's logout strategy is to route to a React component that does this:

```ts
  // Logout.tsx
  useEffect(() => {
    auth0.logout({
      returnTo: process.env.APP_ORIGIN,
    });
  }, [auth0]);
```

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?** 

> Not tested yet.

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 1.10.2
- **Which browsers have you tested in?** Brave, Chrome, Edge
- **Which framework are you using, if applicable (Angular, React, etc):** react
- **Other modules/plugins/libraries that might be involved:** react-router-dom

**Comment by adamjmcgrath** [comment]
Hi @patzj 

> The logout functionality have from auth0/nextjs-auth0 logs out both our main app and supporting app. The logout from auth0/auth0-react only logs out the main app

`nextjs-auth0` logs both apps out because it clears your auth0.com session and `auth0-react`, being a SPA, relies on your auth0.com session to maintain login state (by default at least)

`auth0-react` doesn't log out the other app, even though it also clears the auth0.com session. Because the other app, being a regular web app, relies on a local session (in next.js's case, a stateless encrypted cookie) to maintain login state.

To clear the local session of another app, you'd need something like distributed logout (like OIDC Back-Channel/Front-Channel Logout), which currently is not supported by Auth0.
