### ISSUE TITLE
OnRedirectCallback appstate.returnTo not working when deployed in sub directory.

### ISSUE THREAD

**Issue by appanasantosh** [auth0/auth0-react#399]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

> redirectToCallback is working properly when we deploy app on domain, some thing like (https://green-flower-0ebcdb753.1.azurestaticapps.net/). But where as when we deploy the app on path like (https://green-flower-0ebcdb753.1.azurestaticapps.net/platform) then it is always redirecting to default path, instead of redirecting back to the page which we tried before calling the login.

### What was the expected behavior?

> RedirectCallBack appstate.redirectTo should work same for the app when it is deployed on the sub domain path.

### Reproduction

const onRedirectCallback = (appState: AppState | undefined) => {
    history(appState?.returnTo || window.location.pathname);
  };

The above code is not working as expected when the app is deployed on subdomain
### Environment

- auth0-react: 1.9.0
- React

**Comment by adamjmcgrath** [comment]
Hi @appanasantosh 

>  (https://green-flower-0ebcdb753.1.azurestaticapps.net/). But where as when we deploy the app on sub domain like (https://green-flower-0ebcdb753.1.azurestaticapps.net/platform) 

These look like the same sub-domain to me, I assume you mean that `returnTo` is not working when the application is served under a path (eg /platform) rather than at the root?

The page's path shouldn't affect the operation of `onRedirectCallback`, as long as the `appState` is correctly set. Can you show me the code you're using to set the `appState` and preferable a HAR file (with any sensitive information removed)

**Comment by appanasantosh** [comment]
Hi @adamjmcgrath
Yes the returnTo is not working when application is deployed under path "/platform".
Here is the wrapper, I am writing on top of the Auth0Provider. And the children passed are protected routes, which uses withAuthenticationRequired component that uses the defaultReturnTo (const defaultReturnTo = (): string =>
  `${window.location.pathname}${window.location.search}`;) to set the appstate.returnTo.

Wrapper:
const HexAuth0Provider = (props: React.PropsWithChildren<Auth0ProviderConfig>) => {
  const history = useNavigate();

  const onRedirectCallback = (appState: AppState | undefined) => {
    history(appState?.returnTo || window.location.pathname);
  };

  return (
    <Auth0Provider {...props} redirectUri={props.redirectUrl || window.location.origin} onRedirectCallback={onRedirectCallback}>
      {props.children}
    </Auth0Provider>
  );
};

**Comment by appanasantosh** [comment]
Thanks @adamjmcgrath I have fixed the issue by setting the returnTo manually in withAuthenticationRequired, instead of depending on the default returnTo.
