### ISSUE TITLE
Contributing to SDK

### ISSUE THREAD

**Issue by aggmoulik** [auth0/auth0-react#40]
Hello Sir, I am looking to work on the project but I can't find issues or ROADMAP for the same. So, that I can contribute regularly. @adamjmcgrath

**Comment by adamjmcgrath** [comment]
Hi @aggmoulik - thank you for your kind offer. 

We don't have a public Roadmap and there are currently no open Issues. But we always welcome PRs to fix bugs and make improvements if you can find any
