### ISSUE TITLE
Possible to enrich onRedirectCallback with User/idToken info?

### ISSUE THREAD

**Issue by dsbrianwebster** [auth0/auth0-react#400]
### Describe the problem you'd like to have solved
As a developer working with Auth0 + Single page react applications, I would like to have a simpler and more flexible way to conditionally redirect users. Ideally this would happen inside the already present `onRedirectCallback` function.

> A clear and concise description of what you want to happen.

A hypothetical example of what this _could_ look like, might be like...

```tsx
const onRedirectCallback = (appState: AppState | undefined, user: User) => {
  const isVip = auth0User['https://namespace.com/isVip'];  

  if (isVip) return Router.replace(`/welcome/vip`);
  
  Router.replace(appState && appState.returnTo ? appState.returnTo : window.location.pathname);
};
```

> A clear and concise description of any alternatives you've considered or any work-arounds that are currently in place.

Currently `onRedirectCallback` only offers the `AppState` object that we pass in when calling the initial `loginWithRedirect` function. The only workarounds we seem to have are to not use `onRedirectCallback` at all and instead work all this logic out in a `useEffect` hook on a generic `/callback` page. Perhaps that is what we have to do, but in that instance we lose access to the `AppState` data we get in `onRedirectCallback` and need to come up with a different solution for when we want access to the `returnTo` value (localStorage generally).

**Comment by devjmetivier** [comment]
@dsbrianwebster @adamjmcgrath I've created PR #401 to resolve this issue.

**Comment by adamjmcgrath** [comment]
Released in https://github.com/auth0/auth0-react/releases/tag/v1.11.0 - thanks @devjmetivier
