### ISSUE TITLE
getIdTokenClaims resolves successfully but returns `undefined` for ID Claims

### ISSUE THREAD

**Issue by shahid7292** [auth0/auth0-react#402]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

> Provide a clear and concise description of the issue

https://community.auth0.com/t/getidtokenclaims-resolves-successfully-but-returns-undefined-for-id-claims/48139/4

I am having exact same issue discussed in this blog

### What was the expected behavior?

> Tell us about the behavior you expected to see

If getIdTokenClaims resolves successfully then it should return id_token value

### Environment

> Please provide the following:

- **Version of `auth0-react` used : *1.10.2*
- **Which browsers have you tested in? *Chrome*
- **Which framework are you using, if applicable (Angular, React, etc): *React*
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @shahid7292 - thanks for raising this

Did you provide different scopes to `loginWithRedirect` than those you provided to `<Auth0Provider>`?

Calling  `loginWithRedirect` with a custom scope should only be used to get _additional_ tokens to the one's you already have, you then pass the different `scopes` to `getAccessToken`/`getIdTokenClaims` to tell the SDK which token you want. eg

```js
<Auth0Provider>...</Auth0Provider>
// SDK's default scope is now "openid profile email"
loginWithRedirect({ scope: 'custom-scope' });
// the cache is now populated with 1 token for scope=custom-scope
getIdTokenClaims()
// this looks up the cache for default scope=openid profile email and finds nothing, since only scope=custom-scope is in the cache
getIdTokenClaims({ scope: 'custom-scope' })
// will return the ID token in the cache
```

Note there is work to simplify this behaviour in SPA JS v2 https://github.com/auth0/auth0-spa-js/pull/967

**Comment by shahid7292** [comment]
@adamjmcgrath i have not passed scope anywhere. I have left it to default values

**Comment by shahid7292** [comment]
This code is working fro me in this way.
If we wait for `access_token` to be generated then we will get `id_token`.
```
useEffect(() => {
    const getToken = async () => {
      const {getAccessTokenSilently, getIdTokenClaims} = useAuth0();
      const access_token = await getAccessTokenSilently();
      const id_token = await getIdTokenClaims();
      console.log("access_token", access_token);
      console.log("id_token", id_token);
      CookieService().setAppToken({access: id_token.__raw});
    };
    getToken();
 }, [getAccessTokenSilently, getIdTokenClaims]);
```

**Comment by reify-tanner-stirrat** [comment]
I just ran into this behavior and it's unintuitive and frustrating. Is there a reason that `getIdTokenClaims` doesn't wait until there's a token available?

**Comment by frederikprijck** [comment]
As explained in the other issue, an undefined id token is a valid value in the case the user hasnt authenticated.

**Comment by TurkishCat** [comment]
> This code is working fro me in this way. If we wait for `access_token` to be generated then we will get `id_token`.
> 
> ```
> useEffect(() => {
>     const getToken = async () => {
>       const {getAccessTokenSilently, getIdTokenClaims} = useAuth0();
>       const access_token = await getAccessTokenSilently();
>       const id_token = await getIdTokenClaims();
>       console.log("access_token", access_token);
>       console.log("id_token", id_token);
>       CookieService().setAppToken({access: id_token.__raw});
>     };
>     getToken();
>  }, [getAccessTokenSilently, getIdTokenClaims]);
> ```

Thanks dude, why does it even behave this way.
