### ISSUE TITLE
Custom token endpoint

### ISSUE THREAD

**Issue by Djay77** [auth0/auth0-react#409]
### Describe the problem you'd like to have solved

> We can't define an other token endpoint. The default value is "oauth/token"
In my case, we have a specific subdomain for oauth : oauth2.domain.com and the token endpoint is oauth2.domain.com/token

### Describe the ideal solution

> Add a param in Auth0Provider to define a custom base for oauth URL ?
## Alternatives and current work-arounds

> No work-around seem possible
The endpoint is hardcoded in auth0-spa-js

**Comment by adamjmcgrath** [comment]
Thanks for raising this @Djay77 - this SDK is for Auth0 only, so can't be configured with other providers

Please see https://github.com/auth0/auth0-react/issues/361#issuecomment-1122013724 for more info
