### ISSUE TITLE
URI hash fragment doesn't seem to be redirecting

### ISSUE THREAD

**Issue by dudo** [auth0/auth0-react#412]
### Describe the problem

When redirecting to my application, the url hash fragment doesn't seem to be consumed by Auth0Provider.

### What was the expected behavior?

I guess I'm not sure what I should be doing on my app when auth0 redirects back.

### Reproduction

This is in the latest version of chrome. It's probably important to note that I'm using preact, but I don't think that's the issue.

I'm logging in from localhost:8080, and redirecting to localhost:8081.

**login url**
<https://dev-id.us.auth0.com/authorize?response_type=token&client_id=dev-key&redirect_uri=http://localhost:8081>

**redirect**
<img width="602" alt="image" src="https://user-images.githubusercontent.com/2963800/193714402-7bd3c70e-6ba5-48de-ac2d-7959b4a905b3.png">

**code index.js**
```js
import { Auth0Provider } from "@auth0/auth0-react";

...

const onRedirectCallback = (appState) => {
  history.push(
    appState && appState.returnTo ? appState.returnTo : window.location.pathname
  );
};

const providerConfig = {
  domain: import.meta.env.AUTH0_DOMAIN,
  clientId: import.meta.env.AUTH0_CLIENT_ID,
  redirectUri: window.location.origin,
  onRedirectCallback
}

const About = lazy(() => import('./pages/about/index.jsx'));

export const App = () => {
  return (
    <Auth0Provider {...providerConfig}>
      <LocationProvider>
        <div class="app">
          <Header />
          <ErrorBoundary>
            <Router>
              <Route path="/" component={Home} />
              <Route path="/about" component={About} />
              <Route default component={NotFound} />
            </Router>
          </ErrorBoundary>
        </div>
      </LocationProvider>
    </Auth0Provider>
  );
}
```

**code /home**
```js
import { useAuth0 } from "@auth0/auth0-react";

const Home = () => {
  const {
    isLoading,
    isAuthenticated,
    error,
    user,
    loginWithRedirect,
    logout,
  } = useAuth0();

  if (isLoading) {
    return <div>Loading...</div>;
  }

  if (error) {
    return <div>Oops... {error.message}</div>;
  }

  if (isAuthenticated) {
    return (
      <div>
        Hello {user.name}{' '}
        <button onClick={() => logout({ returnTo: window.location.origin })}>
          Log out
        </button>
      </div>
    );
  } else {
    return <button onClick={loginWithRedirect}>Log in</button>;
  }
}

export default Home;
```

Clicking the `loginWithRedirect` button here works... it makes me re-authenticate, then redirects back to my app, and it works great. I noticed that the redirect that the js click returns to has the token within the query params, and not the hash fragment. That _seems_ to be the issue.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/2963800/193714489-0729b0e4-a28d-4ee7-8d2e-f9ad70b7a0db.png">

In my case, I'm developing the "marketing pages" with the login button separately from the "app" that gets logged into - hence the different flows. Hopefully that makes sense.

Thanks for your help!

**Comment by adamjmcgrath** [comment]
> https://dev-id.us.auth0.com/authorize?response_type=token&client_id=dev-key&redirect_uri=http://localhost:8081

Hi @dudo - auth0-react doesn't support the implicit flow, only authorization code flow with PKCE

> Clicking the loginWithRedirect button here works...

Can you not use `loginWithRedirect` in the place where you're trying to login by requesting `/authorize?response_type=token`?

**Comment by dudo** [comment]
Hello, Adam! That explains why the login works within the react app. So... as for using `loginWithRedirect`... I'd love to keep the marketing pages as free of js as possible. The existing login button is just an href, and I would love to keep it that way. 

Are there no levers I can tweak to get the redirect shaped appropriately?

**Comment by adamjmcgrath** [comment]
Hi @dudo - in addition to crafting the `/authorize` url, `loginWithRedirect` also drops some verification cookies that need to be verified on the callback.

If you don't want to use the SDK on the marketing site you could just link to your app site from the marketing site then redirect to the login from there. (eg `marketing site --> app site --> login form --> app site`)

**Comment by dudo** [comment]
Hmmm... this kinda feels like the left hand isn't able to talk to right hand. This feels like a reasonable flow, and everything in the docs says to just use the href.

Any plans to support this? Or... a better solution?

**Comment by adamjmcgrath** [comment]
> Hmmm... this kinda feels like the left hand (universal login url) isn't able to talk to right hand (official js library). This feels like a reasonable flow, and everything in the docs says to just use the href.

It's not a flow I've heard of. Could you share a link to one of these docs?

There is no OIDC flow for SPAs that supports just linking to the authorization server without first storing at least some state to be verified in the authorization response (see https://auth0.com/docs/secure/attack-protection/state-parameters).

The recommended OIDC flow for SPAs, which this SDK uses, is the authorization code grant with Proof Key for Code Exchange (PKCE) which requires additional checks to be stored on the client in the authorization request and verified in the authorization response.

The solution I've suggested for your use case is the OIDC recommended way of initiating login from a 3rd party (if your marketing website either can't generate the necessary state/PKCE checks or is on another domain it's effectively a 3rd party) 

> In some cases, the login flow is initiated by an OpenID Provider or another party (marketing site), rather than the Relying Party (app). In this case, the initiator (marketing site) redirects to the RP (app) at its login initiation endpoint, which requests that the RP (app) send an Authentication Request to a specified OP (auth0). 
https://openid.net/specs/openid-connect-core-1_0.html#ThirdPartyInitiatedLogin

**Comment by adamjmcgrath** [comment]
> Forgive me if this is frustrating, for I am not an authentication expert. Thank you for bringing me up to speed!

It's no problem

> At the end of the day... both the href and the js are just calling a url with some instructions for the callback, no?

Unfortunately not, additional checks need to be stored on the client when making the authorization request and retrieved by the client to verify the authorization response.

In your case, this means that your marketing site must generate some values (including state and a cryptographically generated code challenge and verifier) to include in the authorize url and store on the browser. Then your app needs to access those values and use them to verify the authorization response on your redirect callback page.

These limitations are not unique to this SDK or Auth0, this is just how the protocol works.

> What are the levers I need to pull to have parity in their behavior?

I can only recommend the suggestions I've already given you:
- use the SDK to initiate the login from your marketing site (assuming your marketing site and app are on the same domain in your other environments as well)
- link to the app, then immediately initiate the login from there

**Comment by dudo** [comment]
Sounds good. Thanks for the explanation!
