### ISSUE TITLE
Currently it is Impossible to get Refresh Token to revoke it

### ISSUE THREAD

**Issue by mikhail-slauth** [auth0/auth0-react#413]
### Currently it is Impossible to get current Refresh Token to revoke it

> I need to revoke Refresh Token on log out (see https://auth0.com/docs/secure/tokens/refresh-tokens/revoke-refresh-tokens), but this is not possible, because I can't get it anyhow via current api. For some reasons `refresh_token` is omitted from `getAccessTokenSilently` method (see https://github.com/auth0/auth0-spa-js/blob/master/src/global.ts#L641).

### Possible solutions

> Implement dedicated method `revokeRefreshToken` which will revoke current refresh token according to doc in  https://auth0.com/docs/secure/tokens/refresh-tokens/revoke-refresh-tokens

**Comment by adamjmcgrath** [comment]
This SDK is a wrapper for `auth0-spa-js` so closing in favour of https://github.com/auth0/auth0-spa-js/issues/1013
