### ISSUE TITLE
Native App Auth Flow

### ISSUE THREAD

**Issue by MGough** [auth0/auth0-react#417]
### Describe the problem you'd like to have solved
I want to be able to authenticate a user using a browser based flow, triggered from a native desktop app which is running React/NextJS.

Currently there's a function called `getAccessTokenWithPopup` which takes a fixed set of options on how to authenticate the user: `display?: "page" | "popup" | "touch" | "wap"`. These all have different purposes, but for my native app none of these are suitable. My users want to know that they're authenticating at the correct URL in the App, as they might be using SSO in Auth0 and don't want to type their (for example) google credentials into the app itself. The options here don't trigger a browser opening in the desktop app.

I'm not running the app on a constrained device, so device code flow doesn't make sense here, and according to best practice I should be doing this in the browser rather than natively in my app: https://www.rfc-editor.org/rfc/rfc8252#section-5

### Describe the ideal solution
I would like to be able to inject a function as a `display` option. For example instead of `getAccessTokenWithPopup`:
```ts
getAccessToken({
    display: (authorizeUrl) => { ... My function def here which will handle displaying the auth, and will call handleRedirect when it's done ... }
})
```

## Alternatives and current work-arounds
Currently I'm building an authorize URL, handling the authorization in Auth0 in the browser, capturing the result and then calling `handleRedirect`:
```ts
const authorizeUrl = await buildAuthorizeUrl();
// My function that handles the user browser interaction
userLoginInAuth0(authorizeUrl);

// I capture the result from the redirect to my URI Scheme asynchronously, then this happens
await handleRedirectCallback(redirectURL);
```

### Additional context
Happy to help explain more if it's unclear. Perhaps I've missed something!

**Comment by adamjmcgrath** [comment]
Hi @MGough - thanks for raising this

Your workaround looks generally like what we would recommend for logging in through browser from a native application

For example see our Ionic & Capacitor (React) Quickstart:

- Build login url and open the browser https://auth0.com/docs/quickstart/native/ionic-react/01-login#add-login-to-your-application
- Handle the callback and close the browser https://auth0.com/docs/quickstart/native/ionic-react/01-login#handling-the-callback

**Comment by MGough** [comment]
> Hi @MGough - thanks for raising this
> 
> Your workaround looks generally like what we would recommend for logging in through browser from a native application
> 
> For example see our Ionic & Capacitor (React) Quickstart:
> 
>     * Build login url and open the browser https://auth0.com/docs/quickstart/native/ionic-react/01-login#add-login-to-your-application
> 
>     * Handle the callback and close the browser https://auth0.com/docs/quickstart/native/ionic-react/01-login#handling-the-callback

Oh interesting thank you! Glad to hear I've not used some functions that just happen to be available, but they're in fact referenced in your own guides. I'd not considered looking there as I've not heard of Ionic & Capacitor. I only really stumbled across the workaround thanks to the API docs.

Perhaps it's something that needs some tweaking/adding in the guides somewhere to be more generic? In my case I'm using Tauri at the moment but could foresee similar challenges with Electron or other similar frameworks.

**Comment by adamjmcgrath** [comment]
Thanks for the suggestion @MGough - the docs in this repo focus on the web scenario. But we have lot's of quickstarts for specific use cases like native/hybrid apps
