### ISSUE TITLE
Login failed errors

### ISSUE THREAD

**Issue by Moinax** [auth0/auth0-react#424]
### Describe the problem

We see a lot of "Login failed" errors in our logs without further explanation.

### What was the expected behavior?

We expect to have more information about the cause of the error, because at the moment we don't have any clue where the problem is.

By reading your code, it seems to be a fallback error when you cannot actually identify the error in the `normalizeErrorFn`

```
const normalizeErrorFn = (fallbackMessage: string) => (
  error: Error | { error: string; error_description?: string } | ProgressEvent
): Error => {
  if ('error' in error) {
    return new OAuthError(error.error, error.error_description);
  }
  if (error instanceof Error) {
    return error;
  }
  return new Error(fallbackMessage);
};
```

So I guess the issue is either @auth0/auth0-spa-js not correctly throwing the error or Auth0 backend API not providing a good error response, but in any case this should be fixed, because now we have customers complaining about not being able to connect and we definitely have no way to identify the issue behind it.

At the very least, we would like to get the original error message, something like this should do the trick:

```
const normalizeErrorFn = (fallbackMessage: string) => (
  error: Error | { error: string; error_description?: string } | ProgressEvent
): Error => {
  if ('error' in error) {
    return new OAuthError(error.error, error.error_description);
  }
  if (error instanceof Error) {
    return error;
  }
  return new Error(`${fallbackMessage} (${JSON.stringify(error)})`);
};
```

### Reproduction

We cannot reproduce it, that's actually the main issue here and we would like to get more context in the error message to be able to reproduce it.

### Environment

- auth0-react > 1.10.2 
- Chrome 106.0.0
- Mac OS X 10.15.7
- react > 18.0
- @auth0/auth0-spa-js : ^1.22.0

**Comment by adamjmcgrath** [comment]
Hey @Moinax - thanks for raising this

This will be a `ProgressEvent` - this is an artefact of the fact that `auth0-spa-js` uses `unfetch` as a ponyfill - which uses `XMLHTTPRequest` which [issues `ProgressEvents` when it encounters an error](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/error_event#event_type) 

Even if we changed the fallback message to what your requesting, it wouldn't help much:

```js
console.log(`${fallbackMessage} (${JSON.stringify(error)})`)
// Login failed ({"isTrusted":false})
```

if the error doesn't have a payload, I expect it's a Network error (the user's browser was offline temporarily) - you should be able to confirm this by checking for corresponding network errors (or other request errors) in the browser to the `/oauth/token` endpoint

`auth0-spa-js@2` has removed this ponyfil and will be using fetch, which should give you a better error - we're planning on upgrading this SDK to `auth0-spa-js@2` in the next quarter, so this will be resolved by that

**Comment by adamjmcgrath** [comment]
@Moinax - Closing, as I believe https://github.com/auth0/auth0-react/issues/424#issuecomment-1293708712 answers your question
