### ISSUE TITLE
logout does not log out all subdomains

### ISSUE THREAD

**Issue by williamwjs** [auth0/auth0-react#439]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I have two apps under two subdomains: a.my.app and b.my.app
It is working well for logging in, where I could login from either of the two to get both subdomains signed in.

However, when I do logout on one subdomain, it does not also log out on the other subdomain.

### What was the expected behavior?

When clicking logout in one subdomain, it should also log out all subdomains

### Reproduction

- Step 1: Implement auth with auth0-react in both subdomains
- Step 2: Log in from the first subdomain
- Step 3: Navigate to the second subdomain to confirm that it is logged in
- Step 4: Log out from the second subdomain
- Step 5: Navigate back to the first subdomain - noticing you are still logged in

### Environment

- **Version of `auth0-react` used:** 1.12.0
- **Which browsers have you tested in?** Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by williamwjs** [comment]
The issue is only reproducible if `cacheLocation="localstorage"`. So I guess it is not easy to update the local storage entry in other subdomain

**Comment by adamjmcgrath** [comment]
Hi @williamwjs - thanks for raising this

You can't share `localStorage` objects across subdomains, so this is not possible with auth0-react

> Step 3: Navigate to the second subdomain to confirm that it is logged in

You're logged in on the second subdomain because the SDK is logging you in silently with an iframe and web message - there isn't an equivalent mechanism for logging out.

In order to logout from the second subdomain you need to visit the subdomain, you could perhaps do this automatically on logout from the first subdomain.
