### ISSUE TITLE
Option to cache a token

### ISSUE THREAD

**Issue by kenahrens** [auth0/auth0-react#44]
### Describe the problem you'd like to have solved

I'm using this library on my React app and to protect calls to an API. Each time I made an API call, it generates a new access token. Since the token is good for some amount of time (configurable in Auth0), I'd like an option to cache the token.

### Describe the ideal solution

Ideally there would be some additional options around getting tokens in addition to the current get token silently. Perhaps getOrCreateToken or something like that which checks the cache first or fetches the token if need be.

## Alternatives and current work-arounds

I'm storing the token in local storage and as a cookie (I know it's gross but some folks love cookies). I don't have a smart way to know how to replace the token in local cache.

```
...
  const { isLoading, isAuthenticated, user, logout, getAccessTokenSilently } = useAuth0();

  useEffect(function mountCookie() {
    async function setCookie() {
      if (isAuthenticated) {
        const token = await getAccessTokenSilently({});
        localStorage.setItem('token', token);
        let expiry = new Date();
        expiry.setHours(expiry.getHours() + 10);
        const myCookie = `awesomeCookie=${token}; expires=${expiry}; path=/`;
        window.document.cookie = myCookie;
      }
    }
    setCookie();
  }, [isAuthenticated, getAccessTokenSilently])
...
```

### Additional context

Note 1: I tried your other library for SPA and this one is better, thank you!

Note 2: I found the behavior of the service is different if you provide an empty object to `getAccessTokenSilently` or if you provide scopes. If you provide an empty input you get an access token, but if you provide some scopes then you will get a JWT. I'm testing both options, the example above is with an access token only.

**Comment by adamjmcgrath** [comment]
Hi @kenahrens - the SDK wraps `auth0-spa-js` so `getAccessTokenSilently` will behave the same as https://auth0.github.io/auth0-spa-js/classes/auth0client.html#gettokensilently

If you call `getAccessTokenSilently()` and there is a valid access token in its in memory cache, it will return it - so there is no need to cache the token yourself.

**Comment by dayvough** [comment]
hi @adamjmcgrath: sorry I'm just new to all these frontend frameworks, nextjs, and auth flows (coming from backend). If I wanted to persist the user's login, how and where do I call `getAccessTokenSilently`? An example would be helpful. ☺️

**Comment by adamjmcgrath** [comment]
Hi @dayvough 

To persist the user's login you just need to wrap your main app component in the `Auth0Provider` component and prompt the user to login, see https://github.com/auth0/auth0-react#getting-started

> how and where do I call getAccessTokenSilently? 

For calling `getAccessTokenSilently` you do this just before you need to request a protected API. There's a simple example here https://github.com/auth0/auth0-react#call-an-api, a more detailed example here https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#4-create-a-useapi-hook-for-accessing-protected-apis-with-an-access-token and some example apps here https://github.com/auth0/auth0-react/tree/master/examples

Closing this now, feel free to open an issue if you have any problems using the SDK

**Comment by zhil** [comment]
By default tokens are cached in memory, and getTokenSilently still send request to .../oauth/token each time when you reload page.

its correct behavior because of security (it provide better protection against XSS), but.. its annoying and it slow down my App page loading speed. So, I am also using localstorage cache
```
<Auth0Provider
....
      cacheLocation="localstorage"
    >
```

I hope it will save time for somebody  :)

**Comment by ianchanning** [comment]
@zhil It is not recommended by OWASP to store your token in localstorage: https://github.com/OWASP/CheatSheetSeries/blob/master/cheatsheets/JSON_Web_Token_for_Java_Cheat_Sheet.md#symptom-4

**Comment by githorse** [comment]
`cacheLocation="localstorage"` is a lifesaver. I reload my browser a hundred times a day[^1], and if my wifi isn't great it can take 1-3 seconds, sometimes longer, to fetch all of the tokens. I've been scheming various ways to do exactly what this option gives me for free.

But, of course, I don't want to impair my app's security posture in production. Is there any reason I should not something like this?

```
<Auth0Provider
  ....
  cacheLocation={process.env.NODE_ENV === 'development' ? 'localstorage' : 'memory'}
>
```

[^1]: Sure, in theory, hot module reloading should make this unnecessary, but I've never gotten it to work reliably.
