### ISSUE TITLE
How to use Auth0 with React Router v6.4 Data api

### ISSUE THREAD

**Issue by lasseklovstad** [auth0/auth0-react#442]
### Describe the problem
Hello!
It doesn't exist any documentation on best practise using react Auth0 with the new react router v.6.4 Data api. The main issue is that the acces token can only be retrieved with the useAuth0 hook. 

### What was the expected behavior?

This is my understanding of how it might be done:
```
export const App = () => {
    return (
        <Auth0Provider
            domain={import.meta.env.VITE_DOMAIN}
            clientId={import.meta.env.VITE_CLIENTID}
            redirectUri={window.location.origin}
            audience={import.meta.env.VITE_AUDIENCE}
        >
            <Routing />
        </Auth0Provider>
    )
}

const router = (auth0Context: Auth0ContextInterface) =>
    createBrowserRouter([
        {
            path: "/",
            loader: async () => {
                const token = await auth0Context.getAccessTokenSilently()
                const response = await fetch("/api/user", { headers: { Authorization: `Bearer ${token}` } })
                const user = response.json()
                return user
            },
            element: <div>hello</div>,
        },
    ])

export const Routing = () => {
    const auth0Context = useAuth0()
    return <RouterProvider router={router(auth0Context)} />
}

```

**Comment by adamjmcgrath** [comment]
Hi @lasseklovstad - thanks for raising this

It looks like you can't use hooks or react context when loading data with the React Router v6.4 Data api. Have a look at this document for how to get the access token outside of the react render lifecycle: https://gist.github.com/adamjmcgrath/0ed6a04047aad16506ca24d85f1b2a5c

**Comment by adamjmcgrath** [comment]
Think https://github.com/auth0/auth0-react/issues/442#issuecomment-1346332329 should answer your question, so closing
