### ISSUE TITLE
How to implement Google offline access

### ISSUE THREAD

**Issue by ppascualv** [auth0/auth0-react#457]
### Describe the problem

Hi there,

I’m working with Auth0-react library using the Auth0Provider component and I need to get the refresh tokens.
After reading this post [Store and retrieve Google Refresh token - #4 by mathiasconradt](https://community.auth0.com/t/store-and-retrieve-google-refresh-token/28973/4) I successfully did most of the things mentions except this one:

In order to make Auth0 get a refresh token in the first place, your SPA needs to make the authorize request with the parameters:

access_type: "offline"

as well as the respective audience to the authorize request, such as:

connection_scope: "https://www.googleapis.com/auth/calendar.events.readonly"

Example here: [Can’t get google refresh token using auth0.js - #2 by vinicius.spagnol](http://community.auth0.com/t/cant-get-google-refresh-token-using-auth0-js/11756/2)

How can I do that using the mentioned component?

Thanks

**Comment by adamjmcgrath** [comment]
Hi @ppascualv 

You can pass custom parameters to the authorize request in the Auth0Provider or loginMethod:

E.g per login

```js
const { loginWithRedirect } = useAuth0();
loginWithRedirect({
    access_type: 'offline', 
    connection_scope: 'https://www.googleapis.com/auth/calendar.events.readonly', 
})
```

or for all logins

```jsx
<Auth0Provider
  access_type="offline"
  connection_scope="https://www.googleapis.com/auth/calendar.events.readonly">
```

Note the signature will change slightly when v2 will be released in the new year (check the migration docs when it does)

**Comment by adamjmcgrath** [comment]
Think https://github.com/auth0/auth0-react/issues/457#issuecomment-1346336336 should answer your question so closing

**Comment by AlexcastroDev** [comment]
> Hi @ppascualv
> 
> You can pass custom parameters to the authorize request in the Auth0Provider or loginMethod:
> 
> E.g per login
> 
> ```js
> const { loginWithRedirect } = useAuth0();
> loginWithRedirect({
>     access_type: 'offline', 
>     connection_scope: 'https://www.googleapis.com/auth/calendar.events.readonly', 
> })
> ```
> 
> or for all logins
> 
> ```js
> <Auth0Provider
>   access_type="offline"
>   connection_scope="https://www.googleapis.com/auth/calendar.events.readonly">
> ```
> 
> Note the signature will change slightly when v2 will be released in the new year (check the migration docs when it does)

Does it change for today's implementation ?

**Comment by frederikprijck** [comment]
@AlexcastroDev yes, the param goes in `authorizationParams`:
```ts
const { loginWithRedirect } = useAuth0();
loginWithRedirect({
    authorizationParams: {
      access_type: "offline"
      connection_scope: "https://www.googleapis.com/auth/calendar.events.readonly"
    }
})
```
or
```
<Auth0Provider
  authorizationParams={{
    access_type="offline"
    connection_scope="https://www.googleapis.com/auth/calendar.events.readonly"
  }}>
```
