### ISSUE TITLE
Support dynamic URLs in `Allowed Logout URLs` when user is logged out

### ISSUE THREAD

**Issue by som-matrix** [auth0/auth0-react#458]
### Problem Description

-  Currently when we create a Single page application , we add callback urls, logout urls , web origin.
-  But i noticed the URLs that are mentioned there and supported are only the index routes.
-  My concern is for logout URLs.

For eg: I am in a page called `localhost:8000/rooms?queryParams...` and i am performing the login functionality there by using the `loginWithPopup` method. So after successful authentication , user is logged in and stay on the same page and we get the user info.

Now comes the `logout` functionality , for that we need to invoke this method and pass the `federated` option to `true` so that when user logs out and login again they will see the login popup again.

Here on logout , it redirects to the index routes mentioned in `Allowed Logout URLs` , so is there a option where i can pass a page location like above which has a `pathname` and query parameters which are dynamic ?

### Describe the ideal solution
- In dashboard it is mentioned we can pass wildcards like `http://*.[example.com](http://example.com/)`.
- Is there a option to pass like this `http://*.[example.com/*](http://example.com/*)` which also take the query params ?

Like this 
![Screenshot 2022-12-12 at 1 34 38 PM](https://user-images.githubusercontent.com/69161480/206993379-f521530e-43e1-4e52-8b68-1dd8885b41ed.jpg)

**Comment by adamjmcgrath** [comment]
Hi @som-matrix - thanks for raising this

You can pass a url to the logout function at logout time, eg

```js
const { logout } = useAuth0();
logout({ return: `http://example.com/custompath?custom=query` })
```

Here you could use the current url to derive the `returnTo` parameter.

However you can't use a wildcard for pathnames in "Allowed Logout URLs" this is a security restriction put on by the Authorization Server, so there's nothing the SDK can do to work around this.

You can however specify multiple "Allowed Logout URLs" and have dynamic query params, since these are not taken into account by the Authorization Server when validating the returnTo.

**Comment by som-matrix** [comment]
Hi @adamjmcgrath  thanks for the reply.

But `returnTo` only takes the URL that are mentioned in `Allowed Logout URLs` right ?  But will this URL work -> `http://example.com/custompath?custom=query` what if my `custom` in url is not always equals to `query` it has a different value

**Comment by som-matrix** [comment]
@adamjmcgrath here what i tried, i have attached a screenshot
> what were you expecting to happen
so you mentioned to use it like this `logout({ returnTo: `http://example.com/custompath?custom=query` })` 

and my function is 
`const logoutUsingAuth0 = () =>
    logout({
      federated: true,
      returnTo: window.location.href,
    });
`

> what happened? (include error messages, screenshots, anything helpful)

and i got this error 
![Screenshot 2022-12-13 at 4 08 39 PM](https://user-images.githubusercontent.com/69161480/207295680-0e220402-ba1e-4dc9-a1ad-3c37a40cd583.jpg)

**Comment by adamjmcgrath** [comment]
@som-matrix - you need to add `http://localhost:8000/en/bookings/rooms` to the list of "Allowed Logout URLs" for your application `0SBTpuwTY7ZF0vaCFZ5ZpGF16I54DFw5` on your `ayana-stg.us.auth0.com` tenant, once you do that the logout will succeed

**Comment by som-matrix** [comment]
Thanks @adamjmcgrath  this is working now. 
Bdw i have one question , there is no harm on publicly mentioning the auth0 client id and domain like as you mentioned above ?
just wanted to make sure nothing else

**Comment by adamjmcgrath** [comment]
No worries @som-matrix 

> there is no harm on publicly mentioning the auth0 client id and domain like as you mentioned above ?

Correct, the client id and domain are public so there's no harm in sharing them 👍 

Closing, feel free to ping me if you want to reopen

**Comment by som-matrix** [comment]
Okay cool 👍🏼
