### ISSUE TITLE
loginWithPopup not opening new tab correctly thus window.postMessage fails

### ISSUE THREAD

**Issue by spenweb** [auth0/auth0-react#460]
### Describe the problem

Sometimes, no new tab is opened when calling `loginWithPopup` on mobile devices but instead the current tab redirects to auth0.com. Thus, `window.postMessage` call fails on the authorization (auth0.com) origin as the other window does not exist. This is the error I was finally able to track down on the auth0.com/authorize?{...} page:
```
Unable to post message to https://example.com Recipient has origin https://example.auth0.com/
```
Here is a screenshot of the error message in the JavaScript console:
<img width="721" alt="image" src="https://user-images.githubusercontent.com/46385475/207471004-908e6b6b-a0b2-40e0-ab5c-e6cbd5fe9834.png">

Additionally, sometimes upon calling `loginWithPopup`, a new tab *is* opened but the href is `about:blank`.

### What was the expected behavior?

I expect when calling `loginWithPopup` that a new tab is opened instead of the current tab being redirected.

### Reproduction

This bug is intermittent. However, if I continually try to log in, eventually the issue will happen.

Try the following steps on an iPhone iOS 16.1 on Safari with a login button with an onClick handler using `loginWithPopup`.

### Environment
- **Version of `auth0-react` used:** 1.10.2
- **Which browsers have you tested in?** Safari on iOS 16.2
- **Which framework are you using, if applicable (Angular, React, etc):** NextJS

**Comment by adamjmcgrath** [comment]
Hi @spenweb - thanks for raising this

I've tried to reproduce this on Safari iOS 16 using https://codepen.io/adamjmcgrath/full/rNKXpJy and am not able to.

TBH, all the sdk does is [`window.open` the authorization url](https://github.com/auth0/auth0-spa-js/blob/master/src/utils.ts#L89-L100) - it doesn't have any control about how Safari should interpret `window.open` - but if it's opening the url in the same window, that looks like an issue with Safari - I've had a look around and can't find any reports of that issue

Can you perhaps share a video of it happening so I can observe the behaviour?

https://user-images.githubusercontent.com/1299658/207876211-980be250-fc51-4e8c-8d06-e25f5155e2b0.mov

**Comment by spenweb** [comment]
Thank you for your review @adamjmcgrath. Unfortunately, the screen recording I have contains sensitive information. I have since moved away from using the login with popup feature and am simply redirecting for now. If I run across this issue again, I will attempt to capture a video or make a simple repo for testing.
