### ISSUE TITLE
Protected route is not redirected to auth0 login page on production

### ISSUE THREAD

**Issue by NguyenTam2206** [auth0/auth0-react#461]
Hi there, please support me on this case.

### Describe the problem

- Protected route is not redirected to auth0 login page on production. 
- withAuthenticationRequired not working properly on production.
- Something is wrong on router
### What was the expected behavior?

1.  Enter directly https://mydomain/testpage (this is a protected route) on address bar and hit enter (still not logged in)
2. App will redirect to auth0 login page, then log in
3. App redirects exactly to /testpage.

### Reproduction
On localhost, everything work well as expectation.

1.  Enter directly https://mydomain/testpage (this is a protected route) on address bar and hit enter (still not logged in)
2. App will redirect to auth0 login page, then log in
3. App redirects exactly to /testpage.

On production:

1. Enter directly https://mydomain/testpage on address bar and hit enter (still not logged in)
2. App will redirect to my login page (/) same as Auth0Provider redirectUri prop (I think so) and stay there instead of redirect to auth0 login page

Here are some informations:

`testpage`
```
import { withAuthenticationRequired } from '@auth0/auth0-react';
import PageLoader from '../layouts/PageLoader';

const TestPage: React.FC = () => {
  return <div>This is a test auth0 page</div>;
};

export default withAuthenticationRequired(TestPage, {
  loginOptions: {
    appState: {
      on: 'test page',
    },
  },
  returnTo: () => window.location.href,
  onRedirecting: () => (
    <div className="page-layout">
      <PageLoader />
    </div>
  ),
});
```
Configuration
```
const onRedirectCallback = (appState: any) => {
    console.log('appState', appState);
    router.replace(
      appState && appState.returnTo
        ? appState.returnTo
        : window.location.pathname
    );
  };

//Auth0Provider config
domain: process.env.NX_AUTH0_DOMAIN,
audience: process.env.NX_AUTH0_AUDIENCE,
clientId: process.env.NX_AUTH0_CLIENT_ID,
redirectUri: process.env.NX_BASE_URI,
connection: process.env.NX_AUTH0_CONNECTION,
useRefreshTokens: true,
advancedOptions: {
  defaultScope: 'openid profile email offline_access',
},
onRedirectCallback,
```

After follow those steps above, I can see the console.log result on localhost but not on production (got stuck)
```
appState {on: 'test page', returnTo: 'http://localhost:3000/testpage'}
```

Besides, I saw something wrong on router on production.

My url after I hit enter directly on address bar is `https://mydomain/shares` (another protected route) but router.pathname, router.route still are `/`, just router.asPath is `/shares`. It seems  stuck at `/`
Here is my console.log router on production
```
router {pathname: '/', route: '/', query: {…}, asPath: '/shares', components: {…}, …}
```

### Environment

- Version of `auth0-react` used:  "^1.12.0" 
- Which browsers have you tested in? Chrome
- Which framework are you using? Nextjs (next: "12.2.5")

**Comment by adamjmcgrath** [comment]
Hi @NguyenTam2206 - thanks for raising this

I'm not sure from looking at the information you've shared. It looks like your production server is setup to handle URLs differently to your development server. Happy to debug it for you if you want to share a link

**Comment by NguyenTam2206** [comment]
Thanks for your respond. 
I think there is a difference between development and production environments.

development: `next build && start next`
production: `next build && next export`

I thought development had Nodejs but production didn't
I tried to create a route `/testpage` but has no any thing related to auth0, just normal route (was not protected by `withAuthenticationRequired`). 
Result: the router still could not access `/testpage` on production (same issue I mentioned above). Now I surely know it is not an issue of `auth0-react`.

Do you have any suggestion for this case?
I already tried to add some lines (follow [this issue](https://github.com/vercel/next.js/discussions/10522)) in `next.config.js` but result didn't change. Is this a deployment configuration issue?
```
const nextConfig = {
  ...
  trailingSlash: true,
  exportPathMap: async function () {
    return {
      '/': { page: '/' },
      '/shares': { page: '/shares' },
      '/contact': { page: '/contact' },
      '/testpage': { page: '/testpage' },
    };
  }
}
```

**Comment by adamjmcgrath** [comment]
Hi @NguyenTam2206 - not sure to be honest

You could try having a look at this Vercel example https://github.com/vercel/next.js/tree/canary/examples/with-static-export

Since this isn't an issue with the SDK, am going to close
