### ISSUE TITLE
Auth0Provider multiple audiences?

### ISSUE THREAD

**Issue by dudo** [auth0/auth0-react#462]
I'm not sure if this is a bug, so much as I'm just confused... 

I'm trying to access the identity provider's token (Github) via my app. I've found some conflicting support answers

- https://community.auth0.com/t/can-i-get-the-github-access-token/47237/3
- https://community.auth0.com/t/how-to-access-authenticated-social-token/81781/4

So, I'm using the Auth0Provider config that has me pass an audience/scope tuple of sorts. That allows me to access my api, but I also need to access 

```js
{ 
  audience: `https://${import.meta.env.AUTH0_DOMAIN}/api/v2/`, 
  scope: "read:current_user read:user_idp_tokens"
}
```

in order to get a token that can be used with Github (I think...). That doesn't seem possible with Auth0Provider. Is my thinking way off here? How can I get consent for both APIs?

**Comment by adamjmcgrath** [comment]
Hi @dudo 

Have a look at https://auth0.com/docs/secure/tokens/access-tokens/identity-provider-access-tokens

You get an access token for the management api then use the management API (/api/v2/users endpoint) to get the access token for your connection. The access token will be available in the identities array, under the element for the particular connection (so you only need to specify the audience for the management API).

You'll also need to use the `connection_scope` parameter to pass the required scopes onto your connection (GitHub) when logging in, eg

```js
{ 
  audience: `https://${import.meta.env.AUTH0_DOMAIN}/api/v2/`, 
  scope: "read:current_user read:user_idp_tokens",
  connection_scope: "read:project"
}
```

**Comment by dudo** [comment]
Thanks for the quick response @adamjmcgrath! I think understand that part, but what I'm stuck on is the react provider bits. My app is already "initialized" if you will to talk to **my** api via an audience and a scope. When I try to call the auth0 api I get errors about my my token's access.

I tried using the popup method to re-ask for the right permissions, but then the Auth0Provider says that there's mismatched state.

I can give you some code examples if it'll help. Just wondering if I'm conceptually off before I keep pushing. Thanks for your help!

**Comment by dudo** [comment]
With `getAccessTokenWithPopup` should I be expecting the popup as I switch routes between the page that needs the identity token vs the "regular" pages?

Here's the error I'm getting...

![Screenshot 2022-12-20 at 11 12 55](https://user-images.githubusercontent.com/2963800/208748344-299f9e77-48a2-4198-86e5-91828562d314.png)

Few things to unpack. 

- The invalid state (can probably explain the page blipping around, maybe?)
- The response from `/api/v2/users/${user?.sub}` doesn't include any access tokens

Here's some code... Hopefully this makes sense with it pared down a bit.

```js
const onRedirectCallback = (appState) => {
  history.push(
    appState && appState.returnTo ? appState.returnTo : window.location.pathname
  );
};

const providerConfig = {
  domain: import.meta.env.AUTH0_DOMAIN,
  clientId: import.meta.env.AUTH0_CLIENT_ID,
  redirectUri: window.location.origin,
  onRedirectCallback,
  useRefreshTokens: true,
  audience: import.meta.env.AUTH0_AUDIENCE,
  scope: "read:all write:all",
};

export const AuthProvider = ({ children }) => {
  return <Auth0Provider {...providerConfig}>{children}</Auth0Provider>;
};
```

```js
// This is the meat and potatoes of my question, I believe
export const useIdentity = async () => {
  const { user, isAuthenticated, getAccessTokenWithPopup } = useAuth0();

  if (!isAuthenticated) return;

  const token = await getAccessTokenWithPopup({
    audience: `https://${import.meta.env.AUTH0_DOMAIN}/api/v2/`,
    scope: "read:current_user read:user_idp_tokens",
    connection_scope: "read:project"
  });

  const response = await fetch(`https://${import.meta.env.AUTH0_DOMAIN}/api/v2/users/${user?.sub}`, {
    headers: {
      'Content-Type': 'application/json',
      'Authorization': `Bearer ${token}`,
    }
  })

  return response.json();
};
```

```js
const Profile = () => {
  const { user } = useAuth0();
  const identity = useIdentity();

  identity.then(response => {
    console.log(response);
  })

  // making an api call to my local backend and rendering some things from the response which seems to be working fine
};

export default Profile;

```

```js
// Primary entrypoint of the react app
<AuthProvider>
  <App>
    <ErrorBoundary>
      <Router>
        <Route path="/people/:page?" component={People} />
        <Route path="/profile" component={Profile} />
        <Route default component={NotFound} />
      </Router>
    </ErrorBoundary>
  </App>
</AuthProvider>
```

**Comment by adamjmcgrath** [comment]
> The response from /api/v2/users/${user?.sub} doesn't include any access tokens

I've just tested this and couldn't get one either. It turns out that public clients like SPAs are not allowed to request the `read:user_idp_tokens` scope, only confidential clients (see the limitations for SPAs here https://auth0.com/docs/secure/tokens/access-tokens/get-management-api-tokens-for-single-page-applications#limitations)

Apologies, I didn't know this scope was restricted like this. You wont be able to get an access token for GH directly from your browser, you'd need to login via a server side web application with those scopes, then that application would need to get the token from `/api/v2/users/:id` and pass it to the browser.

**Comment by dudo** [comment]
Huh... If I need to get the access token from the backend, I might as well make the api request from the backend as well. No need for a roundtrip, in my case.

Thanks for clarifying. Happy Holidays!

**Comment by adamjmcgrath** [comment]
Thanks @dudo - Happy Holidays to you!
