### ISSUE TITLE
Add a screen_hint option for password reset under loginWithRedirect

### ISSUE THREAD

**Issue by thibautdm** [auth0/auth0-react#465]
### Describe the problem you'd like to have solved

At this moment it's not possible to redirect directly to a forgot password page. 

### Describe the ideal solution

It would be nice if this would be possible by adding an extra option to screen_hint.

## Alternatives and current work-arounds

I didn't find any workaround. You would have to go first to the login page and then manually click on the forgot password CTA.

**Comment by frederikprijck** [comment]
Thanks for reaching out, this is not something our SDK can solve but something that needs to be supported on Auth0 side before our SDK can expose any such property.

You can provide your feedback on https://auth0.com/feedback.

Closing this, as there isn't anything our SDK can do as it's not supported on Auth0's side.
