### ISSUE TITLE
`authorizationParams=[object Object]`  after upgrading to v2.0.0

### ISSUE THREAD

**Issue by jonasb** [auth0/auth0-react#479]
### Describe the problem

After upgrading to v2.0.0 the browser is opening an auth0 url where the `authorizationParams` is `[object Object]`, i.e. invalid. The url is `https://dossierhq-tutorial.eu.auth0.com/authorize?authorizationParams=%5Bobject%20Object%5D&client_id=....`

<img width="816" alt="image" src="https://user-images.githubusercontent.com/2461/213915049-7ac39110-c34c-4e77-a380-13eeef6bced7.png">

### What was the expected behavior?

It should be possible to login.

### Reproduction

(Sorry, haven't had the time to recreate a minimal repro)

- Upgrade to 2.0.0
- [Adjust to breaking changes in 2.0.0](https://github.com/dossierhq/dossierhq/pull/509/commits/732805d0822ca014d0521e53dc9e86774825d42f)
- Run app, click on login button, which uses `loginWithRedirect()`

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-react` used:**  2.0.0
- **Which browsers have you tested in?** Firefox/Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by seljabali** [comment]
I'm seeing the exact same problem:

```
https://....auth0.com/authorize
?authorizationParams=[object Object]
&client_id=L...
&scope=openid profile email
&response_type=code
&response_mode=query
&state=bXYy...==
&nonce=TktlbV...==
&code_challenge=A985...
&code_challenge_method=S256
&auth0Client=eyJuYW...=
```

**Comment by frederikprijck** [comment]
Thanks for reaching out. I will need to look into this and see what could be causing this. Can you verify this happens when both auth0-react v2 and auth0-spa-js v2 are installed locally?

**Comment by seljabali** [comment]
Hi @frederikprijck. 

`npm install @auth0/auth0-spa-js` fixed the issue! 

Perhaps we needed this dependency all along? It worked fine beforehand however without it.

In any case, if it's a hard new requirement, let's please have the [v2 migration guide](https://github.com/auth0/auth0-react/blob/beta/MIGRATION_GUIDE.md) reflect that.

Best!

**Comment by frederikprijck** [comment]
Hey @seljabali ,

No, you should not have to explicitly install auth0-spa-js manually, sorry about that confusion.
But installing auth0-react should install auth0-spa-js, and installing v2 of auth0-react should install v2 of auth0-spa-js.

How did you upgrade auth0-react? Did npm warn you about any incompatible versions?

**Comment by seljabali** [comment]
@frederikprijck, I just checked out the commit before adding `auth0-spa-js` dependency manually and ran it, however didn't come across the error. Perhaps it was a build caching issue? I'm not sure. Thanks again for the help! Hope this helps others.

**Comment by jonasb** [comment]
@frederikprijck I'm using `pnpm` as the package manager (wrapped by [rush](https://rushjs.io/)). Adding `@auth0/auth0-spa-js` didn't fix the issue for me, but purging all `node_modules` and reinstalling worked for me (`rush purge && rush update`).

Thanks for the assistance! 👋

**Comment by frankalbenesius** [comment]
my team also ran into this problem while using `pnpm`. removing `node_modules` and restarting completely also worked for us. thank you for the help!
