### ISSUE TITLE
ReactDOM.render is not a function - Following Guide

### ISSUE THREAD

**Issue by mkempster22** [auth0/auth0-react#483]
### Describe the problem

Following the guide: https://auth0.com/docs/quickstart/spa/react
I cannot get the initial page to load at all. With directly copying the code provided i get `Uncaught TypeError: ReactDOM.render is not a function`
Which is to be expected it seems as ReactDOM.render isn't in current versions of React

### What was the expected behavior?

Page to load content

### Reproduction

I have the following code:

```
import React from 'react'
import ReactDOM from 'react-dom/client'
import App from './App'
import './index.css'
import { Auth0Provider } from '@auth0/auth0-react'


ReactDOM.render(
  <Auth0Provider
    domain="-----"
    clientId="------"
    authorizationParams={{
      redirect_uri: window.location.origin
    }}
  >
    <App />
  </Auth0Provider>,
  document.getElementById("root")
);
```

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 2.0.0
- **Which browsers have you tested in?** Chrome and Firefox (up to date)
- **Which framework are you using, if applicable (Angular, React, etc):** React 18.0.26 - Vite 3.0.0
- **Other modules/plugins/libraries that might be involved:**
```
{
  "name": "-----",
  "private": true,
  "version": "0.0.0",
  "type": "module",
  "scripts": {
    "dev": "vite",
    "build": "vite build",
    "preview": "vite preview"
  },
  "dependencies": {
    "@auth0/auth0-react": "^2.0.0",
    "react": "^18.2.0",
    "react-dom": "^18.2.0"
  },
  "devDependencies": {
    "@types/react": "^18.0.26",
    "@types/react-dom": "^18.0.9",
    "@vitejs/plugin-react": "^3.0.0",
    "autoprefixer": "^10.4.13",
    "postcss": "^8.4.21",
    "tailwindcss": "^3.2.4",
    "vite": "^4.0.0"
  }
}
```

**Comment by mkempster22** [comment]
Managed to fix with my own code as pasted below but would like to know if it's supposed to work in the documented way with current react versions?

```
ReactDOM.createRoot(document.getElementById('root')).render(
  <React.StrictMode>
    <Auth0Provider
      domain="DOMAIN----"
      clientId="CLIENTID----"
      authorizationParams={{
        redirect_uri: window.location.origin
      }}
    >
      <App />
    </Auth0Provider>,
  </React.StrictMode>
)
```

**Comment by adamjmcgrath** [comment]
Hi @mkempster22 - thanks for raising this

I've just tested this on the latest version of React (currently 18.2.0) and `ReactDOM.render` works as expected (you get a deprecation warning - because you should move to ReactDOM.createRoot)

I'll add a note to the README about v18
