### ISSUE TITLE
[Native] Electron(React) + loginWithPopup doesn't open the popup

### ISSUE THREAD

**Issue by realChakrawarti** [auth0/auth0-react#487]
### Describe the problem

Trying to login using the `loginWithPopup` opens up the below popup in Windows:

![image](https://user-images.githubusercontent.com/105297743/214296078-277f6c14-397b-4592-a18e-bfd63d57e7c7.png)

### What was the expected behavior?

Should open up the popup correctly

### Environment

- **Version of `auth0-react` used:** 1.12.1
- **Which browsers have you tested in?**
- **Which framework are you using, if applicable (Angular, React, etc):** Electron + React
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @realChakrawarti - thanks for raising this

We don't support Electron out of the box, I suggest you have a look at this repo that implements Electron with auth0-angular, which should be pretty similar https://github.com/frederikprijck/auth0-electron-angular
