### ISSUE TITLE
Add permissions from access_token to user object

### ISSUE THREAD

**Issue by dev-geddy** [auth0/auth0-react#490]
### Describe the problem you'd like to have solved

> When I want to show/hide client-side UI feature based on the permissions - I have no way to access permissions that are listed in the `access_token`.

### Describe the ideal solution

> Ideally I would like to access permissions in the user's object, like `user.permissions` where permissions would be an array of strings, so I would be able to check for particular permission by `user.permissions.includes('my-permission')`. I would expect permissions data to be taken from decoded `access_token`.

## Alternatives and current work-arounds

> For the time being I have modified `auth0-sdk-js` and `auth0-react` internally, added a call to additional API endpoint to retrieve the list of permissions and add it to user's object.

### Additional context

> As a developer I want an easy access to the list of user's permissions on the client side application.

**Comment by frederikprijck** [comment]
Thanks for reaching out.

Access Tokens are ment to be parsed by an API, not the Client, see: https://auth0.com/docs/secure/tokens#access-tokens
Therefore our SDK does not parse the Access Token, and we have no plans to do so.

What you can do is one of the following:

- Use a custom Rule or Action in Auth0 to ensure the permissions are stored in the Id token. In this case, it will automatically be added to the user / id token claims in our SDK.
- Use your own API to parse the Access Token and return a list of permissions for you to use.

Closing this, as we won't be parsing the access token in our SDK.
