### ISSUE TITLE
loginWithRedirect Typescript Error

### ISSUE THREAD

**Issue by nazmiboxed** [auth0/auth0-react#492]
<img width="199" alt="image" src="https://user-images.githubusercontent.com/106607730/216540862-6b0dd843-39a6-4fc8-8f60-943b9bb9e0df.png">

I'm getting TS error when adding invitation into the `loginWithRedirect` options. According to the example, https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#use-with-auth0-organizations , that seem to be the right place to add `invitation`.

Is it still the same to add `invitation` in v2?

**Comment by frederikprijck** [comment]
Thanks for reporting, no this is not the same and I updated that doc just now, thanks.

It should be set on the authorizationParams, see: https://auth0.github.io/auth0-react/interfaces/AuthorizationParams.html
