### ISSUE TITLE
"Unable to issue redirect for OAuth 2.0 transaction" server error after upgrade to 2.0.0

### ISSUE THREAD

**Issue by HaGuesto** [auth0/auth0-react#494]
By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

After upgrading auth0-react from 1.12.0 to 2.0.0 and following the migration guide, I cannot log into my application anymore.

After logging in, I get the following error
> server_error: Unable to issue redirect for OAuth 2.0 transaction

### What was the expected behavior?

It redirects me back from the Auth0 login page to my application

### Reproduction

- I upgraded my auth0-react version from 1.12.0 to 2.0.0
- I only changed the definition of my Auth0Provider from

```
// Following this guide
// https://auth0.com/blog/complete-guide-to-react-user-authentication/#Set-Up-the-Auth0-React-SDK

import React from "react";
import { useNavigate } from "react-router-dom";
import { Auth0Provider } from "@auth0/auth0-react";

function Auth0ProviderWithHistory({ children }) {
  const domain = process.env.REACT_APP_AUTH0_DOMAIN as string;
  const clientId = process.env.REACT_APP_AUTH0_CLIENT_ID as string;
  const audience = process.env.REACT_APP_AUTH0_AUDIENCE as string;

  const navigate = useNavigate();

  const onRedirectCallback = (appState) => {
    navigate(appState?.returnTo || window.location.pathname);
  };

  return (
    <Auth0Provider
      domain={domain}
      clientId={clientId}
      audience={audience}
      redirectUri={window.location.origin}
      onRedirectCallback={onRedirectCallback}
    >
      {children}
    </Auth0Provider>
  );
}

export default Auth0ProviderWithHistory;
```

To

```
// Following this guide
// https://auth0.com/blog/complete-guide-to-react-user-authentication/#Set-Up-the-Auth0-React-SDK

import React from "react";
import { useNavigate } from "react-router-dom";
import { Auth0Provider } from "@auth0/auth0-react";

function Auth0ProviderWithHistory({ children }) {
  const domain = process.env.REACT_APP_AUTH0_DOMAIN as string;
  const clientId = process.env.REACT_APP_AUTH0_CLIENT_ID as string;
  const audience = process.env.REACT_APP_AUTH0_AUDIENCE as string;

  const navigate = useNavigate();

  const onRedirectCallback = (appState) => {
    navigate(appState?.returnTo || window.location.pathname);
  };

  return (
    <Auth0Provider
      domain={domain}
      clientId={clientId}
      authorizationParams={{
        audience,
        redirect_uri: window.location.origin,
      }}
      onRedirectCallback = {onRedirectCallback}
    >
      {children}
    </Auth0Provider>
  );
}

export default Auth0ProviderWithHistory;

```

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 2.0.0
- **Which browsers have you tested in?** Chrome
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by ewanharris** [comment]
Hey @HaGuesto, this error usually happens due to no `redirect_uri` being sent I believe, however your code looks correct to me. 

Maybe check your logs in the management UI to see if you can verify it's being sent correctly? We've had [one issue](https://github.com/auth0/auth0-react/issues/479) around the update not being installed as expected so potentially also try removing `node_modules` and re-installing to make sure the correct dependency is installed?

**Comment by HaGuesto** [comment]
Removing `node_modules` and re-installing worked for me. Thank you for the quick reply!

**Comment by ewanharris** [comment]
Great to hear! I'll close this issue out
