### ISSUE TITLE
"Unable to issue redirect for OAuth 2.0 transaction" server error after upgrade to 2.0.0

### ISSUE THREAD

**Issue by sproctor** [auth0/auth0-react#495]
I'm re-opening someone else's bug. v2 breaks compatibility with no in-code warning. I just spent a few hours diagnosing this breakage in new code because every reference, including the comments in the current code (https://github.com/auth0/auth0-react/blob/2dc770d0b53f74a910d6018a3ce3099171ee9c9c/src/auth0-provider.tsx#L121) silently fail.

My suggestion is to either support the old parameters or throw an exception if they're used.

**Comment by frederikprijck** [comment]
As mentioned in the other issue, when u remove node_modules, and install it again, does the error show up?

TypeScript should complain about the fact that `redirectUri` is not allowed.

**Comment by sproctor** [comment]
TypeScript didn't complain because my `gatsby-browser.js` is JavaScript. Changing it to a typescript file shows an error in my IDE, but nothing else. Gatsby doesn't do type-checking in TypeScript files. https://www.gatsbyjs.com/plugins/gatsby-plugin-typescript/

I think still think it would make sense to raise an exception when The old, unsupported arguments are used. I imagine that a decent portion of people are using this plugin with JavaScript, and a few with Gatsby.

**Comment by frederikprijck** [comment]
Thanks, i don't think we should bloat out SDK with all kind of checks, as we have more than just one property. This is where our migration guide and api documentation can come in handy. 

Happy to update our migration guide were needed.

I do agree our docs regarding Gatsby need to be updated, so will try and find out who to reach out to.

Thanks for reaching out, and sorry for the inconvenience.

**Comment by sproctor** [comment]
Just to throw out some more old references that should probably be updated or removed:

https://github.com/auth0-blog/gatsby-auth0
https://github.com/auth0-blog/gatsby-recipe-react
https://github.com/auth0-blog/gatsby-recipes-auth0
https://github.com/auth0-blog/auth0-gatsby-site
