### ISSUE TITLE
Client-side decoding a vulnerability?

### ISSUE THREAD

**Issue by low-ghost** [auth0/auth0-react#5]
From glancing at this project, it seems like the initial login request hits the server to generate a jwt and all subsequent verification occurs on the client. Assuming that secrets are involved, a client decoding the jwt would need access to the secret stored on the server in order to produce a verified decoding. Otherwise, although someone couldn't tamper with an existing token, there's nothing stopping him or her from generating a new token with the necessary fields to reach sensitive data. Being that there's no real way to store sensitive data on the client, isn't this a rather large problem? However, I'm potentially missing something about the signing/decoding of jwt's.

**Comment by ntotten** [comment]
This is not a security issue. This is the client side oauth flow. You can see more docs here on how it works: https://auth0.com/docs/protocols#oauth-for-native-clients-and-javascript-in-the-browser
