### ISSUE TITLE
expose the idToken

### ISSUE THREAD

**Issue by wrannaman** [auth0/auth0-react#50]
### Describe the problem you'd like to have solved

I'd like to get the Id token after I authenticate a user

### Describe the ideal solution

const token = auth0.getIdToken()

## Alternatives and current work-arounds

Struggling to find a way to get the id token with the universal login flow without calling the /oath/token endpoint myself.

### Additional context
```
  "auth0-js": "^9.13.2",
  "auth0-lock": "^11.24.3",
```

Calling redirect with 
this.props.auth0.loginWithRedirect()

I can see the /oath/token endpoint is called successfully and returns an `id_token`

**Comment by wrannaman** [comment]
It looks like it's exposed on the `getIdTokenClaims` call under the `__raw` property. Why so hidden? I'd imagine many people, myself included just want a JWT without buying into managing scopes and permissions through auth0.

**Comment by adamjmcgrath** [comment]
Hi @wrannaman - thanks for raising this

We use the `id_token` internally to give you access to the user's claims. We generally discourage the developer from using the `id_token` to authenticate with an API. Instead, we encourage you to define your API in the Auth0 dashboard and add the API identifier in the `audience` prop when initialising the SDK. Then you will then be able to get JWT access tokens using `getAccessTokenSilently` to authenticate against your API.

We do however understand that there are some use cases where getting this token could be useful, so we added the __raw property.

Closing this now, feel free to reopen if you want to continue the conversation.

**Comment by wrannaman** [comment]
Thanks for your thoughts, but as much as I love Auth0, you're asking me to now buy into your whole opinionated way of doing things... which I don't want to do.
