### ISSUE TITLE
Missing migration precisions on withAuthenticationRequired

### ISSUE THREAD

**Issue by benjaminbrgs** [auth0/auth0-react#502]
### Describe the problem

Before v2, we could specify options in the `withAuthenticationRequired` function like the following

```js
export default withAuthenticationRequired(ProfilePage, {
  loginOptions: { prompt: "login" },
});
```

Now, the `prompt` option is not accepted anymore in the loginOptions.
It should be add in `authorizationParams` in the provider like

```js
ReactDOM.render(
  <Auth0Provider
    domain="YOUR_AUTH0_DOMAIN"
    clientId="YOUR_AUTH0_CLIENT_ID"
    authorizationParams={{
      redirect_uri: window.location.origin,
      audience: "YOUR_AUDIENCE_ID",
      scope: "openid profile email",
      prompt: "login"
    }}
  >
    <App />
  </Auth0Provider>,
  document.getElementById('app')
)
```

### What was the expected behavior?

Add an explanation in the migration guide.

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 2.0.0
- **Which browsers have you tested in?:** Chrome, Firefox, Safari
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:** /

**Comment by frederikprijck** [comment]
You should be able to use 
```
export default withAuthenticationRequired(ProfilePage, {
  loginOptions: { authorizationParams: { prompt: "login" } },
});
```

Would that work?

**Comment by benjaminbrgs** [comment]
Thanks for the explanation, I can confirm that your example works as well.
I'm still in favour of adding this to the list of affected functions because it didn't come to my mind at first 👍🏻
