### ISSUE TITLE
Not able to keep user logged in for longer than a day

### ISSUE THREAD

**Issue by Michael-Xie** [auth0/auth0-react#508]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem
> Provide a clear and concise description of the issue
I want to keep the user logged in and not fall back to the login splash page. In order to do that, I have make a call every 2 hours using `getAccessTokenSilently` to get a new token. However, after about a day, `isAuthenticated` will become `false` and goes from the Main page to the Login Splash page. However, when pressing the login button, it doesn't go to the redirect page to log in, it would go to the Main page

### What was the expected behavior?

> Tell us about the behavior you expected to see
I want the users to stay logged into our authenticated pages as long as possible; until the up limit that they need to login again.
 
### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

1. Log in to SPA
2. Let it stay on overnight

console log that the refetching of access token is done, yet `isAuthenticated` is false because the user object is empty. Note that the console log's `user' object is a combination of the original `user` object from auth0 and other keys I added. Also, it is still being refetched even after returning to the splash screen. Below is the ending snippet of console logs 
```
got access token after 2 HOURS
build.umd.js:3103 eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVXQWJqM1ZjalFaeDZSWHVWUm (partially removed)
build.umd.js:3103 {isLoading: false, isAuthenticated: false, user: {…}}isAuthenticated: falseisLoading: falseuser: {customClaims: {…}}customClaims: {accessBuilder: true}[[Prototype]]: Object[[Prototype]]: Object
build.umd.js:3103 got access token after 2 HOURS
build.umd.js:3103 eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVXQWJqM1ZjalFaeDZSWHVWUm (partially removed)
build.umd.js:3103 got access token after 2 HOURS
build.umd.js:3103 eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6IjVXQWJqM1ZjalFaeDZSWHVWUm (partially removed)
```

for some reason there are two auth0 key-value pairs in localstorage
![Screenshot from 2023-02-17 09-39-52](https://user-images.githubusercontent.com/6239834/219684865-0022a9da-42f8-4319-ba81-d6b77c0ccdeb.png)

also, in the cookies section, `(...).isauthenticated` are true 
![Screenshot from 2023-02-17 09-40-40](https://user-images.githubusercontent.com/6239834/219685218-498211d5-c04f-4101-9856-e4a36f6d6336.png)

In React, the Auth0 provider looks like this:

```
REACT_APP_CLIENT=vbh7pNZaYTMf2fbn5JMq9BVcxt34rsCv
REACT_APP_DOMAIN=dev-6kijuc-8.us.auth0.com
```

```
	<Auth0Provider
		domain={process.env.REACT_APP_DOMAIN}
		clientId={process.env.REACT_APP_CLIENT}
		redirectUri={window.location.origin}
		audience={process.env.REACT_APP_AUTH_AUDIENCE}
		useRefreshTokens
		cacheLocation="localstorage"
	>
		<StyledEngineProvider injectFirst>
			<ThemeProvider theme={theme}>
				<ScopedCssBaseline>
					<NotificationsProvider position="bottom-center">
						<App />
					</NotificationsProvider>
				</ScopedCssBaseline>
			</ThemeProvider>
		</StyledEngineProvider>
	</Auth0Provider>,
```

A snippet of `App.js`

```
	const {
		isAuthenticated,
		isLoading,
		error,
		user,
	} = useApplicationData();

        console.log({ isLoading, isAuthenticated, user });
	if (isLoading) {
		return (
			<LoadingScreen>
				<Spinner color="i5OGreen" size={50} />
			</LoadingScreen>
		);
	}

	// https://community.auth0.com/t/user-is-undefined-and-isauthenticated-returns-false-after-login/87495
	if (!isLoading && !isAuthenticated) {
		return <SplashScreen />;
	}

	return (
		<div className="App">
			{error && (
				<Notification
					data={{
						type: 'error',
						message: error,
					}}
					snackbar
				/>
			)}
			{isAuthenticated && (
				<UserContext.Provider value={userInfo}>
					<Router>
						<TopBar
							customers={customers}
							handleCustomerSwitch={switchCustomer}
						/>
						<Content>
							{currentCustomer && (
								<SideBar availablePages={currentCustomer.pages} />
							)}

							<Routes>
								<Route
									path="/home"
									element={
```

snippet of code that is refetching token periodically in `useApplicationData`
```
	useEffect(() => {
		const HOURS = 2;
		const refresh = setInterval(async () => {
			const token = await getAccessTokenSilently({
				scope: process.env.REACT_APP_AUTH_SCOPE,
			});
			console.log(`got access token after ${HOURS} HOURS`);
			console.log(token);
		}, HOURS * 60 * 60 * 1000);
		return () => clearInterval(refresh);
	}, []);
```

in auth0, the application setting snippet is as follows:
![Screenshot from 2023-02-17 09-51-29](https://user-images.githubusercontent.com/6239834/219687688-db55d25e-2444-47b3-b079-b69636ed3e55.png)

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** "^1.12.0"
- **Which browsers have you tested in?** Chrome, Firefox
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**
    "react-router-dom": "^6.4.3",

**Comment by scottquested** [comment]
I have the same issue!

**Comment by worthbak** [comment]
Same issue - daily logins are nearly a dealbreaker for my use of Auth0 in my app. Any clarity would be much appreciated!

**Comment by frederikprijck** [comment]
Thanks for reaching out @Michael-Xie , we wil look into this but have a couple of questions.

> for some reason there are two auth0 key-value pairs in localstorage

There can be many in local storage, and that's by design. So nothing weird going on with seeing two here.
However, can you verify both of these have a refresh_token? I can see the second has one, but the one that includes the `read:reports` scope isn't showing one, does it have one?

If not, did it have one initially and did it get removed overnight?

Can you reproduce this in [our sample application](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01)? If you can't can you please provide the HAR file containing the relevant requests to Auth0 so we can look into the requests made to Auth0 and the responses received from it? That would help us understand what our SDK could be doing incorrect.

@scottquested and @worthbak , thanks for chiming in here. If anyone of you would also be able to either try the sample application or provide a HAR file, that would help speed things up.

**Comment by scottquested** [comment]
I'm not sure if this helps, or is related to @Michael-Xie but it seems my issue was user error 🙈

I was actually getting a `missing_refresh_token` every 24 hours and only a logout/login would fix the token issue. 

Diving a bit further, it seems I have fixed this by setting the API access settings to "Allow offline access". Seems to have worked over the weekend!

<img width="974" alt="Screenshot 2023-02-27 at 08 32 36" src="https://user-images.githubusercontent.com/4488112/221514472-ce3384a6-28c1-4806-9c1f-77d93df90791.png">

**Comment by frederikprijck** [comment]
I have been able to reproduce this and to solve it with v1 of our SDK you want to **move the scope, currently set on getAccessTokenSilently, to the AuthProvider and ensure the AuthProvider contains all scopes you plan to use throughout your application**. You can keep the scope on `getAccessTokenSilently`, but you want to ensure it also exist on AuthProvider.

That said, I believe this should be solved in v2. So upgrading to v2 is probably the ideal solution.

**Let me elaborate what's happening in v1:**

- `AuthProvider` is configured with the default scope, resulting in a set of tokens thats valid for a certain period of time for these scopes
- using `isAuthenticated` relies on those tokens to determine whether or not a user is authenticated. So as long as those tokens are valid, the user is considered authenticated.
- `getAccessTokenSilently` is used with a different scope, resulting in another set of tokens thats valid for a certain period of time. As these are not the "main tokens" (which are based on the `AuthProvider`), they do not impact the authentication state.
- The `useEffect` is refreshing the second set of tokens every two hours, but it's not refreshing the original tokens that are the ones that drive the isAuthenticated state. This means that after a period of time, the first tokenset will be expired, and isAuthenticated will be false. While the second set of tokens will still be valid.

Based on how v1 handles authentication state, I believe this is working as expected.
However, as we agree that this is weird, we reworked isAuthenticated, getUser and getIdTokenClaims in v2, to not behave like this anymore. We haven't solved this in v1 as it's a breaking change and we can not solve this without breaking people, hence the v2.

**Comment by Michael-Xie** [comment]
> I'm not sure if this helps, or is related to @Michael-Xie but it seems my issue was user error see_no_evil
> 
> I was actually getting a `missing_refresh_token` every 24 hours and only a logout/login would fix the token issue.
> 
> Diving a bit further, it seems I have fixed this by setting the API access settings to "Allow offline access". Seems to have worked over the weekend!
> 
> <img alt="Screenshot 2023-02-27 at 08 32 36" width="974" src="https://user-images.githubusercontent.com/4488112/221514472-ce3384a6-28c1-4806-9c1f-77d93df90791.png">

Thanks for the update @scottquested 

I did have the "allow offline access" enabled for the API application
![Screenshot from 2023-02-28 18-12-28](https://user-images.githubusercontent.com/6239834/222004364-a59dabf0-9be3-4092-8274-9f85ee1deca6.png)

What version of auth0 are you using?

**Comment by scottquested** [comment]
@Michael-Xie 2.0

**Comment by Michael-Xie** [comment]
> I have been able to reproduce this and to solve it with v1 of our SDK you want to **move the scope, currently set on getAccessTokenSilently, to the Auth0Provider and ensure the Auth0Provider contains all scopes you plan to use throughout your application**. You can keep the scope on `getAccessTokenSilently`, but you want to ensure it also exist on Auth0Provider.
> 
> That said, I this should be solved in v2. So upgrading to v2 is probably the ideal solution.
> 
> I reproduced it in v1, and could not reproduce it in v2.
> 
> **Let me elaborate what's happening in v1:**
> 
> * `Auth0Provider` is configured with the default scope, resulting in a set of tokens thats valid for a certain period of time for these scopes
> * using `isAuthenticated` relies on those tokens to determine whether or not a user is authenticated. So as long as those tokens are valid, the user is considered authenticated.
> * `getAccessTokenSilently` is used with a different scope, resulting in another set of tokens thats valid for a certain period of time. As these are not the "main tokens" (which are based on the `Auth0Provider`), they do not impact the authentication state.
> * The `useEffect` is refreshing the second set of tokens every two hours, but it's not refreshing the original tokens that are the ones that drive the isAuthenticated state. This means that after a period of time, the first tokenset will be expired, and isAuthenticated will be false. While the second set of tokens will still be valid.
> 
> Based on how v1 handles authentication state, I believe this is working as "expected". However, as we agree that this is weird, we reworked isAuthenticated, getUser and getIdTokenClaims in v2, to not behave like this anymore. We haven't solved this in v1 as it's a breaking change and we can not solve this without breaking people, hence the v2.

Thanks for the thorough explanation. I didn't realize that `Auth0Provider` has `scope` prop until you mentioned it and then referencing the [v.1.12.2 tag](https://github.com/auth0/auth0-react/blob/v1.12.1/src/auth0-provider.tsx). Glad, v2 got reworked, because have different sets of tokens depending on scope wasn't too intuitive or hard to find documentations on its use cases.

I will give upgrading to v2 a shot.

**Comment by Michael-Xie** [comment]
> @Michael-Xie 2.0

Thanks~! Gonna try upgrading to v2~! **fingers-crossed**

**Comment by Michael-Xie** [comment]
> Let us know if you have any difficulties, so we can assist where needed and see if we can improve documentation.
> 
> Be sure to read the [migration guide](https://github.com/auth0/auth0-react/blob/master/MIGRATION_GUIDE.md) thoroughly.
> 
> > because have different sets of tokens depending on scope wasn't too intuitive or hard to find documentations on its use cases.
> 
> This is still the case in v2 tho, nothing has changed on that regard, this is how OAuth works, see https://oauth.net/2/scope/. The idea is that you only get a token for the scopes you asked for, in this case you:
> 
> * Initially asked for a token with the default scopes
> * Then ask for a token with more scopes
> 
> Because you are asking for more scopes then the scopes used for the token that was already issued, we need to contact Auth0 again to retrieve another set of tokens.
> 
> To avoid all of this, even with v2, you want to **only** set scope on the Auth0Provider, and not when u call any of our SDK's methods.
> 
> The only thing we did rework with v2 is how all of this affects the `isAuthenticated`, `user` and `idTokenClaims` state.

Hi @frederikprijck~!

Thanks for the links and explanation, they are really helpful~!

For the migration, I was able to migrate successfully to v2 and the user won't go back to the Splash page within 24 hours.

A couple of side questions I have are:
1. How does `isAuthenticated` go from true to false? From my understanding, if the `user` object exists then it is true. Does that mean that `id_token`'s expiration controls the state of `isAuthenticated`?
2. If I want the user to stay logged until the max expiration is reached (I think it is 30 days) before the need to re-login, would calling `getAccessTokenSilently` in an interval enable this behaviour?

**Comment by frederikprijck** [comment]
Good that migration worked.

1. No, the expiration on the id token is only used to accept an id token, and it doesnt have any direct relation to the isAuthenticated state. isAuthenticated will be set to false when Auth0 returns a login_required error in the event of trying to get a new access token when calling getAccessTokenSilently.

2. What do you mean with max expiration? Are you referring to the session duration on Auth0's side?

**Comment by Michael-Xie** [comment]
> Good to hear that migration worked 🎉 .
> 
> 1. No, the expiration on the id token is only used to accept an id token, and it doesnt have any direct relation to the isAuthenticated state. isAuthenticated will be set to false when Auth0 returns a login_required error in the event of trying to get a new access token when calling getAccessTokenSilently.

I see, how do we control when the login_required error will happen? Would adjusting the token expiration for a Custom API on auth0 do that?

> 2. What do you mean with max expiration? Are you referring to the session duration on Auth0's side?

Yeah, that's correct. https://auth0.com/docs/manage-users/sessions/session-lifetime-limits

What I want to do is to have the users stay logged in until they want to log out or until some lifetime limit is reached for the session. That was why I had the `useEffect` to `getAccessTokenSilently()` in order to keep the user logged in.

**Comment by frederikprijck** [comment]
> I see, how do we control when the login_required error will happen? Would adjusting the token expiration for a Custom API on auth0 do that?

A login_required is thrown by Auth0, so it relies on the Auth0 session duration, which you can control in your tenant settings.

Once you use refresh tokens, you also want to look into configuring the refresh token lifetime, see https://auth0.com/docs/secure/tokens/refresh-tokens/configure-refresh-token-expiration.

**Comment by Michael-Xie** [comment]
> > I see, how do we control when the login_required error will happen? Would adjusting the token expiration for a Custom API on auth0 do that?
> 
> A login_required is thrown by Auth0, so it relies on the Auth0 session duration, which you can control in your tenant settings.
> 
> Once you use refresh tokens, you also want to look into configuring the refresh token lifetime, see https://auth0.com/docs/secure/tokens/refresh-tokens/configure-refresh-token-expiration.

Hi @frederikprijck,

I did some experimentation with the different settings and here are the results:



Action | Result
-- | --
Update Session Cookie settings (Inactivity time: 5min, Require Log in in: 10min) | Didn’t log user out. Token's `expiresAt` in local storage didn’t change
Update Id token expiration to 600s (10min) for i-5o application | No effect on getting user to log out. Token's `expiresAt` didn't change
Update Access Token expiration for functions-api with expiration set to 600s (10min) | local storage token's `expiresAt` date set to expire in 10 min and got refreshed subsequently
Turn rotate token off for i-5o application | Error since there is no refresh token and current app version needs it with missing token error. Also, no calls to the api server are made after the access token expired. There are no access token in local storage. Only the id token is retained and that is also expired. It doesn't log user out.
Add back rotate token and shorten absolute lifetime of refresh token to less than 10min (8.3 min or 500 sec) | access token in local storage only contains the expired refresh token with error that refresh token is invalid or unknown. There is an error User is not logged out.

It seems like the access token setting has the most effect. When the refresh token is active, the access token is automatically refreshed. So the user is still authenticated. If the refresh tokens settings were adjusted, the access token would expire, but the user is still authenticated.

What would the next step be to better understand how to control the `isAuthenticated` state?

**Comment by sdevil7th** [comment]
> Hey,
> 
> The isAuthenticated state is defined by what Auth0 tells us. If u use refresh tokens, you disconnect from Auth0's session and you will be considered authenticated until Auth0 tells us otherwise.
> 
> This should happen by throwing a `login_required` when calling `getTokenSilently` when you have either have set useRefreshTokens to false, or useRefreshTokens and useRefreshTokensFallback to true.
> 
> If you use refresh token but have not set `useRefreshTokensFallback` to true, calling getTokenSilently might throw a `invalid_grant` error when the refresh token is expired.
> 
> This doesnt mean the user is no longer authenticated, but we can not tell for sure. In that case, you want to catch `invalid_grant` and decide yourself what you want to do (e.g. call logout).
> 
> Also note that the id token expiration will have absolutely no effect on the duration of isAuthenticated.
> 
> Hopefully this helps. Let me know if it does not.

You saved me from a paranoia!! I just had to add `useRefreshTokensFallback={true}` when I updated to react 18 and auth0-react@2. I wish I read your comment earlier @frederikprijck ! Thanks a ton!
