### ISSUE TITLE
Fails to install with npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.

### ISSUE THREAD

**Issue by chrishj59** [auth0/auth0-react#509]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

> On install with the command 
npm i @auth0/auth0-react
I get the error noted below
npm WARN deprecated stable@0.1.8: Modern JS already guarantees Array#sort() is a stable sort, so this library is deprecated. See the compatibility table on MDN: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort#browser_compatibility
npm WARN deprecated svgo@1.3.2: This SVGO version is no longer supported. Upgrade to v2.x.x.
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR!
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login

### What was the expected behavior?
install command to install the package

> Tell us about the behavior you expected to see
npm undated  0 vulernablities

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Step 1
- npm i @auth0/auth0-react

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-react` used:**
- **Which browsers have you tested in?**
- **Which framework are you using, if applicable (Angular, React, etc):**
- **Other modules/plugins/libraries that might be involved:**

**Comment by ewanharris** [comment]
Hey @chrishj59, I can't seem to reproduce this error and I'm wondering if it's potentially environment/machine specific? The `npm ERR! Incorrect or missing password.` line seems to indicate that there's an error with your npm authentication, are you potentially using a private registry or maybe try running `npm login` to see if that fixes it?

**Comment by chrishj59** [comment]
Hi

**Comment by chrishj59** [comment]
Hi, 
This was due to an NPM token that had expired when I attempted to use @auth0/auth0-react.
Thank you
