### ISSUE TITLE
`withClaimCheck` example in 2.x migration guide does not work with NextJS

### ISSUE THREAD

**Issue by LucasLemanowicz** [auth0/auth0-react#512]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

The `withClaimCheck` example on the 2.x migration guide (https://github.com/auth0/auth0-react/blob/525ccf8/MIGRATION_GUIDE.md#removal-of-claimcheck-on-withauthenticationrequired) does not work. The use of `useAuth0()` in `withClaimCheck` violates the rule of hooks, and causes issues when trying to load the route in NextJS.

When page opened via a `Link`:
<img width="975" alt="Screenshot 2023-02-20 at 7 42 41 PM" src="https://user-images.githubusercontent.com/361348/220220199-fc03ca9c-e9bd-4891-8582-a0f0d89bb61d.png">

When directly accessing the page:
<img width="981" alt="Screenshot 2023-02-20 at 7 42 22 PM" src="https://user-images.githubusercontent.com/361348/220220164-f0fe3a4c-102d-408b-bc85-2bbb88bd2032.png">

### What was the expected behavior?

I expected the example to work.

### Reproduction

- See code https://github.com/LucasLemanowicz/auth0-withclaimcheck-repro
- When you go to `/secret` it will fail

### Environment

- **Version of `auth0-react` used:** 2.0.0
- **Which browsers have you tested in?** Browser-agnostic
- **Which framework are you using, if applicable (Angular, React, etc):** React 18.2.0, NextJS 12.3.4 (and also NextJS 13.1.6), Typescript 4.9.5
- **Other modules/plugins/libraries that might be involved:**

**Comment by ewanharris** [comment]
Hey @LucasLemanowicz, thanks for raising this issue!

I've put up a PR that amends our suggestion to instead create and return a component from the `withClaimCheck` HOC, you can find that PR at #513

For the sample you provided (thanks for that by the way!), it would change the `withClaimCheck` to be as follows, I've tested it within the sample and everything seems to work just fine.

```ts
export function withClaimCheck(Component: NextPage, claimCheckOptions: ClaimCheckProps) {
  const WithClaimCheckComponent = () => {
    const { user } = useAuth0();

    if (claimCheckOptions.claimCheck(user)) {
        return <Component />;
    }

    Router.push(claimCheckOptions.returnTo);
    return <BlankPage />;
  }

  return WithClaimCheckComponent;
}


```
