### ISSUE TITLE
Auto-logout on domain redirection

### ISSUE THREAD

**Issue by theIYD** [auth0/auth0-react#517]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

I have a usecase where a user signs up to the platform with an email & an auto-generated password is sent to his email. The user is created in Auth0. Now on the first login, the user needs to setup his personal account with details like company name, domain, number of users under the company, updating the password etc etc. 

Post submitting these details, the password is reset to the new one, domain is set under the `user_metadata` and a redirection happens to the new domain which the user mentioned in the form. Once the redirection happens (`/authorize`), the silent auth fails with `Login Required` and goes back to the login page. 

### What was the expected behavior?

The expected behaviour is to not logout the user and after redirection, the user should proceed to the application. 

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

- Signup a user with email. An auto-generated password sent to the email
- Login with email & password (silent-auth success)
- Provide a domain
- Redirect to `old-domain/authorize` & then redirect to `new-domain/authorize`
- Logs out (silent-auth fails)

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

Code snippet doing the redirection:
![image](https://user-images.githubusercontent.com/10477827/221464847-b25e3557-032b-49a4-9bde-6b8af201cfb1.png)

Code snippet of `Auth0Provider`:
![image](https://user-images.githubusercontent.com/10477827/221464972-e5a357ca-9dac-4291-8b4c-a75a6b23ae77.png)

### Environment

> Please provide the following:

- **Version of `auth0-react` used: 1.6.0** 
- **Which browsers have you tested in?: Chrome, Firefox**
- **Which framework are you using, if applicable (Angular, React, etc): React**
- **Other modules/plugins/libraries that might be involved: None**

**Comment by frederikprijck** [comment]
Thanks for reaching out.

When you mention old and new domain, are you referring to the application's domain or Auth0's domain?
Can you elaborate on how that redirection is happening as well as include a HAR file that contains the calls to Auth0?

That would help understand why it might return login_required.

Important to note is that login_required is an error returned by Auth0, not by our SDK. There is not much we can do to fix it other then ensure we send the correct information, which the HAR file should tell us.

Even better would be if you can provide a reproduction, as called out in the issue template.

Thanks

**Comment by theIYD** [comment]
By old and new domain, I meant the application's domain.

Example: 
abc.test.com - old domain
efg.test.com - redirected to new domain

Here is HAR file: https://drive.google.com/file/d/19ZQbcV4nD-Ua8DCF8oUOnUC0qcx04ihk/view?usp=sharing

I would not be able to provide the reproduction as it is very specific to the application which I work with.

**Comment by adamjmcgrath** [comment]
Hi @theIYD,

From the information you've shared - it's not possible to figure out what the issue is. It's likely something specific to your application. 

If you can provide an example the reproduces the issue we'd be happy to debug it for you, otherwise am closing the issue - feel free to ping me if you want to provide a reproducible example and I'll reopen it.
