### ISSUE TITLE
Protecting nextjs api routes with middleware?

### ISSUE THREAD

**Issue by sgoodluck** [auth0/auth0-react#518]
**Context**

- We are deploying a Next.js hybrid SPA/SSR application to Cloudflare Pages (a regular static site with NextJS API routes acting as a proxy server)

- We are using this SDK over the nextjs-auth SDK due to [ an edge-incompatibility issue](https://github.com/auth0/nextjs-auth0/issues/1079#issuecomment-1446399962)

**Objective**

We would like to protect our [API routes](https://nextjs.org/docs/api-routes/introduction) using this SDK's authentication.

Specifically, we would like to implement Next.js middleware to check authentication before allowing requests to our proxy API like this [documentation sample](https://nextjs.org/docs/advanced-features/middleware#producing-a-response). 

**Questions**

1. Do you think this is recommended or possible?
2. Can the [getAccessToken](https://gist.github.com/adamjmcgrath/0ed6a04047aad16506ca24d85f1b2a5c) method be used in the middleware here given that the middleware exists in a separate context? 
3. Can both SDKs be used in conjunction with one another to achieve this functionality? (Example [using other SDK](https://github.com/auth0/nextjs-auth0/blob/main/EXAMPLES.md#protecting-pages-with-middleware))
4. What would be the recommended approach to protect our Nextjs API Routes if none of the above?

**Other Context**
https://github.com/cloudflare/cloudflare-docs/issues/6565

Using Cloudflare workers may have been supported at some point but stripped out due to a security issue. So monitoring there as well... 

**Current Approach**

Right now, my plan is to use this library to get my JWT, then make calls to our API routes using fetch/axios and adding the JWT to the auth header so the middleware can act on it. TBD on whether this approach will work or is ill-advised

**Comment by adamjmcgrath** [comment]
Hi @sgoodluck 

> Right now, my plan is to use this library to get my JWT, then make calls to our API routes using fetch/axios and adding the JWT to the auth header so the middleware can act on it. TBD on whether this approach will work or is ill-advised

This is a good approach. You just need an SDK that will protect your middleware with a JWT bearer access token. Unfortunately, currently [our javascript SDK](https://github.com/auth0/node-oauth2-jwt-bearer/tree/main/packages/express-oauth2-jwt-bearer) that does this is just for Express.

Our Next SDK uses https://github.com/sandrinodimattia/serverless-jwt in it's examples for protecting an API (see https://github.com/auth0/nextjs-auth0/blob/main/examples/kitchen-sink-example/pages/api/my/shows.ts)

**Comment by sgoodluck** [comment]
Ah, that looks like it might do exactly what we need - thank you for the link!

**Comment by adamjmcgrath** [comment]
This looks resolved so closing, feel free to ping this thread if you have any other feedback @sgoodluck
