### ISSUE TITLE
Library does not redirect as usually when Refresh Token absolute lifetime is shortened

### ISSUE THREAD

**Issue by charliearaya** [auth0/auth0-react#519]
### Describe the problem

When refresh token expires I get a 403 response with the following message:
`{"error":"invalid_grant","error_description":"Unknown or invalid refresh token."}
`

Usually the app redirects to the login page of my webapp but not after shortening the refresh token absolute lifetime to 120 seconds.

### What was the expected behavior?

To be redirected to my webapp's login page

### Reproduction
* Set refresh token absolute lifetime to 120s in the management console
* Wait the time
* As a logged in user refresh the webapp

### Environment

- **Version of this library used: 1.10.2**
- **Which framework are you using, if applicable: React 17.0.2**
- **Other modules/plugins/libraries that might be involved: **
- **Any other relevant information you think would be useful:**

**Comment by adamjmcgrath** [comment]
Hi @charliearaya - thanks for raising this

This is expected behaviour - when the refresh token expires you need to handle the `invalid_grant` error in your application and prompt the user to login again.

**Comment by adamjmcgrath** [comment]
Closing this issue, as I believe https://github.com/auth0/auth0-react/issues/519#issuecomment-1467884128 answers your question. Feel free to ping me if you want to reopen it.

**Comment by namfal** [comment]
In case anyone stumbles upon this, I encounter a similar problem when upgrading from v1 to v2 but mine wasn't really about the expiration period. Setting `useRefreshTokensFallback` to `true` fixed it for me.
