### ISSUE TITLE
Would this allow a custom login page?

### ISSUE THREAD

**Issue by zachrickards** [auth0/auth0-react#52]

**Comment by adamjmcgrath** [comment]
Hi @zachrickards 

Yes, this library uses the Auth0 Universal Login Page which can be customised, take a look here for more info https://auth0.com/docs/universal-login

**Comment by zachrickards** [comment]
@adamjmcgrath sorry, should have been more descriptive and clear. Does this allow for an embedded page of our own, all I'm seeing is loginWithRedirect which takes you to the hosted Auth0 page, but I want the login page customized and as a part of my SPA.

**Comment by adamjmcgrath** [comment]
Hi @zachrickards - no, we only do 'Universal Login Page' which is hosted on your tenant.

If you want to host the login form yourself, check out https://github.com/auth0/lock
