### ISSUE TITLE
`cookieDomain` doesn't seem to share auth between (sub)domains

### ISSUE THREAD

**Issue by MrDiggles2** [auth0/auth0-react#523]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

Hello, I am setting up a B2B application where customer have their own Auth0 organizations and have their applications on separate subdomains, e.g. company1.localtest.me, company2.localtest.me.

Users log in at the second level domain (i.e. localtest.me) using the universal login flow with the organization prompt. When redirected back to localtest.me (via `redirect_uri`), I would like to redirect the user to their organization subdomain, i.e. company1.localtest.me.

I am using `cookieDomain=.localtest.me` to share authentication between the domains but I keep getting kicked back to the login page.

### What was the expected behavior?

> Tell us about the behavior you expected to see

Redirecting the user to their organization subdomain after logging in should not trigger another login flow.

### Reproduction

> Detail the steps taken to reproduce this error, and whether this issue can be reproduced consistently or if it is intermittent.
> **Note**: If clear, reproducable steps or the smallest sample app demonstrating misbehavior cannot be provided, we may not be able to follow up on this bug report.

AuthProvider usage:

```
<Auth0Provider
  domain={AUTH0_DOMAIN}
  clientId={CLIENT_ID}
  authorizationParams={{
    redirect_uri: 'https://localtest.me:8080',
  }}
  cookieDomain='.localtest.me'
>
  <Main />
</Auth0Provider>
```

Inside `Main.tsx`:

```
const auth = useAuth0();

useEffect(() => {
  if (auth.error) auth.logout();

  auth.getIdTokenClaims().then(idToken => {
    if (idToken) {
      const newUrl = `https://${idToken['https://localtest.me/companyId']}.localtest.me:8080`;

      if (!window.location.href.includes(newUrl)) {
        window.location.href = newUrl;
      }
    }
  });
}, [auth]);
```

Here is the `.har` file (with some sensitive entries removed): [p1test.us.auth0.com.har.log](https://github.com/auth0/auth0-react/files/10970582/p1test.us.auth0.com.har.log)

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

If so, provide steps:

> Where applicable, please include:
>
> - The smallest possible sample app that reproduces the undesirable behavior
> - Log files (redact/remove sensitive information)
> - Application settings (redact/remove sensitive information)
> - `clientId` and `domain` (these are publicly available)
> - Screenshots

### Environment

> Please provide the following:

- **Version of `auth0-react` used:** 2.0.1
- **Which browsers have you tested in?** Chrome, Safari
- **Which framework are you using, if applicable (Angular, React, etc):** React
- **Other modules/plugins/libraries that might be involved:**

**Comment by adamjmcgrath** [comment]
Hi @MrDiggles2 - thanks for raising this

I can see from the HAR file that `https://company1.localtest.me:8080/` correctly picks up the `is.authenticated` cookie and attempts to do silent auth, so there is no issue with your `cookieDomain=.localtest.me` configuration.

I can see that your silent auth request (the `/authorize?...&prompt=none...`) that you make form an iframe on `https://company1.localtest.me:8080/` is not picking up the `auth0` cookie on `p1test.us.auth0.com` so you're getting a `login_required` error.

I can't see ay reason why that cookie would be blocked, but as `/authorize` is being loaded in an iframe, it's a 3rd party cookie and there are [various reasons](https://github.com/auth0/auth0-spa-js/blob/master/FAQ.md#why-is-the-user-logged-out-when-they-refresh-the-page-in-their-spa) why it might be blocked (although I can't see why it would fail with your use case).

When inspecting the request in your network tab, you may get more information than is shared in the HAR file. Take a look at the "Cookies" tab for the `/authorize?...&prompt=none...` request - it may tell you why the 3rd Party `auth0` cookie is being blocked (perhaps some privacy/security settings on your Chrome browser).

**Comment by MrDiggles2** [comment]
@adamjmcgrath - Thank you for the quick response.

I looked in my Chrome settings and realized I had set it to block third party cookies in "incognito mode" which I had been using to avoid logging in and out 🤦 

![Screen Shot 2023-03-15 at 9 34 57 AM](https://user-images.githubusercontent.com/1780320/225324680-125e50ab-1a40-464a-b757-3ce7e4b08b8a.png)

After flipping it to "Allow all cookies", it is now working as expected.

Thank you very much!

**Comment by adamjmcgrath** [comment]
Glad you got it working @MrDiggles2, and thanks for sharing the solution 👍

**Comment by EssamKayal96** [comment]
Hello @MrDiggles2 Thanks for sharing the solution, I am working on the same case as yours.

I have a question though, how did you test the redirection and using domainCookies on local, I am struggling with testing it locally.
 
Thanks in advance.
