### ISSUE TITLE
Bug with loginWithRedirect

### ISSUE THREAD

**Issue by rau** [auth0/auth0-react#524]
### Describe the problem

I’m using the auth0 react package. Pretty simple log in flow. Standard stuff.

I have a super odd bug, which is sometimes triggered, and sometimes not. Users will try to click on a button that has the onClick={loginWithRedirect}, and nothing will happen. No console output, nothing to sentry, there is no error at all. The button simply doesn’t do anything.

Below is the code we use:

```
<AwesomeButton
	type='primary'
	style={{
		"--button-primary-color": "#7c55d6",
		"--button-primary-color-dark": "#6444ad",
		"--button-primary-color-light": "#fff",
		"--button-primary-color-hover": "#6444ad",
		"--button-primary-color-active": "#6444ad",
	}}
	onPress={() =>
		loginWithRedirect({
			screen_hint: "login",
			mode: "login",
		})
	}
>
	Log in
</AwesomeButton>
```

```
const root = ReactDOM.createRoot(document.getElementById("root"))
root.render(
	<BrowserRouter>
		<Auth0Provider
			domain={process.env.REACT_APP_AUTH0_DOMAIN}
			clientId={process.env.REACT_APP_AUTH0_CLIENT_ID}
			redirectUri={process.env.REACT_APP_REDIRECT_URI}
			audience={process.env.REACT_APP_AUDIENCE}
			scope='read:current_user'
			useRefreshTokens={true}
			cacheLocation='localstorage'
		>
			<App />
			<Toaster />
		</Auth0Provider>
	</BrowserRouter>
)
```

To check it out for yourself, see the prod link: [https://app.delilah.ai/](https://app.delilah.ai/)

### What was the expected behavior?

The expected behavior is that clicking on the button should cause it to redirect to login.

### Reproduction

 It’s difficult to recreate, as we don’t know what causes it, but it affects a decent amount (5-10% of our users). My suspicion is adblock or antivirus, but sometimes after disabling those, it still occurs. My other suspicion is that environment variables aren't getting loaded somehow for the Auth0 wrapper? But I don't know how that could be possible. Frontend service is Vercel, environment variables are definitely set.

**Can the behavior be reproduced using the [React SDK Playground](https://github.com/auth0/auth0-react/blob/master/CONTRIBUTING.md#local-development)?**

No

### Environment

> Please provide the following:

- **Version of `auth0-react` used:**
- 1.12.0
- **Which browsers have you tested in?**
- Chrome, Safari
- **Which framework are you using, if applicable (Angular, React, etc):**
- React
- **Other modules/plugins/libraries that might be involved:**
- Vercel?

**Comment by rau** [comment]
Hey, any help? This bug is kicking our production app's ass, 20% of users just can't click the button. Is there any sort of temporary workaround?

**Comment by frederikprijck** [comment]
Hello,

Going to the app you shared appears to work on two different machines on our end.

It's hard for us to help with the context provided and we have no control over environment variables (as it's a browser) or anti-virus or other tools.

What i do recommend is changing it to `onClick={() => loginWithRedirect()}` to ensure the click event object is not sent to our SDK. I don't see how that would cause issues, but i believe it's better to ensure not to pass these kind of objects in to avoid any conflict.

Happy to help if you can provide us with more context to reproduce this, but unfortunately i believe there isn't much we can help with based in the information provided.

**Comment by frederikprijck** [comment]
Can you provide more information about what exception is being thrown in a new issue @withintheruins14 ? A HAR file or reproduction would also help.

I am closing this one as I believe the OP went inactive.
