### ISSUE TITLE
Double redirect with loginWithRedirect after upgrade to version 2

### ISSUE THREAD

**Issue by jBenes** [auth0/auth0-react#525]
### Describe the problem

After upgrading to 2.0.1 from version 1.x.x, loginWithRedirect started redirecting user outside of the app twice.

We are using Ionic, Capacitor and `SafariViewController` lib to handle redirect. Problem happens on iOS mobile app.

Old behavior:

- User clicks login -> SafariViewController opens page so user can log in -> user is redirected back to the app

New behavior:

- User clicks login -> SafariViewController opens page so user can log in -> user is redirected back to the app -> user is redirected to chrome (for ~1s, domain of our auth0 server dev-XXXXXXX.us.auth0.com) -> user is immediately redirected back to the app

Note: User gets logged in, but the main problem is that user is redirected to Chrome on iOS. App Store might evaluate it as breaking their policies. User should stay in the app or use Safari View Controller for any other activity.

### What was the expected behavior?

I expect that user would stay in the app and wouldn't be redirected to chrome at all, like before upgrade.

### Reproduction

Our login handler after upgrade looks like this:

```
    const available = await SafariViewController.isAvailable();

    if (available) {
      await loginWithRedirect({
        authorizationParams: {
          connection: "apple",
        },
        async openUrl(url) {
          SafariViewController.show({
            url: url,
            hidden: false,
            transition: "curl",
            enterReaderModeIfAvailable: true,
          }).subscribe();
        },
      });
    } else {
      // android
    }
```

Provider config:

```
      <Auth0Provider
        domain={auth0_domain}
        clientId={auth0_client_id}
        authorizationParams={{
          redirectUri: auth0_callback_uri,
        }}
      >
```

### Environment

- **Version of `auth0-react` used:** 2.0.1
- **Which browsers have you tested in?** iOS app + Safari and Chrome installed on the phone as default browser
- **Which framework are you using:** Ionic, Capacitor, React

**Comment by frederikprijck** [comment]
Thanks for reaching out.

What library are you using to use SafariViewController, and what's the reason not to use [capacitor's browser plugin](https://capacitorjs.com/docs/apis/browser), which uses `SFSafariViewController` on iOS? Would the issue persist when using the Capacitor's Browser Plugin instead?

Thanks.

**Comment by jBenes** [comment]
Hi @frederikprijck ,
there is no real reason, I didn't know that plugin you mention uses SVC internally. Thank for pointing it out.

I have tried plugin you suggest and I got the same result.

User is logged via safari, then redirected back and then chrome is open for a second and closed again.

**Comment by frederikprijck** [comment]
Can you please share a reproduction, as I have not noticed that behavior before with our Sample that does use v2 of this SDK: https://github.com/auth0-samples/auth0-ionic-samples/tree/main/react

You can use the above example application to reproduce it, then share it with us. Happy to look into it.

**Comment by jBenes** [comment]
I have tried sample app and it works well.
But when comparing example solution I found out that problem was actually somewhere else. We made a mistake while migrating "localOnly" param of logout. We locally log user out from auth0 after login and we proceed with our own auth.

Thanks for helping us and sorry for bothering with a problem on our side.

**Comment by withintheruins14** [comment]
you used `redirectUri` when the docs say `redirect_uri ` @jBenes

**Comment by jBenes** [comment]
Yes, I missed that. Thanks!
