### ISSUE TITLE
Multiple authorize calls via loginWithRedirect and reponse failure

### ISSUE THREAD

**Issue by withintheruins14** [auth0/auth0-react#526]
Multiple authorize calls via `loginWithRedirect` and response failure

Now using the 2.0 package, but this was happening for some time before (about a month). Nothing had changed in our client code and suddenly 4 calls to authorize endpoint would go out after successfully passing the login screen. Then it goes away for a good chunk of the day. Then it comes back. I don't have much guess - the first thing I tried was upgrading and that fixed it for a while. Now it's back

<img width="1189" alt="Screen Shot 2023-04-03 at 12 16 34 PM" src="https://user-images.githubusercontent.com/2576699/229582179-cb207ff3-3dd3-4142-abab-748561660934.png">

I've prepared a har file: https://www.dropbox.com/s/z2ojf2tnfx4pjcu/authorize_har.har?dl=0

**Comment by douglasgomes98** [comment]
@withintheruins14 found a solution?
