### ISSUE TITLE
withAuthenticationRequired on Routes Leads to Blank Page After Login

### ISSUE THREAD

**Issue by hikarukujo** [auth0/auth0-react#53]
### Description

We've recently deployed our first Auth0-enabled React app and I used the withAuthenticationRequired method in auth-react to protect two of our routes in our primary application. When you first load the app on a computer with cache cleared (or which has never logged in before), it will follow to the login page properly and process the login properly, then dump you back to the skeleton of the site with no content in the render area. Pressing F5 will load the page as expected after that point. It never has the error again once you're logged in.

### Reproduction

Our index.js calls the plugin and then renders with ReactDom and BrowserRouter statements:
```
import { Auth0Provider } from "@auth0/auth0-react";

ReactDOM.render(
  <Auth0Provider
    domain="REDACTED"
    clientId="REDACTED"
    redirectUri={window.location.origin}
  >
	  <BrowserRouter>
	      <App />
	      <Spinner />
	  </BrowserRouter>
  </Auth0Provider>,
  document.getElementById('root')
);
```

Then, the primary app's js file will route the endpoints for both primary functions of the app:
```
  render() {
    return (
      <div className="App">
        <header>
          <div id="logo">
            <span className="icon"></span>
            <span>REDACTED APP NAME</span>
          </div>
        </header>
        <main>
          <Switch>
            <Route exact path="/related_orders/:orderId" location={this.props.location} render={props => <OrderList {...props} sendOrderInfoToParent={this.setOrderInfo} sendCustInfoToParent={this.setCustInfo}/>}>
            </Route>
            <Route path="/calendar">
              <Calendar ordersFromParent={this.state.orders} custInfoFromParent={this.state.custInfo}/>
            </Route>
          </Switch>
        </main>
      </div>
    );
  }
}
```

Inside of each path, I've enclosed the export default statement with the withAuthenticationRequired statements as so:
```
export default withAuthenticationRequired(Calendar, {
    // Show a message while the user waits to be redirected to the login page.
    onRedirecting: () => <h2 align="center" style={{ color: 'white' }}>One moment, please.</h2>,
});
```

Still, each time I use a private window or clear my cache, I get the login process until it redirects back and then just sits at a skeleton page with nothing in the render zone:
<img width="2672" alt="Screenshot 2020-06-30 20 23 28" src="https://user-images.githubusercontent.com/5297911/86192616-9cee7c00-bb0f-11ea-8018-6dfb8cb79d9f.png">

If I press F5, the app renders properly:
<img width="1716" alt="Screenshot 2020-06-30 20 25 00" src="https://user-images.githubusercontent.com/5297911/86192700-c8716680-bb0f-11ea-9e56-7c1b49d06263.png">

### Environment

We're running in a Docker image in Kubernetes, base image is node:alpine.

Relevant Plugins:
auth0-react v1.0.0
react v16.11.0
react-dom v16.13.1
react-router-dom v5.2.0

Clients Tested (Same browsers on all 4 platforms):
- Windows 10 1909
- Windows 10 2004
- Mac OS X 10.15.5
- Mac OS X 10.15.3
- Chrome 83.0.4103.116
- Firefox 77.0.1 (64-bit)

Package.json Dependencies:
    "@auth0/auth0-react": "^1.0.0",
    "@fortawesome/fontawesome-svg-core": "^1.2.28",
    "@fortawesome/free-solid-svg-icons": "^5.13.0",
    "@fortawesome/react-fontawesome": "^0.1.9",
    "@material-ui/core": "^4.9.14",
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.5.0",
    "@testing-library/user-event": "^7.2.1",
    "axios": "^0.19.2",
    "cors": "^2.8.5",
    "date-fns": "^2.12.0",
    "express": "^4.17.1",
    "express-jwt": "^5.3.3",
    "http": "0.0.1-security",
    "jwks-rsa": "^1.8.1",
    "logkitty": "^0.7.1",
    "mobx": "^5.15.4",
    "mobx-react": "^6.2.2",
    "mobx-react-lite": "^2.0.7",
    "popper.js": "^1.16.1",
    "prop-types": "^15.7.2",
    "react": "^16.11.0",
    "react-bootstrap": "^1.0.1",
    "react-bootstrap-table-next": "^4.0.2",
    "react-bootstrap-table2-editor": "^1.4.0",
    "react-calendar": "^3.1.0",
    "react-dom": "^16.13.1",
    "react-loader-spinner": "^3.1.14",
    "react-native": "^0.62.2",
    "react-promise-tracker": "^2.1.0",
    "react-router-dom": "^5.2.0",
    "react-scripts": "3.4.1",
    "react-select": "^3.1.0",
    "react-spinners-kit": "^1.9.1",
    "react-table": "^7.0.4",
    "react-time-picker": "^4.0.1",
    "socket.io": "^2.3.0",
    "time-number": "^1.1.0",
    "websockets": "^0.2.0"

**Comment by adamjmcgrath** [comment]
Hi @hikarukujo 

When using javascript routers (eg react-router, reach router, etc) you need to write your own `onRedirectCallback` to handle the redirect after login, because each router does redirects differently.

Take a look at our react-router example https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#1-protecting-a-route-in-a-react-router-dom-app

Essentially, you want to change your snippet to something like:

```
import { Auth0Provider } from "@auth0/auth0-react";
// When using custom history module, use "Router" not "BrowserRouter"
import { Router } from 'react-router-dom';

// Use a custom history module to access history outside of a component
const history = createBrowserHistory();

const onRedirectCallback = (appState) => {
  // Use the router's history module to replace the url
  history.replace(appState?.returnTo || window.location.pathname);
};

ReactDOM.render(
  <Auth0Provider
    domain="REDACTED"
    clientId="REDACTED"
    redirectUri={window.location.origin}
  >
            {/* Don't forget to add the history to your router */}
	   <Router history={history}>
	      <App />
	      <Spinner />
	  </Router>
  </Auth0Provider>,
  document.getElementById('root')
);
```

**Comment by adamjmcgrath** [comment]
@hikarukujo - let me know if that suggestion fixes the issue for you

**Comment by adamjmcgrath** [comment]
I'm going to go ahead and close this issue, feel free to reopen if you're still running into problems
