### ISSUE TITLE
Richer token data required in getTokenSilently response 

### ISSUE THREAD

**Issue by ledger32570** [auth0/auth0-react#533]
### The problem

We are building an application that contains highly sensitive financial information. As a consequence of this, we have extremely high-security standards. These high-security standards present some interesting UX challenges that are impossible to solve with the limited information we get back from the `getTokenSilently` request and lack of ability to check a session without extending it. For context, our Auth0 token set up looks like this:

- Rotating refresh tokens
- 1 min expiry on the _access token_
- 10 min **_inactivity_** expiry on the _refresh token_
- 60 min **_absolute_** expiry on the _refresh token_

### Requirements:
- MUST present the user a prompt any time they are nearing the point of ABSOLUTE EXPIRY. 
- MUST immediately blur the screen and present a prompt to the user when the INACTIVITY EXPIRY is met
- Solution must work across multiple tabs

### Proposal: 

**New Function** 

Provide a new function `checkSession` that returns `valid | reached_inactivity_expiry | reached_absolute_expiry`
This new function should NOT extend the session in any way (like getTokenSilently does). This would allow me to periodically check the session without extending it. 

**Enhance token/getTokenSilently response**
- Add `absolute_exp` to getTokenSilently response. This should be a timestamp of the future date/time that the refresh token will absolutely expire. This will enable us to present a prompt to the user X minutes before absolute expiry. 

The combination of these two enhancements would give us a lot of options to play with when communicating session information to our users. `

**Comment by frederikprijck** [comment]
Thanks for reaching out. Once our SDK receives a Refresh Token, there is no way for us to periodically check any of those expiries. The only way we know if it's still valid, is by sending it to Auth0 to refresh the tokens, which doesn't look like what you want.

I would recommend providing product feedback for this on https://auth0.com/feedback, as we can not do anything from the SDK perspective if the server does not give us such information.

The only thing I can recommend for now is to build something for this in your own application.

One additional question I have is to try and understand why you use Refresh Tokens. Would you be able to drop using them, and rely on the Auth0 session instead?

**Comment by ledger32570** [comment]
Thanks for the response. We opted for refresh tokens to benefit from the security benefits brought about by having a shorter-lived access token. Would be keen to learn how to achieve high security using the Auth0 session instead.  Can you share more information?

**Comment by frederikprijck** [comment]
You can still have a short lived access token without refresh tokens. The idea is the same, once it's expired the SDk will refresh it in one of these two ways when calling getTokenSilently:

- when using refresh tokens, it calls oauth/token with the refresh token
- when not using refresh tokens, it uses an iframe to navigate to auth0's /authorize endpoint and rely on the exitence of the cookie over their.

In both situations, it will return a new access token. From the users perspective, the behavior should be identical as the above is all things under the hood that you do not need to do anything for, expect enabling/disabling refresh tokens.

**Comment by frederikprijck** [comment]
Closing as I think this was anwsered. Happy to reopen if not.
