### ISSUE TITLE
Should we `await` when calling the "loginWithRedirect" function on button click?

### ISSUE THREAD

**Issue by vanuverma** [auth0/auth0-react#535]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem

***** This is more of a clarification question and based on the answer provided, can be treated as an issue *****

I am using the "auth0-react" package inside my react app and while following this guide here https://auth0.com/docs/quickstart/spa/react/interactive#add-login-to-your-application I noticed that the `loginWithRedirect` function is not `awaited`.
However, according to this document, https://github.com/auth0/auth0-react/blob/e69387d6481ff16293b9907ac4484fe10a17c746/src/auth0-context.tsx#L97, the `loginWithRedirect` function returns a `Promise<void>`.

My question is whether the `loginWithRedirect` function needs to be `awaited` or not, and if NOT, what is the reason?

### Environment

> Please provide the following:

- **Version of `auth0-react` used:*2.0.2*
- **Which browsers have you tested in?*Chrome*
- **Which framework are you using, if applicable (Angular, React, etc):*React*
- **Other modules/plugins/libraries that might be involved:**

**Comment by frederikprijck** [comment]
Hello.

Calling `loginWithRedirect` will redirect away. it returns a promise because it uses async functions internally. You can await it, but there is no strict need because in that example, there is nothing after calling `loginWithRedirect`.

If you'd have the following code:

```ts
await loginWithRedirect({openUrl: () => { ... }});
callAFunctionThatDoesSomethingElse();
```
In the above you do need to await, because you are doing something else after calling loginWithRedirect. But typical applications do not do that and should only call `loginWithRedirect`, as we know that will result in closing your current app.

Hopefully this helps.

**Comment by vanuverma** [comment]
Hi @frederikprijck thanks for your feedback. 
In my react app, if I was not using the `async...await` approach to call the `loginWithRedirect` function, then after successful login with Auth0, the `logout` endpoint was triggered immediately even without clicking on the `logout` button. 
But, once I added the `async...await` for `loginWithRedirect` function, this issue stopped happening. I can confirm that the Auth0 settings were not updated between these code changes.

Can you please provide some suggestions on why this could be happening?

PS: 
I am trying to store the authenticated user info into React Context so that my child components can only refer to React context and do not require to import `@auth0/auth0-react` in each of them.

**Comment by frederikprijck** [comment]
I dont see how the login and logout functions are related in such a way that not awaiting login would call logout.

Can you please provide some code to look into so I can try and identify how you can avoid that?

> I am trying to store the authenticated user info into React Context 

Keep in mind we already store it in React Context for you.
