### ISSUE TITLE
Using Auth with class components

### ISSUE THREAD

**Issue by agaace** [auth0/auth0-react#54]
There's very scarce documentation on how to use this library with class components. I found this example:

```javascript
import React, { Component } from 'react';
import { withAuth0 } from '@auth0/auth0-react';

class Profile extends Component {
  render() {
    const { user } = this.props.auth0;
    return <div>Hello {user.name}</div>;
  }
}

export default withAuth0(Profile);
```

Now I want to achieve something like this:

```javascript
import React, { Component } from 'react';
import { withAuth0 } from '@auth0/auth0-react';

class Profile extends Component {
  render() {
    const { user } = this.props.auth0;
    const isAuthenticated = ??? // <---- how do I get this value?
    return isAuthenticated ? renderAuthenticatedUser(user) : renderUnauthenticatedUser();
  }
}

export default withAuth0(Profile);
```

How do I do this? I've been reading through the docs and scratching my head for quite a while..

**Comment by adamjmcgrath** [comment]
Hi @agaace - thanks for raising this

`this.props.auth0` has all the same properties (auth state and auth methods) that the `useAuth0` hook has. so you can use it to get the `isAuthenticated` property:

```js
import React, { Component } from 'react';
import { withAuth0 } from '@auth0/auth0-react';

class Profile extends Component {
  render() {
    const { user, isAuthenticated } = this.props.auth0;
    return isAuthenticated ? renderAuthenticatedUser(user) : renderUnauthenticatedUser();
  }
}

export default withAuth0(Profile);
```

Let me make a change to the docs that should make this a bit clearer

**Comment by agaace** [comment]
Your solution is not working for me. IsAuthenticated is ALWAYS false and it never changes to true. There's never any lifecycle event that would update this value (I tried componentDidUpdate, willReceiveProps and the new combo that's in place of the deprecated willReceiveProps). Any ideas how to listen for updates?

**Comment by adamjmcgrath** [comment]
Hi @agaace - are you still seeing this issue? I wasn't sure from you're [other comment](https://github.com/auth0/auth0-react/issues/59#issue-651016375) whether you'd resolved this or not

**Comment by Cammac7** [comment]
sorry to raise a closed ticket, but how does one go about getting the user's token (ie the 'getAccessTokenSilently' flow) when using a class component? I'm running into the same issues of difficulty when not using hooks.

**Comment by adamjmcgrath** [comment]
@Cammac7 

```js
import React, { Component } from 'react';
import { withAuth0 } from '@auth0/auth0-react';

class Products extends Component {
  componentDidMount() {
    const { getAccessTokenSilently } = this.props.auth0;
    getAccessTokenSilently().
      .then(token => fetch(`https://my-api.com/products`, { headers: authorization: `Bearer ${token}` }))
      .then(res => res.json())
      .then(json => this.setState({ data: json }));
    ...
  }
}

export default withAuth0(Products);
```

**Comment by Cammac7** [comment]
Thank you so much!

**Comment by jo3n** [comment]
> Hi @agaace - are you still seeing this issue? I wasn't sure from you're [other comment](https://github.com/auth0/auth0-react/issues/59#issue-651016375) whether you'd resolved this or not

Hi @adamjmcgrath, I'm actually running into this myself where ```this.props.auth0``` doesn't update. Is this expected behaviors or is there another way to retrieve the updated authenticated state through another function call?
