### ISSUE TITLE
Unhandled exception when cookies are disabled

### ISSUE THREAD

**Issue by ryan-nauman** [auth0/auth0-react#540]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I expect the `<Auth0Provider />` to provide a way to deal with users who have cookies disabled. For these users the following exception is thrown:

`DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document`

Is there a way for this to work or do I simply need to handle the exception myself? Am I overlooking anything?

### Reproduction

1. Run the auth0-react sample app
2. Disable cookies in chrome
3. Reload the page

![exception](https://github.com/auth0/auth0-react/assets/994384/edfefc26-64d8-4f2a-9972-e47c1ce1193b)

### Additional context

Happens in both chrome & mobile safari.

### auth0-react version

1.1.2 & 2.1.0

### React version

17 & 18

### Which browsers have you tested in?

Chrome, Other

**Comment by frederikprijck** [comment]
Closing as I believe your question was answered and there isn't much we can do from the SDK side.

Happy to continue the conversation as needed.

**Comment by ryan-nauman** [comment]
@frederikprijck thank you for getting back to me! I agree with the flow & the need to use session storage. However, I don't agree with the component throwing a DOMException. At the least I would expect a custom exception than can be guarded against. Ideally I would expect a property allowing a developer to have a fallback scenario. 

With the component in its current state I am forced to either:

1.  wrap the `<Auth0Provider />` component with an error boundary. bad: app is unusable as everthing is a child of the provider
2. check for the exception myself and conditionally include `<Auth0Provider />` using my own component, e.g.:
```
export const MyAuthProvider = ({ children }) => {
  try {
    // trying to reference sessionStorage at all with cookies disabled throws this error:
    // DOMException: Failed to read the 'sessionStorage' property from 'Window': Access is denied for this document.
    iBlewUp = typeof sessionStorage;
    return (
      <Auth0Provider
        domain={process.env.REACT_APP_AUTH0_DOMAIN}
        clientId={process.env.REACT_APP_AUTH0_CLIENT_ID}
        audience={process.env.REACT_APP_AUTH0_AUDIENCE}
        redirectUri={window.location.origin}
        onRedirectCallback={onRedirectCallback}
        scope="read:current_user update:current_user_metadata"
        // cacheLocation="localstorage"
        useRefreshTokens
      >
        {children}
      </Auth0Provider>
    );
  } catch (error) {
    console.log('guess what, i blew up', iBlewUp, error);
    return children;
  }
}
```

**Comment by frederikprijck** [comment]
> At the least I would expect a custom exception than can be guarded against

Why can't you guard against the DOMException? I mean, we can catch the DOMException and throw something else. But what's stopping you from doing that yourself? Our SDK isn't usable without that at all. So we would be adding code only to accomodate for scenario's that are expected to not work in the first place. So I am trying to understand what justifies that.

> Ideally I would expect a property allowing a developer to have a fallback scenario.

Could you elaborate what fallback you have in mind?

**Comment by ryan-nauman** [comment]
The con with guarding against DOMException is that if the underlying mechanisms change (e.g., session storage vs. something else) then I am at the mercy of guarding black boxed code and playing cat & mouse. Although this may be a moot point as I cannot render `<Auth0Provider />` without an error boundary or manual exception checking as shown above. The fallback scenarios are the only clean path forward.

Fallback scenarios could be:

* a boolean property such as **suppressErrors** which renders the children even if there was a problem
* a function property such as **onError** which is called when there's a problem that lets me act on it (telemetry or other)

These fallback scenarios would allow for unauthenticated users to interact vs. the entire application being unusable.

**Comment by frederikprijck** [comment]
Fair point, I will get this fixed and ensure we improve this.

**Comment by frederikprijck** [comment]
We cut a new release that ensures the Auth0Provider doesn't throw that error anymore.
We didnt change anything about the DOMException, but we did ensure the Auth0Provider can render properly instead of error in the case when cookies are disabled.

This wont make the SDK usable without cookies and site-data, but it should render properly now and propagate errors through the error property we have on our state.

Can you try it out and let us know?

**Comment by ryan-nauman** [comment]
This work's much better for us now. I can monitor `{ error } = useAuth0();` as well as catch via `loginWithRedirect({...}).catch()`

Thank you!
