### ISSUE TITLE
Using useRefreshTokens=true doesn't allow for getAccessTokenSilently to return updated scope

### ISSUE THREAD

**Issue by daralthus** [auth0/auth0-react#541]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

If a user gets new permissions assigned I should be able to call `getAccessTokenSilently` (with `cacheMode="off"`) to get an updated access_token with the new scope.

It seems like this works only if `useRefreshTokens=false` Then the request is made with `grant_type: authorization_code` and the new token is returned with the updated scope as expected.

If I have `useRefreshTokens=true` the call uses `grant_type: refresh_token` and the returned token's scope stays the same, leaving out any of the updates that happened in the meantime to the user's permissions.

While there is documentation on useRefreshTokens: calls in iframes, etc., this particular difference seems to be undocumented and might be a bug. If it's not a bug an option to call getAccessTokenSilently with the fallback request would be preferable than having to completely turn off the refresh_token rotation mechanism.

(I understand it is possible to achieve the same with `getAccessTokenWithPopup`, but I would prefer not to ruin UX for a first-party app and it seems it's possible to achieve this with `getAccessTokenSilently` too.)

### Reproduction

1. Setup 
```jsx
<Auth0Provider authorizationParams={{ audience: process.env.audience, scope: "admin" }} useRefreshTokens={true} useRefreshTokensFallback={true} >
```
2. Sign up with a new user. At this point this user has no roles or permissions.
3. Call 
```js
const { scope } = await getAccessTokenSilently({
  detailedResponse: true,
  cacheMode: "off",
  authorizationParams: {
    audience: process.env.audience,
    scope: "admin",
  },
})
```
4. NOTE: scope has `admin` missing as expected.
5. Add the `admin` permission to the user for the audience.
6. Re-run the call from step 3.
7. NOTE: the scope is still missing `admin`, this is unexpected.
8. Update `Auth0Provider` with `useRefreshTokens={false}`
9. Re-run the call from step 3.
10. NOTE: the scope now includes `admin`

### auth0-react version

3.0.1

### React version

18.2.0

### Which browsers have you tested in?

Chrome, Safari

**Comment by frederikprijck** [comment]
Hey,

Our SDK does not support that when using refresh tokens.

Can you set `useRefreshTokensFallback` to true, that should allow for what you want, but using iframes.

Let me know if that does not help.

**Comment by daralthus** [comment]
Thanks for the suggestion! 

I did try that before making this issue: The fallback does not get triggered as the usual call with refresh_token grant type returns fine. It's just that the API doesn't return an up to date scope in the new token. It does that only for calls with authorization_code grant type.

Is there a way to force the fallback call somehow?

**Comment by frederikprijck** [comment]
Thanks for that info. I think i see the problem now.

Will look into and see what can be done.

**Comment by frederikprijck** [comment]
Thanks, having talked about this internally, there isn't much we can do.

A user is expected to give consent in quite some situations before an application can use a newly assigned scope.

When you request the `ADMIN` scope, but the user has no `ADMIN` scope, no consent will be asked for this scope.
Once you ensure the user has the `ADMIN` scope, and you re-request the `ADMIN` scope, the user might need to give consent for this scope before being able to use it.

This can only be done through `loginWithRedirect` or `loginWithPopup`.

Therefore, it's advised to call `loginWithRedirect` or `loginWithPopup` in situations where this kind of things have changed. The user is then prompted for consent as needed, and the tokens will include the correct scope. If no consent is needed, the user is not prompted for anything and will instantly end back in your application, with tokens using the `ADMIN` scope.

Doing this silently might work in some situations, but a lot situations will require the above consent so it's advices to use `loginWith*` to handle this.
