### ISSUE TITLE
Cannot login with difference account

### ISSUE THREAD

**Issue by de2dhvu1** [auth0/auth0-react#542]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

For old version 1.12.0 can choose account to login with this code `loginWithRedirect({ prompt: "login" })`
But the new version 2.1.0 `prompt` not found

### Describe the ideal solution

Give me a solution

### Alternatives and current workarounds

..

### Additional context

,,,,

**Comment by frederikprijck** [comment]
Thanks for reaching out. For v2, you want:

```
loginWithRedirect({
  authorizationParams: {
    prompt: 'login'
  }
})
```

See: https://auth0.github.io/auth0-react/interfaces/AuthorizationParams.html#prompt
