### ISSUE TITLE
Typescript typing inconsistencies for the logout function

### ISSUE THREAD

**Issue by Mgrdich** [auth0/auth0-react#545]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/master/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

https://github.com/auth0/auth0-react/blob/bcfd2199b616ca50c20c2701acbd6e7e2e06f92b/src/auth0-provider.tsx#L199-L200

logout here is a promise , while when we use the hook to retrieve it is not typed as such , and we will end up with type inconsistencies

https://github.com/auth0/auth0-react/blob/bcfd2199b616ca50c20c2701acbd6e7e2e06f92b/src/auth0-context.tsx#L130

why they are different is it intentional ?

### Reproduction

1. Check the interface typing
2. Check the code that is run with the actual provider

### auth0-react version

2.1.0 

### React version

18.2.0

### Which browsers have you tested in?

Other

**Comment by frederikprijck** [comment]
Thanks, I opened a PR to address this.
