### ISSUE TITLE
Error:  Invalid parameter: client_id must be a string

### ISSUE THREAD

**Issue by nairsandeep** [auth0/auth0-react#56]
### Hello, 

I have been using the **react-auth0-spa** as per the quicks start documentation. I am trying to change over to the @auth0/auth0-react. 

I have installed the rpm package and made the code modification for the switch over, but I am getting an error stating  **_'Error:  Invalid parameter: client_id must be a string'._** 

Here is my piece of code 

import { Auth0Provider } from '@auth0/auth0-react';
import config from './auth_config.json';

app.js

`ReactDOM.render(
    <Auth0Provider
        domain={config.domain}
        client_id={config.clientId}
        redirect_uri={window.location.origin}
        onRedirectCallback={onRedirectCallback}>
        <Provider store={configureStore()}>
            <App />
        </Provider>
    </Auth0Provider>,
    document.getElementById('root')
);`

config.json
{
    "domain": "dev-[].auth0.com",
    "clientId": "--------------------"
}

thanks in advance

**Comment by adamjmcgrath** [comment]
Hi @nairsandeep - thanks for raising this issue

> `client_id={config.clientId} redirect_uri={window.location.origin}`

`Auth0Provider` expects `clientId` and `redirectUri` so your app.js should be:

```js
ReactDOM.render(
  <Auth0Provider
    domain={config.domain}
    clientId={config.clientId}
    redirectUri={window.location.origin}
    onRedirectCallback={onRedirectCallback}>
      <Provider store={configureStore()}>
        <App />
      </Provider>
  </Auth0Provider>,
  document.getElementById('root')
);
```

There shouldn't be any docs that state `client_id`, I've checked the quickstart, let me know if there are any I'm not aware of.

**Comment by nairsandeep** [comment]
Hello, @adamjmcgrath thank you for the response. My code was based on the old quick start ( using the react-auth0-spa.js); I have made the correction and the issue is resolved. 

One quick question, previously the onRedirectCallback was 
`const onRedirectCallback = (appState) => {
    history.push(appState && appState.targetUrl ? appState.targetUrl : window.location.pathname);
};`

but on the current quick start, there is no such prop given for the Auth0Provider. Should I use it?

**Comment by adamjmcgrath** [comment]
Thanks for letting me know @nairsandeep 

The default `onRedirectCallback` is fine if you don't have a JavaScript router, but you'll need to pass in your own if you're using a custom JavaScript router, we have examples for [react-router](https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#1-protecting-a-route-in-a-react-router-dom-app), [Gatsby](https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#2-protecting-a-route-in-a-gatsby-app) and [Next.js](https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#3-protecting-a-route-in-a-nextjs-app-in-spa-mode)

**Comment by nairsandeep** [comment]
Thanks a lot @adamjmcgrath
