### ISSUE TITLE
How do I use the react library to display the sign up page?

### ISSUE THREAD

**Issue by agaace** [auth0/auth0-react#59]
Hello, I have login and logout buttons working. Now I'd like to have a signup button but I can't find my way through documentation to do so.

**Comment by adamjmcgrath** [comment]
Hi @agaace 

auth0-react uses the Universal Login Page https://auth0.com/docs/universal-login

If you're using the new universal login page, you can pass `screen_hint=signup` as an additional parameter to your login, eg:

```js
const { loginWithRedirect } = useAuth0();
const login = () => loginWithRedirect();
const signUp = () => loginWithRedirect({ screen_hint: 'signup' });
```

If you're using the classic login page https://auth0.com/docs/universal-login/classic it's more involved. You pass an extra parameter to the authorize server through `loginWithRedirect`, again eg:

```js
const signUp = () => loginWithRedirect({ initialScreen: 'signUp' });
```

Then customise the Universal Login Page in your Auth0 dashboard to pick up this parameter in `config.extraParams` and pass it to `Auth0Lock`, (see https://auth0.com/docs/libraries/lock/v11/configuration#initialscreen-string-) eg:

```js
var lock = new Auth0Lock(config.clientID, config.auth0Domain, {
  (...)
  initialScreen: config.extraParams.initialScreen,
  (...)
});
```

More info here:
https://community.auth0.com/t/how-to-redirect-user-to-hosted-signup-page/9482/2

**Comment by adamjmcgrath** [comment]
Hi @agaace - closing this, feel free to reopen if my suggestion doesn't work for you or you have any other questions

**Comment by agaace** [comment]
@adamjmcgrath Thank you for detailed instructions, very helpful!
The problem I have now is that when I do this
```js
const signUp = () => loginWithRedirect({ screen_hint: 'signup' });
```

When I click the button, I don't get redirected to a sign up page. I get an error saying signing up is disabled. Is it disabled by default for a newly created app? How do I enable it? I don't seem to be able to find this option anywhere in the dashboard.

**Comment by agaace** [comment]
Ahhh, never mind. Turns out signing up is enabled at the connection level, not application level. Working like a charm now, thank you!

**Comment by simonv3** [comment]
I'm getting this error as well, though I want people to be able to log in and not sign up. 

I followed the directions here: 

https://auth0.com/blog/complete-guide-to-react-user-authentication/

And the pages captured by the private route redirect to the login page (so they use the `withAuthenticationRequired`, but clicking on the log in button now shows the error message above. 

I would comment or look in the blog post comments, but those aren't loading :/

**Comment by underbluewaters** [comment]
I just wanted to flag that this is not included in the API documentation, or typescript defs. I was about to file a new ticket before I found this post.

**Comment by frederikprijck** [comment]
@coreyward yes, this is since v2. See https://github.com/auth0/auth0-react/blob/master/MIGRATION_GUIDE.md#introduction-of-authorizationparams

**Comment by ferrjohnpainagan** [comment]
for` "@auth0/auth0-react": "^2.2.1",` the code below doesnt work

i have a custom login experience setup

`const signUp = () => loginWithRedirect({ initialScreen: 'signUp' });`

**Comment by frederikprijck** [comment]
If you want custom parameters to be send to auth0, pass them as properties on authorizationParams.

**Comment by ferrjohnpainagan** [comment]
this is how i did it but it doesnt work

it still loads the login page, im using `custom login experience`
```
onClick={() =>
                    loginWithRedirect({
                      authorizationParams: {
                        screen_hint: 'signup',
                      },
                    })
                  }
```

**Comment by frederikprijck** [comment]
Let's keep the communication in https://github.com/auth0/auth0-react/issues/571.
