### ISSUE TITLE
Organization name still not supported 2.2.1

### ISSUE THREAD

**Issue by weisssean** [auth0/auth0-react#590]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

We are using v2.2.1 and organization name still does not seem to be supported although the documentation says it does. 

When using the organization ID everything works, but when using the organization name it's returning invalid request:
`http://localhost:3000/?error=invalid_request&error_description=authorization%20request%20parameter%20organization%20must%20be%20an%20organization%20id&state=T1N2Q3BSdi1wT1YwU1RjZGRRUWxadEhpVFVyMEppSDlqUGpZQVFmRTBMUg%3D%3D`

### Reproduction

Build a sample app:

<Auth0Provider
    domain="yourclient.auth0.com"
    clientId="<yourclient>"
    authorizationParams={{
      organization: "<name>",
      redirectUri: window.location.origin,
    }}
    <React.StrictMode>
      <App />
    </React.StrictMode>
  </Auth0Provider>

Expected result: shows a popup for the organization
result: 
`http://localhost:3000/?error=invalid_request&error_description=authorization%20request%20parameter%20organization%20must%20be%20an%20organization%20id&state=T1N2Q3BSdi1wT1YwU1RjZGRRUWxadEhpVFVyMEppSDlqUGpZQVFmRTBMUg%3D%3D`

### auth0-react version

2.2.1

### React version

18.2.0

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
It looks like auth0 is returning an error indicating it expects an id. That means your tenant isnt configured to accept organization names, and isn't something we can solve on the SDK side.

Can you try ensuring that's enabled and try again?

**Comment by weisssean** [comment]
Not a bug: I found my issue, in your tenant advanced settings you need to enable this option. It will save a lot of people a lot of time if you add it to the documentation as it is required for this to work.
