### ISSUE TITLE
Login required new oAuth erro?

### ISSUE THREAD

**Issue by joshisplutar** [auth0/auth0-react#62]
Hi, I’m using the auth0 React SDK and trying to make posts to a rails api that has been set up with the auth0 quickstart. When I try to post in the react front end I get a console error in Chrome like so:

Error: Login required
at new OAuthError (errors.tsx:8)
at utils.tsx:17
at utils.tsx:39
at step (0.chunk.js:210)
at Object.throw (0.chunk.js:141)
at rejected (0.chunk.js:103)

I am logged in when I get this error. Also I’m able to make posts to the api if I use the token in the test tab of the dashboard for the rails api. I’m following along with the example listed in “Call an API” at this link https://auth0.com/docs/libraries/auth0-react 1

**Comment by maxpaj** [comment]
I am getting this also, quite unexpected.

**Comment by adamjmcgrath** [comment]
@joshisplutar can you check if @maxpaj's suggestion works for you

If not, do you have code or a running app I can look at to help you debug the issue?

**Comment by joshisplutar** [comment]
I mentioned I was logged in when getting this error. I've isolated the issue for you in a branch of this repo: https://github.com/joshisplutar/tippingpoint/tree/auth0

You'll notice in the LogOutButton component I'm trying to console.log a token just to see if I even get anything but you will immediatly get the Oath error in the console and the app will break. 


import React from "react";
import { useAuth0 } from "@auth0/auth0-react";

const LogoutButton = () => {
  const { isAuthenticated, logout, getAccessTokenSilently } = useAuth0();
  if (isAuthenticated){
    var token = getAccessTokenSilently({
    audience: 'https://quickstarts/api',
    scope: 'create:locations'
  })
  console.log(token)
}

  return (
  isAuthenticated && (
    <button onClick={() => logout()}>Log Out</button>
  )
  )
};

export default LogoutButton;

**Comment by adamjmcgrath** [comment]
Hi @joshisplutar 

`getAccessTokenSilently` returns a promise, so you'll want to `await` the result. You'll also want to use a `useEffect` hook if you're kicking off an async request from your component's render.

```js
const LogoutButton = () => {
  const { isAuthenticated, logout, getAccessTokenSilently } = useAuth0();
  useEffect(() => {
    (async () => {
      if (isAuthenticated) {
        const token = await getAccessTokenSilently({
          audience: 'https://quickstarts/api',
          scope: 'create:locations',
        });
        console.log(token);
      }
    })();
  }, [isAuthenticated]);
  return isAuthenticated && <button onClick={() => logout()}>Log Out</button>;
};
```

**Comment by joshisplutar** [comment]
@adamjmcgrath thanks for the refactore. I'm still learning :)

Using your code I still get the error though. In the console I'm getting:

Uncaught (in promise) Error: Login required
    at new OAuthError (errors.tsx:8)
    at utils.tsx:17
    at utils.tsx:39
    at step (RenderPromises.ts:98)
    at Object.throw (RenderPromises.ts:98)
    at rejected (RenderPromises.ts:98)

and in the browser window it says:

Unhandled Rejection (Error): Login required
new OAuthError
C:/Users/josh.wren/code/src/errors.tsx:8
   5 |  * See: https://openid.net/specs/openid-connect-core-1_0.html#rfc.section.3.1.2.6
   6 |  */
   7 | export class OAuthError extends Error {
>  8 |   constructor(public error: string, public error_description?: string) {
   9 |     super(error_description || error);
  10 |   }
  11 | }
View compiled
(anonymous function)
C:/Users/josh.wren/code/src/utils.tsx:17
  14 |   error: Error | { error: string; error_description?: string } | ProgressEvent
  15 | ): Error => {
  16 |   if ('error' in error) {
> 17 |     return new OAuthError(error.error, error.error_description);
  18 |   }
  19 |   if (error instanceof Error) {
  20 |     return error;
View compiled
(anonymous function)
C:/Users/josh.wren/code/src/utils.tsx:39
  36 |   try {
  37 |     return await getTokenFn(opts);
  38 |   } catch (error) {
> 39 |     throw tokenError(error);
  40 |   }
  41 | };
  42 |

**Comment by adamjmcgrath** [comment]
@joshisplutar Make sure that you login (by calling `loginWithRedirect`)

If you're still having issues, please share the running app or code and I'll take a look

**Comment by joshisplutar** [comment]
It works now. I had the wrong audience value. My mistake. Thanks for the help.

**Comment by adamjmcgrath** [comment]
Great - thanks for letting me know @joshisplutar
