### ISSUE TITLE
Error: Invalid state

### ISSUE THREAD

**Issue by hornta** [auth0/auth0-react#620]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I'm getting this error in the browser when I perform a page refresh in the middle of the login operation and I wish it could be more smoothly handled by this package.

The error is described here as well: https://community.auth0.com/t/invalid-state-on-reload-auth0-callback-url-using-auth0-spa-js-and-angular-8/36469/10

```
Error: Invalid state
    at te.handleRedirectCallback (auth0-spa-js.production.esm.js:1:31386)
    at auth0-provider.tsx:158:45
    at step (@auth0_auth0-react.js?v=7476f1c7:144:19)
    at Object.next (@auth0_auth0-react.js?v=7476f1c7:91:14)
    at @auth0_auth0-react.js?v=7476f1c7:77:67
    at new Promise (<anonymous>)
    at __awaiter (@auth0_auth0-react.js?v=7476f1c7:59:10)
    at auth0-provider.tsx:154:6
    at auth0-provider.tsx:169:6
    at commitHookEffectListMount (react-dom.development.js:23150:26)
```

### Reproduction

I'm not able to consistently get this error because I have to be quite precise I think in where the page gets refreshed, but some time in the login flow when I reload the page I'm ending up on my website url with both a state and code query parameter like so: `http://localhost:3000/?code=abc&state=123` and my users are unable to recover form this without having to remove these from the URL.

I'm able to reproduce the error on the sample app:
![image](https://github.com/auth0/auth0-react/assets/4553604/14cf8748-d2d5-4ef8-9546-51f6d69a13e9)
`http://localhost:3000/?code=WQsZ2RY9cOMHObLLtbE61Q9HQtJZJHumo2anpv5NIy8f8&state=Y1VrbnVtfjB4cHl%2BNUZGZDFYcWNRS0w0dTd3S0JMMGNnaUI1RmNISlI3Sg%3D%3D`

### auth0-react version

2.2.1

### React version

18.2.0

### Which browsers have you tested in?

Chrome

**Comment by adamjmcgrath** [comment]
Hi @hornta - thanks for raising this

I don't think there's much the SDK can do here - if we deleted the cookie after the code exchange you'd only get invalid grant errors from the `/oauth/token` endpoint for reusing the code (which would be worse IMO)

> my users are unable to recover form this without having to remove these from the URL.

You can prompt the user to login again (or use silent auth (getAccessTokenSilently)) and since you have an existing session, the user will be seamlessly logged in.

**Comment by hornta** [comment]
Alright, I ended up checking if the error was "missing_transaction" from the react hook and then removed the state and code parameter which seemed to solve it.
