### ISSUE TITLE
isAuthenticated is always false

### ISSUE THREAD

**Issue by ryanKrumbholz** [auth0/auth0-react#63]
Hello, I am following the 'React: Login" quickstart (https://auth0.com/docs/quickstart/spa/react/01-login#install-the-auth0-react-sdk) to implement auth0 into one of my projects. However, isAuthenticated remains false after logging in, both following the specific quickstart tutorial and when trying to utilize it elsewhere (see code snippet below). 

https://github.com/ryanKrumbholz/qwik/blob/60dd026f16a91872181ce23f7a7a3c11cb1a0dc2/packages/qwik-client/qwik-client/src/components/AuthenticatedRoute/AuthenticatedRoute.tsx#L2-L10

Using v1.0.0

**Comment by adamjmcgrath** [comment]
Hi @ryanKrumbholz - thanks for raising this

I've run your application and it looks like you're getting 401's from the `/oauth/token` endpoint. Can you check that your Auth0 Application in your dashboard is set to "Single Page Application".

And if it is, can you follow the steps in https://github.com/auth0/auth0-react/issues/49#issuecomment-654466353 and let me know if that resolves your issue?

**Comment by ryanKrumbholz** [comment]
That worked, thanks!

**Comment by adamjmcgrath** [comment]
Great, thanks for letting me know - just to confirm, was your tenant already configured to "Single Page Application", and you had to toggle away and back again, or was it configured to something else?

**Comment by ryanKrumbholz** [comment]
Correct, my tenant was already configured to SPA and I had to toggle it away and back.

**Comment by adamjmcgrath** [comment]
Thanks for confirming, I'll raise this issue internally
