### ISSUE TITLE
GenericError not exported

### ISSUE THREAD

**Issue by elstgav** [auth0/auth0-react#643]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

Following up to:
-  https://github.com/auth0/auth0-react/issues/636

it’s useful to have `GenericError` exported in addition to the other Error classes. This enables clients to quickly detect if they’re dealing with any kind of Auth0 Error:

```tsx
import { GenericError, useAuth0 } from '@auth0/auth0-react'

const ErrorComponent = () => {
  const { error } = useAuth0()

  if (error instanceof GenericError) {
    console.log(error.error_description)
  }

  …
```

### Describe the ideal solution

In `auth0-react/src/index.tsx`, export `GenericError` from `auth0-spa-js`:

```diff
  export {
    …
+   GenericError,
    …
  } from '@auth0/auth0-spa-js';
```

### Alternatives and current workarounds

We can determine the GenericError by grabbing the prototype of any of the child errors:

```tsx
import { AuthenticationError, useAuth0 } from '@auth0/auth0-react'

const ErrorComponent = () => {
  const { error } = useAuth0()

  const GenericAuth0Error = Object.getPrototypeOf(AuthenticationError)

  if (error instanceof GenericError) {
    console.log(error.error_description)
  }

  …
```

### Additional context

All other errors were exported in:
 - https://github.com/auth0/auth0-react/pull/637

**Comment by frederikprijck** [comment]
Thanks for reaching out about this, i will make sure to add this, thanks!
