### ISSUE TITLE
OAuthError is not callable

### ISSUE THREAD

**Issue by elstgav** [auth0/auth0-react#645]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

Introduced in https://github.com/auth0/auth0-react/pull/638; trying to call `new OAuthError('name', 'message')` returns the following error:

```
errors.tsx:10 Uncaught TypeError: Class constructor d cannot be invoked without 'new'
    at new OAuthError (errors.tsx:10:1)
    at <anonymous>:1:1
```

In this case `d` refers to `GenericError`.

Expected result is to return an error object.

### Reproduction

1. Call `new OAuthError('name', 'message')`

### auth0-react version

2.2.3

### React version

17.0.2

### Which browsers have you tested in?

Chrome

**Comment by adamjmcgrath** [comment]
Thanks for reporting @elstgav 

Fixed in https://github.com/auth0/auth0-react/releases/tag/v2.2.3
