### ISSUE TITLE
Error: Consent required while requesting getAccessTokenSilently

### ISSUE THREAD

**Issue by nairsandeep** [auth0/auth0-react#65]
Hello, 

I am getting the Error: Consent required while requesting getAccessTokenSilently (); this happens only on localhost/https://127.0.0.1:3000/ but on production, it's working fine ( i use AWS amplify). 

On my react code this is how I request the access token inside an async function

`token = await getAccessTokenSilently({
                audience,
                claim,
            });

Currently, my workaround is to call getAccessTokenWithPopup() if the silent request returns a promise error which would allow me to run the same code without any authentication bypassing on my dev and production. 

Is there a better way to address this issue? , please do let me know. 

thanks in advance!

**Comment by adamjmcgrath** [comment]
Hi @nairsandeep 

Only first party apps can skip the consent. Localhost will never be a verifiable first party app, so Auth0 will always want to show the consent screen More info: https://auth0.com/docs/api-auth/user-consent 

> Currently, my workaround is to call getAccessTokenWithPopup() if the silent request returns a promise error which would allow me to run the same code without any authentication bypassing on my dev and production.

That's the correct mitigation, we handle the `consent_required` error in the same way in our example https://github.com/auth0/auth0-react/blob/master/EXAMPLES.md#4-create-a-useapi-hook-for-accessing-protected-apis-with-an-access-token

**Comment by nairsandeep** [comment]
Thanks @adamjmcgrath !

**Comment by Jared-Dahlke** [comment]
@adamjmcgrath your link is broken or outdated

**Comment by ewanharris** [comment]
Hey @Jared-Dahlke, we removed that example as we felt there were better resources for the topic. Please see [this response](https://github.com/auth0/auth0-react/issues/499#issuecomment-1422710152) from Adam for some more information
