### ISSUE TITLE
Handling Email Verification within React App

### ISSUE THREAD

**Issue by VED-StuartMorris** [auth0/auth0-react#66]
Do you have any examples of handling email verification within a React App using the auth0-react approach?  

Is this typically handled from the universal login pages or within the client application?  

Currently, we require user to complete email verification in order to log in. We use universal login pages to handle authentication. Once a user signs up they are redirected to our React Application which uses this project. We have an Auth0Provider setup which looks like this:
```
useEffect(() => {
    const initAuth0 = async () => {
      try {
        const auth0FromHook = await createAuth0Client(initOptions);
        setAuth0(auth0FromHook);

        if (
          window.location.search.includes('code=') &&
          window.location.search.includes('state=')
        ) {
          const { appState } = await auth0FromHook.handleRedirectCallback();
          onRedirectCallback(appState);
        }

        const isUserAuthenticated = await auth0FromHook.isAuthenticated();
        setIsAuthenticated(isUserAuthenticated);

        if (isUserAuthenticated) {
          const resultUser = await auth0FromHook.getUser();
          setUser(resultUser);

          // TODO: We need to get the my account menu item here. We can then get the user info to use.
          Log.info(
            `Authenticated resultUser: ${JSON.stringify(resultUser)}`,
            'Auth0-SPA'
          );
        }

        setLoading(false);
      } catch (error) {
        setLoading(false);
        Log.info('error occurred');
        Log.info(error);
      }
    };
    initAuth0();
    // eslint-disable-next-line
  }, []);
```

We are currently catching the error for unverified users:
```
error: "unauthorized"  
error_description: "Please verify your email before logging in."
```

Just wondering if we should have an interim page for this status which allows a user to resend the email verification or constantly checks if the user has completed it? At what point and where would we check this?

**Comment by adamjmcgrath** [comment]
Hi @VED-StuartMorris 

You'd need to handle this in the react app, something like:

```js
const Component = () => {
  const {
    error,
    loginWithRedirect,
  } = useAuth0();

  if (error && error.error_description === 'Please verify your email before logging in.') {
    return (
      <div>
        Please verify your email then <button onClick={loginWithRedirect}>Login</button>
      </div>
    );
  }
}
```

**Comment by adamjmcgrath** [comment]
Hi @VED-StuartMorris - closing this, but feel free to reopen if you have any other questions

**Comment by VED-StuartMorris** [comment]
Mentioning this:
https://github.com/auth0/auth0-react/issues/143
