### ISSUE TITLE
checkJwt middleware doesn't work on API example

### ISSUE THREAD

**Issue by luis199230** [auth0/auth0-react#678]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

I added tokenSigningAlg parameter to auth method from express-oauth2-jwt-bearer

### Reproduction

1. `npm i`
2. `npm run build`
3. `npm run install:examples`
4. `npm run start:api`

### Additional context

With this I solved the issue

```
const checkJwt = auth({
  audience: AUDIENCE,
  issuerBaseURL: `https://${DOMAIN}`,
  tokenSigningAlg: SIGNATURE
});
```

### auth0-react version

2.2.3

### React version

^18.2.0

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
Thanks for reaching out. I assume u are using HS256? If that's the case, it's expected that you need to set that. But for RS256, you shouldnt.

**Comment by frederikprijck** [comment]
Closing, can reopen if needed.
