### ISSUE TITLE
Auth0Provider not sending client_id

### ISSUE THREAD

**Issue by jdsilva-scopesec** [auth0/auth0-react#68]
### Description

> I'm using auth0/auth0-react and trying to follow [Complete Guide to React User Authentication With Auth0](https://auth0.com/blog/complete-guide-to-react-user-authentication).  When I try to implement the LoginButton component and test, I get an error that the client_id is missing.

### Reproduction

> Steps taken are as close as possible to your tutorial with the exception that this is not a "from scratch" project.  I am trying to modify ArchitectUI, a popular dashboard React template project.  I am following the tutorial up to the point of creating a Login/Logout Button component and testing that the user is forwarded to Auth0 for authentication.  I also made sure to configure the domain, client_id, and audience properties for the Auth0Provider component.

> - Log entry from dashboard
{
  "date": "2020-07-14T22:55:59.867Z",
  "type": "f",
  "description": "Missing required parameter: client_id",
  "connection_id": "",
  "ip": "***************",
  "user_agent": "Chrome 83.0.4103 / Windows 10.0.0",
  "details": {
    "body": {},
    "qs": {
      "audience": "*************************************",
      "scope": "openid profile email",
      "response_type": "code",
      "response_mode": "query",
      "state": "************************************************************",
      "nonce": "************************************************************",
      "code_challenge": "********************************************",
      "code_challenge_method": "S256",
      "auth0Client": "********************************************************"
    },
    "error": {
      "message": "Missing required parameter: client_id",
      "oauthError": "invalid_request",
      "type": "request-error"
    },
    "session_id": "*************************************"
  },
  "hostname": "*********************",
  "auth0_client": {
    "name": "auth0-react",
    "version": "1.0.0"
  },
  "log_id": "********************************************************",
  "_id": "**********************************************************",
  "isMobile": false
}
> - Error
![image](https://user-images.githubusercontent.com/66843326/87689081-c9cca100-c755-11ea-8c33-2926c5324c87.png)

### Environment

- **auth0/auth0-react 1.0**
- **React 16.12.0**
- **react-router-dom 5.1**
- **ArchitectUI React template project** [Project link](https://github.com/DashboardPack/architectui-react-theme-free)
- **Win10, VS Code**

**Comment by adamjmcgrath** [comment]
Hi @jdsilva-scopesec 

Couple of things to check:

Make sure your `clientId` is being loaded from the environment variables, so after assigning `clientId` log it to the console and check it is defined.

```js
const clientId = process.env.REACT_APP_AUTH0_CLIENT_ID;
console.log('clientId', clientId)
```

Make sure you're passing `clientId` to the provider (not `client_id`)

```jsx
<Auth0Provider
      clientId={clientId} <==
      ...
    >
    {children}
</Auth0Provider>
```

If you're still getting `Missing required parameter: client_id` please share your code or a running link to your app

**Comment by jdsilva-scopesec** [comment]
Thanks @adamjmcgrath.  It seems I had incorrect parameter names in setting up the provider component.  I have also followed the recommendations for HashRouter in the examples as my project uses that type of router.

**Comment by adamjmcgrath** [comment]
Great - glad it's working for you now
