### ISSUE TITLE
Add warning when calling `useAuth0` outside of `Auth0Provider`

### ISSUE THREAD

**Issue by beaverusiv** [auth0/auth0-react#697]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

When a component that calls `useAuth0` does so without being wrapped in an `Auth0Provider` it silently sits at `loading: true` forever.

### Describe the ideal solution

Usually when working with a context I will create logic like so:

```typescript
export const useApplicant = () => {
	const context = useContext(ApplicantContext);

	if (context === undefined) {
		throw new Error('useApplicant must be used within a ApplicantProvider');
	}

	return context;
};
```

I believe similar logic can be implemented to check for this scenario

**Comment by frederikprijck** [comment]
Thanks, we currently have no plans to add this as that would, technically, we a breaking change.

[There is react-redux that does this only when not in PRODUCTION mode](https://github.com/reduxjs/react-redux/blob/master/src/hooks/useReduxContext.ts#L14-L23), but that would still be a breaking change.

Even though I understand the decreased experience, given the fact that it's a breaking change, this isn't something we can accomodate for for the time being.
