### ISSUE TITLE
Use '.well-known/openid-configuration' to configure Auth0Provider (Auth0Client) calls

### ISSUE THREAD

**Issue by johnny-the-coder** [auth0/auth0-react#700]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like that Auth0Provider (Auth0Client) would use the configuration specified in {domain}/.well-known/openid-configuration to make calls to auth0 endpoints.

Currently configuring custom endpoints for 'authorize' or 'oauth/token' is impossible. Only the domain is configurable.
https://auth0.github.io/auth0-react/functions/Auth0Provider.html
'.well-known/openid-configuration' is not taken into account.

### Describe the ideal solution

The ideal solution would be that Auth0Provider could be configured with '.well-known/openid-configuration', e.g:

```
<Auth0Provider
  domain={domain}
  wellKnown={".well-known/openid-configuration"}    <--- this would be new configuration parameter
  clientId={clientId}
  authorizationParams={{ redirect_uri: window.location.origin }}}>
  <MyApp />
</Auth0Provider>
```

Than calls to authorize and token endpoints (and other enpoints as well) would use urls defined in the well-known file:

authorization_endpoint
token_endpoint
other

**Comment by frederikprijck** [comment]
Closing in favor of https://github.com/auth0/auth0-spa-js/issues/1219
