### ISSUE TITLE
Calling local logout does not clear auth0 provider's state

### ISSUE THREAD

**Issue by kaisalmon** [auth0/auth0-react#72]
### Description

When calling `logout({localOnly: true})` the cookies are removed from the browser, but the auth0 provider's state, (which is parsed down via `withAuth0`) still has `isAuthenticated: true` and all the rest of its state unchanged. This remains until page is refreshed. 

Without this data being cleared (or there being some other way to manually clear this data) the ability to do a local logout seems pointless. 

### Reproduction

In a react project with auth0 login, once logged in, have a component which renders the auth0 `user` and `isAuthenticated` properties. Have a button which calls  `logout({localOnly: true})`.  The `isAuthenticated` is now falsely displaying true.

**Comment by adamjmcgrath** [comment]
Hi @kaisalmon - thanks for raising this

Yep - let me create some work internally to resolve this
