### ISSUE TITLE
Something went wrong when trying to reset password?

### ISSUE THREAD

**Issue by ashish-y** [auth0/auth0-react#74]
### Description

I’m using auth0-react sdk and universal login.
When the “forgot password” button is triggered.
entering a new password throws a message “Something went wrong, please try again”.
But the password does change.

**Expected behavior:** After successful password reset user should be redirected to the app for login.

_This flow is working fine if I use "Customize Password Reset" Page.
The look is old but it properly routes the user back to the app after reset password._

### Reproduction

1.  Click Forgot Password in the universal login screen
2. Check email for reset password link
3. Click the email link 
4. Enter new password and confirm
5. Error Something went wrong, please try again
6. Login with the new password still works

### Environment
SDK version: 1.0.0
Browser: Chrome version 84.0.4147.89

**Comment by adamjmcgrath** [comment]
Hi @ashish-y - this looks like a problem with the universal login page rather than this SDK, let me find out where you should direct this issue and get back to you

**Comment by ashish-y** [comment]
Hi @adamjmcgrath,

I was able to resolve this issue. 
I am using custom MYSQL database with auth0 and the problem was with the change password script template.

I had to do 
return 
`results.changedRows > 0` 

instead of 
`results.length > 0` 

to get a successful password reset message.
