### ISSUE TITLE
Allow user to instanciate the auth0 client themselves and pass it to the provider

### ISSUE THREAD

**Issue by nihauc12** [auth0/auth0-react#758]
### Checklist

- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

I would like to have access to the javascript client (react-agnostic).

### Describe the ideal solution

I would instanciate the client myself and pass it to the Auth0Provider component

### Alternatives and current workarounds

Instanciate 2 clients...

**Comment by frederikprijck** [comment]
Closing as duplicate, see https://github.com/auth0/auth0-react/issues/737#issuecomment-1947921289.
