### ISSUE TITLE
CacheKey clientId field type does not match string | undefined

### ISSUE THREAD

**Issue by malinskibeniamin** [auth0/auth0-react#760]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When building any NextJS app, validity of types will fail when using `@auth0/auth0-react` package.

The package works fine in development, but the build will fail because of the `clientId` being 

### Reproduction

1. Clone any NextJS 14 app router example
2. Use `@auth0/auth0-react`
3. Run `npm run build`
4. Notice the error

### Additional context

```ts
> next build

  ▲ Next.js 14.2.3
  - Environments: .env

   Creating an optimized production build ...
 ✓ Compiled successfully

   Linting and checking validity of types  ..Failed to compile.

./node_modules/@auth0/auth0-spa-js/src/cache/shared.ts:45:27
Type error: Type 'string | undefined' is not assignable to type 'string'.
  Type 'undefined' is not assignable to type 'string'.

  43 |     const [prefix, clientId, audience, scope] = key.split('::');
  44 |
> 45 |     return new CacheKey({ clientId, scope, audience }, prefix);
     |                           ^
  46 |   }
  47 |
  48 |   /**
```

### auth0-react version

2.2.4

### React version

18.3.1

### Which browsers have you tested in?

Chrome

**Comment by nandan-bhat** [comment]
Hello @malinskibeniamin,
Could you provide additional details on the steps needed to reproduce this issue ?

I attempted to reproduce the issue using `Next.js@14.2.3` and `@auth0/auth0-react`, but I wasn't able to encounter the problem you mentioned. Could you provide more details about how you initiated your `Next.js` project (whether you used `npx`, `pnpm`, or `yarn`) and the options you selected during the installation process?

**Comment by malinskibeniamin** [comment]
Hi @nandan-bhat,

Thanks for looking into it - it's been a while but from what I can remember, it could have been due to my older TypeScript version (before 5.0). Sorry for the inconvenience, I will close this issue and if I stumble across it again, I will reopen. Thank you!
