### ISSUE TITLE
Auth0provider  not compatible with useNavigate hook

### ISSUE THREAD

**Issue by mayo7e** [auth0/auth0-react#765]
### Checklist

- [X] The issue can be reproduced in the [auth0-react sample app](https://github.com/auth0-samples/auth0-react-samples/tree/master/Sample-01) (or N/A).
- [X] I have looked into the [Readme](https://github.com/auth0/auth0-react#readme), [Examples](https://github.com/auth0/auth0-react/blob/main/EXAMPLES.md), and [FAQ](https://github.com/auth0/auth0-react/blob/main/FAQ.md) and have not found a suitable solution or answer.
- [X] I have looked into the [API documentation](https://auth0.github.io/auth0-react/) and have not found a suitable solution or answer.
- [X] I have searched the [issues](https://github.com/auth0/auth0-react/issues) and have not found a suitable solution or answer.
- [X] I have searched the [Auth0 Community](https://community.auth0.com) forums and have not found a suitable solution or answer.
- [X] I agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

When using the Auth0 React SDK with React Router v6, attempting to use useNavigate() results in the following error: Uncaught Error: useNavigate() may be used only in the context of a <Router> component. This issue occurs despite wrapping the application with <BrowserRouter> or <RouterProvider> as required by React Router v6.
![Screenshot (20)](https://github.com/auth0/auth0-react/assets/100059302/00abd740-b3d8-47a4-bc89-6d413b817a6d)

### Reproduction

1. Set up a React application using React Router v6.
2. Integrate Auth0 React SDK for authentication.
3. Attempt to use useNavigate() for navigation within the application.

### auth0-react version

2.2.4

### React version

18.3.1

### Which browsers have you tested in?

Chrome

**Comment by frederikprijck** [comment]
We have an example that uses Router-Router and its useNavigate hook. I recommend looking at that: https://github.com/auth0/auth0-react/blob/main/examples/cra-react-router/src/index.tsx.

If you believe there is still an issue with our SDK, please open an issue with more information to allow us to help troubleshoot.
