### ISSUE TITLE
Password-less Support

### ISSUE THREAD

**Issue by jordanparker-me** [auth0/auth0-react#79]
Will the provided auth client be supporting auth.passwordLessStart methods like the web-sdk in the future?

**Comment by adamjmcgrath** [comment]
Hi @jordanparker-me this SDK uses `auth0-spa-js` which uses Universal Login which supports Passwordless - It’s the preferred way to implement Passwordless Authentication (https://auth0.com/docs/connections/passwordless/guides/universal-login)

If you configure Universal Login to use Passwordless (using these docs https://auth0.com/docs/dashboard/guides/universal-login/configure-login-page-passwordless) users will be prompted for Passwordless login on the Universal Login page when they go to login through the SDK

I’ve put an example of using Email passwordless with SPA JS here https://codepen.io/adamjmcgrath/pen/NWNKmyQ

![image](https://user-images.githubusercontent.com/1299658/89297863-76ff4e80-d65c-11ea-9b41-9022dde46074.png)

**Comment by jordanparker-me** [comment]
@adamjmcgrath thanks for the quick response.

What about if you wanted to embed the passwordless auth flow into your company UI?

I have managed to achieve this with auth0-js. Is there a auth0-spa-js approach? The current auth0-js approach appears to not come with session management out of the box.

**Comment by adamjmcgrath** [comment]
Hi @jordanparker-me - I'm afraid not, the only way to do embedded Passwordless is with `auth0-js`, you need to use the Universal Login Page to do Passwordless with `auth0-spa-js`

**Comment by gmwill934** [comment]
Will the `auth0-react` sdk expose these methods? Is there any development on this?

**Comment by adamjmcgrath** [comment]
Hi @gmwill934 - there is no development planned for this SDK to support embedded passworldess I'm afraid.

The only way to use Passwordless with this SDK is through the Universal Login Page which supports Passwordless Authentication and is the preferred way to implement it (https://auth0.com/docs/connections/passwordless/guides/universal-login)
