### ISSUE TITLE
CORS problems with Auth0 and React

### ISSUE THREAD

**Issue by Moezalez** [auth0/auth0-react#8]
I am currently trying implement Auth0 in my NodeJS + React App.
This tutorial given is really good and helpful, though I have one big problem.
Every time I try to login/register via Auth0 I get 

`Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

So I have a rough understanding what that means. But I just don't know where to set the needed options to allow this request to Auth0. On the Server side? In the Browser code?

Do I need to enter my local IP (when developing) into the Allowed Origins (CORS) section of the App?

Best regards

**Comment by ntotten** [comment]
This is a configuration issue with your app. You need to set the allowed domains in the Auth0 app settings. Please contact support@auth0.com for assistance.
