### ISSUE TITLE
Example Gatsby app won't build

### ISSUE THREAD

**Issue by pcolmer** [auth0/auth0-react#83]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Please read through the template below and answer all relevant questions. Your additional work here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Description

There are several problems with the sample code provided for use with Gatsby. This issue covers the ones I've discovered.

### Reproduction

In a clean directory, clone the repo and go into `auth0-react/examples/gatsby-app`.

Run `npm install`. There will be errors because `package.json` has three file references instead of version references (@auth0/auth0-react, react and react-dom). Fix those and run `npm install` again.

Once that completes, run `gatsby build`. This fails in `Nav.js` because `location is not defined`. I "hacked" around that with:

```
const isBrowser = typeof window !== "undefined"
const pathname = isBrowser ? location.pathname : "/";
```

but I don't know if that is the correct solution :)

### Environment

> Please provide the following:

- **Version of this library used:** current repo as of 7th August 2020. Last commit was https://github.com/auth0/auth0-react/commit/caa2d093deba9a3dc4b75056a023de2fe3d69a0d

**Comment by adamjmcgrath** [comment]
Hi @pcolmer - thanks for raising this

> Once that completes, run gatsby build. This fails in Nav.js because location is not defined

Fixed in #84 

> There will be errors because package.json has three file references instead of version references (@auth0/auth0-react, react and react-dom).

These are intended to be file references - the goal is to test the example apps against the local auth0-react binary. You may be getting errors because you didn't build a local auth0-react binary (run `npm run build` in the project's root folder)

> There are several problems with the sample code provided for use with Gatsby. This issue covers the ones I've discovered.

Let me know if you discover any more :)

**Comment by pcolmer** [comment]
> These are intended to be file references - the goal is to test the example apps against the local auth0-react binary. You may be getting errors because you didn't build a local auth0-react binary (run npm run build in the project's root folder)

I appreciate that the example apps run using the local auth0-react binary ... but why are there file references to react and react-dom? Have you modified those libraries?

**Comment by adamjmcgrath** [comment]
> why are there file references to react and react-dom? 

It's a workaround for https://reactjs.org/warnings/invalid-hook-call-warning.html
