### ISSUE TITLE
Improved redirection after Auth0 login

### ISSUE THREAD

**Issue by pcolmer** [auth0/auth0-react#87]
**Please do not report security vulnerabilities here**. The [Responsible Disclosure Program](https://auth0.com/whitehat) details the procedure for disclosing security issues.

**Thank you in advance for helping us to improve this library!** Your attention to detail here is greatly appreciated and will help us respond as quickly as possible. For general support or usage questions, use the [Auth0 Community](https://community.auth0.com/) or [Auth0 Support](https://support.auth0.com/). Finally, to avoid duplicates, please search existing Issues before submitting one here.

By submitting an Issue to this repository, you agree to the terms within the [Auth0 Code of Conduct](https://github.com/auth0/open-source-template/blob/master/CODE-OF-CONDUCT.md).

### Describe the problem you'd like to have solved

At the moment, when a user logs in to authenticate, the web app redirects off to Auth0 where the user enters their credentials and, if successful, Auth0 redirects back to the root page of the web app and then the SDK redirects to the page the user was on when the authentication was initiated.

For my web app, using Gatsby, the redirection to the root page is not as good as the behaviour with the `auth0-js` SDK where a separate "page" was used to handle the callback. The reason why it isn't as good is because the whole of the root page gets rendered before the post-authentication redirect takes place. With the `auth0-js` SDK, the separate callback page allowed for minimal rendering to happen.

### Describe the ideal solution

Provide a means to specify where Auth0 should redirect back to. Ideally, I'd like to be able to have Auth0 redirect straight back to the page the user was on but, if that isn't possible, allow for a minimal callback page to be used.

**Comment by adamjmcgrath** [comment]
Hi @pcolmer

> Provide a means to specify where Auth0 should redirect back to.

You can specify a `redirectUri` either passed in to the `Auth0Provider` or one of the login methods. This can be a url to any  page served by your SPA: the homepage, a minimal callback page or another specific page of your choosing. You just need to make sure that it is specified in "Allowed Callback URLs" in your Auth0 tenant application settings.

**Comment by pcolmer** [comment]
Thanks, @adamjmcgrath. Just missing the obvious as usual 👍
