### ISSUE TITLE
Can't resolve @auth0/auth0-react

### ISSUE THREAD

**Issue by katzcentrality** [auth0/auth0-react#88]
Hi, using the latest version of Create React App and VSCode in Windows 10 with bash as my terminal using auth0 version 2.27.1. I know it's installed because I can check my version in NPM, and because it's in my package.json. However, I get this error "./src/index.js
Module not found: Can't resolve '@auth0/auth0-react' in 'C:\Users\Philip\Desktop\Coding\auth\src'"
when importing "import { Auth0Provider } from "@auth0/auth0-react";".

Thanks!

**Comment by adamjmcgrath** [comment]
Hi @katzcentrality, 

> using auth0 version 2.27.1

It sounds like you've installed `node-auth0` using `npm install auth0` (which is at v2.27.1). Could you try doing `npm install @auth0/auth0-react` and then try building your application again?

**Comment by katzcentrality** [comment]
Good catch - thanks. Seems to have fixed it!

**Comment by Jassi10000** [comment]
<code>npm install @auth0/auth0-react</code>
I wrote exactly this but it's giving the same error

**Comment by stevehobbsdev** [comment]
Hi @Jassi10000, can you please raise a new issue and fill out the template as required. This will allow us to triage this better and help get a resolution. Thanks

**Comment by Jassi10000** [comment]
Sure @stevehobbsdev , thanks for telling
