### ISSUE TITLE
Auth token expiration uses different setting from Auth0 compared with auth0-js SDK

### ISSUE THREAD

**Issue by pcolmer** [auth0/auth0-react#89]
### Description

I have this code in my app to allow me to verify what I'm getting back from Auth0:

```
getAccessTokenSilently().then(token => console.log(token))
```

Using jwt.io to decode the displayed token shows that it expires in 24 hours. In checking the token settings, it looks like this SDK is getting the Token Expiration value whereas auth0-js got the Token Expiration for Browser Flows value:

![image](https://user-images.githubusercontent.com/1979931/89868985-92fa7700-dbab-11ea-8b00-e3ef1ff2f50f.png)

I'm raising this as an issue because it is a change in behaviour between the two SDKs which was unexpected on my part.

### Environment

> Please provide the following:

- **Version of this library used:** 1.0.0
- **Version of the platform or framework used, if applicable:** Gatsby 2.24.27, React 16.12.0

**Comment by adamjmcgrath** [comment]
Hi @pcolmer - thanks for raising this

This SDK uses the authorization code flow (with PKCE) and `auth0-js` uses the Implicit flow

Since the Implicit flow is considered less secure than the code flow, Auth0 suggests a lower token expiration. Now that you're using the authorization code flow you get the regular token expiration.

Check out this blog post for more info https://auth0.com/blog/oauth2-implicit-grant-and-spa/

**Comment by pcolmer** [comment]
Thanks for the clarification, @adamjmcgrath. That makes sense - it just caught me out because I was trying to validate the behaviour of my website when the token expires and the expiration wasn't changing :)

**Comment by pcolmer** [comment]
Hi @adamjmcgrath. I realise that I now have a follow-up question.

Having read https://auth0.com/docs/tokens/refresh-tokens/refresh-token-rotation, should I reconfigure the app to use refresh token rotation or is that not supported/recommended for this SDK?

![image](https://user-images.githubusercontent.com/1979931/89887769-cc8cab80-dbc6-11ea-89d6-7c270e5d0adb.png)

**Comment by adamjmcgrath** [comment]
Hi @pcolmer 

You can use refresh tokens with this SDK by setting [useRefreshTokens](https://auth0.github.io/auth0-react/interfaces/auth0provideroptions.html#userefreshtokens) to `true`. It's generally used with [cacheLocation](https://auth0.github.io/auth0-react/interfaces/auth0provideroptions.html#cachelocation) set to `localstorage` to work around Intelligent Tracking Prevention (ITP) restrictions on Safari and Brave browsers. If you enable refresh tokens in this SDK, you absolutely should set your Refresh Token Behaviour to "Rotating".

You can read more about securing SPAs in the world of ITP here https://auth0.com/blog/securing-single-page-applications-with-refresh-token-rotation/

**Comment by pcolmer** [comment]
Thanks, @adamjmcgrath, for the confirmation.
