### ISSUE TITLE
How to authenticate for multiple audiences?

### ISSUE THREAD

**Issue by pcolmer** [auth0/auth0-react#90]
### Describe the problem you'd like to have solved

I need to be able to retrieve access tokens from Auth0 for multiple audiences. Given that `gatsby-browser.js` wraps the `Auth0Provder` (which specifies the audience) around the root element, I'm not sure how this can be handled.

### Describe the ideal solution

Ideally, I'd like to be able to request multiple audiences in one go but I don't think that Auth0 supports that. Alternatively, I'd like a (simple) way to request credentials for a different audience from the one used on the root element wrapper.

## Alternatives and current work-arounds

No alternatives or work-arounds.

**Comment by adamjmcgrath** [comment]
Hi @pcolmer 

You can get access tokens for multiple audiences by passing different audiences into [getAccessTokenSilently](https://auth0.github.io/auth0-react/interfaces/auth0contextinterface.html#getaccesstokensilently). When consent is required, you can fallback to getting the new access token interactively.

```jsx

<Auth0Provider audience="http://api1" .../>

var accessToken1 = await getAccessTokenSilently();

var accessToken2;
try {
  accessToken2 = await getAccessTokenSilently({ audience: 'http://api2' });
} catch (e) {
  if (e.error === 'consent_required') {
    accessToken2 = await getAccessTokenWithPopup({ audience: 'http://api2' });  
  } else {
    throw e;
  }
}

accessToken1; // AT for http://api1
accessToken2; // AT for http://api2
```

**Comment by pcolmer** [comment]
Thank you, @adamjmcgrath, for the solution and for linking to the documentation! (Hopefully that will result in fewer questions from me).

Unfortunately, I'm getting an error when `getAccessTokenWithPopup` is called:

```
Error: Could not open popup
    at Sr (auth0-react.esm.js:107)
    at e.<anonymous> (auth0-react.esm.js:107)
    at auth0-react.esm.js:107
    at Object.next (auth0-react.esm.js:107)
    at c (auth0-react.esm.js:107)
```

**Comment by pcolmer** [comment]
Please note that I am pulling in `@auth0/auth0-react` v1.0.0. If you want me to use the repo instead, please let me know.

**Comment by adamjmcgrath** [comment]
Hi @pcolmer 

This is because your popup is being blocked by the browser - usually when it's being opened automatically (as opposed to being opened from a click). You'll need to unblock popups, or call `getAccessTokenWithPopup` from a click handler.

Note, the consent_required error will only happen on `localhost`, see https://auth0.com/docs/authorization/user-consent-and-third-party-applications?#skip-consent-for-first-party-applications

**Comment by pcolmer** [comment]
@adamjmcgrath you, sir, are a superstar!

Thank you for your prompt and always helpful replies. I now have my code working :)
