### ISSUE TITLE
Support earlier version of react and react-dom

### ISSUE THREAD

**Issue by tiagob** [auth0/auth0-react#96]
### Describe the problem you'd like to have solved

Can you support an earlier version of react and react-dom? I'm using 16.11. It works fine but the warning is annoying. It's not possible to upgrade my version of react since this is in a mono-repo with an expo react-native app that requires 16.11 (latest version of expo).

### Describe the ideal solution

Update these lines
https://github.com/auth0/auth0-react/blob/master/package.json#L92-L93

To
```
    "react": "^16.11.0",
    "react-dom": "^16.11.0",
```

**Comment by adamjmcgrath** [comment]
Sure 👍  happy to accept a PR

**Comment by tiagob** [comment]
https://github.com/auth0/auth0-react/pull/99

**Comment by tiagob** [comment]
@adamjmcgrath are you publishing an update to npm anytime soon?

**Comment by adamjmcgrath** [comment]
@tiagob - yep, planning on doing this tomorrow https://github.com/auth0/auth0-react/pull/115

**Comment by adamjmcgrath** [comment]
@tiagob Released in 1.1.0

**Comment by tiagob** [comment]
Thanks!
