### ISSUE TITLE
SAML connections support

### ISSUE THREAD

**Issue by martinrojas** [auth0/auth0-react#98]
### Describe the problem you'd like to have solved
Maybe there is something that is just missing from the documentation, but if you need to use this library with a SAML connection to an active directory is there some different values or some other method for specifying which connection you want to use.

My application needs to be able to handle on startup to specify which SAML provider to use for its authentication.

**Comment by adamjmcgrath** [comment]
Hi @martinrojas - this SDK uses Auth0 with the Universal Login Page. If your Auth0 client is setup with a SAML integration and you can login to that through the Universal Login Page, then this library should work without any modification.

**Comment by martinrojas** [comment]
Thank you for the response. In looking at the code a little deeper and translating from the auth0-spa SDK I believe that by calling loginWithRedirect({ connection}) from the useAuth hook I can change the SAML Provider. Will try this next week and post back if the solution works.

**Comment by adamjmcgrath** [comment]
Closing - feel free to reopen if you have any other questions on this
